### ISSUE TITLE
[EPIC] - Webservice

### ISSUE THREAD

**Issue by prestonBot** [PrestaShop/PrestaShop#10069]
> This issue has been migrated from the Forge. Read the [original ticket here](http://forge.prestashop.com/browse/BOGOSS-83).

- _**Reporter:**_ pablo.borowicz
- _**Created at:**_ Thu, 7 Dec 2017 17:38:20 +0100

---

**Webservice has many issues and needs rework**
Just as a summary of important issues to have in mind when reworking the Webservice:

## BUGS
- [x] #19290
- [x] #20121
- [x] #12412
- [ ] #15499
- [x] #16515
- [x] #13802
- [ ] #12877
- [ ] #16086
- [ ] #18953
- [x] #14212
- [x] #13787
- [x] #10172
- [x] #9819
- [x] #24458
- [x] #27109 
- [x] #27634
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35616
- [x] #35619
- [x] #35626

**Products:**
- [x] #9922
- [x] #14322
- [x] #15380
- [x] #19605
- [ ] #14903
- [x] #14439
- [x] #12459
- [ ] #22561
- [x] #11628
- [ ] #22675
- [ ] #23777
- [ ] #25456
- [ ] #28586
- [ ] #31577 

**Cart:**
- [x] #10822
- [ ] #19906
- [x] #23570

**Order:**
- [ ] #13912
- [ ] #10157
- [x] #25335
- [ ] #26647
- [ ] #29133

**Stocks:**
- [ ] #13006
- [ ] #17748
- [ ] #15976
- [ ] #26272

## Features
- [x] #16866
- [x] #17753
- [x] #14351
- [x] #19847
- [x] #14889
- [x] #15774
- [ ] #21543
- [ ] #18277
- [ ] #14704
- [x] #11342
- [ ] #12008

### Need Specs
- [ ] #16785

## BUGS
- [x] #21745
- [x] #22333
- [x] #22565
- [x] #26559

**Products:**

**Cart:**
- [x] #20509
- [x] #23061
- [x] #19252

**Order:**
- [x] #22760

**Stocks:**

## Features
- [x] #19291
- [x] #19590
- [x] #14840
- [x] #21493
- [x] #16954
- [x] #15672
- [x] #26559

### Need Specs

---

Thanks for @eternoendless and @elboletaire for opening and editing this epic

**Comment by elboletaire** [comment]
To be [epic], this issue has too few content.

I'm really interested on this part, specially because I do only work with the webservice. But as I'm still a bit far away from knowing all the nooks and cranies of prestashop, I'll help as I can for now: making a summary of all the issues (more or less) that have been appearing about the webservice.

What's clear here is that the Webservice needs a total rework/remake. We're using symfony now, and we need to do the things "the symfony way". The problem is I'm not sure how ready are we to rework this section. Maybe would be a good idea to have other reworks done (I don't know if there's is even a plan to remake how connection to db is made, which is a critical part here).

Just as a summary of important issues to have in mind when reworking the Webservice:

- [ ] #14889 Accept not only XML, but also json formats both for making and receiving calls (easily done with seralizers/deserializers)
- Like with the current Webservice, add a default behavior generating a REST API over all the resources. This REST API should also implement some ways to filter and order results.
    + Maybe not required but interesting, as this is a shop cms: define a proper way to add/remove items from the cart, without requiring the entire cart information to be sent again. i.e. PUT to `/cart/:id/products`
    + A way to paginate results.
    + The (currently existing) images endpoint.
    + A way to get & limit related entities.
- [ ] #19182 Allow to (properly) load custom management classes for custom API endpoints . This is something available right now, but buggy, as described in the linked issue.
- [ ] #19291 #11053 Improve security by adding an authorization layer. This would require some (new) specific endpoints to be always accessible, like:
  + login
  + forgot password flow
  + signup
- Hooks!
    - [ ]  #16451 #16866 #16451 Ensure new hooks are registered for methods like the login, and also that the proper ones are called for already existing methods that will require rewriting (the `changePassword` method in `PasswordController` cannot be used in this rework in its current state).
    - [ ]  #20509 #13006 #13802 #13912 Hooks related: ensure they receive the exact same data than when not using the webservice. A flag could be added though, to be able to differentiate between webservice calls and normal app calls on hooks. Also, ensure all expected hooks are being called.
    + Add hooks for the request/response process. These could also be useful for the main app (hooks on request received, before sending response, etc), but I do find them more useful for the webservice. Usually for interacting with the app you'll use other hooks (like the ones for the grid, or to directly affect a display zone).
    + I'm saying "hooks for everything!" but maybe some features could be done via services injection instead than using hooks.
- [ ] #19290 Properly define required headers like `HTTP_AUTHORIZATION` on enabling the web service
- [ ] #19335 #19590 Add an API status block.
- [ ] #20121 Be able to define CORS headers in webservice configuration.
- [ ] #12412 Don't forget about the multistore behavior.

Other related webservices issues that would (hopefully) be fixed just by properly reworking the webservice (I feel like they have to be here, as this is an "epic" issue):

- [ ] #11945
- [ ] #15499
- [ ] #17753
- [ ] #9922 
- [ ] #14351 
- [ ] #19847 
- [ ] #19252 
- [ ] #18953 
- [ ] #14322 
- [ ] #14889 
- [ ] #15380 
- [ ] #16515 
- [ ] #14840 
- [ ] #15774 
- [ ] #13802 
- [ ] #12877 
- [ ] #13070 
- [ ] #13071
- [ ] #16086
- [ ] #19906
- [ ] #10822 [API] Filtering orders by date_add NOK
- [ ] #21745  There is no validation message when Enable/Disable webservice keys by bulk actions

**Comment by marionf** [comment]
Thank you for the huge work on this issue @elboletaire 
Do you feel to fix some of these issues ?

**Comment by elboletaire** [comment]
Not yet, as previously said, I'm still kinda newbie. Also, there's stuff which might go before this.

i.e. I don't know what are your plans for the `ObjectModel` nor the database instance. Is prestashop gonna move towards using doctrine? Or will only update the objectmodels to internally use doctrine? If so, is there any issue/PR working on it? I feel like I could help there. Let me know if it's planned already or if at least is there any roadmap.

A good base is required for this webservice rework, and right now I feel like the Model layer of prestashop is kinda "outdated".

**Comment by Matt75** [comment]
> Not yet, as previously said, I'm still kinda newbie. Also, there's stuff which might go before this.
> 
> 
> 
> i.e. I don't know what are your plans for the `ObjectModel` nor the database instance. Is prestashop gonna move towards using doctrine? Or will only update the objectmodels to internally use doctrine? If so, is there any issue/PR working on it? I feel like I could help there. Let me know if it's planned already or if at least is there any roadmap.
> 
> 
> 
> A good base is required for this webservice rework, and right now I feel like the Model layer of prestashop is kinda "outdated".
> 
> 

Webservices will be deprecated in favor of a new API based on CQRS but this is a lot of work, currently not specified. I thinks this couldn't be done before next major version...

I recommend you to read articles of this section : https://build.prestashop.com/news/prestashop-in-2019-and-beyond-introduction/

**Comment by tswfi** [comment]
So is there any timeline for the new api?

**Comment by KminekMatej** [comment]
@elboletaire @tswfi  I created PR where I completely refactored old API. Its worth taking a look #23100
