### ISSUE TITLE
Symfony migration roadmap for 1.7.5

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/PrestaShop#10301]
- Sell
  - Orders
    - [x] [Invoices](https://github.com/PrestaShop/PrestaShop/pull/9230)
    - [x] [Delivery Slips](https://github.com/PrestaShop/PrestaShop/pull/9139)
  - Catalog
    - [x] Categories ([WIP only Grid view](https://github.com/PrestaShop/PrestaShop/pull/10160) by @sarjon )
    - [x] [Categories form](https://github.com/PrestaShop/PrestaShop/issues/10194)
- Improve
  - Design
     - [x] [Theme Catalog](https://github.com/PrestaShop/PrestaShop/pull/9154)
     - [x] [Positions](https://github.com/PrestaShop/PrestaShop/pull/9228)
     - [x] [Link Widget](https://github.com/PrestaShop/prestafony-project/issues/25) (WIP - Joe)
  - Shipping
    - [x] [Preferences](https://github.com/PrestaShop/PrestaShop/pull/9094)
  - Payment
    - [x] [Payment methods](https://github.com/PrestaShop/PrestaShop/pull/9192) (modules configuration pages excluded)
    - [x] [Preferences](https://github.com/PrestaShop/PrestaShop/pull/9225)
  - International
    - [x] [Localization](https://github.com/PrestaShop/PrestaShop/pull/9116)
    - [x] [Geolocation](https://github.com/PrestaShop/PrestaShop/pull/9176)
    - [x] Currencies (Grid view)
    - [x] Currencies (new/edit form action) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)
    - [x] [Translations](https://github.com/PrestaShop/PrestaShop/pull/9449)
- Configure
  - Shop Parameters
    - [x] [Order Settings](https://github.com/PrestaShop/PrestaShop/pull/9007)
    - [x] SEO & URL (Grid view) + https://github.com/PrestaShop/PrestaShop/issues/10123
    - [x] SEO & URL (new/edit form action) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)
  - Advanced Parameters 
    - [X] [LogsPage](https://github.com/PrestaShop/PrestaShop/pull/9457)
    - [X] [Emails](https://github.com/PrestaShop/PrestaShop/pull/9377)  
    - Database
      - [x] [SQL Manager](https://github.com/PrestaShop/PrestaShop/pull/9206)
      - [x] [DB Backup](https://github.com/PrestaShop/PrestaShop/pull/9447)
    - Webservice
      - [X] [List keys + config](https://github.com/PrestaShop/PrestaShop/pull/10208)
      - [x] [Add new key](https://github.com/PrestaShop/prestafony-project/issues/37) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)

- [x] [Security annotations](https://github.com/PrestaShop/PrestaShop/pull/9028)
- [x] [Grid component](https://github.com/PrestaShop/PrestaShop/pull/8990), including [Search](https://github.com/PrestaShop/PrestaShop/pull/8984)
- [x] [Find a way to migrate Module Controllers](https://github.com/PrestaShop/PrestaShop/pull/9153)
- [ ] More tests and docs!
   - [x] [Make a learning module about the Grid system](https://github.com/PrestaShop/prestafony-project/issues/63)
   - [x] [Document Grid system](https://devdocs.prestashop.com/1.7/development/components/grid-component/)
   - [x] [Document How to contribute to the Core](https://devdocs.prestashop.com/1.7/contribute/)
   - [ ] Document How to configure sessions for horizontal scaling
   - [ ] Document How to create tests in Modules
   - [ ] Document How to use Composer in Modules
   - [X] [Document How to override Back Office templates](https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/)
   - [ ] Document How to use and override Ps 1.7 services in modules
   - [x] [Document How to use and override Ps 1.7 commands in modules](https://github.com/PrestaShop/docs/pull/124)
   - [X] [Document How to use and override Ps 1.7 controllers in modules](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/)
   - [X] [Document How to use and override Ps 1.7 forms in modules](https://devdocs.prestashop.com/1.7/modules/concepts/forms/admin-forms/)
   - [ ] Every new feature introduced in 1.7.5 have his tests: migrated pages and Grid system.
