### ISSUE TITLE
[EPIC] Create helper cards/empty states for specific pages

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#10434]
### [UPDATE AUG 1st 19]
Hello,

In order to help merchants have a better understanding of BO pages, we need to add : 

## Helper Cards for pages with information needed
- [ ] #10585 - IMPROVE - Shipping > Carriers
- [ ] #10540 - SELL - Catalog > Attributes & Features > Features
- [x] #30043
- [ ] SELL - Catalog > Stocks > Stock
- [ ] SELL - Catalog > Stocks > Movements
- [ ] CONFIGURE - Shop parameters > Search > Tags 
- [ ] CONFIGURE - Shop parameters > Customer settings > Groups 

See here Invision mockups : https://invis.io/FQNYNAE6RDJ **TBC** @TristanLDD / @prestascott 

**Expected behaviour for all cards :**
- when clicking on the "Learn more" button, a new tab is open with the correct documentation link (different according to the store language : see links in the attached document)
- when clicking on the cross, the card disappears and must not show up again _(@TristanLDD if more information is needed, please add it here)._
- ONLY FOR SEO & URLS : the "Configure Index page" button opens the edit page of the index (ID 4). It replaces the listing page.

**Expected wording and doc URLs :**
- wording : as on the mockups (@LouiseBonnard , if the wording must change please advise the team )
https://docs.google.com/document/d/1e_yu6f3Eq1c430k-a2QA9WLZwbwRSPsIeM_jhp09Jdg/edit

- doc URLs available here : https://docs.google.com/document/d/1xeiEwT02OpBxePesgdd68HxKD6XZe6PqYAT3KD76ol4/edit?usp=sharing

## Empty states for empty pages
- [ ] #10549 - SELL - Catalog > Discounts > Catalog price rules
- [ ] #10546 - SELL - Catalog > Discounts > Cart rules
- [ ] CONFIGURE - Shop parameters > Traffic & SEO > Referrers

### Helper Cards for pages with information needed

- [x] #10123 - CONFIGURE - Shop parameters > Traffic & SEO > SEO & URLs : "Improve your SEO"
- [x] #10565 - IMPROVE - Design > Pages : "Create meaningful content"
- [x] #10193 - SELL - Catalog > Categories : "Set categories"
- [x] #10559 - SELL - Customers > Customers : "Administrate your customers"
- [x] #10502 - CONFIGURE - Advanced parameters > Team : "Manage your team"
- [x] #10552 - SELL - Catalog > Monitoring : "Focus on your catalog"
- [x] #10511 - SELL - Catalog > Attributes & Features > Attributes
- [x] #25149
- [x] CONFIGURE - Shop parameters > Traffic & SEO > Search Engines
- [x] CONFIGURE - Shop parameters > Traffic & SEO > Referrers 

### Empty states for empty pages

- [x] #10545 - SELL - Catalog > Brands & suppliers > Suppliers
- [x] #10631 - SELL - Catalog > Products
- [x] #10550 - SELL - Catalog > Files
- [x] #10581 - SELL - Orders > Credit slips
- [x] SELL - Customer Service > Merchandise Returns

**Comment by CaptainYouz** [comment]
@colinegin: Started to work on it (Design>Pages: Create meaningful content) on commit https://github.com/CaptainYouz/PrestaShop/commit/85e0bccc8319784c3e0bec587144a153b667aa73. (WIP)

**Comment by LouiseBonnard** [comment]
Here is the doc with the wording: https://docs.google.com/document/d/1e_yu6f3Eq1c430k-a2QA9WLZwbwRSPsIeM_jhp09Jdg/edit

**Comment by sarjon** [comment]
> Here is the doc with the wording:

@LouiseBonnard we need access to it.

**Comment by LouiseBonnard** [comment]
@sarjon, oops, my bad, it should be fine now. :-)

**Comment by matks** [comment]
@TristanLDD On Invision, in project "Empty States BO" there is no screen for the Categories empty state.

**Comment by TristanLDD** [comment]
@matks, oops, my bad, it should be fine now. :-)

**Comment by matks** [comment]
> @matks, oops, my bad, it should be fine now. :-)

Hi @TristanLDD, we dont see the empty state 😐? What we need here is the Empty State card, you might have confused it with the Helper Card 😉there are both on Categories page.

**Comment by TristanLDD** [comment]
Hi @matks, the link in Coline's description works for me 🤔 There are two links, one for the helper cards and one for the empty states.

**Comment by TristanLDD** [comment]
Hi @matks, we realized yesterday that 3 empty states where missing, the Categories page empty state is one of them. Louise is working on the wording while I'm doing the design.

**Comment by TristanLDD** [comment]
@matks Actually, there is no empty state for the category page, only the helper card. Using both of them would be like duplicating the same content. Also the demo categories would prevent the empty state to display in the table, that's why using the card is more relevant.

**Comment by matks** [comment]
> @matks Actually, there is no empty state for the category page, only the helper card. Using both of them would be like duplicating the same content. Also the demo categories would prevent the empty state to display in the table, that's why using the card is more relevant.

Makes sense 👍thanks !

**Comment by ElodieOS** [comment]
Hi @colinegin and @matks ! 
Are there still design needs on this topic?

**Comment by ElodieOS** [comment]
Hello everyone! 

In view of the new product Edition, helper cards are no longer a topical issue. We won't be continuing this topic.

The empty state of cart rules will be designed for migration, so I propose to close this issue.
