### ISSUE TITLE
Migrate "Advanced Parameters > Team > Employees > Permissions" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10504]
Part of Symfony migration project
Type: page

**Why it is blocked?**
- Some major issue of the migrated page was found and NEED to be fixed. (That's why the page is hidden).

Todo:
- [x] Migrate page https://github.com/PrestaShop/PrestaShop/pull/12428
- [ ] Multistore header: [specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-3-the-page-can-be-displayed-only-in-all-shops-context)
- [ ] #19502 Add information message for multistore
- [ ] Show the page it is currently hidden
- [ ] Write doc about how Permissions work and how VueJS is used here
- [ ] Old bug number 1: https://github.com/PrestaShop/PrestaShop/issues/10216
- [ ] Old bug number 2: https://github.com/PrestaShop/PrestaShop/issues/10216
- [ ] Old bug https://github.com/PrestaShop/PrestaShop/issues/9572
- [x] Old bug number 3: https://github.com/PrestaShop/PrestaShop/issues/9567
- [x] Old bug number 4: https://github.com/PrestaShop/PrestaShop/issues/12656
- [x] Old bug number 5: https://github.com/PrestaShop/PrestaShop/issues/11547

**Comment by matks** [comment]
Note: see https://github.com/PrestaShop/PrestaShop/pull/11196#issuecomment-450896061

**Comment by marionf** [comment]
This issue should be solved with the migration of the page: #10216

**Comment by marionf** [comment]
Another issue related to permissions: #9567

**Comment by matks** [comment]
Aaaand another 😄 https://github.com/PrestaShop/PrestaShop/issues/12656

**Comment by PierreRambaud** [comment]
@matks #11547

**Comment by matks** [comment]
_left github_

**Comment by hibatallahAouadni** [comment]
Ping @matks what is the status of this issue?

**Comment by PierreRambaud** [comment]
The migration PR has been rebased #12428 we are still working on it afaik

**Comment by hibatallahAouadni** [comment]
Thanks @PierreRambaud :relaxed:

**Comment by PierreRambaud** [comment]
@matks What are we waiting for?
If it's related to automation tests about all possible rules, we should see with @boubkerbribri , otherwise we can maybe find a way to make it mergeable asap :)

**Comment by matks** [comment]
> @matks What are we waiting for?
> If it's related to automation tests about all possible rules, we should see with @boubkerbribri , otherwise we can maybe find a way to make it mergeable asap :)

Sorry I totally avoided this topic last months as I was focused on helping 1.7.8 must-have topics completed :) . Now that 1.7.8 is frozen we can dedicate some time to finish this stuff indeed.

I can review the PR 👍  . If we can have a QA confirmation from @Robin-Fischer-PS that "testing the migration page" is only about the page behavior, not the impacts of modifying permission settings, then we can start ASAP.

**Comment by PierreRambaud** [comment]
Nice to hear that. I will rebase the PR if @Robin-Fischer-PS confirm it, and can improve the previous code if needed

**Comment by Robin-Fischer-PS** [comment]
@PierreRambaud @matks : The functional test of this page will be : 

- Check the behavior of the page is OK
- Check in DB that the data are modified OK
- Check some impacts of modifying permissions settings (not all of them, just 2 or 3), in order to make sure there is no "huge and ugly" regressions.

I think the test of this page will not take more than one day, so we will be able to test it when 1.7.7.5 and 1.7.8.0 PR rush will be over.
