### ISSUE TITLE
Migrate "Catalog > Discounts > Cart rules" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10546]
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate listing #19048
- [ ] Add "New cart rule" button in listing [#19048 (comment)](https://github.com/PrestaShop/PrestaShop/pull/19048#issuecomment-723194566)
- [ ] Add clickable row button in listing [#19048 (comment)](https://github.com/PrestaShop/PrestaShop/pull/19048#issuecomment-723194566)
- [ ] Desing https://invis.io/C6Y03472EN3
- [ ] Use PR (that targets legacy controller) https://github.com/PrestaShop/PrestaShop/pull/12379 to re-apply fix on Symfony
- [ ] Add helper card
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] Modify install-dev/data/xml/quick_access.xml file for orders links

**Feature**
- [ ] [To be discussed] Allow a cart rule not to be compatible with all other cart rules (old and new) #19935

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by BilalDr** [comment]
This page needs to have an Empty States.
Check : Cart rules
https://projects.invisionapp.com/share/FQNYNAE6RDJ#/screens/319796788

Thanks

**Comment by marionf** [comment]
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
