### ISSUE TITLE
Migrate Catalog > Attributes & Features > Features page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10540]
Part of Symfony migration project
Type: page

Todo:
- [ ] Migrate listing and helper card 
PR: https://github.com/PrestaShop/PrestaShop/pull/15045

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by marionf** [comment]
Do you think we can solve this issue during the migration: #11217 ?

**Comment by marionf** [comment]
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] [Remove search fields when listings are empty](https://github.com/PrestaShop/PrestaShop/issues/17597)

**Comment by colinegin** [comment]
This page will need a helper card - design needs to be provided @TristanLDD

**Comment by TristanLDD** [comment]
> This page will need a helper card - design needs to be provided @TristanLDD

The helper card design is now ready for integration ;)

**Comment by LouiseBonnard** [comment]
Improvement #17926 to study when starting the migration.

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Could you please specify this issue status, is it **`To Do`** or **`WIP`**? 
For the moment, I add **`TBS`** label, but please change the status, Thanks!

Ping @marionf this issue is a **Feature** or an **Improvement**? cause it seems it has a lot of tasks :confused: 
Thanks in advance!

**Comment by matks** [comment]
PR started but not finished https://github.com/PrestaShop/PrestaShop/pull/15045

**Comment by zuk3975** [comment]
Don't forget to update facetedsearch module when feature values are finished
