### ISSUE TITLE
Migrate "Catalog > Discounts > Catalog price rules" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10549]
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate page https://github.com/PrestaShop/PrestaShop/pull/13584
- [x] Fix rounding issue https://github.com/PrestaShop/PrestaShop/pull/18691
- [ ] Migrate actions
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] Add empty state (see below)
- [ ] https://github.com/PrestaShop/PrestaShop/issues/14761 Implement FO cache clearing after catalog price rule creation/update

Rounding issue: https://github.com/PrestaShop/PrestaShop/issues/15890

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by BilalDr** [comment]
This page needs to have an Empty States.
Check : Catalog price rules 
https://projects.invisionapp.com/share/5FRLCBENAS4#/screens

Thanks

**Comment by zuk3975** [comment]
Don't forget to migrate condition groups (#13716 doesn't include them)

**Comment by marionf** [comment]
@matks Do you think it's possible to fix the following issue during the migration:
- [ ] https://github.com/PrestaShop/PrestaShop/issues/9862 ?

**Comment by matks** [comment]
> @matks Do you think it's possible to fix the following issue during the migration:
> 
> * [ ]  #9862 ?

No, this is not related to the page internal behavior, this is rather a multistore issue if the shop name is modified.

**Comment by colinegin** [comment]
Hello @zuk3975 , the empty state is missing in the listing when there is no catalog price rule yet, could you add it ? Here is the invision link : https://invis.io/5FRLCBENAS4#/358670484_Catalog_Price_Rules

Thanks !

**Comment by matks** [comment]
@MatShir Can you confirm the "recommended modules" button should be hidden on this listing page ?
Can you confirm the "recommended modules" button should be hidden on the related add/edit page https://github.com/PrestaShop/PrestaShop/issues/10548 ?

**Comment by MatShir** [comment]
@matks Only on the edit/add and **NOT** on the listing, https://github.com/PrestaShop/PrestaShop/issues/12846

**Comment by matks** [comment]
> @matks Only on the edit/add and **NOT** on the listing, #12846

Thanks !

**Comment by boo-code** [comment]
On the unchecked FO cache item, tracked as #14761: measured on `develop`, no clearing is needed for
price correctness, and its absence from the migrated handlers is not a regression. The front office
price follows a catalog price rule immediately in both directions with no cache clearing, because no
native module that renders a price uses Smarty output caching. Measurement and the module-side
invalidation hooks: https://github.com/PrestaShop/PrestaShop/issues/14761#issuecomment-5609727079

The other open boxes here (migrate actions, the two delete-confirmation modals #14462 and #17082,
empty state) are untouched by that.
