### ISSUE TITLE
Migrate "Customers > Customers" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10559]
Type: page
Status: in-progress

Part of Symfony migration project

![capture d ecran 2018-11-28 a 11 40 27](https://user-images.githubusercontent.com/3830050/49146441-726c8980-f302-11e8-946c-aaca86821453.png)

## Page structure
- listing (grid)
- KPI blocks
- row actions (toggle status, view, modify, delete, toggle partners offers newsletter subscription, toggle newsletter subscription)
- bulk actions (enable, disable, delete)
- form to set "required fields"

## Todo:
- [x] Migrate listing (grid) #10916
- [x] Migrate actions #11439
- [x] Migrate view page #10992
- [x] Migrate KPI blocks #11519
- [x] Add helper card https://github.com/PrestaShop/PrestaShop/pull/12128
- [x] Enable it https://github.com/PrestaShop/PrestaShop/pull/12971
- [x] Check customer view page performance with lot of orders/carts

Access : `/admin-dev/index.php/sell/customers/`

**Comment by BilalDr** [comment]
This page needs to have an Helper Card.
refer to this PR : #10434

Thanks

**Comment by marionf** [comment]
We need to think to change this link:
![capture d ecran_408](https://user-images.githubusercontent.com/13449658/46618654-69401700-cb20-11e8-9df3-17506c392953.png)

**Comment by matks** [comment]
PAUSE: Waiting for Product input 😄

**Comment by matks** [comment]
Status: needs to review List Actions PR and 1 last comment for KPI blocks

**Comment by sarjon** [comment]
do you think it's okay to have button in the bottom of the list? for me it seems like a bad UX, you have to scroll all the way down to access this action. :/

do you think we can improve it? @TristanLDD 

![required_fields](https://user-images.githubusercontent.com/15143151/49937847-bf468780-fee0-11e8-85cc-a141ebc3732b.png)

**Comment by TristanLDD** [comment]
Hello @sarjon 

Indeed, this button's position is not optimal, can you please post a screenshot of the whole migrated page so I can figure out a solution?

**Comment by sarjon** [comment]
Here's more or less full page, you can see button on the bottom of the page. When opened in browser, in order to see it you must scroll down.

![customers](https://user-images.githubusercontent.com/15143151/50150168-d5c85680-02c5-11e9-84f9-c451bb937eb5.png)

**Comment by TristanLDD** [comment]
I suggest that we move the button to the top right of the table (on the same line as the bulk action button but on the right), on clic the button will open the same panel as legacy but above the table instead of below it

**Comment by sarjon** [comment]
> I suggest that we move the button to the top right of the table

@matks I don't think we can fix this in 1.7.6.x. It requires improvement for Grid component to allow adding new buttons to it. :/

**Comment by matks** [comment]
> > I suggest that we move the button to the top right of the table
> 
> @matks I don't think we can fix this in 1.7.6.x. It requires improvement for Grid component to allow adding new buttons to it. :/

Agreed 👍
