### ISSUE TITLE
Migrate "Customers > Customers > Add new / edit customer" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10560]
Type: page
Status: in-progress
Part of Symfony migration project

![capture d ecran 2018-12-18 a 10 39 23](https://user-images.githubusercontent.com/3830050/50145170-37ca9100-02b1-11e9-8bb7-bbdb3ae7f9c0.png)

## Todo:
- [x] Migrate form Migrate customer Add/Edit actions #11723
- [x] Migrate ajax customer search route #11783
- [x] Migrate quicklink (see Marion comment below) https://github.com/PrestaShop/PrestaShop/pull/12971
- [x] Update commands/queries to accept native values in Customer subdomain https://github.com/PrestaShop/PrestaShop/pull/13256
- [x]  Clean up `CustomerController` to reorder methods https://github.com/PrestaShop/PrestaShop/pull/13256

Access: `/admin-dev/index.php/sell/customers/` then click on "edit" a customer

**Comment by marionf** [comment]
We need to change this link:
![capture d ecran_408](https://user-images.githubusercontent.com/13449658/46618928-09963b80-cb21-11e8-9fad-ae3e7b2b20b9.png)

**Comment by colinegin** [comment]
Hello @LouiseBonnard , after discussion with @matks (thanks for your feedback @sarjon !), we are thinking that it might be interesting to add an information related to the configuration of customer groups in the customer edit page, in the group section (see screenshot below). What do you think ?

![image](https://user-images.githubusercontent.com/35263827/51263022-c49d6300-19b3-11e9-87e4-12d04acbb472.png)

**Comment by LouiseBonnard** [comment]
You mean dropping a line to explain how customers groups can be configured?

**Comment by LouiseBonnard** [comment]
Hey guys, here are two wordings to help users find their path in the back office:

- Give your customers some privileges, assign them to customer groups in Shop Parameters > Customer Settings

- Remember,/Booster shot: you can create/edit your customer groups in Shop Parameters > Customer Settings

I guess we can localize it in Admin.Shopparameters, but I need to know how it will be integrated to decide if it should be in the Feature or the Help file. ;-)

**Comment by colinegin** [comment]
Option 2 seems more suitable to me, customer groups don't always mean "privileges", rather a categorization or segmentation IMO.

**Comment by sarjon** [comment]
> We need to change this link:

@matks regarding @marionf comment, it seems like "fun". :smile: Customers form (_lite_ version of it, this is how its called) from legacy controller is rendred inside `iframe` in Orders legacy page... do you have suggestions how we deal with it? i dont feel like rendering iframe in new page is good idea.

**Comment by matks** [comment]
@sarjon But this is a true feature, and it makes sense: it provides a quick way to input a new order for a new customer.

Well I guess it's either a modal or a hidden form that pops when button is clicked, isn't it ? But the modal here seems to be used properly: you want to disable the "create order" page while the backoffice user is creating the customer. I have seen a lot of modals badly used but this one seems relevant 😉 .

Wdyt ?

**Comment by sarjon** [comment]
so you're saying we should implement it using `iframe`?

**Comment by matks** [comment]
I see nothing against it. But you seem reluctant 😉please tell what are your reasons against iframes and modals.

**Comment by sarjon** [comment]
no no, im not against modals or iframes. i just was wondering whther using `iframe` instead of simple form inside modal has advantages/disadvantages? :thinking:

**Comment by matks** [comment]
I guess the modal form (without iframe) requires more work as you have to handle the validation / submit / display error or success messages with ajax calls while iframe kindof provides you this of the shelf.

**Comment by sarjon** [comment]
Additional things left to do:
- [ ] Update commands/queries to accept native values in Customer subdomain 
- [ ] Clean up `CustomerController` to reorder methods

**Comment by matks** [comment]
@sarjon 👍 Added to issue description
