### ISSUE TITLE
Migrate "Design > Image Settings > Add new / edit image type" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10564]
Part of Symfony migration project

## Status

This page is a form to edit Image Settings. When clicking on "save" user is redirected to the listing https://github.com/PrestaShop/PrestaShop/issues/10563

In order to finish the migration of this back-office page, we need to:

**Todo List**:
- [x] Continue the PR [https://github.com/PrestaShop/PrestaShop/pull/22159 (see below)
- [ ] The [Multistore header](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178) must also be added to the new Symfony page (if it is not already implemented). You can look at other migrated Symfony pages to see how it is built.
- [ ] New feature to add to the Symfony page: make the page multistore-compliant by introducing #19412
- [x] Finally, we need a _last Pull Request_ to remove the legacy backoffice page and enable the Symfony page (see below)

Please submit one PR for each todo list item.

## About PR https://github.com/PrestaShop/PrestaShop/pull/22159

Please note that in PR https://github.com/PrestaShop/PrestaShop/pull/22159 the contributor wanted to migrate 2 pages together: this one AND https://github.com/PrestaShop/PrestaShop/issues/10563 . It might be wiser to split it into 2 PRs to make code review and testing easier... but we let you decide if this is interesting or a waste of time.

The PR https://github.com/PrestaShop/PrestaShop/pull/22159 aimed to create a new Symfony backoffice  page to replace the legacy page "Design > Image Settings". It was created by a motivated contributor. The new Symfony page should follow the [coding standards](https://devdocs.prestashop-project.org/8/development/architecture/migration-guide/) we have for all Symfony pages while providing the same behavior that the legacy page. It aims to create an equivalent page, but powered by Symfony and Twig :) .

Just like other Symfony pages, the application layer is Symfony + Twig, but it uses the Grid system to fetch and display data.

What you must do for PR https://github.com/PrestaShop/PrestaShop/pull/22159 is to fetch it
- Verify it is correct (for you), if not please fix wrong items you have found
- Have it reviewed (and approved) by committers
- The QA will not test it: they will test the last PR (see below)

## About the last PR

First Todo List items will be done by multiple PRs merged into `develop`. So the work of "create a new Symfony page that provides the same behavior/features as the legacy page" will be carried out BUT it is done on a Symfony page not accessible yet in the backoffice. You can browse it if you know the URL. It's like it's hidden.

In order to "finish" the job, a last PR is needed: this is the PR which _removes legacy files_ and enables the LegacyLinks that will redirect old URLs to the new page. So the new Symfony page replaces the legacy page in the back-office. When this is done, the migration is complete.

It is possible QA will find problems when testing the last PR: behaviors that used to work with the legacy page and are not working / implemented in the Symfony page. Then you must fix them.

Please ask @MatShir if you have questions about the behavior or @matks if you have questions about the code
