### ISSUE TITLE
Migrate "Design > Theme & Logo" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10576]
Type : page
Part of Symfony migration project

![capture d ecran 2018-11-28 a 16 42 13](https://user-images.githubusercontent.com/3830050/49163107-9a70e280-f32c-11e8-99ef-20d21738487b.png)

## Page structure

4 image upload fields and some rendering

## Todo:
- [x] Migrate page, careful with specs https://github.com/PrestaShop/PrestaShop/pull/11169 especiall RTL block and multi-store behavior
- [x] Handle UX improvements https://github.com/PrestaShop/PrestaShop/pull/12331
- [x] If user submits an oversized logo, resize it for the preview
- [x] Check it is compatible with MBO which displays "LIVE FROM PRESTASHOP ADDONS!" footer
- [ ] If it does not exist, add a hook when Theme is reset
- [ ] For PS Ready, check "explore more than X themes" can be hidden

**Comment by matks** [comment]
We have specifications for this page :) ask me when you start it

**Comment by BilalDr** [comment]
You can check specifications : [here ](https://docs.google.com/document/d/1krTRDT40MOpAxePGNap89hpAXFTdR2dIe2t3CQ0e1Uc/edit)

**Comment by matks** [comment]
Status: latest code review feedbacks

**Comment by matks** [comment]
@sarjon We have the design specs 😄 tell me when you get back to work
I'll show you what @TristanLDD has designed for us

**Comment by tomas862** [comment]
Hi @TristanLDD - I can't find any images on zeplin where I can download them. For instance, 
![assets](https://user-images.githubusercontent.com/17051250/51839984-75402680-2313-11e9-8cfb-85b61ea365c0.png)

**Comment by TristanLDD** [comment]
Hi @tomas862 
I don't know what's the problem with Zeplin so I'm going to send you all the assets by email ;)
