### ISSUE TITLE
Migrate "Orders > Shopping Carts" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10584]
Type: page
Part of Symfony migration project

## Status

Todo :
- [ ] Migrate listing
- [ ] Migrate KPIs
- [ ] Remove "Delete" actions from carts that have placed orders (see https://github.com/PrestaShop/PrestaShop/issues/10584#issuecomment-723147564)
- [ ] [Add a modal to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)

Previous PRs for step 1: https://github.com/PrestaShop/PrestaShop/pull/17883 and https://github.com/PrestaShop/PrestaShop/pull/17326

### Controller / template
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by LouiseBonnard** [comment]
Hi there, do we have specifications for this page?

**Comment by matks** [comment]
> Hi there, do we have specifications for this page?

Not that I'm aware, but this page looks simple to understand. @tdavidsonas88 started the work of finishing it, he might have questions though.

ping @tdavidsonas88

**Comment by tdavidsonas88** [comment]
Simple to understand; QA left feedback about the missing changes here: https://github.com/PrestaShop/PrestaShop/pull/14098

**Comment by colinegin** [comment]
Related to the following PR : #17326

**Comment by matks** [comment]
@MatShir I just checked this Page.

I see we added "Remove "Delete" actions from carts that have placed orders." in the TODO List but when I look at current Shopping Carts list, I see no DELETE button 🤔  and there is no Bulk Actions enabled.

So ... maybe "Remove "Delete" actions from carts that have placed orders." is a mistake ?

**Comment by MatShir** [comment]
It looks like it appears only when the cart is not paid.
![image](https://user-images.githubusercontent.com/43613217/98385179-fda63c00-204e-11eb-9f11-355e17e519e4.png)

**Comment by matks** [comment]
> It looks like it appears only when the cart is not paid.
> ![image](https://user-images.githubusercontent.com/43613217/98385179-fda63c00-204e-11eb-9f11-355e17e519e4.png)

Nice ! indeed

**Comment by matks** [comment]
PR started but stale https://github.com/PrestaShop/PrestaShop/pull/17883
