### ISSUE TITLE
Migrate "Shipping > Carriers > Add new / edit carrier" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10586]
Part of Symfony migration project
Type: page

# Status

Todo:
- [ ] Create "add carrier" command https://github.com/PrestaShop/PrestaShop/pull/14551
- [ ] At each save make sure there is data modification before for saving a new carrier in the database 
- [ ] https://docs.prestashop-project.org/functional-documentation/functional-documentation/ux-ui/back-office/improve/shipping/carrier
- [ ] https://www.figma.com/file/QlgjdPJHkpTZ8NSgLa4qzr/Carrier-page?type=design&node-id=0%3A1&mode=design&t=VLVfvOOawEK9yXvJ-1 mock up with new feature ideas
- [ ] Migrate form rendering https://github.com/PrestaShop/PrestaShop/pull/14397
- [ ] Improve wording https://github.com/PrestaShop/PrestaShop/issues/10586
- [ ] Fix old bugs (see below)
- [ ] Multistore header: [specs](https://github.com/PrestaShop/prestashop-specs/blob/master/broader-topics/multistorespecialsspecs.md#list-of-pages-for-specific-case-3-the-page-can-be-displayed-only-in-all-shops-context)

Old bugs:
- [ ] #10384
- [x] https://github.com/PrestaShop/PrestaShop/issues/15214

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by eternoendless** [comment]
We should investigate this issue when we start working on this page: #10384

**Comment by zuk3975** [comment]
@matks, should the carriers form be powered by some kind of vue component that would be used in products page (as suggested for products page at #14492)?

**Comment by matks** [comment]
> #14492

After diving further, we have decided not to use vue.js for the Product Page, we will rely on good old jQuery in order to make the page as customizable as possible.

I think the answer is valid for this page too :/ jQuery it is !

**Comment by rblaurin** [comment]
Hi
Isn't it going to be ready for 1.7.7 anymore?

Thanks!

**Comment by matks** [comment]
> Hi
> Isn't it going to be ready for 1.7.7 anymore?
> 
> Thanks!

Probably not, all of our energy right now is focused on Orders pages (listing, create, view)

**Comment by matks** [comment]
PR started but not finished https://github.com/PrestaShop/PrestaShop/pull/14551

**Comment by matks** [comment]
Another PR on the topic https://github.com/PrestaShop/PrestaShop/pull/14397

**Comment by Hlavtox** [comment]
@matks @kpodemski Few improvements I would like to ask about.

### Min & max
If the price will be 20, what range will it fall into? On the old page, there was clearly specified **LOWER THAN** and **EQUAL OR BIGGER THAN**.

![carrier-ranges-modal](https://github.com/user-attachments/assets/806ac456-98bb-4a86-8eff-deb8b4641c01)

### Range gaps
Are gaps in between ranges handled? I was now resolving a case when a client had following carrier.
Range A, 0-10 CZK
Range B, 11-20 CZK
Range C, 21-30 CZK
Range D 31-99999 CZK
If outside of range, use highest range.

Cart was 10 CZK and client was wondering why the shipping price was falling into the 31-99999 CZK range. Because 10 CZK doesn't fall neither into A or B range.
