### ISSUE TITLE
Migrate "Shop parameters > Search > Search" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10591]
Part of Symfony migration project
- [x] #32019
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)
- [ ] #19369 - Checkboxes for multistore
- [ ] #19321 - Specific settings dropdown for multistore
- [x] #32479
- [x] #32480
- [x] #32481
- [x] #32482
- [x] #32667

**Comment by marionf** [comment]
We need to think to change the link here:

![capture d ecran_406](https://user-images.githubusercontent.com/13449658/46617921-575d7480-cb1e-11e8-93ac-3086b566bbd4.png)

**Comment by zuk3975** [comment]
@aleksiuno

**Comment by aleksiuno** [comment]
On it
