### ISSUE TITLE
Migrate "International > Locations > States" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10606]
Part of Symfony migration project
Type: page

## Status

Todo:
- [x] Migrate listing https://github.com/PrestaShop/PrestaShop/pull/15032
- [x] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [x] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [x] States page - Add new states button is not displayed after incorrect Save #21183
- [x] #29345

#### Controller / routing
- [x] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [x] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [x] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [x] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [x] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [x] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [x] The new controller actions comply with our naming convention
- [x] The new SF routes names and paths comply with our naming convention
- [x] The new Twig template names comply actions with our naming convention
- [x] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [x] CSS being added must follow theme conventions

#### Core layer
- [x] Commands and Queries only use native types but internally use VOs
- [x] All Handlers must have an Interface
##### Conventions
- [x] The created SF service names comply with our naming convention
- [x] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [x] The legacy controller and templates files are gone
- [x] If PR includes a new concept/mechanism, documentation must be written
- [x] JS and CSS assets must be compiled and up-to-date
- [x] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [x] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [x] Commands and Queries are tested with Behat tests
- [x] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [x] (soon) Controller is covered with E2E tests using puppeeter
- [x] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

**Comment by matks** [comment]
https://github.com/PrestaShop/PrestaShop/pull/15032

**Comment by matks** [comment]
Pull Request started but not completed https://github.com/PrestaShop/PrestaShop/pull/15032
