### ISSUE TITLE
Migrate "Shop parameters > Order settings > Statuses" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10619]
## Status

The "Order Statuses" page has been migrated to Symfony but is hidden because there is a few remaining issues. I mistakenly tried to fix all the remaining issues in a single PR https://github.com/PrestaShop/PrestaShop/pull/20442 because each issue needs only some lines of code, so I wanted to submit one PR with medium size rather than PRs with each 10 lines of code.

**It was a mistake** because one issue was eventually found to be much complicated than expected and the PR is blocked so none of the issues are fixed. I will probably have to circle back to submit 1 PR per issue.

So this issue is blocked because of this. Work has been done in https://github.com/PrestaShop/PrestaShop/pull/20442 to fix it but QA has found issues.

<hr>

Part of Symfony migration project
Specs:
https://github.com/PrestaShop/prestashop-specs/pull/83

Todo:
- [x] Migrate page https://github.com/PrestaShop/PrestaShop/pull/17215
- [x] Removes the column Icon (as it is not used anymore)
- [x] @LouiseBonnard  rewording to do, especially on "delivery"
- [x] #19495 Add information message for multistore
- [x] [Add a modal to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
  - #27606
- [x] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
  - #27606

**Comment by marionf** [comment]
To be done during the migration of the page : 

**Features:**
- [x] #15228

**Issue for this page:**
- [x] #12105
- [x] #13838

**Comment by LouiseBonnard** [comment]
Sooo, I've just checked the wording with @MatShir and I have two recommendations regarding the 'Delivery' column and the (wrongly) related tickbox 'Show delivery PDF' - undoubtedly an inheritance of the 1.5 version. Here it is:

- ~keep the 'Delivery' column and name the tickbox with the following wording, _Consider the associated order in delivery._~

- **rename the column 'In transit' and name the tickbox with the following wording, _Set the order as in transit._**

Both solutions suit me fine, I then let @MatShir pick the one he prefers!

**Comment by LouiseBonnard** [comment]
Hi @sowbiba, we've just made up our minds with @MatShir, we will keep the second option. Could you please apply it to the related PR, #17215? Many thanks!

**Comment by matks** [comment]
Will be done by https://github.com/PrestaShop/PrestaShop/pull/17215
