### ISSUE TITLE
Migrate "Shop parameters > Contact > Stores" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10624]
Part of Symfony migration project
- [x] Migrate stores grid with filtering and pagination working (https://github.com/PrestaShop/PrestaShop/pull/31802)
- [ ] Contact form
- [ ] [Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action](https://github.com/PrestaShop/PrestaShop/issues/14462)
- [ ] [Add a modal to confirm or cancel delete action for one row](https://github.com/PrestaShop/PrestaShop/issues/17082)
- [ ] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)
- [ ] #19367 - Checkboxes for multistore
- [ ] #19319 - Specific settings dropdown for multistore

**IMPROVEMENT(S) TO STUDY**

- [ ] #16133 - No set Stores should hide "Our stores" from sitemap -> pages list.

**Comment by marionf** [comment]
We need to think to change this link: 
![capture d ecran_411](https://user-images.githubusercontent.com/13449658/46619207-d902d180-cb21-11e8-9231-043d3691aef8.png)
