### ISSUE TITLE
Migrate "Shop parameters > Customer settings > Groups" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10626]
Part of Symfony migration project

Scope:
- [x] Group list - https://github.com/PrestaShop/PrestaShop/pull/30929
- [ ] Default groups options

Todo: 
- [ ] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)
- [ ] #19366 Checkboxes for multistore
- [ ] #19318 Specific settings dropdown for multistore

Improvements:

- [ ] #21676 Be able to move in bulk clients from one group client to another

Bugs:

- [ ] #21894 Enable/disable members of a customer group isn't working and checkboxes for bulk actions aren't displayed for the 3 first users

**Comment by sarjon** [comment]
@matks would you mind assigning it to me? i've started it then didn't have anything else to do, so i could continue when time comes. :)

**Comment by ks129** [comment]
I would like to get assigned.

I also have a question about currently migrated page - it seems like it doesn't have "Creation date" column and uses 0/1 for "Show prices" column. I cannot find from the original PR if it was intentional or should be fixed.
