### ISSUE TITLE
Improve Catalog > Products page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10631]
Part of Symfony migration project - this page needs rework to be built the same way other migrated pages are done
Type: page

## Status

Todo:
- [x] NumberMinMaxFilterType and IntegerMinMaxFilterType https://github.com/PrestaShop/PrestaShop/pull/14320
- [ ] Introduce new category tree button type https://github.com/PrestaShop/PrestaShop/pull/14619
- [ ] Introduces asynch position column extension https://github.com/PrestaShop/PrestaShop/pull/14528
- [ ] Introduces async bulk action https://github.com/PrestaShop/PrestaShop/pull/14542
- [ ] Migrate list https://github.com/PrestaShop/PrestaShop/pull/14267
- [ ] Migrate list part 2 #10631
- [ ] Add empty state : https://invis.io/5FRLCBENAS4#/358670592_Catalog
- [ ] Check previously known bugs are fixed or fix them
- [ ] Replace checks and crosses on table by toggles and try to not refresh the page when clicking on toggles (show a toast alert instead) (#17177)
- [ ] rewording the reorder button https://github.com/PrestaShop/PrestaShop/issues/17412#event-3336576481
- [ ] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)

#### Controller / routing
- [ ] All controller actions are migrated and protected with `@AdminSecurity` annotations when eligible and `@DemoRestricted` annotations when eligible
- [ ] All links targeting this page are updated: either using _legacy_link or updating the code
- [ ] The new SF routes have `_legacy_link` and `_legacy_parameters` provided and explained
- [ ] Controller catches Domain Exception and translate them nicely
- [ ] Add/Edit controllers must catch global Exception in order to handle ModuleErrorException
#### Template
- [ ] Twig templates must contain relevant blocks to allow partial extension by modules
- [ ] Twig forms must have `form_rest()` and `form_errors()`
- [ ] JS being used on the page can be used as enabled extensions and use a PageMap for selectors
- [ ] Use `@PrestaShop` instead of `PrestaShopBundle` for template root path aliasing
##### Conventions
- [ ] The new controller actions comply with our naming convention
- [ ] The new SF routes names and paths comply with our naming convention
- [ ] The new Twig template names comply actions with our naming convention
- [ ] Created files (controller, JS assets, CSS assets and twig views) must be in the right folder following the convention
- [ ] CSS being added must follow theme conventions

#### Core layer
- [ ] Commands and Queries only use native types but internally use VOs
- [ ] All Handlers must have an Interface
##### Conventions
- [ ] The created SF service names comply with our naming convention
- [ ] The created files must follow the folder convention (Domain, Core, Adapter...)

#### Polishing
- [ ] The legacy controller and templates files are gone
- [ ] If PR includes a new concept/mechanism, documentation must be written
- [ ] JS and CSS assets must be compiled and up-to-date
- [ ] License headers must be up-to-date
- [ ] New hooks have been added to the hooks list and the SQL updates
- [ ] Performance must be correct: page loading time, filtering/sorting/searching response time, actions response time

#### Testing
- [ ] Commands and Queries are tested with Behat tests
- [ ] Eligible Core classes are covered with unit tests*
- [ ] Controller is covered with survival test
- [ ] (soon) Controller is covered with E2E tests using puppeeter
- [ ] If we break E2E tests because IDs change, we must update the E2E tests

*Eligible = easy to isolate and unit tests provide values (for example testing getters/setters is useless)

## Specs
https://github.com/PrestaShop/prestashop-specs/blob/marionf-patch-1/back-office/catalog/catalog-products-listing.md

**Comment by BilalDr** [comment]
This page needs to have an Empty States.
Check : product page : 
https://invis.io/5FRLCBENAS4#/358670592_Catalog

Thanks

**Comment by marionf** [comment]
**Issues on this page:** 
Need a deep study of the multistore issue, to see if we let them in must-have

**Must have**
- [ ] #17885 - Monitoring page empty categories list view action differs from legacy
- [ ] #14713 - BO | Products listing page empty after deleting products in bulk
- [ ] #9612 - [BOOM-5808] Product listing page empty after switching between shops - **`Multistore`**
- [ ] #15291 - Reorder product in category is not working in some condition
- [ ] #9613 - [BOOM-5806] "All shops" view not showing 2nd store products in Multistore - Product Page - **`Multistore`**
- [ ] #14175 - Sorting products not working after duplicating product and changing pages
- [ ] #9811 - [BOOM-4293] Delete category & associate product

**Should have**
- [ ] #10236 - Alt tag empty in product listing BO

**Nice to have**
- [x] #9551 - [BOOM-6136] problem with layout in BO/Products/Filter
- [ ] #11167 - Strange behavior if put in the Min filter a character

**Improvement**
- [ ] #13397 - Duplicate product without image
- [ ] #15398 - BO: Sort items/products for lists>300 not possible
- [ ] #17942 - Can't cancel 'Reorder' in the products listing

**Comment by marionf** [comment]
Specs for the listing to be reviewed by @Robin-Fischer-PS & @MatShir 

https://github.com/PrestaShop/prestashop-specs/blob/marionf-patch-1/back-office/catalog/catalog-products-listing.md

**Comment by hibatallahAouadni** [comment]
Hello, I'm confused :confused: is this an **improvement** or a **feature** or an **epic**?

**Comment by MatShir** [comment]
Issues tag with migration label are usually big epic. We don't flag them as Epic not to pollute the others epic. They don't have the same purpose. Here it is more a to-do list for not forgetting any element during the migration of the page but the other epic are collect of issues with a commun problem.

**Comment by hibatallahAouadni** [comment]
@MatShir thanks for clarification :wink:
