### ISSUE TITLE
Improve "Catalog > Products > Add new / edit product" page & "Products List" page

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#10632]
Part of Symfony migration project - this page needs rework to be built the same way other migrated pages are done
Type: page

# Product Page Multistore migration

Use the opportunity of product page migration to provide the best product page for merchants that is compatible with multistore.

Many merchants have difficulties about the multistore that is not quite fully working. The multistore actions are unclear on the product page. The merchant doesn't understand if the actions will impact all the shops or not.

## Status

Todo:
- [x] Find all technical obstacles and fix them, see https://github.com/PrestaShop/PrestaShop/issues/14405
- [x] Prepare the new architecture, see https://github.com/PrestaShop/PrestaShop/issues/14492
- [x] Multistore header: [Specs](https://github.com/PrestaShop/prestashop-specs/blob/7e820f30347fe69ccd3db5a99ab02ef6f7bbdd54/back-office/multistoregeneralspecs.md#multistore-header-only-from-178)
- [x] Multistore - Update message when a group is selected https://github.com/PrestaShop/PrestaShop/issues/19459
- [x] Enable product page as stable one https://github.com/PrestaShop/PrestaShop/issues/31086
- [x] #31373
### Left todo
**Product List**

- [x] Button Preview https://github.com/PrestaShop/PrestaShop/pull/29039
- [x] Duplicate 
- [x] Delete 
- [x] Enable/Disable 

**Multishop**

//Product List
- [x] Modal to select shop on creation when listing is in All shops
- [x] The multishop selector in product page only shows shops associated to current product & Handle « add product » for multishop (assignation) https://github.com/PrestaShop/PrestaShop/pull/27712
- [x] #29986
- [x] #29987
- [x] Enable/Disable from all shop / one shop https://github.com/PrestaShop/PrestaShop/pull/28245

//Product Add/Edit
- [x] #30119
- [x] #30120
- [x] #30121
- [x] Handle BasicInformation for multishop
- [x] Handle prices data for multishop https://github.com/PrestaShop/PrestaShop/pull/25464
- [x] Handle seo data for multishop
- [x] Handle options data for multishop
- [x] Handle stock data for multishop
- [x] #29343
- [ ] #30124 (postponed to V9 for BC reasons)
- [x] Handle customization fields data for multishop
https://github.com/PrestaShop/PrestaShop/issues/27579
- [x] Handle combinations data generation for multishop https://github.com/PrestaShop/PrestaShop/pull/28395
- [x] Handle combination single/bulk deletion for specific shop and all shops https://github.com/PrestaShop/PrestaShop/pull/28395
- [x] Handle combination form & bulk combination data modification for multishop https://github.com/PrestaShop/PrestaShop/pull/30590
- [x] Handle attachment data for multishop
- [x] handle manufacturer data for multishop
- [x] #29988 (https://github.com/PrestaShop/PrestaShop/pull/31099)
- [x] #30735
- [ ] Fix bug with shared group stock #26738 
- [ ] #31087
- [ ] #31088

//Combinations
- [x] Missing parts for combination mutlishop behavior https://github.com/PrestaShop/PrestaShop/issues/30304
- [x] I generate combination in multishop with attributes not assiociated to all the shops https://github.com/PrestaShop/PrestaShop/issues/30969

**Basic settings**
- [x] Refactor search component
- [x] [Pack] List pack products with images https://github.com/PrestaShop/PrestaShop/pull/27304
- [x] [Related Product] Search component with deletable list items
- [x] [Pack] Endpoint for searching pack products & for adding pack product (ajax action)
- [x] [ Related Product] Search endpoint, form input
- [x] [ Related Product] Search endpoint, form input

**Details tab**

- [x] [File] form type for file upload + command builder + list of files
- [x] [File] form type for file upload + command builder + list of files
- [x] #29819

**Pricing**

- [x] [Specific prices] Form type + command builder + list
- [x] [Specific prices] EditProductSpecificPriceCommand
- [x] [Specific prices] show/hide form for Creating specific price
- [x] [Specific prices] Show/hide modal for Editing specific prices
- [x] [Specific prices] Form type for create/edit + command builder + list template
- [x] [Specific prices\| Handle delete from list
- [x] [Priority management] Form type for priorities + command builder #26938
- [x] New design for pricing (placement of inputs) + preview
- [x] Add ecotax behavior
- [x] https://github.com/PrestaShop/PrestaShop/issues/28997

**Combinations**

- [x] [Edit] formType for bulk edit combination + command builder
- [x] Bulk Delete combinations
- [x] Bulk Delete combinations by filters
- [x] Bulk image associations (command)
- [x] Bulk combination edtion (by Filters / Ids)
- [x] Availability preferences
- [x] Save of the combination’s listing
- [x] Handle delta quantity in combination form
- [x] Handle stock movements display in combination form 

**Creation product**

- [x] modal for the creation of a product
- [ ] Hook for the modal

**Change the product**

- [ ] How the old product data are managed after the product is changed ?

**Quantities**

- [x] quantities with the delta (for product)
- [x] Add movements history grouping in product page https://github.com/PrestaShop/PrestaShop/pull/28640

**New display**

- [x] Move the « Condition » to « Specification » tab #27275
- [x] New header #27233
- [ ] Global UI

**Duplicate**

- [x] Duplicate product
- [x] Cover Dupliaction feature by behats.

**Categories**

- [x] Add new category widget
- [x] https://github.com/PrestaShop/PrestaShop/issues/28995

**Hook**

- [x] Add the tab into the form
- [x] Tab out side of the form for modules

**Footer**

- [x] [Links] preview, Go to catalog, Add new Product

**Option**
- [x] Show/hide « show_price » depending on « available_for_order »
- [x] Improve combination suppliers
- [x] Sync combination wholesale price with default supplier’s price

**SEO tab**
- [x] Tags should be handled by existing component #27328 
- [x] Handle automatic fill of friendly url or else images are not shown and url is invalid

**Shipping tab**
- [x] show/hide delivery time notes depending on type

**Polishing**
- [x] Modules extensibility

**Nice to Have**
- [ ] Combination modal, history panel should be expandable/reducable
- [x] [Specific Prices\| Final design based on mockups
- [ ]  Performance optimization when loading categories in the page
- [ ]  Save only the input edited
- [ ]  Saving notification to let the user know the inputs to save
- [ ] [Priority management] improve priority component with drag and drop feature

Check the issue group by tabs
- [ ] Migrate Basics tab https://github.com/PrestaShop/PrestaShop/issues/14763
- [x] Migrate navbar and layout elements https://github.com/PrestaShop/PrestaShop/issues/14770
- [ ] Migrate tab Quantities https://github.com/PrestaShop/PrestaShop/issues/14771
- [ ] Migrate tab Virtual Products https://github.com/PrestaShop/PrestaShop/issues/14772
- [ ] Migrate tab Combinations https://github.com/PrestaShop/PrestaShop/issues/14773
- [ ] Migrate tab Carriers https://github.com/PrestaShop/PrestaShop/issues/14774
- [ ] Migrate tab Prices https://github.com/PrestaShop/PrestaShop/issues/14775
- [ ] Migrate tab SEO https://github.com/PrestaShop/PrestaShop/issues/14776
- [x] Migrate tab Options https://github.com/PrestaShop/PrestaShop/issues/14777
- [ ] Check all previously known bugs are fixed, or fix them (see below)

**Comment by marionf** [comment]
### - Issues when **duplicating a product** sorted by priority high to low :

**Should-Have**
- [ ] #9828

**Nice to have**
- [x] #11496 PR: https://github.com/PrestaShop/PrestaShop/pull/15712

**New feature**
- [ ] #13397


### - Issues related to **permission** sorted by priority high to low :

**Should-Have**
- [ ] #12636

### - Improvement
- [ ] #15330

**Comment by sarjon** [comment]
Regarding new product page, should we keep same language behavior as it is now:
![old_lang](https://user-images.githubusercontent.com/15143151/62050407-d9d43380-b219-11e9-8dc8-7de27858676c.png)

Or should we use we use language switch as in any other page:
![new_lang](https://user-images.githubusercontent.com/15143151/62050447-e8bae600-b219-11e9-8b37-833e7bddd68a.png)


ping @TristanLDD @eternoendless

**Comment by TristanLDD** [comment]
Hi @sarjon, 
We should use the same language switch as in the other pages 
Thanks!

**Comment by sarjon** [comment]
@TristanLDD just to confirm, we should use this one:

![](https://user-images.githubusercontent.com/15143151/62050447-e8bae600-b219-11e9-8b37-833e7bddd68a.png)

Right?

If so, I should mention that each translatable field in product form will get this dropdown (descriptions, meta inputs and others), it **isn't** the case in current implementation, as there is only one non standard switch.

Is that ok?

**Comment by TristanLDD** [comment]
> @TristanLDD just to confirm, we should use this one:
> 
> ![](https://user-images.githubusercontent.com/15143151/62050447-e8bae600-b219-11e9-8b37-833e7bddd68a.png)
> 
> Right?

Yes 


> If so, I should mention that each translatable field in product form will get this dropdown (descriptions, meta inputs and others), it **isn't** the case in current implementation, as there is only one non standard switch.
> 
> Is that ok?

Yes this behavior will make the translatable fields more recognizable which is a good thing.

**Comment by colinegin** [comment]
FYI @MatShir i just removed this issue from 178 kanban as we should only have issues in the kanban and not EPICs.
