### ISSUE TITLE
[EPIC] Wishlist module integration on PrestaShop 1.7 versions

### ISSUE THREAD

**Issue by BilalDr** [PrestaShop/PrestaShop#11277]
**Description update** 

Add a native module to core features making it possible for merchants to have wishlists on their own websites. 

Here is a detailed user story view that will be addressed for the development of the new wishlist module which will be available on versions >1.7.6.

### Feature 1 : Add to favorites

- [x] #18779 - US 1 - Add an item to a wishlist
- [x] #18780 - US 2 - See my saved favorite items
- [x] #18781 - US 3 - Edit and delete a favorite item

### Feature 2: Creating and Managing Wishlists

- [x] #18782 - US 4 - Add a favorite product to cart
- [x] #18783 - US 5 - Create a new wishlist
- [x] #18784 - US 6 - Modify and delete a wishlist
- [x] #18785 - US 7 - Share a wishlist

### Feature 3 : Back office management

- [x] #18786 - US 8 - Configure the module and view statistics

### Other elements
- [ ] [Addons block ](https://github.com/PrestaShop/PrestaShop/issues/11402)
- [x] #23486 - Wrong cover image for product in block wishlist

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Outdated description** 

Wishlist module ; Adds a block containing the customer's wishlists.

- [x] [All UX Improvement ](https://invis.io/CFOXVATPTUG#/329439751_Page_Produit)

**Back office behaviour** 
As in 1.6, there will be a dropdown to select clients, and a dropdown to select the wishlist created. 
after that, merchants should be able to check products on the wishlist. 
We removed priority, quantity and product declination and now we simply have the product, its name and a direct link to the product. 
![wishlist-bo](https://user-images.githubusercontent.com/40759259/48476410-3fed6780-e7ff-11e8-9fd2-3b24a34c5d82.png)

**Front office behaviour** 
Now, customers are able to add products to their wishlist from the [page of the products](https://projects.invisionapp.com/share/CFOXVATPTUG#/screens/329439751) and from [category pages](https://projects.invisionapp.com/share/CFOXVATPTUG#/screens/329492408).
![categpage](https://user-images.githubusercontent.com/40759259/48476610-d15cd980-e7ff-11e8-938d-abe8e34be685.png)

On their [customer accounts](https://projects.invisionapp.com/share/CFOXVATPTUG#/screens/329439752), they will be able to check, create, delete, edit and even share their wishlist.
![image](https://user-images.githubusercontent.com/40759259/48476657-f7827980-e7ff-11e8-9481-bbc74c510215.png)

After that, from the wishlist, customers are able to add products to their cart by selecting [variant of products. ](https://projects.invisionapp.com/share/CFOXVATPTUG#/screens/329439757)
![image](https://user-images.githubusercontent.com/40759259/48476710-16810b80-e800-11e8-8c58-aa8e81b681f5.png)

Specific behaviour : 
If we delete all lists, when we add a product to wishlist it create automatically a list with the name ('My wishlist'). 

Here is the current [ZIP](https://github.com/PrestaShop/blockwishlist/tree/0eafb91aea556e4ae06c2ffd962aad54eeabb36d)

**Comment by GreatestShowman** [comment]
Hello, this module don't works at all for prestashop 1.7.5.0, is it normal ?

**Comment by Quetzacoalt91** [comment]
Hi,

Yeah, and the objective is to make this module working on 1.7. Thanks to @firstred, that's a work in progress in https://github.com/PrestaShop/blockwishlist/pull/28

**Comment by Matt75** [comment]
I have a modified version of this module for friends using 1.7, it's currently a minimal upgrade.

With [migration of Customer View page](https://github.com/PrestaShop/PrestaShop/issues/11010) in 1.7.6, I have to do a refactoring to make it work.

So I would like to use modern controllers and CQRS pattern like docs and demo module to achieve that.

I look to this issue and I'm worry about functionalities removal suggested here.

Removing product declination is not a good idea, because it's a wishlist who can be shared.

If we remove this, how customer can tell to his friends what size fits to him for example ?
Same for quantity and priority, this is sometimes useful for shared wishlist (So these are optional, same as before).

So I would like to keep this functionalities in newest version. (Friends needs it by the way)

Need help about UX guidelines, there are missing views here like part of Customer view page (BO), account page before go to my wishlists page (FO) for example.

I need help for front integration too, I'm not a guru of CSS and JavaScript 😅😇

And help to implement CQRS pattern (I will following docs) and guidelines about how to add content in Customer view page (BO).

Please note this is a hobby work so it can be slow to complete.
It can be a participating project with community if someone is interested.

**Comment by TristanLDD** [comment]
Hi Matt75, 

There are several reasons why we decided to remove product declination from the module : 

- Benchmark and researches show that wishlists are rarely made to be shared with friends. They are mostly used to compare several items, track price changes or cross-device shopping sessions. 

- The module in 1.6 was suffering from unnecessary complex interface in FO, degrading user experience in most cases. Our objective is to get closer to the wishlist behavior of websites like Asos, with easy to use wishlist and one-clic save for later. 

- Sharing lists with family and friends for special occasions like birthdays and festivals is indeed an interesting option, but we decided to leave that one to the more advanced wishlist modules you can find on Addons Marketplace. 

About the missing designs, I'll check for it and get back to you very quick ;)

**Comment by Matt75** [comment]
Ok seem like regression for me, this module is one of must-have for 1.6 merchants but this choice seem legit.

Moreover these functionalities are really used on 1.6 so we need to choose a strategy to not remove existing data for previous version user who migrate on 1.7

When I worked in agencies, we builded all shops with this module and used this optionnal functionalities. I have friends who use it so we have to think to these people.

So I know this choice of remove these functionalities can be risky and need to be explained to merchants.

If we do a more simpler module, we need to keep associated data and provide hooks to allow extendability for merchants who want to add it or recommendations about premium modules who handle it.

**Comment by rblaurin** [comment]
I have to agree with @Matt75. Removing funcionalities and letting then to Premium modules will not be taken kindly by merchants, who in some cases are already reluctant with 1.7.x adoption. If the intention is to simplify the FO ui, maybe turning some funcionalities optional would be a better way to achieve this.
Anyway, if it is already decided, it is a good idea to provide hooks as suggested by Matt75.

**Comment by Matt75** [comment]
@rblaurin We have a meeting with @TristanLDD on Tuesday to talk about Wishlist. 👍

In fact the needs seems to corresponding to old module favoriteproducts : https://github.com/PrestaShop/favoriteproducts

Thanks for participating, it's very cool to have community members on Github 🤩

**Comment by rblaurin** [comment]
Any ETA for this module?

**Comment by Matt75** [comment]
@rblaurin work is in progress, follow module repository to be notified : https://github.com/PrestaShop/blockwishlist

**Comment by beyondsagency** [comment]
Still no wishlist native on 1.7 after 3 years ?

**Comment by Matt75** [comment]
> Still no wishlist native on 1.7 after 3 years ?

@beyondsagency 

> work is in progress, follow module repository to be notified : https://github.com/PrestaShop/blockwishlist

**Comment by cyrilbarbe** [comment]
How you install this module? I cant with the classic method by clickin the zip file

**Comment by jasper4ni** [comment]
Problem when installing the module in Prestashop ver. 1.7.7.5
Here's the error shown
```php
Attempted to load class "Install" from namespace "PrestaShop\Module\BlockWishList\Database".
 Did you forget a "use" statement for e.g. "PrestaShopBundle\Install\Install", 
"PrestaShop\AccountsAuth\Installer\Install", "PrestaShop\Module\PsAccounts\Module\Install" 
or "PrestaShop\Module\PsEventbus\Module\Install"?

[Symfony\Component\Debug\Exception\ClassNotFoundException 0]
```
![image](https://user-images.githubusercontent.com/68841876/134200903-e60251f5-cf01-4aa6-81db-ecaca7bae013.png)

**Comment by matks** [comment]
> Problem when installing the module in Prestashop ver. 1.7.7.5
> Here's the error shown

The Install.php class is in the right folder https://github.com/PrestaShop/blockwishlist/tree/dev/src/Database

it looks like a Composer cache issue where Composer is unable to find the new php files. I suggest clearing var/cache content.

**Comment by jasper4ni** [comment]
I've deleted the var/cache folder, and tried clear cache in Advanced Parameters/Performance
But it's still the same
Btw, I also updated the ver. to 17.7.8, which is the latest ver.
but still not working

and the php ver. is 7.4

**Comment by jasper4ni** [comment]
> I've deleted the var/cache folder, and tried clear cache in Advanced Parameters/Performance
> But it's still the same
> Btw, I also updated the ver. to 17.7.8, which is the latest ver.
> but still not working

I can provide the link and BO access to u, if u need

**Comment by jasper4ni** [comment]
Hi @matks, do you have any solution for this error?

**Comment by jasper4ni** [comment]
After I move the Install class and uninstall class to under blockwishlist.php, the installation can be process, but another problem show on. When I try to enter the module configure page, the error pop up...
```
The controller for URI "/modules/blockwishlist/configuration" is not callable. 
Class "PrestaShop\Module\BlockWishList\Controller\WishlistConfigurationAdminController" does not exist.

[InvalidArgumentException 0]
```
![image](https://user-images.githubusercontent.com/68841876/134382956-6215b899-2dbb-4a82-b31f-d09cb6767270.png)

I've tried to clear the var/cache but still..

Can anyone help on this? Thx in advance!

**Comment by Joduai** [comment]
Is this module compatible with older 1.7.X versions?
Unfortunately installation fails on ps 1,.7.4.x, and I wonder if changing module's min. requirements wouldn't mess up ps instance after installation?

**Comment by matks** [comment]
@Joduai not compatible with older 1.7.X versions

If you need to use it on older 1.7.X versions you have to adapt it

**Comment by jasper4ni** [comment]
I make a mistake that I install the package directly from dev branch, should download the package from release, problem is sloved ya, thank guys

**Comment by beoji** [comment]
How to change position of button in product miniature? I'm not using default theme

**Comment by beoji** [comment]
Ok, I've done it later but it has to flush cache
