### ISSUE TITLE
[EPIC] Add/Edit a currency with the CLDR implementation

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#11660]
### USER STORY
As a merchant, I want to to be able to add new currencies and to edit it.

### WHY
The CLDR data doesn't always answer all the merchant's needs, and we've seen lots of tickets asking for currency modifications (not available in 1.7 so far).

- [x] #10052 - Here the first part and the related PR #10455

### SPECIFICATION
This new page allows

- To add a new currency
- To edit a currency (this is new in 1.7)

**Add/Edit new currency**

- Currency name *
- ISO code * 
- Decimals 
- Exchange rate

### DETAILED SPECIFICATION

- [Add Currency/ Edit Page Currency ](https://github.com/PrestaShop/prestashop-specs/blob/master/core/back-office/Localization-Currencies-List-Add-Edit.md#currency-adding-editing-and-deleting)

### DESIGN
Link to the Invision models:
https://invis.io/SAPYJZCCR6K

### TODO
- [x] New design @TristanLDD 
- [x] #10190 - Migrate International > Localization > Currencies > Add new / edit currency page @matks 
- [x] #10189 - Migrate International > Localization > Currencies page @matks 
- [x] Find old branch contening first part of the CLDR Front End development @PrestaShop/prestashop-core-developers -> https://github.com/nihco2/PrestaShop/tree/feat/currencies-page-rework
- [x] #12223 - Remove Number decimal in Shop Paremeter
- [x] #15752 - Add currency / edit page currency - 1/3
- [x] #14750 - Edit a currency display by language 2/3
- [x] #14709 - Manage save and interpretation of currency customization 3/3

### ISSUES RELATED
- [x] #9714 - [BOOM-5014] Misleading currency symbol (Denmark)
- [x] #10014 - [BOOM-2277] There is no BYR currency anymore
- [x] #10017 - [BOOM-2065] Decimal support removed from currency
- [x] #10055 - [FF-140] As a User, I want to install a currency
- [x] #10054 - [FF-141] As a User, I want to uninstall a currency
- [x] #10053 - [FF-142] As a User, I want to change some details about a currency

### OLD SPECIFICATION
- [x] #10058 - [FF-71] CLDR - part 3: rework of the currency page (WIP)
- [x] #10057 - [FF-113] CLDR - part 4: rework of the language page (WIP)

**Comment by jolelievre** [comment]
I guess it is linked to this never ending PR ^^? https://github.com/PrestaShop/PrestaShop/pull/10455
@matks @tomlev

**Comment by MatShir** [comment]
Yes it is the 2nd part of the CLDR bringing customization.

**Comment by idnovate** [comment]
How is going to be multistore managed? 

I mean, currently is not possible to define a different configuration for the same currency for each store - mainly currency rate, which is the only thing that can be configured. 
So, you can note define a currency rate of `1` for _store 1_ and `1.1` for _store 2_, for example.

Has it been planned in this development?

**Comment by jolelievre** [comment]
Hello @idnovate,

as far as I know it's not planned in the version 177. I don't know if this feature is planned in the next version.

Although I wonder in which context this can be useful, the exchange rate is not something that should depend on the store it is a global national value so it seems logical to me that the value is the same on every store.

**Comment by BenTen** [comment]
Could you tell that to paypal, I guess they don't know that ^^'

**Comment by idnovate** [comment]
> Hello @idnovate,
> 
> as far as I know it's not planned in the version 177. I don't know if this feature is planned in the next version.
> 
> Although I wonder in which context this can be useful, the exchange rate is not something that should depend on the store it is a global national value so it seems logical to me that the value is the same on every store.

AFAIK the exchange rate depends on the default currency. You could have 2 stores, each one with a different default currency, so the exchange rate would be different:

Store 1:
- USD (default currency)
- EUR -> exchange rate 0,90

Store 2::
- GBP (default currency)
- EUR -> exchange rate 1,18

**Comment by jolelievre** [comment]
You're right it does depend on the default currency, I didn't think about that use case where you have different default currencies This is worth testing and if needed add some feature to deal with this
