### ISSUE TITLE
[EPIC] Transactional emails & Email theme

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#11687]
The idea of this project is to redesign the native email template for transactional emails (for a new account, new order, message to the customer service, etc.). 

- We will also rewrite some of these emails to make them more modern.
- We are currently evaluating the technical feasibility of this project.
- Mock ups & Specs are in progress.

**Here are the related issues:**

1st step : 
- [ ] #11880

2nd step (new EPIC) for customization :
- [ ] #11882

---

## BUGS
- [ ] #9599
- [ ] #21630
- [ ] #22091
- [x] #22330
- [ ] #22540
- [ ] #19081
- [x] #15469
- [x] #24358
- [x] #26919
- [x] #14456
- [ ] #23932
- [x] #27984
- [x] #29880
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35214
- [x] #32508
- [ ] #32971
- [x] #32986 

## FEATURES
- [x] #17430
- [ ] #26417

## Fixed

1st step : 
- [x] #11878
- [x] #11879
- [x] #12458
- [x] #12460
- [x] #15474

2nd step (new EPIC) for customization :

---

### BUGS
- [x] #22553
- [x] #25990
- [x] #26177
- [x] #27581
- [x] #22825

### FEATURES

**Comment by jolelievre** [comment]
Hi, here is the doc where I wrote my feedback on the mail system/architecture:

https://docs.google.com/document/d/1Gp3vX4WjJwTLPXWZgaEC6rDFT0X7x2kvN-j4dzBS9Qc/edit?usp=sharing

Any feedback from @PrestaShop/prestashop-core-developers is welcome

**Comment by jolelievre** [comment]
Here are the related issues:

1st step : 
- [x] Create EmailTemplateGenerator with classic theme https://github.com/PrestaShop/PrestaShop/issues/11878
- [x] Integrate new service EmailTemplateGenerator in install and language install process https://github.com/PrestaShop/PrestaShop/issues/11879
- [x] Integrate email template new design (in native emails + module emails) https://github.com/PrestaShop/PrestaShop/issues/12458
- [x] Rework emails wording where needed #12460
- [ ] Create EmailTemplateCatalog in AdminTranslationsController https://github.com/PrestaShop/PrestaShop/issues/11880

2nd step : 
- [ ] Create a new page to manage new mail templates/themes https://github.com/PrestaShop/PrestaShop/issues/11882
