### ISSUE TITLE
Invoice changes after it was sent to the customer

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12394]
**Issue**
When an order is made, I can change the customer information from the order page in the customer section. These changes update the invoice with the new information even after the invoices were sent to the customer. So a merchant can have different invoices for the same order which it's not legal.

**Describe the solution you'd like**
To block any invoice changes after it was sent to any customer.

**TODO**

- [ ] To block the ability to change the address after any status change that sends the invoice to his customers from the **Order Page**

- [ ] To find all possible actions that can modify an address other than the Order Page in the Back-Office

- [ ] Make sure that all these actions don't change the address order that already sent an invoice

**Comment by marionf** [comment]
It's also the case when you update addresses in customers > adresses
https://github.com/PrestaShop/PrestaShop/issues/13539#issue-436268394

**Comment by khouloudbelguith** [comment]
Hi,

It is also the case when we change the eco-tax of the product as described here: https://github.com/PrestaShop/PrestaShop/issues/14622
The invoice is changed.

**Comment by BenTen** [comment]
If we block the possibility to change the address on the invoice, we have to think how to change the address on the invoice if need it.

**Comment by hanuchin** [comment]
You are not allowed to change an existing order. Thats a fact.

The right solution would be: Make an orderannulation (orderslip) for this invoice and create a new invoice.

But there are several other issues related to a changed order after sending it -> Every hook at the pdf can change old invoices, if you add or remove a module.

**Comment by boo-code** [comment]
There is a precedent for this inside the invoice itself, which I think reframes the discussion above.

`ps_order_invoice` already carries a **`shop_address`** column. `OrderInvoice.php:113` fills it when the invoice is created:

```php
$this->shop_address = OrderInvoice::getCurrentFormattedShopAddress($order->id_shop);
```

and `HTMLTemplateInvoice.php:50-58` falls back to the current one only when that column is empty, with a comment recording that null values were fixed by an upgrade script in 1.6.1.1. So the project already decided that an issued invoice must carry the address as it was, and backfilled old rows to make it hold.

The customer side never got the same treatment. `HTMLTemplateInvoice.php:152` reads it live:

```php
$invoice_address = new Address((int) $this->order->id_address_invoice);
```

`Address::update()` writes in place, with no versioning; the `isUsed()` check there only relaxes required fields. `Address::delete()` is careful in contrast, soft-deleting an address used by an order with the comment "We must absolutely retain all the business data for the order". Deletion preserves history, editing does not.

So this is an inconsistency rather than a missing policy, and it suggests a fix that avoids both objections raised above. @BenTen, nothing needs blocking: the merchant can still correct an address, it just stops rewriting invoices already issued. @hanuchin, no annulation is needed for a typo, only for a real change of substance, which stays a merchant decision.

Concretely, mirroring what `shop_address` already does: a frozen customer address on `ps_order_invoice`, filled at creation, used by the template, with the same "if empty, fall back to the current one" path for rows that predate it plus an upgrade script. That is a schema change on the invoice table, so I would rather have a maintainer say it is the direction before I write it. If it is, I will open it.

Two things it would not cover, worth naming: @khouloudbelguith's ecotax case in #14622 is the same class of problem on a different field, and @hanuchin is right that a module hooked into the PDF can still alter an old invoice at render time. Freezing the address does not solve those.

**Comment by boo-code** [comment]
Opened as #42462, as a draft, taking the freeze approach from my previous comment rather than waiting on the thread to settle.

`ps_order_invoice` gains a `customer_address` column beside `shop_address`, filled by `OrderInvoice::add()` the same way, and the template prefers it. Invoices predating the column, and orders whose address has since been removed, fall back to the live lookup exactly as today, so nothing changes for existing shops until an invoice is issued after the upgrade.

The PR body says which of the three approaches on this thread it takes and why the other two are not it, so it can be overturned in one comment. In short: blocking edits leaves @BenTen's objection unanswered, annulling an invoice is right for a real change of substance but disproportionate for a typo, and versioning addresses on update reaches carts, default addresses and modules for the same outcome.

The upgrade script for existing shops is one `ALTER TABLE`, and since 9.x those live in PrestaShop/autoupgrade rather than core, so it is not in this diff. I will open it there once the direction is accepted.
