### ISSUE TITLE
[EPIC] Make PrestaShop resilient regarding external services

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#12851]
PrestaShop's core must be able to work even when the server cannot make requests to external service.
The Circuit Breaker is the technical solution to handle the different cases requests and responses from external services.

### Installer
- [ ] #10456 - Installer - call API for Modules, translations, and other information

### Login & Dashbord Page
- [x] #12828 - Page Dashboard - Asynchronous Calls for Gamification JSON files
- [x] #12848 - Page Dashboard - Asynchronous Calls for Gamification CSS files
- [x] #12833 - Page Login - List modules call API for Recommended Modules
- [x] #12831 - Page Login - must_have.xml API call in AdminController
- [x] #12830 - Page Login/Dashboard - call for Tips & Updates section 
- [x] #12827 - Page Login/Dashboard - Blog RSS feed API
- [x] #12826 - Page Login - call native_all.xml in AdminController
- [x] #12825 - Page Login - call native.xml in Admin controller

### Misc
- [x] #20835 - Secure calls to addons.prestashop.com behind Circuit Breaker

**Comment by matks** [comment]
I notice a HTTP 500 in my console on Dashboard for following URL: http://api.prestashop.com/version/check_version.php?v=1.7.7.0&lang=fr&autoupgrade=0&hosted_mode=0

It does not seems to be in the list 🤔I guess it's used to check whether I am running the latest PS version.

**Comment by muyncky** [comment]
Great topic, love it!

Maybe have a look at these two:

**classes/Tools.php:3820**

```
$end_point = 'api.addons.prestashop.com';
```

**modules/ps_faviconnotificationbo/classes/APIFAQClass.php:26**
```
$url = 'http://api.addons.prestashop.com/request/faq/'.$module_key.'/'.$version.'/'.$iso_code;
```

I have by default an override for Tools.php, just to prevent this.
