### ISSUE TITLE
[EPIC] Fix topwatchers issues

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#13816]
All **Topwatchers** issues are listed here:

## Souhld be fixed during the migration of the product page in 1.7.8:
- [x] #9945 - The "add a product" page creates a ghost product the moment you open it
- [x] #9809 - Large number of product combinations block browser

## Priority 1 - To do

- [x] #9757 - Free gift is not displayed correctly on cart
- [ ] #14979 - Cart / checkout performance issue when there are multiple products in the cart
- [x] #10258
- [ ] #9599

## Priority 2 - Need to be specified or more investigation
- [ ] #11115 - Duplicate order reference for different order
- [ ] #9664 - 500 error duplicate entry for key 'product_default' in multistore when changing a product with combinations into a standard product and when creating combinations on the second shop
- [x] #10274 - Changing the product quantty in all shops context displays an error "Shop context types other than single shop are not supported"
- [ ] #9779 - = rounding in FO
- [ ] #10122 - Creating a customer account from a guest email account creates a second account
- [ ] #15369 - = carriers 
- [ ] #9998 - = carriers 
- [x] #10600 - Support SVG
- [ ] #14703
- [ ] #/17317
- [x] #12907

## Fixed:
- [x] #9641 - Out of stock notification sent each time editing or deleting a product with combination
- [x] #15878
- [x] #12170 - Modifying an address in order table creates another address instead of changing the original one
- [x] #9795 - Link widget: doesn't work in multiple shops
- [x] #9816 - Wrong translations of BO menu
- [x] #11435 - By default, select the payment method if only one available
- [x] #9634 - [BOOM-5683] Double click on "Add to cart" on the product page FO freezes the page
- [x] #9659 - [BOOM-5403] Profiling for hooks and modules are broken
- [x] #11105 - Error 500 while clearing the cache
- [x] #10026 - [BOOM-1506] In BO Product page, ecotax tax excl is used instead of ecotax tax incl
- [x] #9932 - [BOOM-3566] When a customer edits an used billing address (address used before for order)
- [x] #12241 - Product with combination
- [x] #10739 - Free shipping as visitor
- [x] #9726 - [BOOM-4929] Order message UTF8 problem
- [x] #9890 - [BOOM-3849] css & js should use CDN when activated
- [x] #11172 -  No carrier available in checkout with free shipping cart rule **`really hard to fix`**
- [x] #11722 -  Bad calculation and total when there are many free gifts
- [x] #14595 - Price specification not found for currency: "EUR" - 1.7.6.0
- [x] #14733 - It is not possible to edit the "Back office translations" in PrestaShop 1.7.6.0
- [x] #12687 - classic theme template catalog/_partials/miniatures/product.tpl incorrectly specifies schema.org/Product
- [x] #9667 - [BOOM-5345] It is not possible to buy a product without stock when other combinations have stock
- [x] #9956 - [BOOM-3373] "Default order by" doesn't work for all options 
- [x] #9763 - [BOOM-4673] Shopping cart multi-store
- [x] #9540 - [BOOM-6170] Calculate carrier price on the real order price
- [x] #9665 - [BOOM-5355] minimum order in the second currency does not work
- [x] #9697 - [BOOM-5139] Unable to translate some strings in bank wire payment module
- [x] #9782 - [BOOM-4524] cant view shopping carts if customer deleted 
- [x] #9810 - [BOOM-4296] Emails enabled in ps_emailsubscription module are not sent
- [x] #9883 - [BOOM-3909] error in Chrome when hit back from product to categor
- [x] #9891 - [BOOM-3848] DNI mandatory for Italy, but not for other countries
- [x] #9916 - [BOOM-3671] Viewed products don't work on fresh installed PS1.7
- [x] #9942 - [BOOM-3455] Add new referrer error
- [x] #9992 - [BOOM-2910] faceted search price slider does not show
- [x] #10013 - [BOOM-2330] Cart subtotals issues as setting prices VAT excl. per all clients groups
- [x] #10264 - Major bug with Virtual Products 
- [x] #10387 - You may be not allowed to download this module
- [x] #10638 - [BOOM-1223] [Again!!] Undefined $urls index in ajax rendered template
- [x] #10934 - Error notice on psaddonsconnect - BO
- [x] #11873 - Hook reset during theme upgrade (1.7.5 from 1.7.4.4)
- [x] #9866 - Error "Frontcontroller::init - Cart cannot be loaded or an order has already been placed using this cart" in logs while using the reorder feature
- [x] #20177 - Explore upgrade capabilities of Softaculous
- [x] #10762 - There isn't verification of the product quantity in stock at the last order step (payment), so order of out of stock product can be done while it's not autorized

**Comment by mvorisek** [comment]
https://github.com/PrestaShop/PrestaShop/issues/22262 is a real issue, as `proc_open` is disabled almost on every public hosting and the only solution is to use removed `mail()` somehow, or require smtp details to make outgoing emails working.

**Comment by Hlavtox** [comment]
There is almost nothing on this list now. We can filter the rest by using labels.
