### ISSUE TITLE
[EPIC] Upgrade to jQuery latest, use jQuery migrate for retro compatibility

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#13829]
We are currently using old or very old versions of jQuery. These versions have never been upgraded because of breaking changes introduced in later versions. Using [jQuery Migrate](https://github.com/jquery/jquery-migrate) we could upgrade them to the latest version without breaking backwards compatibility.

## Improvements

- [x] #14929 - Upgrade to jQuery latest, use jQuery migrate for retro compatibility 1/4 - CORE THEME & CLASSIC THEME
- [x] #14930 - Upgrade to jQuery latest, use jQuery migrate for retro compatibility 2/4 - DEFAULT THEME BO
- [x] #14931 - Upgrade to jQuery latest, use jQuery migrate for retro compatibility 3/4 - UI KIT
- [x] #15508 - Update jquery to latest version in Installation process 4/4

**Comment by FredBrockstedt** [comment]
There are three JS security vulnerabilities in 1.7.5.2 (and lower versions):
2 - JQuery2.2.4 - Medium
1 - JQuery UI1.10.3 - High
They are fixed in the current versions of JQuery/UI.

**Comment by ghost** [comment]
To cut in 4 parts:

- [x] Core theme & Classic Theme #14929 
- [x] Default Theme BO #14930 
- [x] UI kit #14931 
- [x] Installation process #15508

**Comment by matthieu-rolland** [comment]
Here is the official migration guide:

https://jquery.com/upgrade-guide/3.0/#overview

For example we already use a jquery-migrate (version 1.2.1) in the back office, and it can't be used simultaneously with jquery-migrate 3.x.

So in a nutshell, the process should be as follow:

**1/** Change jquery version from 1.11 to 1.12 (minimal version supported by the migration script)

**2/** Check that nothing is broken, fix when it's broken

**3/** Once bugs have been fixed, change jquery version to 3.0 and add the jquery-migrate v3 `jquery-migrate-3.1.0.js `

**4/** Check that there is no bug, update jquery libraries if needed.

**Comment by matthieu-rolland** [comment]
I added an issue to this epic: #15508

**Comment by ghost** [comment]
Hi @matthieu-rolland 
Are we completely done with this EPIC or are there still some related tasks to add to the EPIC?
