### ISSUE TITLE
[EPIC] Add/edit product page (known bugs)

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13891]
### - Issues in **basic settings tab** sorted by priority high to low :

**Must-Have**
- [x] #9945 - The "add a product" page creates a ghost product the moment you open it
- [x] #12773 - Improve product images management in basic settings tab #9631

**Should-Have**
- [x] #14910 - Error when save an existing product before it is fully loaded PR: #15034
- [x] #9752 - [BOOM-4741] Can't create category on product page
- [x] #9625 - [BOOM-5738] Product custom feature does not save after changing default language
- [x] #10137 - After duplicating product I'm unable to upload images on the created product (PS1.7.4.2)
- [x] #9626 - [BOOM-5734] Changes are not saved, category is not deleted from the list of the "ASSOCIATED CATEGORIES"
- [ ] #11587 - variants of products in pack of products
- [x] #9617 - [BOOM-5787] Add the same simple product [ to a pack / to related products ]
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35765
- [x] #34347 

**Improvement**
- [ ] #20331 - Highlight categories in dropdown menus of the product page when using keyboard
- [x] #29137

**Nice to Have**
- [ ] #15383 - Multistore Product feature saving bug
- [x] #34142
- [ ] #21689 - Disabling feature in Performance doesnt hide the button in the product page
- [ ] #10024 - [BOOM-1664] Product page - Online/Offline behavior
- [ ] #9631 - [BOOM-5702] There is no alert after deleting / editing an image in the product page - BO
- [ ] #10459 - There's no condition in the product's name - Multilanguage
- [ ] #16004 - Problem with French Canada local settings on 1.7.5.1
- [ ] #9960 - You shouldn't be able to associate a product to itself or associate several times the same product

**New feature**
- [ ] #12773 - Improve product images management in basic settings tab

### - Issues in **price tab** sorted by priority high to low :

**Must-Have**
- [ ] #9855 - Bad recalculation of price tax excl field after entering an ecotax for a product with VAT **`ecotax`**
- [ ] #15044 - Improve ecotax management in BO product page **`ecotax`**
- [ ] #10030 - [BOOM-375] The ecotax is added to the new product price defined (through specific price) while it should be included **`ecotax`**
- [ ] #14093 - Ecotax and Cost price decimals are truncated on BO when the product has combinations
- [ ] #9972 - [BOOM-3165] Price calculation product combination HT / TTC
- [ ] #12363 - Specific price to combinations applied incorrectly
- [x] #34748 

**New feature**
- [ ] #11329 - PS1.7 add Specific Price with time (hours)

**Should-Have**
- [ ] #9576 - [BOOM-6047] Unable to save a product- price cannot be saved - Multistore
- [x] #33949 
- [x] #34260

**Nice to Have**
- [ ] #15785 - BO: Unable to update "Price per unit" field after importing products & combinations
- [x] #33541
- [ ] #12911 - When you edit a specific price in BO and you close the modal with ESC, you cannot scroll anymore in the product form

### - Issues in **combinations tab** sorted by priority high to low :

**Must-Have**
- [ ] #16102 - As a merchant when I change a value for a combination, I want it to be automatically saved without clicking on Save
- [ ] #9809 - [BOOM-4298] Large number of product combinations block browser PR: #16103 
- [ ] #9826 - [BOOM-4202] Generate combinations
- [ ] #14910 - Error when save an existing product before it is fully loaded PR: #15034
- [ ] #13479 - Automatically assign a "default" image to a product combination
- [ ] #9936 - [BOOM-3544] Product backoffice image hover alt text

**Improvement**
- [ ] #11305 - Shipping fees per combination
- [ ] Product: allow up to 14 chars in EAN field **`PR`** #17362
- [ ] #20536 - Merchant should be able to set delivery information for each combination

**Should-Have**
- [ ] #9686 - [BOOM-5237] BO: Multistore | List of the attributes, with the association only to the second shop, doesn't appear in the product page
- [ ] #15405 - In product combinations the "Final retail price (tax excl.)" doesn't change setting "Impact on price (tax incl.)"
- [ ] #14913 - Variation product negative quantity bug
- [ ] #12814 - Wrong quantities showing in BO for products with combinations

**Nice to Have**
- [ ] #14372 - Delete product inventory at editing time (Persian language)
- [ ] #12244 - Multishop Default combinations not reassigned if you delete it
- [ ] #9737 - [BOOM-4827] Changing default combination
- [ ] #9601 - [BOOM-5849] All the attribute Size group are not selected, if we select the attribute Size and value ALL in the combination bar

**New feature**
- [ ] http://forge.prestashop.com/browse/FF-74
Work already started: https://github.com/PrestaShop/PrestaShop/pull/7890

### - Issues in **quantities tab** sorted by priority high to low :

**Should-Have**
- [ ] #13147 - Error in product location

### - Issues in **virtual product tab** sorted by priority high to low :

**Nice to Have**
- [ ] #9623 - [BOOM-5752] Delete "condition" and "location" for virtual products

### - Issues in **shipping tab** sorted by priority high to low :

**Nice to have**
- [ ] #15377 - Available carriers for a product

### - Issues in **SEO tab** sorted by priority high to low :

**Improvement**
- [ ] #14317 - Merchant should be able to choose to index/noindex each prestashop url

**Should-Have**
- [ ] #14984 - SEO preview on product page
- [ ] #15936 - Friendly url not create in some case

### - Issues in **options tab** sorted by priority high to low :

**Improvement**
- [ ] #14135 - Attachments ui/ux improvement request
- [ ] #11795 - Needs Numeric Field on Product Customization Field

**Nice to Have**
- [ ] #9580 - [BOOM-6036] Default supplier is not automatically selected
- [ ] #15553 - Product Back Office - Invalid keyword - no error message - no save

### - Issues when **duplicating a product** sorted by priority high to low :

**Should-Have**
- [ ] #9828 - [BOOM-4188] When cloning a product, carrier info doesn't copy

**New feature**
- [ ] #13397 - Duplicate product without image

### - Issues related to **permission** sorted by priority high to low :

**Should-Have**
- [ ] #12636 - [PS 1.7.X] BO Product edit access blocking product add

### - Issues with **Related Product** sorted by priority high to low :

**Nice to have**
- [ ] #21739 - [BO - Product] Bug in typeahead while searching a related Product

### - Must-have in all tabs
- [ ] #16299 - Add language selector next to each multilanguage fields in product page

## Fixed
- [x] #11496 - BO Product tabs width problem in polish PR: #15712
- [x] #9790 - [BOOM-4458] Product attached files
- [x] #16272 - Add information message for attached files in product options tab
- [x] #14054 - URL in SEO preview is not correct when the product is not active
- [x] #11379 - Multiple carriers with same name & delay key will not be display
Work already started: https://github.com/PrestaShop/PrestaShop/pull/12379
- [x] #14431 - BO bug in HTML - wrong display of help-box
- [x] #12440 - BO - Product page - combinations creation
- [x] #9910 - [BOOM-3704] Decimal display problems in combination page
- [x] #9896 - [BOOM-3825] Invalid price in combination
- [x] #15059 - When editing a cmbination, the ecotax field is tax incl
- [x] #16223 - As a merchant I need to know if the prices are displayed tax incl or tax excl
- [x] #14052 - Highlight element in dropdown menus of the product page when using keyboard
- [x] #16101 - As a merchant I want to edit my combination reference without editing it
- [x] #15416 - The final product price for the combination sould be displayed also tax included
- [x] #16100 - Collapse right column if combinations have already been generated
- [x] #9939 - [BOOM-3475] Seulement 5 attributs proposés / Only five attribtues shown
- [x] #16108 - As a merchant I want to be able to search and sort my combinations
- [x] #12475 - Issue with the link "Manage tax rules in the pricing tab
- [x] #18701 - variable catalog > products
- [x] #14052 - Highlight element in dropdown menus of the product page when using keyboard
- [x] #15038 - Ecotax field shouldn't be displayed in BO if the product is virtual **`ecotax`**
- [x] #10792 - Unit price reset to 0 if you activate/deactivate or duplicate products in bo product list
- [x] #12078 - BO: Price was change - Same for the unit price
- [x] #10026 - [BOOM-1506] In BO Product page, ecotax tax excl is used instead of ecotax tax incl **`ecotax`**
- [x] #9678 - [BOOM-5269] BO - Product page > Brand select dropdown
- [x] #16308 - Tax Rules : Incorrect display value in Price Tab of admin product controller
- [x] #13513 - Product settings hints misbehave when loading tabs with ajax
- [x] #17957 - Declinaison reference is not displayed on pack composition
- [x] #9668 - [BOOM-5335] Summery and describtion bug
- [x] #9680 - [BOOM-5265] Duplication of feature line in product page
- [x] #14955 - Category tree on BO product page
- [x] #16415 - Display issue in the product page when a category has more than 30 chars
- [x] #14052 - Highlight element in dropdown menus of the product page when using keyboard
- [x] #15018 - Product feature indexation PR: #15035
- [x] #12061 - Product images in multishop
- [x] #12832 - Product image position not updatable in multishop [1.6.1.23]
- [x] #9720 - [BOOM-4964] Clone product, can't remove photo product
- [x] #14985 - Remove tabs for summary & description fields in product page 
- [x] #9668
- [x] #16306 - Improve feature creation in product page
- [x] #15330 - Confusing display of VAT in product BO, when VAT disabled

**Comment by khouloudbelguith** [comment]
Hi @marionf,

We should add this issue: https://github.com/PrestaShop/PrestaShop/issues/17885 to the Product page bug list as commented here: https://github.com/PrestaShop/PrestaShop/issues/17885#issuecomment-592750718

Thanks!

**Comment by boo-code** [comment]
Measured against the current state of every item: this checklist is far further along than it reads.

There are 104 entries, 53 ticked and 51 not. All 53 ticked ones are genuinely closed, so nothing here is marked done that is not. Of the 51 unticked, 46 are closed as well - they were fixed without the box being crossed.

Five are actually still open:

- #9972 - price impact saved as 259.999999 instead of 260
- #11305 - shipping fees per combination
- #12363 - specific price applied incorrectly to combinations
- #12814 - wrong quantities shown in the back office for products with combinations
- #14317 - choosing index or noindex per URL

So the standing is 99 of 104 rather than 53 of 104, and four of the five that remain are the same subject: what happens to a price or a quantity once a product has combinations. The fifth is a SEO setting unrelated to the rest.
