### ISSUE TITLE
[EPIC] Order page 1.7.7

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#13890]
### New features

Listing page : 
- [x] #14732 - Order preview in Order page list
- [x] #14736 - Right click "open in new tab" over the full width of order table line
- [x] #14741 - Dropdown next to the status of the command to modify it
 ~~Redesign of the bulk action - #14743~~ not part of the project anymore
- [x] #15230 - KPI header redesigned
- [x] #15231 - Client name clickeable

Detail page : 
- [x] #14745 - [EPIC] Order view redesign
- [x] Check that user without edit permissions works the same as in legacy

###  Bug Fixing while migrating the page
Through the migration from Legacy to the Symfony framework, some of the issues related to this page can be fixed. 
Here a prioritization of this issue:
**Issues Must-Have sorted by priority high to low :**
~- [ ] #11492 - Order displays incorrect information~ **`moved to EPIC`** #17598
- [x] #12442 - Major bug with Virtual Products command
- [x] #12521 - Error total count in order edit PS 1.7.5
- [x] #13809 - Can't add a promo in order page
- [x] #9850 - [BOOM-4098] CLONE - Currency issue while adding payment to order
- [x] #13880 - Bug in displayed discount when adding product (linked to a coupon) to an existing order from BO

**Issues Should-Have sorted by priority high to low :**
~- [ ] #11115 - Duplicate order reference for different order 2/2~ **`moved to EPIC`** #17598
~- [ ] #9676 [BOOM-5292] Order in bo no longer display which employee created it~ **`moved to EPIC`** #17598
~- [ ] #9783 - [BOOM-4495] validateOrder Messages~ **`moved to EPIC`** #17598
~- [ ] #10157 - No invoice number when updating an order with API~ **`moved to EPIC`** #17598
~- [ ] #10988 - Prix unitaire et devise~ **`moved to EPIC`** #17598
- [x] #9689 - [BOOM-5205] Customization Field generates 2 products in cart (Backoffice)
- [x] #13061 - The lines inside table > tbody payments in orders tab go out of their coantiner
- [x] #13275 - Overlap between From and To with the Help part of the orders page
- [x] #14417 - Order page - Add the currency symbol

**Issues Nice to Have sorted by priority high to low :**
~- [ ] #12746 - Missing Price with vat and without vat at order details~ **`moved to EPIC`** #17598
~- [ ] #9735 - [BOOM-4851] Admin new ordre product search, selects wrong combination~ **`moved to EPIC`** #17598
~- [ ] #12682 - BO manual order shows wrong shipping price (one product without changes)~ **`moved to EPIC`** #17598
- [x] #9876 - [BOOM-3952] Undefined currency and currency exchange block appears in the order management form
- [x] #9830 - [BOOM-4169] CLONE - "Error: Product price must be set"
- [x] #12588 - Order payment duplicated depending on order state configuration
- [x] #11034 - Add a new discount with invalid reduction_percent => there is no alert - Order Back office
- [x] #11176 - Shipping modal does not show up on IE 11
- [x] #13782 - Shipping part empty in BO when the order contains a virtual product
- [x] #10393 - It is necessary to replace Google Maps from order pages
- [x] #15716 - "Add a product" and "Add a new discount" buttons disappear after editing a product in view order page

**Comment by hibatallahAouadni** [comment]
@MatShir Why this Epic closed when there's some issues still open? Shall we move those issues to this Epic #17598?

**Comment by MatShir** [comment]
@hibatallahAouadni This Epic was a development epic planned for 1.7.7. Since the 1.7.7 is done, this epic is not relevant anymore.

**Comment by hibatallahAouadni** [comment]
@MatShir So should we move the open issues to the other Epic?

**Comment by MatShir** [comment]
Yes I guess !
