### ISSUE TITLE
[EPIC] Add a modal to confirm or cancel delete in bulk actions

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14462]
**Describe the bug**
Add a modal like on product list (Catalog > Products) to confirm or cancel delete in bulk action and remove the other one

**Third part to do during the migration of each pages from 1.7.7**
Pages not yet migrated for which it must be added:
- [ ] Orders > Carts
- [ ] Catalog > Attributes
- [ ] Catalog > Features
- [ ] Catalog > Discounts > Cart rules
- [ ] Catalog > Discounts > Catalog price rules
- [ ] Customers > Customer service
- [ ] Design > Image settings
- [ ] Shipping > Carriers
- [ ] International > Locations > Zones
- [ ] International > Locations > Countries
- [ ] International > Locations > States
- [ ] International > Taxes > Tax rules
- [ ] International > Taxes > Tax rules > Edit a tax rule > Countries
- [ ] Shop parameters > Customer settings > Titles
- [ ] Shop parameters > Contact > Stores
- [ ] Shop parameters > Traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags

## Fixed
- [x] Shop parameters > Traffic & SEO > Search engines #10589
- [x] Shop parameters > Order settings > Statuses : #27606
- [x] Customers > Order messages - #18641
- [x] Customers > Addresses
- [x] #17816 - Add a modal to confirm or cancel delete in bulk actions 1.7.7 [1/2] 
- [x] #17845 - Add a modal to confirm or cancel delete in bulk actions 1.7.8 [2/2] 

**Screenshots**

Add this modal (@LouiseBonnard for the wording, do you think it's better to have the same general wording for all or to have a specific one for each pages ?)

![capture d'écran_1723](https://user-images.githubusercontent.com/13449658/60580979-4f1d2780-9d86-11e9-98b8-3129b605fd4b.png)

Remove this one

![capture d'écran_1724](https://user-images.githubusercontent.com/13449658/60581665-90620700-9d87-11e9-98d6-d8bb91b0c6d2.png)

**Comment by marionf** [comment]
@matks FYI

**Comment by LouiseBonnard** [comment]
@marionf, I think one global wording is better. Something like:

_Delete selection_
_Are you sure you want to (permanently) delete all selected items?_

Another thing is that it is currently possible to perform a bulk action with only one item selected. Do we want to keep this behavior? If yes, the wording should be adapted, like _Are you sure you want to delete the selected item(s)?_.

**Comment by marionf** [comment]
Yes, I think we can keep this behavior for now

**Comment by LouiseBonnard** [comment]
@marionf, alright. In this case, let's write:

_Delete selection
Are you sure you want to delete the selected item(s)?_

**Comment by matks** [comment]
1st implemention in PR https://github.com/PrestaShop/PrestaShop/pull/16820
When this one has been validated, I will enable it on all targeted pages.

**Comment by marionf** [comment]
@matks 
I missed that there is also a confirmation when a single line is deleted
Do you think it's possible to implement also a modal for a single line at the same time or do you need another issue ?

**Comment by jolelievre** [comment]
@marionf you mean when you click on the row action? in the column at the right?

If yes, the good news is that with the component that @NeOMakinG created the modal should be reusable for this kind of behaviour as well.

**Comment by marionf** [comment]
> @marionf you mean when you click on the row action? in the column at the right?

Yes

> If yes, the good news is that with the component that @NeOMakinG created the modal should be reusable for this kind of behaviour as well.

Perfect :+1: I am going to create a new issue

**Comment by marionf** [comment]
Here it is: #17082

**Comment by matks** [comment]
@marionf it seems "International > Localization > Currencies" page has no bulk delete action, probably because legacy page did not have bulk delete action too. Shall we introduce one ?

**Comment by marionf** [comment]
Well seen @matks 
We will leave this page without checkboxes, I removed it from the list

**Comment by colinegin** [comment]
@marionf @matks can you tell me what is the status of this issue ?

**Comment by matks** [comment]
@colinegin WIP

As there are a huge number of pages to do, I do small PRs to modify them slowly and ease the work of QA. I check the items already done in this issue boyd.

**Comment by marionf** [comment]
First part done in 1.7.7: https://github.com/PrestaShop/PrestaShop/issues/17816
Second part to do in 1.7.8: https://github.com/PrestaShop/PrestaShop/issues/17845

**Comment by Hlavtox** [comment]
This is gradually done during the migration of the pages. It comes out naturally because these components are used automatically. :-)
