### ISSUE TITLE
[EPIC] Order view redesign 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#14745]
### USER STORY
As a merchant, I want to view my order with the essential information easily accessible and without scrolling in the order page.

### WHY
The essential information is scattered throughout the page making it difficult to read the command requiring to make many necessary scrolls. As it is one of the main used pages of the software, the reading must be smooth and efficient.

### SPECIFICATION
The main evolution of this page is to reorganize all content in a readable and logical way for more fluid use (and to address the current scroll problem).
It as to be: 
- Optimizes for responsive and mobile consultation 
- Optimizes to display many products in the order

### Design & Detailed Specification

- [x] #14747 - Deletion of the banner at the top of the order page (Date - Total - Messages - Number of products) 
- [x] #15827 - Payments Tab - 10/11 
- [x] #15821 - Customer block - 4/11
- [x] #15822 - Status Tab Order - 5/11
- [x] #15823 - Documents Tab Order - 6/11
- [x] #15824 - Shipping Tab Order - 7/11
- [x] #15825 - Merchandise return Tab Order - 8/11
- [x] #15818 - Order Actions (update status, view invoice, delivery slip) - 1/11
- [x] #15826 - Products Panel - 9/11
- [x] #15828 - Messages Panel - 11/11
- [x] #15820 - Partial Refund - 3/11
- [x] #15819 - Print Order - 2/11
- [x] #16523 - Hooks

**Comment by Hlavtox** [comment]
Checkout my modified order template. Could give you some ideas. :-)

I have some custom functions like invoice pdf upload, estimated shipping date etc., but the page needed a huge cleanup.

![order](https://user-images.githubusercontent.com/6097524/61467187-7b869580-a97b-11e9-980d-ae72732f9202.png)

**Comment by MatShir** [comment]
#11492

**Comment by MatShir** [comment]
#11492

**Comment by colinegin** [comment]
All done here ! I close the issue
