### ISSUE TITLE
[EPIC] Product page - Virtual products tab 4/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14772]
### - As a merchant I want to be able to manage my virtual products

[https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#virtual-product-tab-epic](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#virtual-product-tab-epic) 

- [ ] #19662 - [Virtual Product tab] - Quantity 1/4 
- [ ] #19663 - [Virtual Product tab] - Stock 2/4
- [ ] #19664 - [Virtual Product tab] - Associated files 3/4
- [ ] #19665 - [Virtual Product tab] - Availability preferences 4/4

### - Issues related to **virtual product** sorted by priority high to low :

**Nice to Have**
- [ ] #9623 - [BOOM-5752] Delete "condition" and "location" for virtual products

**Improvements**
- [ ] #11796 - Customize product replay status **`TBS`**
- [ ] #24778 - Be able to specify 'label when not in stock and backorders disabled' for each product

## Fixed
- [x] #22069 - Saving virtual product attachment is modifying product price if a specific price is set on the product

**Comment by marionf** [comment]
### - Issues related to **virtual product** sorted by priority high to low :

**Nice to Have**
- [ ] #9623
