### ISSUE TITLE
[EPIC] Product page - Combinations tab 5/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14773]
### - As a merchant, I want to be able to manage my products with combinations

https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#combinations-tab-epic

- [ ] #20648 - [Combinations tab] - Combinaison List 1/2
- [ ] #20649 - [Combinations tab] - Combinaison Edit 2/2

### [- As a merchant I want to know if there are errors when I complete a field in the product page](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#combinations-tab-)

---
### - Issues in **combinations tab** sorted by priority high to low :

**Must-Have**
- [ ] #16102 - As a merchant when I change a value for a combination, I want it to be automatically saved without clicking on Save
- [x] #9809 - [BOOM-4298] Large number of product combinations block browser
- [ ] #9826 - [BOOM-4202] Generate combinations
- [x] #14910 - Error when save an existing product before it is fully loaded PR: #15034
- [ ] #13479 - Automatically assign a "default" image to a product combination
- [ ] #9936 - [BOOM-3544] Product backoffice image hover alt text
- [ ]  #9972 - [BOOM-3165] Price calculation product combination HT / TTC

**Improvement**
- [ ] #11305 - Shipping fees per combination
- [ ] Product: allow up to 14 chars in EAN field PR #17362
- [x] #20536 - Merchant should be able to set delivery information for each combination
- [ ] #24778 - Be able to specify 'label when not in stock and backorders disabled' for each product
- [ ] #22165 - Saving product with combination without value in quantity field

**Should-Have**
- [ ] #9686 - [BOOM-5237] BO: Multistore | List of the attributes, with the association only to the second shop, doesn't appear in the product page PR #13217
- [x] #15405 - In product combinations the "Final retail price (tax excl.)" doesn't change setting "Impact on price (tax incl.)"
- [ ] #14913 - Variation product negative quantity bug
- [ ] #12814 - Wrong quantities showing in BO for products with combinations

**Nice to Have**
- [ ] #14372 - Delete product inventory at editing time (Persian language)
- [ ] #12244 - Multishop Default combinations not reassigned if you delete it
- [ ] #9737 - [BOOM-4827] Changing default combination
- [ ] #9601 - [BOOM-5849] All the attribute Size group are not selected, if we select the attribute Size and value ALL in the combination bar
- [ ] #10021 - Display the specific price in the combinations tab respecting the CLDR 

**New feature**
- [ ] http://forge.prestashop.com/browse/FF-74 - Work already started: #7890

## Bugs
- [x] #26611
- [x] #28430
- [ ] #32125 

## Fixed

- [x] #16103 - Add pagination for combinations listing
- [x] #16108 - As a merchant I want to be able to search and sort my combinations
- [x] #22788 - Add custom module fields in ProductCombination form 
- [x] #23922
- [x] #26424
- [x] #12440 - BO - Product page - combinations creation
- [x] #9910 - [BOOM-3704] Decimal display problems in combination page
- [x] #9896 - [BOOM-3825] Invalid price in combination
- [x] #15059 - When editing a cmbination, the ecotax field is tax incl
- [x] #16223 - As a merchant I need to know if the prices are displayed tax incl or tax excl
- [x] #18949 - [BO][IMPROVIMENT] Allow check all in product combinations
- [x] #14052 - Highlight element in dropdown menus of the product page when using keyboard
- [x] #16101 - As a merchant I want to edit my combination reference without editing it
- [x] #15416 - The final product price for the combination sould be displayed also tax included
- [x] #16100 - Collapse right column if combinations have already been generated
- [x] #9939 - [BOOM-3475] Seulement 5 attributs proposés / Only five attribtues shown

**Comment by marionf** [comment]
### - Issues in **combinations tab** sorted by priority high to low :

**Must-Have**
- [ ] #16102
- [ ] #9809
- [ ] #9826
- [ ] #14910 PR: https://github.com/PrestaShop/PrestaShop/pull/15034
- [ ] #13479 
- [ ] #9936
- [ ]  #9972

**Improvement**
- [ ] #11305
- [ ] #17362
- [ ] #20536
- [ ] #22165

**Should-Have**
- [ ] #9686 - PR #13217 - Multistore
- [ ] #15405
- [ ] #14913
- [ ] #12814

**Nice to Have**
- [ ] #14372
- [ ] #12244 - Multistore
- [ ] #9737
- [ ] #9601
- [ ] #10021 Display the specific price in the combinations tab respecting the CLDR 
**New feature**
- [ ] http://forge.prestashop.com/browse/FF-74
Work already started: https://github.com/PrestaShop/PrestaShop/pull/7890

## Fixed
- [x] #16103
- [x] #16108
- [x] #9939
- [x] #16101
- [x] #15416
- [x] #16100
- [x] #14052
- [x] #15059
- [x] #16223
- [x] #12440
- [x] #9910
- [x] #9896

**Comment by Argez** [comment]
Hi. I am having a problem in the combinations tab. They do not show me the combinations of a product when in multishops I select all shops and in network of the chrome inspector I get an error 500

**Comment by Jonatan949** [comment]
I have a problem related with this. When the customer adds a product with combinations to the cart, the combination of products that the customer chooses is not chosen, the Samsung S21 Plus always appears. This problem only occurs in the mobile version, in the computer version it works fine.

What can I do?

Regards,
