### ISSUE TITLE
[EPIC] Product page - All tabs 1/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14770]
## Issues when **duplicating a product** sorted by priority high to low

**Must-have**
- [x] #16299 - Add language selector next to each multilanguage fields in product page
- [x] #9945 - The "add a product" page creates a ghost product the moment you open it
- [x] #14910 - Error when save an existing product before it is fully loaded

**Should-Have**
- [x] #9828 - [BOOM-4188] When cloning a product, carrier info doesn't copy
- [x] #9576 - [BOOM-6047] Unable to save a product- price cannot be saved **`Multistore`** 
- [ ] #10137 - After duplicating product I'm unable to upload images on the created product **`Multistore`**

**Nice to have**
- [x] #16004 - Problem with French Canada local settings on 1.7.5.1

**New feature**
- [ ] #13397 - Duplicate product without image

## Issues related to **permission** sorted by priority high to low

**Should-Have**
- [ ] #12636 - [PS 1.7.X] BO Product edit access blocking product add

## Improvement
- [x] #18203 - Add a warning when registering a product activated at €0

**New issues to prioritize:**
- [x] #10459 - There's no condition in the product's name - Multilanguage
- [x] #10024 - [BOOM-1664] Product page - Online/Offline behavior

---
### BUGS
- [x] #25691

## Fixed
- [x] #22278 - Pagination is not working on Product Quick Navigation Popup 1.7.7
- [x] #15330 - Confusing display of VAT in product BO, when VAT disabled
- [x] #18173 - Tabs of product page have different widths in back end with view only permission
- [x] #11496 - BO Product tabs width problem in polish **`Fixed by`**  #15712
- [x] #13698 - PHP Fatal error: Out of memory in CategoryDataProvider.php **`Duplicate of`** #19281
- [x] #9720 - [BOOM-4964] Clone product, can't remove photo product **`Multistore`**

**Comment by marionf** [comment]
### - Issues when **duplicating a product** sorted by priority high to low :

**Must-have**
- [ ] #16299
- [ ] #9945
- [ ] #13698
- [ ] https://github.com/PrestaShop/PrestaShop/issues/14910

**Should-Have**
- [ ] #9828
- [ ] #9576 - Multistore 
- [ ] #10137 - Multistore
- [x] #9720 - Multistore

**Nice to have**
- [ ] #16004
- [ ] https://github.com/PrestaShop/PrestaShop/issues/18173
- [x] #11496 PR: https://github.com/PrestaShop/PrestaShop/pull/15712

**New feature**
- [ ] #13397

### - Issues related to **permission** sorted by priority high to low :

**Should-Have**
- [ ] #12636

### - Improvement
- [ ] #15330
- [ ] #18203 warning message

New issues to prioritize:
- [ ] https://github.com/PrestaShop/PrestaShop/issues/16004
- [ ] https://github.com/PrestaShop/PrestaShop/issues/10459
- [ ] https://github.com/PrestaShop/PrestaShop/issues/10024

**Comment by matks** [comment]
@marionf @MatShir Does this issue relates also to the top bar ? with the product name and the dropdown to choose the type of Product ?

**Comment by marionf** [comment]
@matks Yes, the top bar with product name, product type, language selector, buttons: sales / product list / help and also to the footer bar: preview, delete, online / offline, save, duplicate, go to catalog and add new product

**Comment by MatShir** [comment]
**Product name field**
When you create a new product, invalid characters for the name field are: <>;=#{} 
If you have only one language installed and enter an invalid character and save, you have an error "This value is not valid." displayed under the field.

![capture d'écran_1746](https://user-images.githubusercontent.com/13449658/60906145-cc5d0680-a276-11e9-93ef-fb62fa59e1d6.png)

But if you have many languages installed, the error is displayed in a different way:

![capture d'écran_1747](https://user-images.githubusercontent.com/13449658/60906236-fc0c0e80-a276-11e9-9485-ca64dc707103.png)

- [ ] We should display the error under the field when there are many languages with the language concerned: "This value is not valid. - Language: Français (French) "

**Comment by zuk3975** [comment]
@MatShir Enabling/disabling product resets Redirect options.
I found this in Product::toggleStatus(), please approve this is expected behavior and add to specs.

* When I enabe product, its redirect type becomes 404 and redirect target 0.
* When I disable product, its redirect type becomes 301-category and redirect target 0.

RedirectType 404 means once product is offline(disabled), "Product not found page" will be shown to customer
RedirectType 301-category used along redirect target 0 means that once product is offline(disabled), customer will be redirected to main category page.
ping @jolelievre too (I hope it may save some time if you aware of this when in progress implementing product form)


**EDIT**
Current product page does not use Product::toggleStatus(), so only UpdateProductStatusCommand does, which might just be a mistake. (so anyway, need clarification if abovementioned feature is expected or not).

**Comment by jolelievre** [comment]
@zuk3975 I think this is a bug so I opened an issue for it https://github.com/PrestaShop/PrestaShop/issues/21929
