### ISSUE TITLE
[EPIC] Product page - SEO tab 8/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14776]
### - Here is the list of the elements of SEO tab:
[https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#seo-tab-epic](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#seo-tab-epic) 

- [x] #19677 - [SEO tab] - Search Engine Optimization 1/2
- [x] #19678 - [SEO tab] - Redirection page 2/2

### [- As a merchant I want to know if there are errors when I complete a field in the product page](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#seo-tab-)

---
## Issues in **SEO tab** sorted by priority high to low :

**Should-Have**
- [x] #14984 - SEO preview on product page
- [ ] #15936 - Friendly url not create in some case.
- [ ] #17078 - Product Meta description not filled by default in the SEO preview

## Improvement
- [ ] #14317 - Merchant should be able to choose to index/noindex each prestashop url

## Fixed
- [x] #14054 - URL in SEO preview is not correct when the product is not active
- [x] #21495 - Bug on "reset url" button of the product pages when "Accented URLs" is enabled and there are special characters in the product name

**Comment by marionf** [comment]
### - Issues in **SEO tab** sorted by priority high to low :

**Should-Have**
- [ ] #14984
- [ ] #15936
- [ ] #17078

**Improvement**
- [ ] #14317

## Fixed
- [x] #14054
- [x] #21495 Bug on "reset url" button of the product pages when "Accented URLs" is enabled and there are special characters in the product name
