### ISSUE TITLE
[EPIC] Product page - Prices tab 7/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14775]
### - As a merchant I want to be able to manage the prices of my products

[https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#pricing-tab-epic](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#pricing-tab-epic) 

- [x] #19671
- [x] #19672
- [x] #19673

### [- As a merchant I want to know if there are errors when I complete a field in the product page](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#pricing-tab-)

- [ ]  #18861

### Issues in PRICE TAB sorted by priority high to low :
**Regression on develop**

**Must-Have**
- [ ] #9855 - **`ecotax`**
- [ ] #15044 - **`ecotax`**
- [ ] #10030 - **`ecotax`**
- [x] #14093
- [ ] #12363

**New feature**
- [x] #11329

**wording**

**Should-Have**
- [x] #22552

**Nice to Have**
- [x] #15785
- [x] #12911

### Issues in PRICE TAB without priroty
- [ ] #18656 
- [x] #22552
- [x] #24860 
- [x] #25045
- [x] #28430
- [x] #29296
- [ ] https://github.com/PrestaShop/PrestaShop/issues/31830

## Fixed
- [x] #27051
- [x]  #20223
- [x] #12475
- [x] #9897
- [x] #18701
- [x] #14052
- [x] #12078
- [x] #10792
- [x] #10026 - **`ecotax`**
- [x] https://github.com/PrestaShop/PrestaShop/issues/18751#event-3336713500
- [x] #19674
- [x] #15038 - **`ecotax`**

**Comment by marionf** [comment]
- Use a constant for decimal precision for ecotax computation #18861

### - Issues in **price tab** sorted by priority high to low :
**Regression on develop**

**Must-Have**
- [ ] #9855 ecotax
- [ ] #15044 ecotax
- [ ] #10030 ecotax
- [ ] #14093 
- [ ] #12363

**New feature**
- [ ] #11329

**wording**

**Should-Have**
- [ ] #22552 - Try to add a specific price to a product, then add another one, you will see that the selected user for the previous specific price is still selected

**Nice to Have**
- [ ] #15785
- [ ] #12911

## Fixed
- [x]  #20223
- [x] #12475
- [x] #9897
- [x] #18701
- [x] #14052
- [x] #10792
- [x] #10026 ecotax
- [x] https://github.com/PrestaShop/PrestaShop/issues/18751#event-3336713500
- [x] #12078
- [x] #15038 ecotax

**Comment by MatShir** [comment]
- Use a constant for decimal precision for ecotax computation #18861
