### ISSUE TITLE
[EPIC] Product page - Shipping tab 6/9

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#14774]
### - As a merchant I want to be able to manage carriers information for my products

[https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md##shipping-tab-epic](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#shipping-tab-epic) 

**This tab is not displayed for a virtual product.**

- [ ] #19666 - [Shipping tab] - Package dimension 1/4
- [ ] #19667 - [Shipping tab] - Delivery Time 2/4
- [ ] #19668 - [Shipping tab] - Shipping fees 3/4
- [ ] #19669 - [Shipping tab ] - Available carriers 4/4

### [- As a merchant I want to know if there are errors when I complete a field in the product page](https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/catalog/catalog-products-add-edit.md#shipping-tab-)

---

### - Issues in **shipping tab** sorted by priority high to low :

**Should-Have**

**Improvement**
- [x] #15377 - Available carriers for a product
- [x] #10759 - Delivery Time, confusing UI in back-office

**Bugs**
- [ ] #24497 - List of available carriers in product edit page contain disabled carriers - product v1

## Fixed
- [x] #24687 - Precise product weight is not correctly displayed in back-office
- [x] #11379 - Multiple carriers with same name & delay key will not be display PR: #12379

**Comment by marionf** [comment]
### - Issues in **shipping tab** sorted by priority high to low :

**Should-Have**

**Improvement**
- [ ] #15377

## Fixed
- [x] #11379 
Work already started: https://github.com/PrestaShop/PrestaShop/pull/12379
