### ISSUE TITLE
[EPIC] - FO Merchandising improvements 

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#15166]
A few improvements and bug fixes are needed for the product listings **and quickviews** on front office, in order to correctly display product combinations :

## Improvements
- [x] #13479
- [x]  #12501
- [x] #15164 
- [x] #15738

## Bugs
- [x] #15463
- [x] #21240
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35219
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35220
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35624

## Fixed
- [x] #21389

**Comment by Maofree** [comment]
Hi
there are some news about corrections of these things?
there are so important and useful for all eshop, is it possible to increase the priority of them? it is past 1 year
thanks

**Comment by Gipielle** [comment]
Hello, any news about this ?

**Comment by marionf** [comment]
Hello guys,

This topic required a lot of study to prepare specifications, it's not the priority right now
Furthermore some features listed in this issue are already available with modules like [advanced search](https://addons.prestashop.com/fr/recherches-filtres/2778-advanced-search-4-recherche-par-filtres.html)

**Comment by Maofree** [comment]
hi
you're suggesting buying a module that costs € 300, so I don't think it's a satisfactory solution. Prestashop is a cms to create eshops, and these functions should be implemented by default because otherwise one could use presentation cms, if he wants to be the best cms for eshops he should foresee these functions as other similar ones do

bye

**Comment by TheKruspe** [comment]
In my opinion, this issue should be titled `Fix product search with combinations`, together with https://github.com/PrestaShop/PrestaShop/issues/16952, https://github.com/PrestaShop/PrestaShop/issues/18172, https://github.com/PrestaShop/PrestaShop/issues/10018 and maybe https://github.com/PrestaShop/PrestaShop/issues/26676. Almost any of these tickets is older than two years. If these issues still have low priority, can this epic be moved to `Nice To Have`, so that others can work on it?

**Comment by Hlavtox** [comment]
Closing as almost all issues have been resolved and the thread is dead.
