### ISSUE TITLE
Add a step in the upgrade process for pre checks

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/PrestaShop#15197]
In order to prevent compatibility issues, we should add an array in the module specifying the PHP versions compatible with PrestaShop.

If the current env is incompatible with the destination version, the upgade must be blocked.

Other tasks:
* [x] Check the current PHP version with the required one for the PrestaShop version **(Fixed by PrestaShop/autoupgrade#312)**
* [x] Check permission / open_basedir restriction (See https://github.com/PrestaShop/PrestaShop/issues/9597)
* [ ] Check (https://github.com/PrestaShop/autoupgrade/issues/122) and disable overrides
* [ ] Disable modules

**Comment by khouloudbelguith** [comment]
Ping @colinegin @marionf

**Comment by Quetzacoalt91** [comment]
From Update Assistant v7, the online channel is now able to select the perfect destination version based on the version of the running PHP server.

See https://github.com/PrestaShop/autoupgrade/pull/902 for more details.
