### ISSUE TITLE
[EPIC] Listing Order Page redesign

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#15248]
## Features

- [x] #14736 - Right click "open in new tab" over the full width of order table line
- [x] #14741 - Dropdown next to the status of the command to modify it
- [x] #15230 - KPI header redesigned
- [x] #15231 - Client name clickable
- [x] #14732 - Order preview in Order page list

**Comment by colinegin** [comment]
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/13890
