### ISSUE TITLE
[EPIC] Modern modules (using Symfony)

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#15255]
We want to allow people to build modern modules for PrestaShop, using Symfony features (Symfony controllers, Symfony services, Twig templates ...)

This means:
- everything that is possible using legacy module system should be possible using Symfony module system
- add some useful features made possible by Symfony (like enabling a Bundle)
- write documentation about it of course

## Provide Symfony modules all legacy modules capabilities

- [ ] #13701 - Provide a bridge for Helper classes / allow Helper classes for Symfony

## New features

- [ ] #12172 - Suggestion of new features as console commands
- [x] #21752 - Blockreassurance - URL not available in front office 

## BUGS
- [x] #15653 - Searching for a module in Quicksearch BO links to module catalog

## Fixed
- [x] #21825 - configuration button no longer appears after installation
- [x] #11264 - After uninstalling the module, the related tab in the BO menu is not found
- [x] #14855 - Use command line to generate module files
- [x] #12585 - Provide powerful form customization without the need for template override
- [x] #11596 - Enable Doctrine usage in modules 
- [x] #14941 - Provide helpers/extension/annotations to manage MultiLang in doctrine entities 
- [x] #12640 - Manage tabs
