### ISSUE TITLE
[EPIC] Migrate data from PS 1.6 modules when installing 1.7 ones

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#15359]
Upgrading to PS 1.7 requires to install new modules, especially modules which provide the same feature as in 1.6 but which have a different technical name, preventing them from being only upgraded.

During this process, we should migrate the data from the previous module (the similar one built for 1.6) before uninstalling it. Then, the new module will install itself and retrieve the details from the previous module. (See as reference: PrestaShop/ps_customtext#13).

To manage this work on 40 different modules, we have split it in 5 different batches :

- [ ] #13350 - 1st batch - modules which do not require any configuration
- [ ] #13376 - 2nd batch - modules with a limited configuration details stored on the shop
- [ ] #14022 - 3rd batch - modules with a limited configuration details stored on the shop, but which are preinstalled with PS 1.7
- [ ] #14031 - 4th batch - more complex modules as they store data in our database and / or the filesystem
- [ ] #14404 - 5th batch - modules which are not preinstalled but are still important for a shop running on .17

**Comment by Hlavtox** [comment]
Closing, will never happen or finished.
