### ISSUE TITLE
[EPIC] - Specific price by quantity in FO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#15816]
**All issues related to Specific price by quantity in FO**

## BUGS 
- [ ] #15933 - Bad price amount when specific prices by quantity are applied and delivery address is on a country with price with tax excluded
- [x] #9642 - [BOOM-5562] An empty () is displayed in the product page FO

## Fixed
- [x] #15817 - Change wording in FO when there is specific price by quantity
- [x] #9929 - [BOOM-3580] Quantity discount wrong calculation when price display method is tax excluded
- [x] #15835 - Bad discount amount when specific price by quantity is configured tax excl and prices are displayed tax incl in FO
- [x] #15866 - Bad discount display when specific price is configured with new product price and discount in FO
- [x] #16163 Unit price is wrong when there are several specific prices per quantity - PR #15100
