### ISSUE TITLE
Update tax rates

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16122]
As part of the localization packs rework, tax rates must be updated. Here is the list of the packs to update:

- [x] #16078 Update Argentinian conversion and tax rates
- [x] #16291 Update Austrian tax rates

20% Standard Rate
13% Reduced Rate
10% Reduced Rate
0% Zero Rate

- [x] #16079 Update Azerbaijani tax rates
- [x] #16291 Update Belarusian tax rates

20% Standard Rate

- [x] #16244 Update Brazilian tax rates
- [x] #16291 Update Bulgarian tax rates

20% Standard Rate
9% Reduced Rate
0% Zero Rate

- [x] #16291 Update Chinese tax rates

13% Standard Rate
9% Standard Rate
6% Standard Rate

- [x] #16161 Update Colombian tax rates
- [x] #16244 Update Costa Rican tax rates
- [x] #16291 Update Croatian tax rates

25% Standard Rate
13% Reduced Rate
5% Reduced Rate
0% Zero Rate

- [x] #16179 Update Dominican Republic tax rates
- [x] #16181 Update Ecuadorian tax rates
- [x] #16182 Update Egyptian tax rates
- [x] #16183 Update Fijian tax rates
- [x] #16055 Update Greek tax rates
- [x] #16185 Update Guyanan tax rates
- [x] #16000 Update Indian tax rates
- [x] #16186 Update Indonesian tax rates
- [x] #16188 Update Iranian tax rates
- [x] #16187 Update Israeli tax rates
- [x] #16291 Update Italian tax rates

22% Standard Rate
10% Reduced Rate
5% Reduced Rate
4% Reduced Rate
0% Zero Rate

- [x] #16189 Update Japanese tax rates
- [x] #16291 Update Latvian tax rates

21% Standard Rate
12% Reduced Rate
5% Reduced Rate
0% Zero Rate

- [x] #16291 Update Maltese tax rates

18% Standard Rate
7% Reduced Rate
5% Reduced Rate
0% Zero Rate

- [x] #15969 Update Mexican tax rates
- [x] #16190 Update Moldavian tax rates
- [x] #16218 Update New Zealander tax rates
- [x] #16193 Update Norwegian tax rates
- [x] #16244 Update Peruvian tax rates
- [x] #16291 Update Filipino tax rates

18% Higher Rate
12% Standard Rate
0% Reduced Rate

- [x] #16291 Update Panamese tax rates

7% Standard Rate
15% Higher Rate
10% Higher Rate
0% Zero Rate

- [x] #16291 Update Portuguese tax rates

23% Standard Rate
13% Reduced Rate
6% Reduced Rate
0% Zero Rate

- [x] #16291 Update Romanian tax rates

19% Standard Rate
9% Reduced Rate
5% Reduced Rate
0% Zero Rate

- [x] #16218 Update Russian tax rates
- [x] #16218 Add Saudi Arabian tax rates
- [x] #16218 Update Serbian tax rates
- [x] #16218 Update South African tax rates
- [x] #15968 Update Swedish tax rates
- [x] #16160 Update Swiss tax rates
- [x] #16218 Update Tanzanian tax rates
- [x]  #16291 Update Tunisian tax rates

19% Standard Rate
13% Reduced Rate
7% Reduced Rate
0% Zero Rate

- [x] #16218 Update Ukrainian tax rates
- [x] #16218 Update Venezuelan tax rates
- [x] #16218 Update Vietnamese tax rates

**Here are some useful links to complete this task:**

Feedback from our partner agencies [here](https://docs.google.com/spreadsheets/d/1_7K8p_wif-p1rs5xGXx6_p3NrY0TuLjgYPa-sNFzQKk/edit?usp=sharing)
Feedback from our ambassadors [here](https://docs.google.com/spreadsheets/d/1QvBo1q_ddSZU3wcawGN_oZVeutY-CB5eJaYfky6HXys/edit?usp=sharing)
International rates by countries [here](https://www.avalara.com/vatlive/en/vat-rates/international-vat-and-gst-rates.html)
