### ISSUE TITLE
Add BD, BA, CM, MG, and SN localization packs

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#16435]
**Is your feature request related to a problem? Please describe:**

Among other requests, we have Ambassadors in some countries which are not localized in PrestaShop, let's offer them a nice environment so that their commitment can have more impact on the local community and make PrestaShop goes deeper international!

**Describe the solution you'd like:**

It could be nice to natively provide basic local information such as taxes, currencies, languages, units, etc. for the following countries:

- [x] **Bangladesh (BD)**: 161 active stores (#16927)

<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Bangladesh" version="1.0">
	<currencies>
		<currency name="Taka" iso_code="BDT" iso_code_num="050" sign="৳" blank="1" format="1" decimals="1" />
	</currencies>
	<languages>
		<language iso_code="bn" />
	</languages>
	<taxes>
		<tax id="1" name="VAT BD 15%" rate="15" />

		<taxRulesGroup name="BD Standard Rate (15%)">
			<taxRule iso_code_country="bd" id_tax="1" />
		</taxRulesGroup>
	</taxes>
	<units>
		<unit type="weight" value="kg" />
		<unit type="volume" value="L" />
		<unit type="short_distance" value="cm" />
		<unit type="base_distance" value="m" />
		<unit type="long_distance" value="km" />
	</units>
</localizationPack>

- [x] **Bosnia-Herzegovina (BA)**: 73 active stores (#16927)

<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Bosnia and Herzegovina" version="1.0">
	<currencies>
		<currency name="Konvertibilna Marka" iso_code="BAM" iso_code_num="977" sign="KM" blank="0" format="1" decimals="1" />
	</currencies>
	<languages>
		<language iso_code="bs" />
	</languages>
	<taxes>
		<tax id="1" name="PDV BA 17%" rate="17" />
		<tax id="2" name="PDV BA 0%" rate="0" />

		<taxRulesGroup name="BA Standard Rate (17%)">
			<taxRule iso_code_country="ba" id_tax="1" />
		</taxRulesGroup>

		<taxRulesGroup name="BA Zero Rate (0%)">
			<taxRule iso_code_country="ba" id_tax="2" />
		</taxRulesGroup>
	</taxes>
	<units>
		<unit type="weight" value="kg" />
		<unit type="volume" value="L" />
		<unit type="short_distance" value="cm" />
		<unit type="base_distance" value="m" />
		<unit type="long_distance" value="km" />
	</units>
</localizationPack>

- [x] **Cameroon (CM)**: 130 active stores (#16927)

<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Cameroon" version="1.0">
	<currencies>
		<currency name="Franc CFA" iso_code="XAF" iso_code_num="950" sign="FCFA" blank="1" format="2" decimals="0" />
	</currencies>
	<languages>
		<language iso_code="fr" />
		<language iso_code="en" />
	</languages>
	<taxes>
		<tax id="1" name="TVA CM 19.25%" rate="19.25" />
		<tax id="2" name="TVA CM 0%" rate="0" />

		<taxRulesGroup name="CM Standard Rate (19.25%)">
			<taxRule iso_code_country="cm" id_tax="1" />
		</taxRulesGroup>

		<taxRulesGroup name="CM Zero Rate (0%)">
			<taxRule iso_code_country="cm" id_tax="2" />
		</taxRulesGroup>
	</taxes>
	<units>
		<unit type="weight" value="kg" />
		<unit type="volume" value="L" />
		<unit type="short_distance" value="cm" />
		<unit type="base_distance" value="m" />
		<unit type="long_distance" value="km" />
	</units>
</localizationPack>

- [x] **Madagascar (MG)**: 263 active stores (#16927)

<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Madagascar" version="1.0">
	<currencies>
		<currency name="Ariary" iso_code="MGA" iso_code_num="969" sign="Ar" blank="1" conversion_rate="4078.42" format="2" decimals="0" />
	</currencies>
	<languages>
		<language iso_code="fr" />
		<language iso_code="mg" />
	</languages>
	<taxes>
		<tax id="1" name="TVA MG 20%" rate="20" />

		<taxRulesGroup name="MG Standard Rate (20%)">
			<taxRule iso_code_country="mg" id_tax="1" />
		</taxRulesGroup>
	</taxes>
	<units>
		<unit type="weight" value="kg" />
		<unit type="volume" value="L" />
		<unit type="short_distance" value="cm" />
		<unit type="base_distance" value="m" />
		<unit type="long_distance" value="km" />
	</units>
</localizationPack>

- [x] **Senegal (SN)**: 142 active stores (#16927)

<?xml version="1.0" encoding="UTF-8" ?>
<localizationPack name="Senegal" version="1.0">
	<currencies>
		<currency name="Franc CFA" iso_code="XOF" iso_code_num="952" sign="FCFA" blank="1" format="2" decimals="0" />
	</currencies>
	<languages>
		<language iso_code="fr" />
	</languages>
	<taxes>
		<tax id="1" name="TVA SN 18%" rate="18" />
		<tax id="2" name="TVA SN 15%" rate="15" />
		<tax id="3" name="TVA SN 10%" rate="10" />

		<taxRulesGroup name="SN Standard Rate (18%)">
			<taxRule iso_code_country="sn" id_tax="1" />
		</taxRulesGroup>

		<taxRulesGroup name="SN Tourism Rate (15%)">
			<taxRule iso_code_country="sn" id_tax="2" />
		</taxRulesGroup>

		<taxRulesGroup name="SN Reduced Rate (10%)">
			<taxRule iso_code_country="sn" id_tax="3" />
		</taxRulesGroup>
	</taxes>
	<units>
		<unit type="weight" value="kg" />
		<unit type="volume" value="L" />
		<unit type="short_distance" value="cm" />
		<unit type="base_distance" value="m" />
		<unit type="long_distance" value="km" />
	</units>
</localizationPack>
