### ISSUE TITLE
[EPIC] Improvements for UI Kit

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#16587]
PrestaShop back office UI Kit must be improved in order to have a solid Design System. Currently, we can find different designs for the same buttons, inconsistency between the text and the colors (cf. alerts) and components misplacement.

Colors, typography and shadows are in the [Style Guide page](https://invis.io/S9UXGJA73B5).
The specs can also be found in the ["Inspect mode"](https://projects.invisionapp.com/d/main/#/console/18908855/393895460/inspect) of InVision.
PrestaShop uses [Material icons](https://material.io/resources/icons/?style=baseline) for its back office.

# Alerts
- [x] #16595 - Toast alerts
- [x] #16606 - Short sticky alerts
- [x] #16607 - Long sticky alerts

# Buttons
- [x] #16589 - Single buttons
- [x] #16593 - Button group
- [x] #16594 - Buttons with dropdown

# Cards
- [x] #16608 - Cards

# Dropdowns
- [x] #16609 - Dropdowns
- [x] #16610 - Dropdowns under icon
- [x] #16611 - Dropdowns with search

# Input group
- [x] #16597 - Inputs
- [x] #16598 - Search bars
- [x] #16599 - Input number
- [x] #16600 - Multiple inputs
- [x] #16601 - Radio buttons
- [x] #16602 - Checkboxes
- [x] #16603 - Tooltips
- [x] #16604 - Toggles
- [x] #16605 - Breadcrumbs

# Modals
- [x] #16613 - Modals

**Comment by NeOMakinG** [comment]
Everything should be done for now, we need to wait for the PRs to be merged before we check together everything is right or pixel perfect, and then I need to create a new PR about fixing stylelint errors before integrating it to a CI

**Comment by colinegin** [comment]
As everything has been merged in this EPIC, I close it.
Congratulations !
