### ISSUE TITLE
Specific prices and customer group discount display bug

### ISSUE THREAD

**Issue by langziyang** [PrestaShop/PrestaShop#16664]
prestashop version 1.7.6.1(i guess all 1.7.x)

1、set product price is 1000.00
2、add specific prices is save 60.00 form 10 numbers
<img width="1455" alt="admin1" src="https://user-images.githubusercontent.com/2345387/70015775-58baed80-15b9-11ea-94f2-4634d92c676a.png">

3、set customer group discount is save 90%
<img width="887" alt="admin2" src="https://user-images.githubusercontent.com/2345387/70015840-9750a800-15b9-11ea-9924-689a2a62e1d4.png">

then the product detail page show the debug
<img width="1450" alt="front" src="https://user-images.githubusercontent.com/2345387/70016030-2c53a100-15ba-11ea-8654-b714cb45e978.png">

**Comment by khouloudbelguith** [comment]
Hi @langziyang,

We are aware of this issue.
We have an epic with all cases to reproduce the issue as reported here: https://github.com/PrestaShop/PrestaShop/issues/15816
- [x] https://github.com/PrestaShop/PrestaShop/issues/9929 => fixed
- [x] https://github.com/PrestaShop/PrestaShop/issues/15817 => fixed
- [ ] https://github.com/PrestaShop/PrestaShop/issues/15835 Bad discount amount when specific price by quantity is configured tax excl and prices are displayed tax incl in FO
- [ ] https://github.com/PrestaShop/PrestaShop/issues/15866 Bad discount display when specific price is configured with new product price and discount in FO
- [ ] https://github.com/PrestaShop/PrestaShop/issues/16163 Unit price is wrong when there are several specific prices per quantity

Your ticket is a duplicate of #15816
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment]
Duplicate of #15816
