### ISSUE TITLE
[EPIC] - Password improvements

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#16672]
This epic is related to customer password improvements for more security and better user experience. It details all open issues and improvements related to this topic, more can be added in the future.

A more in depth study needs to be conducted to define if all issues are interesting AND feasible.

## Bugs
- [ ] #10475 - PS 1.7 PASSWORD_LENGTH 

## Improvements
- [ ] #16170 - Password Change : Permit browsers to suggest securely-generated passwords
- [ ] #15413 - Set an expiration time for the Password reset link

## Fixed
- [x] #11752 - Weak password policy
