### ISSUE TITLE
[EPIC] - Checkout

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#17034]
When shopping online, one crucial user experience happens when the customer is experiencing the checkout phase. We have not planned to rework the PrestaShop checkout in the next few months but since it is a pretty big topic, let's start gathering issues about it:

## Cart summary
- [x] #9944
- [x] #9781
- [x] #12958
- [ ] #18801
- [x] #25841
- [x] #24838
- [ ] #31656

## Personal information step (sign in)
- [ ] #16196
- [x] #25481

## Address step
- [x] #16723
- [x] #23757

## Shipping Step
- [ ] #25179

## Gift Voucher
- [ ] #21644

## Gift message step
- [x] #9574

## Payment step
- [x] #17621
- [x] #9756
- [ ] #16623
- [x] #24619

## Order confirmation
- [x] #9997
- [x] #25177
- [ ] https://github.com/PrestaShop/PrestaShop/issues/27462
- [x] #34483 

## Quantity check
- [ ] #18958 , cf. https://github.com/PrestaShop/PrestaShop/issues/18958#issuecomment-705571741
- [ ] https://github.com/PrestaShop/PrestaShop/issues/27484
- [x] #27871

## Other issues
- [x] #14361
- [x] #26983
- [ ] #29431

## Hot topic: revamping the checkout?
- [x] #15406
- [x] #22157

## Fixed
- [x] #9927
- [x] #21961
- [x] #19963
- [x] #16348
- [x] #10762
- [x] #18215
- [x] #11435
- [x] #18229
- [x] #26044
- [x] #24817
- [x] #27340
- [x] #20952
- [x] #21807
- [x] #21437
- [x] #23808
- [x] #9831
- [x] #11595
- [x] #21477
- [x] #26852

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-product-team Added #19963 to this epic

**Comment by Matt75** [comment]
@PrestaShop/prestashop-product-team Then https://github.com/PrestaShop/docs/issues/508
Many issues for Payment Modules since years !
