### ISSUE TITLE
[EPIC] Add a modal to confirm or cancel delete action for one row

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#17082]
**Describe the bug**

Add a modal like on product list to confirm or cancel deletion of a row instead of the browser one

⚠ Add this modal **with the following message** - edited by @LouiseBonnard following https://github.com/PrestaShop/PrestaShop/issues/14462#issuecomment-508394667:

`title` = _Delete selection_ in _Admin.Actions_
`confirm_message` = _Are you sure you want to delete the selected item(s)?_ in _Admin.Global_

`confirm_button_label` = _Delete_ in _Admin.Actions_
`close_button_label` = _Cancel_ in _Admin.Actions_

---

Already migrated pages for which it must be added:
- [x] #17847 - Add a modal to confirm or cancel delete for one row [1/1] 

**Second part to do during the migration of each pages from 1.7.8**
Pages not yet migrated for which it must be added:
- [ ] Orders > Carts
- [ ] Catalog > Attributes
- [ ] Catalog > Features
- [ ] Catalog > Discounts > Cart rules
- [ ] Catalog > Discounts > Catalog price rules
- [ ] Customers > Customer service
- [ ] Design > Image settings
- [ ] Shipping > Carriers
- [ ] International > Locations > Zones
- [ ] International > Locations > Countries
- [ ] International > Locations > States
- [ ] International > Taxes > Tax rules
- [ ] International > Taxes > Tax rules > Edit a tax rule > Countries
- [ ] Shop parameters > Customer settings > Titles
- [x] Shop parameters > Order settings > Statuses : #27606
- [ ] Shop parameters > Contact > Stores
- [x] Shop parameters > Traffic & SEO > Search engines #10589
- [ ] Shop parameters > Traffic & SEO > Referrers
- [ ] Shop parameters > Search > Search
- [ ] Shop parameters > Search > Tags

**Screenshots**

![capture d'écran_1723](https://user-images.githubusercontent.com/13449658/60580979-4f1d2780-9d86-11e9-98b8-3129b605fd4b.png)

Remove this one

![capture d'écran_1724](https://user-images.githubusercontent.com/13449658/60581665-90620700-9d87-11e9-98d6-d8bb91b0c6d2.png)

**Comment by jolelievre** [comment]
What is the target of this modification? Maybe a bit late for 1.7.7 so maybe in 1.7.8?

**Comment by marionf** [comment]
@jolelievre yes, 1.7.8

**Comment by marionf** [comment]
@sowbiba 

I created a specific issue for the 1.7.8: https://github.com/PrestaShop/PrestaShop/issues/17847
