### ISSUE TITLE
[UI Kit] Improvements corrections

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/PrestaShop#17177]
Epic: #16587 

[Link to InVision prototype](https://invis.io/S9UXGJA73B5)

List components that haven't been called on the back-office but have been integrated in the UI Kit.

# Alerts

- [x]  Delete "click me to delete"
- [x]  Icon must be aligned with the first text line
- [x]  "Read more" button stays in black
- [x] Sticky warning alert: background #FFFBD3, icon #FAB000
- [x] Verify the button text color: #363A41 ("Read more") 
- [x] Replace all toast alerts by the new design from the UI Kit
- [x] Success toast alert: green #53D572 
- [x] Warning toast alert: orangey yellow #FAB000  
- [ ] Add animation for the new toast alerts

# Cards

- [x]  Fix using cards were it shouldn't be (cf. tables)

→ Need to be ready for 1.8

# Buttons

- [x]  Fix the radius on button in the toolbar
- [x]  Fix icon on dropdown (rotating on click)
- [x]  Rem to be validate
- [x]  No background for outline buttons
- [x]  Button stays active after click on button group (cf. date)

# Radio buttons

- [x]  Fix radius

# Photos

- [x]  Delete radius on pictures (Catalog > Products)

# Placeholders

- [x]  Change italic text by regular (placeholder, search bar)
# Toolbox

- [x]  Padding: 10px
- [x]  Icon size: 19px
- [x]  Show toolbox infos on hover and not on click
- [x] Change the markup to show new toolbox

# Ratios/Spacers

- [ ]  Change by 4px, 8px, 16px, 24px, 32px, 64px

# Toggles

- [x]  Put the right grey when toggle is off: #B3C7CD
- [x]  Replace "YES/NO" buttons by toggles
- [x]  Replace checks and crosses on table by toggles and try to not refresh the page when clicking on toggles (show a toast alert instead)

# Typography

- [x] Update font size: 
![image](https://user-images.githubusercontent.com/54888056/91569568-1fe05700-e946-11ea-9f81-c827037545f3.png)

**Comment by NeOMakinG** [comment]
Not refreshing on toggles on product list is not doable without backend works on it and it's pretty huge, you should speak about it with core team, I did put the toggles instead of checks and crosses anyway.

**Comment by NeOMakinG** [comment]
So, the activate/desactivate action should be done with this issue : https://github.com/PrestaShop/PrestaShop/issues/10631 , gonna do it when the list system will be migrated to a grid one !

**Comment by TristanLDD** [comment]
New corrections to do : 

- [x] Use #36A41 color on "Read more" button in alerts

- [x] Change markup on toolboxes to display the new design 

- [x] Add the new design on all alertboxes + add the appearance effect

**Comment by colinegin** [comment]
Hello @prestascott @NeOMakinG , is there anything left to do here ?

**Comment by NeOMakinG** [comment]
Except deploying it to NPM after getting it tested by the QA with a brut path, nothing

**Comment by NeOMakinG** [comment]
See this : https://github.com/PrestaShop/PrestaShop/pull/17253

(need a rebase btw)

**Comment by LouiseBonnard** [comment]
Wait for the UI kit release.
