### ISSUE TITLE
Finish @todo in 1.7.7 migrated code

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#17282]
We put some `@todo` in 1.7.7 migrated code to be handled later.

Later is now 💪 !

For each `@todo`, we must
- [remove it if irrelevant
or
- fix it
or
- answer it
or
- [create an issue about it

### TODO List

**In BO Theme JS:**
- [x] js/pages/order/create/customer-manager.js
- [x] js/pages/order/message/order-view-page-messages-handler.js

**In Adapter namespace:**
* [x] src/Core/Domain/Address/Command/SetRequiredFieldsForAddressCommand - #17526
* [x]  src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php - #17348
* [ ]  src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php
* [x]  src/Adapter/Order/CommandHandler/ChangeOrderCurrencyHandler.php - #17672
* [ ]  src/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php
* [ ]  src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php
* [ ]  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php
* [x]  src/Adapter/Order/Refund/OrderRefundCalculator.php - #17850
* [x]  src/Adapter/Order/Refund/OrderSlipCreator.php - `associated with mailer. As we don't have a new mailer yet, these todo's should be left for future`
* [x]  src/Adapter/Order/Refund/VoucherGenerator.php - `associated with mailer. As we don't have a new mailer yet, these todo's should be left for future`
* [x]  src/Adapter/Product/QueryHandler/SearchProductsHandler.php - #17736 

**In Core namespace:** 
* [ ]  src/Core/Grid/Data/Factory/CatalogPriceRuleGridDataFactory.php
* [ ]  src/Core/Grid/Definition/Factory/Monitoring/EmptyCategoryGridDefinitionFactory.php

**In PrestaShopBundle:**

* [ ]  src/Core/Grid/Data/Factory/CatalogPriceRuleGridDataFactory.php
* [ ]  src/Core/Grid/Definition/Factory/Monitoring/EmptyCategoryGridDefinitionFactory.php
* [ ]  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php
* [ ]  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig

**All checked items only have its designated pull requests or answers, it might not be merged yet.**

**Comment by zuk3975** [comment]
- `Add required fields validation` in SetRequiredFieldsForAddressCommand - #17526

- `fix showing not found customers and rerender after change customer` in customer-manager.js - #17325 

- `move to private method` in AddCartRuleToOrderHandler - #17348

**Comment by zuk3975** [comment]
**In BO Theme JS:**
* [x]  js/pages/order/create/customer- [ ]manager.js - #17325 
* [x]  js/pages/order/message/order- [ ]view- [ ]page- [ ]messages- [ ]handler.js - #17531 

**In Adapter namespace:**
* [x] src/Core/Domain/Address/Command/SetRequiredFieldsForAddressCommand - #17526
* [ ]  **src/Adapter/Order/CommandHandler/AddCartRuleToOrderHandler.php - #17348**
* [ ]  **src/Adapter/Order/CommandHandler/AddProductToOrderHandler.php - #17348**
* [x]  src/Adapter/Order/CommandHandler/ChangeOrderCurrencyHandler.php - #17672
* [ ]  s**rc/Adapter/Order/CommandHandler/DeleteProductFromOrderHandler.php - #17348**
* [ ]  **src/Adapter/Order/CommandHandler/UpdateProductInOrderHandler.php - #17348**
* [x]  src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php - #17864 `removes todo because behavior already handled in controller`
* [x]  src/Adapter/Order/Refund/OrderRefundCalculator.php - #17850
* [x]  src/Adapter/Order/Refund/OrderSlipCreator.php - `associated with mailer. As we don't have a new mailer yet, these todo's should be left for future`
* [x]  src/Adapter/Order/Refund/VoucherGenerator.php - `associated with mailer. As we don't have a new mailer yet, these todo's should be left for future`
* [x]  src/Adapter/Product/QueryHandler/SearchProductsHandler.php - #17736 

**In Core namespace:** 
* [x]  src/Core/Grid/Data/Factory/CatalogPriceRuleGridDataFactory.php - https://github.com/PrestaShop/PrestaShop/pull/17884
* [x]  src/Core/Grid/Definition/Factory/Monitoring/EmptyCategoryGridDefinitionFactory.php - raised #17885

**In PrestaShopBundle:**

* [x]  src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController.php - #17864
* [x]  src/PrestaShopBundle/Resources/views/Admin/Sell/Order/Order/Blocks/Create/cart.html.twig - #17861

**All checked items only have its designated PR's/issues or answers, it might not be merged yet.**

**NOTE**
Todo's which was supposed to be fixed in with #17348 (bolded in list) should move to develop, because of serious confllicts that occured during refactoring. For more info check https://github.com/PrestaShop/PrestaShop/pull/17348#issuecomment-608507088

**Comment by matks** [comment]
@zuk3975 copied into issue description

**Comment by zuk3975** [comment]
> Todo's which was supposed to be fixed in with #17348  should move to develop, because of serious confllicts that occured during refactoring. For more info check #17348 (comment).

created reminder issue for 1.7.8: #18545.
@matks I think we can close this issue, as everything else is resolved.

**Comment by colinegin** [comment]
ping @matks what's the status of this issue ?
