### ISSUE TITLE
[EPIC] Order Pages, a new start

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17598]
After the redesign of the Order Page with the implementation of new features, we receive feedback and idea to improve it in future versions.

This epic will centralize the feedback from bug to improvement.

## Specified features
- [ ] #17225
- [x] #14754
- [x] #17903
- [x] #14752

**tax subject**
- [ ] #20821
- [ ] #15954
- [ ] #20817
- [x] #18307
- [x] #16129
- [x] #20977
- [ ] #20178

**About the employees historic and interactions:**
- [ ] #9676
- [x] #14547
- [x] #13537

## Features ideas to explore
- [ ] #19043
- [ ]  Reworking the search filter system of the list view
- [ ] Reworking the data export system (see if it should be part of a more global reflection)
- [ ] Rework of the statistics banner
- [ ]  Reworking the message timeline system and adding specific notes
- [ ] Possibility of customizing the columns of the listing: leave the choice among a predefined list
- [x] #14743
- [ ] #18210
- [ ] #20135
- [ ] #20231
- [x] #16953
- [ ] #22121
- [ ] #22083

## Features
- [x] #17035
- [x] #20819
- [x] #23308
- [x] #21766

## Bugs
- [ ] #18576
- [ ] #11492
- [ ] #10157
- [ ] #16155
- [x] #18767
- [x] #21501
- [x] #16578
- [x] #22410
- [x] #21284
- [x] #24281
- [ ] #24531
- [x] #24560
- [x] #26450
- [x] #19950
- [x] #27951
- [ ] #29009
- [ ] #29208
- [x] #31282 
- [ ] #35062
- [x] #31489
- [ ] #35504

**Issues Must-Have sorted by priority high to low :** [Originally posted in #13890]
- [ ] #11492

**Issues Should-Have sorted by priority high to low :** [Originally posted in #13890]
- [ ] #11115
- [ ] #9676
- [ ] #9783
- [ ] #10157
- [x] #10988

**Issues Nice to Have sorted by priority high to low :** [Originally posted in #13890]
- [ ] #12746
- [ ] #9735
- [x] #12682

### FO issues
- [ ] #25581

### Create order
- [ ] #23620
- [x] #31594 

### Merchandise Return

- [ ] #10029
- [x] #14901

### Partial refund
- [ ] #16869
- [x] #15522
- [ ] #28982
- [x] #29299
- [ ] #33529 

### Order messages
- [x] #28801
- [ ] https://github.com/PrestaShop/PrestaShop/issues/34968

## Payment Module
- [x] #10066
- [x] #11012
- [x] #17346
- [ ] #9783

## Fixed
- [x] #17729
- [x] #21005
- [x] #20557
- [x] #20560
- [x] #21438
- [x] #21504
- [x] #21529 
- [x] #21531
- [x] #21562
- [x] #21566
- [x] #21659
- [x] #21810
- [x] #21815
- [x] #21983
- [x] #21991
- [x] #22830
- [x] #11396
- [x] #15873
- [x]  #16275
- [x] #22891
- [x] #23216
- [x] #22109
- [x] #22124
- [x] #22105
- [x] #22243
- [x] #22590
- [x] #9660
- [x] #23230
- [x] #26804
- [x] #21293
- [x] #21717
- [x] #21734
- [x] #21812
- [x] #21829
- [x] #21873
- [x] #22004
- [x] #22138
- [x] #22096
- [x] #22086
- [x] #22071
- [x] #22029
- [x] #22231
- [x] #22263
- [x] #22424
- [x] #22611
- [x] #22625
- [x] #22979
- [x] #22983
- [x] #21500
- [x] #21506
- [x] #21548
- [x] #21549
- [x] #16567
- [x] #22321
- [x] #23116
- [x] #22643
- [x] #22644
- [x] #19111
- [x] #21995
- [x] #14753
- [x] #14736
- [x] #10393
- [x] #19200
- [x] #26376
- [x] #27267
- [x] #9644
- [x] #22652
- [x] #27336
- [x] #25650
- [x] #24901

**Comment by zuk3975** [comment]
**Bug**:
- [ ] - `Order view page`. After adding product with invoice and a free shipping, the order totals are incorrect. (discount is added to reduce the relevant shipping price, but the shipping is not increased). This was already discussed at 1.7.7.x pre-release, it seems its not so easy to fix that without introducing another bugs, because shipping is recalculate for whole cart, when feature is demanding it to only add to single product.

- [ ] - `Order view page`. There is a setting "recalculate order shipping price". If we delete all products from the order which had (lets say $7) shipping price, and we have that setting turned off, should shipping be recalculated or not? because theoretically it should not be recalculated, but at feature point of view it doesn't make sense to leave order with 0 products and $7 shipping price.

**Features ideas to explore:**
- [ ] - `Order view page`. Adding product with option "create new invoice" and "free shipping". Should free shipping be applied to whole cart, single product (as a discount) or to invoice only, or maybe this feature could be removed at all? And finally, consider should order still have multiple invoices, as the multi-shipping feature is no longer available?

**Comment by madsoliver** [comment]
Hi 🙂

Should the title of this be "Order management, a new start"? 

**The following questions should be easy to answer for the merchant:**
1. What does all the checkboxes inside `Shop Parameters > Order settings > Statuses > Edit status` mean?
2. How do I generate an invoice?
3. How do I make sure my customer gets an email?
4. How do I generate a delivery slip?
5. What causes an order to _reserve stock_?
6. What causes and order to _decrease physical stock_?
7. What causes an order to be "locked", and not editable?
8. Why can I add discount to an order after it's locked, but not add/remove/edit products?
9. Why does invoices change when an order is edited? Should they not be credited and a new be made? (for book-keeping)
10. What happens when I change to status _Canceled_ on an order? Does it create a credit note? Does it return items to stock? Does it refund via the payment provider?
11. What happens when I change to status _Refunded_ on an order? Does it create a credit note? Does it return items to stock? Does it refund via the payment provider?
12. What happens when I refund/return items inside the order? Does it create a credit note? Does it return items to stock? Does it refund via the payment provider?
13. Why does orders suddenly get other states like "In rest"?

I find myself needing to test, test and test myself if a client ask me some of the questions above.  I am afraid that it not only lacks documentation for this, but the order-system needs a rework. In my opinion there is to much magic going on in the background. We are somewhere in between a fully flexible order-system where one can do what ever one wants (ouch, dont tell the accountant that we live-edit invoices that we allready sent to the customer), and a locked system, where for example some strange wording like "Show delivery PDF" causes an order to be locked. 

I think, since there are so many different use-cases, the magic (actions grouped toghether) should be removed, and one should let the merchant decide what should happen instead for each order-state:
- with a set of new clearly defined and documented checkboxes inside  `Shop Parameters > Order settings > Statuses > Edit status`.

**Comment by TheEnglishGartner** [comment]
Hi all, sorry if this is not aligned with the topic in scope. 

I have a PS 1.7.8.8 Warehouse Theme 

All modules updated although I have a strange issue, which has been mentioned in another post ;

BO - Order page - An error is displayed when decreasing the gifted product quantity "Could not find the product in cart, meaning Order and Cart are out of sync" #22004

In my Prestashop I get the below:

Could not find the product in cart, meaning Order and Cart are out of sync

and order has been placed - but afterwards I would like to give a discount (which I have been doing many times) When I put in the discount as a value / amount a red bar appears with the above txt. 

Im using One page checkout

![Red BAr - When Trying to provide Discount](https://user-images.githubusercontent.com/92990704/213922923-5dd57eaa-384f-41db-82e2-d57622d30c92.JPG)


Best

**Comment by madsoliver** [comment]
I made a discussion for parts of this: 
https://github.com/PrestaShop/PrestaShop/discussions/31038
