### ISSUE TITLE
[ORDER PAGE] Display correction 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#17655]
Go through in the missed display and see what could be improved

## Part 1 
**ORDER VIEW**

Need a dev back on these issues : 

- [x] Empty rectangle below the tabs (status, transport...)

- [x] The stock location is displayed in cancel, partial, standard and return products while none of the products have a stock location. It should only display it if only one of them has a stock location.

- [x] The refunded column is always displayed by default even if the merchandise return is deactivated and if no refund has been made.

- [x] Border between `%` (or `€`) and the value field in the "Add a discount" popup is too thick. Adding the class `input-group-text` on the value field should solve it.

- [x] Check if we can dynamically change the color of the top left status dropdown according to the selected status. 

Front-end issues :

- [x] Put the label of the Order list on the Order page in the status history

- [x] The label is not well rounded in a stock greater than two in the product list of the order page.

- [x] The status change does not correspond to the expected display.

- [x] The button to edit the merchant's address page goes below the label when the screen size is reduced.

- [x] In a reduced screen, the button that goes to the line is too close to the drop-down menu to update the status (see on the mobile view).

- [x] Pop-in of messages in a reduced screen makes the profiles icons all line up on the left while some should stay on the right.

- [x] The block of messages in a reduced screen puts the icons below the message when it should stay above the message.
Change the number of messages displayed to 4 instead of 2.

- [x] Adding a discount.
The discount value when you want to increase the value of the field using the top arrow increases the value by 0.01. Can it be changed to 1 or maybe 10?

- [x] The trash icon in the discount list is in blue, whereas it should only be displayed in blue when the mouse passes over it.

- [x] Review the display (alignment of the input with the label) of the amount to be entered when the refund, partial refund and standard refund buttons interact.

- [x] The numbers labeled in black in the customer block have a size that looks smaller than normal.
- [x] The numbers labeled in black in the pop-in of the product packs are smaller than normal.
- [x] The link to see the packs is too close to the product name.

- [x] Added ":" after custom text labels in the product list when displaying a customized product.
- [x] Review the partial refund shipping field.

- [x] All the fields in add and edit are not aligned
- [x] The "configure message" link is too much of a dropdown in the message block.
- [x] See if there are any changes or comments to be made in the mobile view. 
- [ ] ~~The radio does not look like in the ui kit design when using a partial refund with a discount~~ --> not to be done in 177

- [x] Mobile: center the content of the main buttons (top of the page buttons)

**Comment by Progi1984** [comment]
Fixed by #17801
