### ISSUE TITLE
[EPIC] - SEO optimizations

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#18402]
Listing of all issues related to SEO fixes and improvements :

#### Generic SEO issues
- [x] #16865
- [x] #14336
- [ ] When crawling, some parameters have been blocked by the robots.txt, including controller attachment (http://dev2017.concept-bureau.fr/index.php?controller=attachment&id_attachment=254 ), JS and CSS. The robots.txt is here to block the crawl, but not the indexation. For parameters, it should avoid getting this type of URL on the website by rewriting it or deleting useless links. It would also be necessary to authorize css/js files so that the crawler can use them : Allow: /*css?* and Allow: /*js?* might be a solution, but this should be adapted according to what Google says in the Search Console. 
- [x] #22962
- [x] #12253
- [x] #10247
- [ ] #17095
- [ ] #13418
- [ ] #27490
- [x] #29945 
- [x] #28941
- [x] #31607
- [x] #32296
- [x] #33642

#### Product page and listing page
- [x] #9635
- [ ] #9784
- [x] #9980
- [x] #15764
- [x] #10206
- [ ] #16488
- [x] #26456
- [ ] #26778
- [x] #23534
- [ ] #23096
- [ ] #31914
- [ ] #18546
- [x] #34925

#### Category page
- [x] #13737
- [ ] #17516
- [x] #18109
- [x] #27414
- [ ] Pagination : To avoid duplication with category subpages, brands, etc. it is necessary to declare previous and next pages so that Googlebot understands the following site contents when there is pagination. 

_→ For page 1 :_ 
- Put in the head a declaration of page 2 : `<link rel="next" href="http://dev2017.concept-bureau.fr/42-siege-de-bureau?page=2">`
- Meta robots in Index, follow Canonical to itself (page 1)

_→ For page 2, 3, X (excluding the last page) :_ 
- In the head, declare previous and next pages : `<link rel="next" href="http://dev2017.concept-bureau.fr/42-siege-de-bureau?page=SUIVANTE"> et <link rel="prev" href="http://dev2017.concept-bureau.fr/42-siege-de-bureau?PRECEDENTE">`

_→ For last page :_  Same as other pages except that their is no next page to declare.

- [ ] Give the option (which can be enabled or disabled) to add in category page title and H1 « Page X on Y »
- [x] Add a new text block below the category page and faceted search
- [x] #18634
- [ ] #17688
- [x] #21386
- [x] #15420
- [x] #15490

#### Other pages
- [ ] Change default metatitle of the store so that its name does not appear at the end
- [ ] SEO & URLS : put 301 redirection by default for all pages. 
- [ ] #10653
- [ ] https://github.com/PrestaShop/PrestaShop/issues/30825
- [ ] https://github.com/PrestaShop/PrestaShop/issues/33971

#### Modules
- [ ] Cross selling should be put in no index
- [x] #22081

## Features
- [x] #13016
- [x] #23533

#### Product page and listing page
- [x] #18529
- [x] #15554
- [x] #17737
- [x] #18134

#### Other pages
- [x] #11144
- [ ] #14317

#### Modules
- [x] #16992
- [x] #16767
- [ ] #16268

#### Generic SEO issues
- [x] #22092
- [x] #23632
- [x] #14629
- [x] #28468

#### Product page and listing page
- [x] #18299
- [x] #21391
- [x] #21929
- [x] #26195

#### Category page
- [x]  #17122
- [x] #25065
- [x] #25871

#### Other pages
- [x] #9503

#### Modules
- [x] Add the search bar in the 404 page

### Features
- [x] #22538
- [x] #22748
- [x] #22867
- [x] #17713
- [x] #25667
- [x] #27596
- [x] #27526

#### Product page and listing page
- [x] #11041
- [x] #17878
- [x] #27413

#### Modules

**Comment by Gipielle** [comment]
Yes !

**Comment by LouiseBonnard** [comment]
Hi @colinegin, PR #15587 might be interesting for this EPIC. :-)

**Comment by cedricfontaine** [comment]
Hello @colinegin attribute id in the URLs is not optimal for the crawl budget on very large catalog. https://github.com/PrestaShop/PrestaShop/issues/18687

**Comment by colinegin** [comment]
Thanks for your feedback @cedricfontaine, this is very interesting.
Wdyt @jolelievre ?

**Comment by Gipielle** [comment]
Delete category will be automatically make the redirect to superior one and not give a 404 page error for me.

**Comment by Gipielle** [comment]
Epic redirect :-)
https://drive.google.com/file/d/1-hopgdMlpVoLcHJrKF8ixMsEAXWZVw6S/view

**Comment by sam-pires** [comment]
I think we can add to this EPIC to do a checkup of rich snippets and schema markups, this would solve many issues related to these topics, and be state-of-the-art on it :)

**Comment by domaingood** [comment]
Add Task For SEO Removes Ids & Numbers from your Store URLs https://github.com/PrestaShop/PrestaShop/issues/20677

**Comment by alfonsolr09** [comment]
> * []  [# 22962](https://github.com/PrestaShop/PrestaShop/issues/22962) - Prestashop 1.7.6.8 Google no reconoce los fragmentos enriquecidos

this error has been fixed with #22417
