### ISSUE TITLE
[EPIC] Images formats

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#18518]
Many feature requests focus on the need for PrestaShop to support more image formats. Indeed, images have great business value for online stores and their formats have quite evolved since the release of PrestaShop 1.7. Let's gather here some improvement issues and organize the work to be done:

**1. Make PrestaShop support SVG & WEBP formats**
- [ ] https://github.com/PrestaShop/PrestaShop/discussions/32240
- [x] #19921
- [ ] https://github.com/PrestaShop/PrestaShop/discussions/32254
- [x] #27706

**2. Add SVG & WebP support for native modules**
- [ ] Banner
- [ ] Image Slider

**3. Study the favicon case later**
- [x] #10290

---

## Handle the required extensions
- [ ] #18391 - Fixed by #18410

## Improve images regeneration and image settings
- [x] #16206
- [x] #18016
- [x] #18169
- [x] #18257 
- [x] #18599
- [x] #20962
- [x] #9605
- [x] #9725 **`TBS`**
- [ ] #26111
- [x] #26552
- [x] #15183
- [x] #29139
- [x] #30032 
- [x] #32351

## Regarding combinations
- [x] #17317

## Regarding modules 
- [x] #16989

## Manage images
- [x] #20857
- [x] #18852
- [x] #30046 

## Fixed
- [x] #10096
- [x] #23920
- [x] #18769
- [x] #25850 
- [x] Block Reassurance, cf. https://github.com/PrestaShop/PrestaShop/issues/15939
- [x] #17673 - Fixed by #21627 ?
- [x] #10356

**Comment by davidglezz** [comment]
- [ ] Support SVG for shop logo
