### ISSUE TITLE
Release 1.7.6.5

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#18645]
This issue tracks the status of the PrestaShop 1.7.6.5 release

### Information

Q | A
--|--
**Type** | Patch version
**Milestone** | [1.7.6.5](https://github.com/PrestaShop/PrestaShop/milestone/63)
**Kanban** | [1.7.6.x](https://github.com/PrestaShop/PrestaShop/projects/4)
**Estimated release** | 2020-04-20

### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] [Release](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.5)
- [x] Available for upgrade
- [x] [Docker image](https://github.com/PrestaShop/docker/pull/218)

**Comment by eternoendless** [comment]
Release is currently being built 🏗️

**Comment by matks** [comment]
Release has passed QA validation 🚀thanks @PrestaShop/prestashop-qa !

1.7.6.5 is now ready to be delivered.
We expect complete delivery (ZIP being distributed + release note + multiple small updates such as new docker image creation) to be fully done on next Monday. As it is already Friday noon, we don't perform the delivery following [No deploy on Friday](https://stackoverflow.com/questions/2115612/why-not-to-deploy-on-a-friday) rule.
If Monday delivery is finished, people should be able to upgrade their shops on Tuesday.

**Comment by eternoendless** [comment]
1.7.6.5 [has been released](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.5)! 🎉

**Comment by ttoine** [comment]
🎉

**Comment by PierreRambaud** [comment]
Docker tag for 1.7.6.5 is available https://hub.docker.com/layers/prestashop/prestashop/1.7.6.5/images/sha256-9e7163fe086655ce0fbc2614532597903cc6ac3f4edc279607034f813f545b19?context=repo
List of updated tags: https://hub.docker.com/repository/docker/prestashop/prestashop/tags?page=1

**Comment by eternoendless** [comment]
Release complete

**Comment by alfonsolr09** [comment]
how can i uprgrade it with 1 click upgrade?
