### ISSUE TITLE
Release 1.7.7.0 🚀

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#18647]
This issue tracks the status of the PrestaShop 1.7.7.0 release

### Information

Q | A
--|--
**Type** | Minor version
**Milestone** | [1.7.7.0](https://github.com/PrestaShop/PrestaShop/milestone/54)
**Kanban** | [1.7.7.x](https://github.com/PrestaShop/PrestaShop/projects/7)
**Beta release** | [Beta 1](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-beta.1) (May 2020), [Beta 2](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-beta.2) (Sep 2020)
**Release Candidate** | [RC 1](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-rc.1) (November 2020)
**Final release** | [Stable](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0) (December 2020)

### Current status

- [x] Specification
- [x] Feature development
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Release (Beta)
- [x] Build (Beta 2)
- [x] QA validation (Beta 2)
- [x] Release (Beta 2)
- [x] Build (RC1)
- [x] QA validation (RC1)
- [x] Release (RC1)
- [x] Build (Final)
- [x] QA validation (Final)
- [x] Final release
- [x] Available for upgrade
- [x] Build docker images
- [x] Release blog article

**Comment by eternoendless** [comment]
The release is currently in late stabilization phase.

**Comment by eternoendless** [comment]
Update: we're finishing the last critical bug fixes before beta. We'll send a build to QA once [all issues labeled "High"](https://github.com/PrestaShop/PrestaShop/projects/7?card_filter_query=label%3Ahigh) have been merged.

**Comment by eternoendless** [comment]
The stabilization phase has now ended, we are now able to build and test the first beta! 🎉 

Stay tuned for beta 1 release next week (hopefully).

**Comment by jolelievre** [comment]
The beta build 1 is ready, and is being validated by the QA team

**Comment by eternoendless** [comment]
The build is still being verified by QA. Unless a critical bug is found, we expect to be able to deliver it early next week.

**Comment by jolelievre** [comment]
The beta build has been validated by QA team, it should be available really soon now...

**Comment by PululuK** [comment]
Good job guys. Thank you !

**Comment by jolelievre** [comment]
The 1.7.7.0 Beta 1 is officially available:

https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-beta.1

Thanks to all the contributors for this release 😉 Waiting for your feedback ^^

**Comment by matks** [comment]
It would be great to be able to track the reported issues for beta and update this issue with the number of bugs to be fixed before RC1 😄

**Comment by eternoendless** [comment]
> It would be great to be able to track the reported issues for beta and update this issue with the number of bugs to be fixed before RC1

IMO that's what the [kanban](https://github.com/PrestaShop/PrestaShop/projects/7) is for.

**Comment by daghb** [comment]
Is there a beta docker image available? Which tag should I pull?

**Comment by matks** [comment]
We have a `beta` image in the hub 🤔 but I did not check what it does
https://github.com/PrestaShop/docker

**Comment by daghb** [comment]
Thanks, @matks - I'll try that one out. I guess it will be too early to ask what the upgrade paths are from a 1.7.6.1 docker image?

**Comment by eternoendless** [comment]
## Status update: beta 2 incoming

Over 130 PRs have been merged to 1.7.7.x since Beta 1 was built. Even though quite a lot of bugs have been fixed (particularly in the Orders page), new bugs keep popping up, so we're still not 100% confident about the branch's stability.

Since Beta 1 is now three months old, we have decided to issue a second beta build that contains all fixes merged since. This will give us more time to continue squashing bugs and at the same time provide the community with a more up to date version to continue testing.

We're targeting a **Beta 2** which will be built next Monday and released on **September 1st**. This will be followed by an RC early October at the latest.

**Comment by jolelievre** [comment]
You will be pleased to know that the Beta 2 has been built and is currently being tested by the QA team ^^

**Comment by prestaforum** [comment]
Hi, is there any progress on this test phase ? I am waiting to test it for a customer. Please provide some updates ;)

**Comment by matks** [comment]
## Status update: beta 2 build validated

The 1.7.7.0 Beta 2 build has been validated by QA team. The test campaign contained 414 manual tests, and
- 90% are successfull (373)
- 3% cannot be run in current context (blocked) (12)
- 7% are failing (29)

Since the 7% failing tests are not blocking issues, we will be able to deliver the build publicly and open the second public beta period for 1.7.7.0.

**Comment by matks** [comment]
## Status update: release of beta 2 🚀 

=> Read the [Release note](https://build.prestashop.com/news/prestashop-1-7-7-0-beta2-release/) on Build 📖 

You can download 💾  this beta version:
- On [prestashop.com website](https://www.prestashop.com/en/file/prestashop_1-7-7-0-beta-2-zip/download?token=UbT5nmNu)
- On [Github](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-beta.2)

**Comment by eternoendless** [comment]
## Status update: RC 1 has been built! 🏗️ 

The Release Candidate has been built yesterday and is now under QA validation. If everything goes well you can expect it to be published around October 12th.

**Comment by matks** [comment]
## Status update: RC 1 build 1 is faulty 🚫 

QA team found multiple issues, and the issues list contains 1 critical bug and 1 major bug:
- https://github.com/PrestaShop/PrestaShop/issues/21300 Missing Gift and Recycled packaging when Creating a new Order
- https://github.com/PrestaShop/PrestaShop/issues/21323 Incorrect discount value & amount in View an Order page when using different currencies

These items have been moved into the [1.7.7 Kanban](https://github.com/PrestaShop/PrestaShop/projects/7) and are currently being fixed. Following the fixes delivery, we will be able to build a new ZIP archive which will be **RC 1 build 2** and it will be transferred to QA team again for validation.

**Comment by eternoendless** [comment]
## Status update: RC 1 build 2 has been created! 🏗️ 

The second build of Release Candidate 1 has been created on Tuesday and is currently undergoing QA validation. If everything goes well you can expect it to be published next week.

**Comment by 8ele8** [comment]
When do you think the final release will be in November ? 
Beginning of November? Mid-November? Or first at the end of November?

Prestashop 1.7.6 is compatible with PHP up to PHP 7.2, but not PHP 7.3. 
https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

Webhosting companies who want to ensure the security of their customers' webspaces and of their servers will decommission PHP 7.2 as soon as it reaches its end-of-life (i.e. Nov. 30th) 
If the final release of Prestashop occurs too late in November, this may result into many user with an non-working shop. Which can be pretty bad for the ones whose business relies on their Prestashop store :(        
Or can you confirm that the RC1 is working fine with PHP 7.3 and could it be an acceptable temporary solution for users in case the final release is delayed or happens first late in November? 

Thanks in advance for the info about that :)

**Comment by eternoendless** [comment]
Hi @8ele8 

To the best of our knowledge, RC1 is working fine in php 7.3. You will be able to use it in production if you choose to, but you won't be able to upgrade to a second RC (if there is one) or the final version using the 1-click upgrade module.

We're targeting early November, but this will depend on the build's stability once it's released.

**Comment by jolelievre** [comment]
## Status update: RC 1 build 3 has been created! 🛠

The third build of Release Candidate 1 has been created today and passed on to the QA team. Since the added fix is only about the Order page scope they won't need to start over from square 1. The whole order page will be re-tested for safety though! Current QA progress is around 75% of the whole test campaign.

So let's all hope this is the last build 🤞😅. and that we soon will be able to provide a RC release to the community!

**Comment by jolelievre** [comment]
## Status update: RC 1 is finally released! 🎉🚀

So patience paid up!! ^^ We are proud, and relieved, to announce you the release of the RC1 for PrestaShop version 1.7.7.0!!!

You can download this version:

- on [Github](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0-rc.1)
- on [PrestaShop website](https://www.prestashop.com/en/developers-versions)

And if you want more details about the content of this RC1 version feel free to read our article because [PrestaShop 1.7.7.0 RC1 Is Ready To Be Tested!](https://build.prestashop.com/news/prestashop-1-7-7-0-rc-release/)

As our [release lifecycle](https://devdocs.prestashop.com/1.7/project/release/patch-release-lifecycle/#release-candidate) states, this version is open for community to test, and unless some major Bug is found within ~one week~ two weeks it will become, de facto, the stable official build for 1.7.7.0 version.

So don't hesitate to test it, this is how we improve PrestaShop together!!

**Comment by thbl** [comment]
@jolelievre is it ready for final build ?

**Comment by matks** [comment]
> @jolelievre is it ready for final build ?

Today is the last day 😉  it is possible to submit bug reports for 1.7.7.0 RC1 until 17th of November, midnight. Past this point we'll consider that the Release Candidate is ready for stable release.

**Comment by ristokekovic** [comment]
Will the 1.7.7 version be released today?

**Comment by thbl** [comment]
@Risto995 maby next year

**Comment by matks** [comment]
Hi, well, maybe it was wrong to say "Today is the last day" because some people decided to test the release candidate yesterday and found major issues 😛  https://github.com/PrestaShop/PrestaShop/issues/21948

That is a joke obviously 😄  we are grateful that people test the release candidate.

So we have a few more bugs to fix.

By the way @thbl @Risto995 did you test the release candidate 😉  ? It's never too late

**Comment by ghost** [comment]
@matks i tested the RC before but no the upgrade :rofl:  ( :1st_place_medal: tester )  , there are an other major issue with the logo

I go to open an issue in autoupgrade to make RC chanel << Great Again >> it's easier for all tester and merchant :)

**Comment by matks** [comment]
## Status update: RC 1 is faulty 🚫 

Some important issues have been reported.

These items have been moved into the [1.7.7 Kanban](https://github.com/PrestaShop/PrestaShop/projects/7) and are currently being fixed.

**Comment by eternoendless** [comment]
Note that only issues labeled "Must-have" will be fixed for 1.7.7.0

**Comment by CJH297** [comment]
Is a release anticipated before the month end? I'm one of those mentioned by 8ele8 as having an ISP that will cease to permit use of php 7.2 - that is, if am still using 7.2 after community support ends, I have a large invoice to pay for 'enhanced support' to keep it running (it will be automatically charged for a year, and is expensive). I understand that I could use the beta version, but the lack of ability to update isn't good - I know no code, just a user. Will the release be in time?

**Comment by Daaaaad** [comment]
@CJH297 By curiosity: What's your ISP? Those rules seems very strict to me 🤔

**Comment by CJH297** [comment]
1&1 (now Ionos). I had this problem once before - I had a domain registered and a php attached to it by default, but only used the domain for forwarding. No website attached. I had a big bill when that php was decommissioned because they were now supporting the old version, which cost extra. I argued my way out of it because I was not using the php and couldn't be. It was a struggle and not one I can repeat, because this time I really will be using the old php come the end of the month, if I have no upgrade in place. They don't decommission the php itself, just add a bill for 'extended support' or some such name.

That's what happened last time, so my assumption is that it will happen again.

I utterly appreciate this is volunteer time I'm asking about ... but equally, the nearness of timing makes me nervous.

**Comment by ghost** [comment]
Php 7.2 end on Inos in Mars 2021 

```
Que doivent faire les utilisateurs de PHP 7.2 maintenant ?
Le support officiel de PHP 7.2 prendra fin le 30 novembre 2020. Si votre site Web utilise PHP 7.2 avec IONOS, vous serez informé par email que vous ne pouvez continuer à utiliser PHP 7.2 que dans le cadre du Support Prolongé PHP 7.2. Support Prolongé PHP 7.2 est gratuit jusqu'en mars 2021
```

**Comment by simonvik** [comment]
We will at one.com remove php 7.2 when it reaches EOL.

**Comment by CJH297** [comment]
Thanks okom3pom - that sounds useful if it applies. I have searched Ionos and cannot find this on the English site, though; nothing about extended support for 7.2 being free for a period that I have found. I hope it will apply if the release is not ready

**Comment by jolelievre** [comment]
## Status update: Stable version has been built! 🏗️

We finished fixing the last must-have bugs today, so we were finally able to build the expected stable build version. The build is now in the hands of our QA team who will perform long campaign tests on this, hopefully, final build!!

This campaign usually takes from 4 to 5 days, so if everything is right and no new critical bugs are found then the build will be validated and you can expect the final release of PrestaShop 1.7.7.0 at the beginning of next week!

**Comment by icemansparks** [comment]
Unfortunately, this will still be a walk on knife's edge for some of us whose hosters like one.com will just remove PHP 7.2 on 30th of november for good.

**Comment by matks** [comment]
## Status update: latest build is ✅  but we have found _upgrade_ issues 🚫 

QA team has finished the test campaign and no major issues have been found in the release 🎉  .

However QA team also performed thorough testing of the upgrade process and has found multiples issues. All the possible update paths (1.6.1 to 1.7.7 ; 1.7.2 to 1.7.7 ; 1.7.3 to 1.7.7 ...) have been tested.

The reported issues are currently being fixed by the maintainer team.

**Comment by jolelievre** [comment]
# Status update: PrestaShop 1.7.7.0 Stable version is finally released! 🎉🚀

Most of you didn't expect any more, we had our own moments of doubts.. especially during the last days which were kind of epic 😅. But there it is! The stable version of PrestaShop 1.7.7.0 is finally released and ready for download!!

You can get this version:

on [Github](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.0)
on [PrestaShop website](https://www.prestashop.com/en/developers-versions)

And if you want more details about the content of this finale version an article will be release tomorrow on our [Blog](https://build.prestashop.com/).

## Auto upgrade

You can also upgrade your shop to 1.7.7.0, however for shop which version is below 1.7.6 you **MUST** use the latest version (4.11.0) of our [1-Click Upgrade module](https://github.com/PrestaShop/autoupgrade) which contains a bug fix when upgrading from versions older than 1.7.6.0 And as usual **don't do this in prod right away** always test in a test/preprod environment first 😉

## Big thanks

We'd like to thank all the contributors that participated in this version, as well as all the people who are not tracked by Github but who participated in this version via specifications, testing, commenting, reporting bugs, ... This is all a team work so congratulations to everyone!!

Time to celebrate ^^ 🍻

**Credits (to scroll down with an epic music)**

123monsite-regis
202 ecommerce
Abdullah
Adib Aroui
Aitbella Mohamed
Alexis Haumaitre
Amazzing
andromaque
Antoine Damiron
Antoine Thomas
Ashish Sharawat
Aude
Aurélien Pelletier
Benjamin
Benjamin Dussouillez
Boubker Bribri
Christian Kubitza
Christophe Zarebski
cirykpopeye
Clotaire Renaud
Codencode
ComonSoft
Damian Dominella
Daniel Hlavacek
Daniel Ziegenberg
Darius Aleksiunas
David Gonzalez
Dheeraj Sharma
Dinesh Badrukhiya
Dmitry
Florentin Garnier
Florian Bergeron
Florian Le Gars
Florian Lemaitre
Franck Lefèvre
François Peyret
Gavin Kalikapersaud
hacchus
Harlock
Horia Rudan
Ibrahima Sow
idnovate
JBWModules
Jean-François Viguier
Jevgenij Visockij
Jocelyn Fournier
Jonas Erixon
Jonathan François
Jonathan Lelievre
Jonathan Vollebregt
Julian Eberius
Julien Gissinger
Julius Žukauskas
Justinas Urbanavicius
Karel Faille
Khouloud Belguith
Klemart3D
Krystian Podemski
ks129
Laurynas Sedys
Louise Bonnard
Luc Vandesype
Manfredi Petruso
Marek Hanuš
Marion François
Marvin Sauraye
Mateusz Furga
Mathias Reker
Mathieu Ferment
Matthias Raigne
Matthieu Rolland
Maxim Krizhanovsky
Mehdi Badrani
Michael Voříšek
Mickaël Andrieu
mushroot
Nesrine Abdmouleh
okom3pom
Pablo Borowicz
Paulo Baptista
Peeyush Agrawal
Pierre Rambaud
pojebunny
Presta Module
Prestashark.eu
Prestaworks
PrestaworksNiklas
PululuK
Puma
Raimondas Sapola
Raúl Jiménez
Rinku Kazeno
Rodrigo Laurindo
Rokas Zygmantas
Rolige eCommerce Solutions
Roman Ondráček
seleda
Sergio Quiñonez
Simon Garny
Simone
Stephane Decisy
Sylvestre Nicky
Sébastien Bareyre
Tadas Davidsonas
Tanguy Salmon
Thomas Baccelli
Thomas L'huillier
Thomas Leviandier
Thomas Nabord
Tomas Ilginis
Tuni-Soft
Valentin Szczupak
venditdevs
Vincent Hadjedj
Vladimir
Web Premiere
webmak
Yannick Armand
Šarūnas Jonušas

**Comment by metacreo** [comment]
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'shop.ps_link_block' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block_lang` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'shop.ps_link_block_lang' doesn't exist
SQL 1.7.7.0 1146 in ALTER TABLE `ps_link_block_shop` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci: Table 'shop.ps_link_block_shop' doesn't exist

**Comment by kpodemski** [comment]
@metacreo thanks, this is indeed an issue as convert tables from module shouldn't be places in core upgrade file, I'll create an issue for this
