### ISSUE TITLE
[EPIC] Multistore 1.7.8 - Linklist module & BO page CMS

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19297]
All the issues realted to Linklist module & BO page CMS with Multistore

## BUGS

- [x] #9795 - Linklist - Compatible multistore **`must have`**

## IMPROVEMENTS
- [x] #18965 - Position column should be displayed only in a specific store context when the multistore is enabled **`must have`**

## FEATURES
- [x] #19295 - Linklist - Add multistore header **`must have`**
- [x] #19296 - Linklist - Add multistore shop association block **`must have`**
- [x] #23521 - Linklist - Make the listing multistore compliant  **`must have`**

**Comment by beyondsagency** [comment]
UP

**Comment by kpodemski** [comment]
@PrestaShop/prestashop-core-developers @marionf 

I'd like to work on this. If no one is already assigned I'll handle this in upcoming days 👍

**Comment by matks** [comment]
About the multistore header: the idea is to build a reusable set of PHP an JavaScript classes to be used everywhere

@matthieu-rolland started the implementation, if I am not wrong, somewhere on one BO page
So you better wait for the PR to be merged then you can reuse it 😉 

ping @matthieu-rolland

**Comment by kpodemski** [comment]
@matks is this going to replace this element:
https://www.dropbox.com/s/y2istldih08jdy6/Zrzut%20ekranu%202020-09-18%20o%2012.03.17.png?dl=0

or the idea is to have duplicated block to be more visible?

**Comment by kpodemski** [comment]
@matks 

It's an interesting topic, I'm not sure if this issue is a place to have such a discussion, but for me it's not that obvious that we should treat this multi-store header as separated included on every page or module component. 

Maybe it should be controller by BO theme, and we should be able to just remove it from the context if page or module is not fully compatible with multi-store?

Unless I understood you wrong and the idea is to have it globally but as a component, without need to include it on every page.

**Comment by matks** [comment]
> @matks is this going to replace this element:
> https://www.dropbox.com/s/y2istldih08jdy6/Zrzut%20ekranu%202020-09-18%20o%2012.03.17.png?dl=0
> 
> or the idea is to have duplicated block to be more visible?

Indeed it will replace this element. It's like a v2.

Specifications are here https://github.com/PrestaShop/prestashop-specs/blob/master/back-office/multistoregeneralspecs.md

It looks like this

<img width="598" alt="Capture d’écran 2020-09-18 à 15 04 40" src="https://user-images.githubusercontent.com/3830050/93600737-6a427a00-f9c0-11ea-99c0-fe95a3c024a5.png">

**Comment by matks** [comment]
> Maybe it should be controller by BO theme, and we should be able to just remove it from the context if page or module is not fully compatible with multi-store?

Unfortunately, it seems not every BO page behaves the same for multistore behavior 😢 . We have identified at least 4 different "multistore page" categories:

- "affected" pages, for example Add/Edit Category where you "link" the modified entity with shops
- "override" pages where you can decide if your action should impact "all shops" or "a group of shop" or "only one shop" using the infamous checkboxes
- one more I dont remember what it is 😅 
- custom pages that have their own rules 😛 

This is why we believe the work must happen page by page. Each of them needs to be identified to see how it fits inside MultiShop BO feature.

**Comment by kpodemski** [comment]
@matks 

ok, this v2 is prepared to be only on "modern" pages? or both, legacy and modern? I'm asking if as a module developer I need to think about 1.7.8 as a version which introduce huge change to PrestaShop ecosystem

As far as I understand specification for now this idea is for core pages, not for the modules.

**Comment by marionf** [comment]
Hi @kpodemski 

It's great to hear you want to work on this :+1: 

The new multistore header is a must have for the 1.7.8 for migrated pages (as you can see in the [EPIC](https://github.com/PrestaShop/PrestaShop/issues/19304))
It's a nice to have for legacy pages

The linklist module is already in symfony, so the new multistore header will have to be implemented
But I guess, it's better to wait its implementation on at least one symfony page of the BO (issue is [here](https://github.com/PrestaShop/PrestaShop/issues/19300))

In the meantime you can start working on the two first issues of this EPIC if you want :)

**Comment by marionf** [comment]
Thank you @kpodemski for the great work on the module :clap:

**Comment by beyondsagency** [comment]
Thanks @kpodemski
