### ISSUE TITLE
[Basic settings tab] - Features 10/14

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19520]
As a merchant, I want to be able to complete the basic information of my products.

The **Features section** is displayed if the Feature option in the Advanced Parameters / Performance / Optional features page enables otherwise the section is hidden.

Display the section's title "Feature" even if there is so feature saved.

- [ ] **Add a feature**: By default the selected option is "Choose a feature".
All the features are displayed in the drop-down and are sorted by position ASC. If there are several features with the same name, then the ID of the feature is displayed before its name. If you have not yet selected a feature, the “pre-defined value” drop-down is disabled and the “customized value” fields should be also disabled \([issue 16306](https://github.com/PrestaShop/PrestaShop/issues/16306)\)       
When you select a feature, both fields \(pre-defined & customized value\) are enabled.       
The features and the associated values are displayed in the product details tab of the front-office.
- [ ]  **Feature pre-defined value**: All the values of the selected feature are displayed in the drop-down and are sorted by name ASC.
If there are several features' values with the same name, then the ID of the feature's value is displayed before its name If you select a pre-defined value, the customized value should be disabled because a feature can’t have both (issue [#16306](https://github.com/PrestaShop/PrestaShop/issues/16306))
When you add a feature with a pre-defined value, it’s added in all languages enabled.
- [ ]  **Feature customized value**: If you start enter a customized value, the pre-defined value drop-down should be disabled because a feature can’t have both \([issue 16306](https://github.com/PrestaShop/PrestaShop/issues/16306)\)      
When you add a feature with a customized value, the feature is added in all languages enabled but the customized value field stays empty in the other languages than the selected one.       
A drop-down next to the field is displayed when there are several languages installed \(disabled languages are displayed in the drop-down\). It allows to choose in which language the field is displayed. Also, in the case of multilanguage, if an error occurs, then I must be warned in the message which language is problematic \([improvement 16299](https://github.com/PrestaShop/PrestaShop/issues/16299)\)
- [ ]  **Delete feature**: Button to delete the feature. When you click on it, you have a modal for cancel or confirm the action. When you delete a feature, it’s deleted in all languages.

---

## Improvements
- [ ] #16306 - Improve feature creation in product page

## Bugs
- [ ] #21689 - Disabling feature in Performance doesnt hide the button in the product page
- [ ] #20027 - Custom feature value does not save in multilanguage shop duplicate of https://github.com/PrestaShop/PrestaShop/issues/13751
- [ ] #9625 - [BOOM-5738] Product custom feature does not save after changing default language
- [ ] #15383 - Multistore Product feature saving bug **`Multistore`**
- [ ] #23299 - Wrong popup displayed when the custom text of feature is above 255 char

**Comment by MatShir** [comment]
**Feature fields**
When you add a customized value for a feature, invalid characters are: _<>=#{}_ and you are limited to maximum 255 characters.
If you enter an invalid character or more than 255 chars and save, you have a success message "settings updated" but the feature isn't added.

- [ ] When you save, if your customized value contains an invalid character, we should display the error "This value is not valid" under the field. When there are many languages the language concerned should be displayed: "This value is not valid. - Language: Français (French) "

- [ ] If you try to enter more than 255 chars, an error message should be displayed under the field: “This value is too long. It should have 255 character or less.”

- [ ] When you add a new feature, if you have not yet selected a feature, the “pre-defined value” drop-down is disabled and the “customized value” field should be also disabled (currently it’s not). When you select a feature, both fields (pre-defined & customized value) are enabled.
If you select a pre-defined value, the customized value field should be disabled.
If you start enter a customized value, the pre-defined value drop-down should be disabled.

**Comment by MatShir** [comment]
**Improvement**:
- [ ] #16306
Issue:
- [ ] Disabling feature in Performance doesnt hide the button in the product page #21689
- [ ] https://github.com/PrestaShop/PrestaShop/issues/19212
- [ ] https://github.com/PrestaShop/PrestaShop/issues/20027 duplicate of https://github.com/PrestaShop/PrestaShop/issues/13751
- [ ] https://github.com/PrestaShop/PrestaShop/issues/9625
- [ ] https://github.com/PrestaShop/PrestaShop/issues/15383 - Multistore

**Comment by colinegin** [comment]
Ping @MatShir issue #9680 should be fixed during the development of the tab, as this can be quite frustrating to not be able to delete a feature.

**Comment by zuk3975** [comment]
Reminder issue for features:
* When last feature is left and I switch it back to default value "Choose feature", click save and error appears.
![Screenshot from 2021-08-27 19-32-08](https://user-images.githubusercontent.com/31609858/131159711-2201130e-de6a-478a-a41b-e22f5a264f19.png)
* https://github.com/PrestaShop/PrestaShop/pull/12388 :heavy_check_mark: This seems to be handled already (if FeatureId is not selected, then its not saved at all)
