### ISSUE TITLE
[WIP][EPIC] Form Type reusability and stability

### ISSUE THREAD

**Issue by 202-ecommerce** [PrestaShop/PrestaShop#19537]
This EPIC is based on a [sample module](https://github.com/202ecommerce/checkboform) with all From Type from PrestaShop Bundle or Symfony.

## Qualified by the author

- [ ] #11329 - PS1.7 add Specific Price with time (hours)
- [ ] #18806 - Improvement > CategoryChoiceTreeType to add a "check all button"
- [ ] #19547 - Bug > GeneratableTextType and ReductionType show help two times
- [ ] #19555 - Improvement > Form Type error are not managed on each fields

- [ ] Improve documentation for all Form Type

## Fixed
- [x] Help on textarea (twig) show 2 times > fixed by #19453
- [x] Help on FormattedTextareaType show 2 times > fixed by #19453
- [x] #19612 - Improvement > CategoryChoiceTreeType, ChoiceCategoriesTreeType ShopChoiceTreeType "required" attibute doesn't validate fields
- [x] #19552 - Bug + Refactoring > IpAddressType not reusable without template custumization
- [x] #19540 - Bug > Form Type help and popover tooltip not display properly
- [x] #19544 - Bug > CustomMoneyType or ResizableTextType looks unused and throw an error when used

**Comment by MatShir** [comment]
Hi @clotaire202,
It seems to be an improvement. Could you please provide us with more info? We need more details to understand the issue. It will help prioritize it.

Usually, when we create an epic it's a prioritized list of issues. Each issue is resolved by a pull request, which helps the quality assurance and product team understand the whys and how of each PR. But we can adapt according to your comments.

Thank you

**Comment by clotairer** [comment]
@MatShir

This summary is work in progress (WIP). I cannot publish all tickets in the same time ... This part of PrestaShop is quite forgotten. I need some time to check and report all "suspicious" behaviour.

But you will receive an issue for each line here with a full explanation. How to reproduce, if it's an improvement, if it's a bug, ... all details you need to take a decision, to approve a development or to reject an improvement.

There are lot of issues to use and re-use PrestaShop From Type. The code has probably never been tested on module context and that's what we do, just because we need it. We could create our own From Type but it does not improve the comunity project.

Please give me a little time to report all to the community (feedbacks are welcome). After that's I hope we will have a overview to improve PrestaShop on this issue.

Thank you.
Clotaire

**Comment by MatShir** [comment]
Thank for your clarification :smile:

**Comment by clotairer** [comment]
A first batch qualified is now available here. There is more things to be improved.
