### ISSUE TITLE
[EPIC] Errors when adding a product with minimum quantity in order page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19595]
The issues below are grouped in an epic because it seems they have to be solved together.

## BUGS

- [x] #18568 - BO - Order page - An exception is displayed when adding a product with a min quantity
- [x] #18695 - A product allowed to be ordered out of stock with a minimum quantity cannot be added to the BO order.
- [x] #19607 - The minimum quantity is not respected when I add a product 
- [x] #21525 - BO - Order page - An error 500 is displayed when adding a product with a min quantity

**Comment by zuk3975** [comment]
There was a discussion about how to handle scenario when merchant adds product with a custom price to order in which  identical product already exists.
So:
1. Our main goal is to merge identical product rows (maybe in 1.7.8 or later, but not for 177)
2. That means we cannot handle different prices for same product

The solution for 1.7.7:
We check if order already has identical product. If it contains identical product, we don't allow to change product price anymore, but leave the existing product price instead. (in future we will want only to increase the quantity of existing product)
And if merchant updates the product price in the list, all of identical product prices should change.

@MatShir please correct me if I'm wrong

**Comment by marionf** [comment]
@MatShir The 3 issues are fixed, we can close this epic :tada:

**Comment by khouloudbelguith** [comment]
Hi @MatShir,

we have an issue related to this Epic reported here: https://github.com/PrestaShop/PrestaShop/issues/21525.
Can we re-open this Epic?

Thanks!

**Comment by MatShir** [comment]
No need, the issue will be quickly closed for the 1.7.7 build.
