### ISSUE TITLE
[EPIC] BO - Display and update error on cart rule in the order 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19594]
The issues below are grouped in an epic because it seems they have to be solve together.

## BUGS 

- [x] #19184 - BO - Order detail - Voucher is displayed multiple time 
- [x] #19591 - Adding a second product in the order does not update correctly the cart list 
- [x] #19592 - Update product's quantity in the order does not update the discount 
- [x] #19890 - Update product's price in the order does not update the discount 
- [x] #19960 - Order BO discount removing/changing not working properly

**Comment by marionf** [comment]
All issues are fixed, I close this EPIC
