### ISSUE TITLE
[EPIC] Product List 

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#19676]
## Listing
- [x] #20221 - [BO][PRODUCTS] Add product count filtered **`Nice to have`**
- [x] #10236 - Alt tag empty in product listing BO
- [x] https://github.com/PrestaShop/PrestaShop/issues/27757

**In the header, there is "New product" button allowing to open the form to create a new product**

## Bulk actions drop-down
- [ ] #22906 - Mass action -> Stock availability preferences

## Rearrange button
- [x] #17412 - Switch 'Reorder' into 'Rearrange' in the products listing #17412

## Changing the position of products
- [ ] #15291 - Reorder product in category is not working in some condition

## Search
- [x] #11167 - Strange behavior if put in the Min filter a character

## Actions
- [ ] #20669 - Allow merchants to easily configure, what data do they want to see in BO **`To be studied`**

## Pagination
- [x] #22441 - Pagination in backoffice products after filtering by category PS1.7.6.1

## Fixed
- [x] #10792 - Unit price reset to 0 if you activate/deactivate or duplicate products in bo product list **`Must-have`**
- [x] #17942 - Can't cancel 'Reorder' in the products listing

**Comment by MatShir** [comment]
**Must-have**:
https://github.com/PrestaShop/PrestaShop/issues/10792

**Nice to have**:
https://github.com/PrestaShop/PrestaShop/issues/20221

**To be studied**
https://github.com/PrestaShop/PrestaShop/issues/20669
