### ISSUE TITLE
[EPIC] Linkchecker errors

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/PrestaShop#19761]
#### Describe the bug

When running linkchecker from UI tests, I found several console or response errors

#### Expected behavior

No error found 

#### Steps to Reproduce

- [x] #18776 - A. **BO - orders Pages** =>
1. Go to 'BO -> orders or BO -> orders -> add order' page
2. Open console (`F12` in chrome then console tab)
3. See error
![image](https://user-images.githubusercontent.com/48441421/84670095-f0fd3c00-af25-11ea-9ce1-bb93e4c01e32.png)

- [x] #20484 - B. **BO - Add product page (tinyMCE error)**
1. Go to 'BO -> products -> add product' page
2. Open console (`F12` in chrome then console tab)
3. See error
![image](https://user-images.githubusercontent.com/48441421/84670595-9d3f2280-af26-11ea-8ff8-7a68eec9dcd9.png)

- [x] #19498 - C. :heavy_check_mark: **BO - module catalog**
1. Go to 'BO -> module catalog ' page
2. Open network (`F12` in chrome then newtork tab), the same errors are displayed in console tab
3. See errors
![image](https://user-images.githubusercontent.com/48441421/84671739-04110b80-af28-11ea-835c-890469900866.png)
![image](https://user-images.githubusercontent.com/48441421/84672085-68cc6600-af28-11ea-8b12-9e960131b027.png)

- [x] #20485 - D. **FO - product page (in french)**
1. Go to 'FO'
2. switch language to FR
3. go to first product page
4. Open console (`F12` in chrome)
5. See error
![image](https://user-images.githubusercontent.com/48441421/84672304-b052f200-af28-11ea-9512-4eb992ae56ff.png)

PS : You can see these errors by running linkchecker from [this PR](https://github.com/PrestaShop/PrestaShop/pull/19727)
PS2: The work on the linkchecker is still in WIP, there is maybe more errors (that we can find later)

#### Additional information

* PrestaShop version: branch 1.7.7.x
* PHP version: 7.3

**Comment by matks** [comment]
Also 
**BO - orders Pages**
1. Go to 'BO -> orders or BO -> orders -> add order' page
2. Click "create a customer" button to open modal

**Comment by boubkerbribri** [comment]
> Also
> **BO - orders Pages**
> 
>     1. Go to 'BO -> orders or BO -> orders -> add order' page
> 
>     2. Click "create a customer" button to open modal

Thanks matks, we didn't see that because we check only urls (not user scenarios), we will find a way to improve our script.

Error displayed when click on create customer : 
![image](https://user-images.githubusercontent.com/48441421/84674665-8c44e000-af2b-11ea-97e8-d7fbbe6a8508.png)

**Comment by marionf** [comment]
All issues are fixed, I close this EPIC :tada:
