### ISSUE TITLE
[EPIC] - Products (combination, customized) & Pack stock issues

### ISSUE THREAD

**Issue by colinegin** [PrestaShop/PrestaShop#19846]
This EPIC centralizes issues related to problems in stock and quantities for all types of products.
For issues related to the stock page, please follow #19813.

## BUGS

**Packs**
- [ ] #9806
- [ ] #9814
- [x] #14329
- [ ] #26728

**Customized products**
- [x] #9974
- [ ] #28688
- [ ] #36208
- [ ] #29663
- [x] #30071 
- [ ] #31261
- [x] #32233
- [x] #32714
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35625
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35631
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35623

**Virtual products**
- [x] #9502
- [x] #24149
- [ ] #14419

**Products with combinations**
- [ ] #12814
- [x] #30179
- [x] #21271
- [ ] #16581
- [x] #24587
- [x] #25308
- [x] #25722
- [x] #25817
- [x] #26763
- [x] #14744
- [x] #9901 
- [ ] #27816
- [x] #29460
- [x] #29506
- [x] #29863 
- [x] #33545 
- [ ] #33720 
- [x] #34358 
- [x] #34694
- [ ] #35481

## Features

**Packs**
- [x] #20001

**All products**
- [ ] #16713

------------------

## BUGS

**Packs**
- [x] #9671
- [x] #13769
- [x] #21034
- [x] #9728

**Customized products**
- [x] #26374

**Products with combinations**
- [x] #20454

**Comment by Progi1984** [comment]
@PrestaShop/prestashop-product-team Added #20001 to this EPIC

**Comment by hugolin69** [comment]
Hi,
There is so much to say. Yes, this topic is EPIC.

- Pack stock incorrect after order when choosing to decrement both #9671
The last point works also when choosing "Decrement only the products of the pack".
If you try to order a pack in this case, it will decrease the physical quantities, instead of decreasing the virtual quantity of the source product, the stock page will not show the good quantity etc... Really !!! I would like to meet the intern who work on that.
How can we have a buggy CMS in 1.7.6 ????!!! This is a main feature !

Lost between Magento that needs now 10 people to work on it, and Prestashop, that is more buggy than ever on core features. they exited the Advanced Stock System, because they can not manage it, how good is that !???
Prestashop cost everyday more in modules, modules that comes with main critical errors.

Yes this topic is going to be EPIC.

**Comment by jonpontet** [comment]
Any chance some progress can be made on this ? We are awaiting these fixes with anticipation !

**Comment by marionf** [comment]
You can make it progress by submitting a pull request:
https://github.com/PrestaShop/PrestaShop/tree/develop

**Comment by jonpontet** [comment]
> You can make it progress by submitting a pull request:
> https://github.com/PrestaShop/PrestaShop/tree/develop

Very true - if only I knew how to fix it ! (which I guess is the trouble you are having?)

**Comment by kylak** [comment]
Warning guys; product->location is "@deprecated since 1.7.8" (cf. classes/Product.php), to use the location system we can/should use StockAvailable::$location instead.
Prestashop 1.7.8 BO reads the "product location" in the stock_available database table and not in the product database table (even if there's a location field in the product table).
In Ps 1.7.8, when the "product location" is set through the BO, both the location in the stock_available database table and in the product table are updated. 
#16581
