### ISSUE TITLE
[EPIC] - Productcomments module

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#19933]
## Multistore issues
- [x] #19932
- [x] #19934 

## Features
- [x] #17837 

## Bugs
- [x] #29863
- [x] #30345 
- [x] #30543

#### Multistore issues
- [x] #19811

#### Features
- [x] #15597
- [x] #16339 - [PR](https://github.com/PrestaShop/productcomments/pull/45) 
- [x] #18817 
- [x] #19336 - [PR](https://github.com/PrestaShop/productcomments/pull/55) 
- [x] #24814
- [x] #27089 - [PR](https://github.com/PrestaShop/productcomments/pull/124)
- [x] #28855
- [x] #29357
- [x] #28879

#### Bugs
- [x] #27845
- [x] #28935
- [x] #13368
- [x] #16505
- [x] #19122
- [x] #20343  
- [x] #21171 
- [x] #22222 
- [x] #22481
- [x] #23218
- [x] #24528 
- [x] #26274
- [x] #27007
- [x] #28929
