### ISSUE TITLE
Release 1.7.6.6 🚀

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#19959]
This issue tracks the status of the PrestaShop 1.7.6.6 release

1.7.6.6 is a new patch version for 1.7.6.x branch.

### Information

Q | A
--|--
**Type** | Patch version
**Milestone** | [1.7.6.6](https://github.com/PrestaShop/PrestaShop/milestone/65)
**Kanban** | [1.7.6.x](https://github.com/PrestaShop/PrestaShop/projects/4)
**Estimated release** | 2020-07-02

### Current status

- [x] Development
- [x] Build
- [x] QA validation ▶️ found regressions (see below)
- [x] Fixing found regressions
- [x] 2nd build
- [x] QA validation
- [x] [Release](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.6.6)
- [x] Available for upgrade

_Note_: since release 1.7.6.7 is scheduled we will not provide a 1.7.6.6 Docker image in order to allow people to jump directly to 1.7.6.7 version

**Comment by Hlavtox** [comment]
Good, so https://github.com/PrestaShop/PrestaShop/issues/18674 can be fixed 🚀

**Comment by matks** [comment]
## 🚧 ⛑️ STATUS UPDATE

Almost all the last Pull Requests eligible for 1.7.6.6 have been merged. However we have identified at least 2 regressions introduced by the merge of the day.

#### Issues to be fixed before release

1. https://github.com/PrestaShop/PrestaShop/issues/19988 Some code for PS 1.7.6.6 is not compatible with php5
This issue has been reported by Travis CI and can be fixed with PR https://github.com/PrestaShop/PrestaShop/pull/19986
2. https://github.com/PrestaShop/PrestaShop/issues/19989 It is not possible to disable a module from BO page
This issue has been reported by Travis CI and can be fixed with PR https://github.com/PrestaShop/PrestaShop/pull/19990

Note: https://github.com/PrestaShop/PrestaShop/pull/19990 embeds the fix https://github.com/PrestaShop/PrestaShop/pull/19986 so merging https://github.com/PrestaShop/PrestaShop/pull/19990 will fix the 2 issues.

#### Pull Requests to be merged release

1. https://github.com/PrestaShop/PrestaShop/pull/19984 Update license headers date for PS 1.7.6.6
2. Merge the 1.7.6.6 ChangeLog

**Comment by matks** [comment]
## 🚧 🚥 STATUS UPDATE

`1.7.6.x` branch has been completed for release, and a 1st ZIP archive has been built. It has been delivered to QA team who will be able to launch the standard patch release test campaign.

This test campaign aims to find whether this patch introduces new bugs.

If the campaign reports that no bugs are found, the new patch release will be validated by QA team and we will be able to proceed to release.

More details about the process on https://devdocs.prestashop.com/1.7/release/minor-release-lifecycle/#what-happens-in-six-weeks

**Comment by matks** [comment]
## 🚧 ⛑️  STATUS UPDATE

QA test campaign still going on. It's a long campaign as `1.7.6.6` supports php5 _and_ php7 versions.

A trivial issue has been identified:
- the style of the "confirm" window fro "delete" action has been modified in BO "Attributes" page

A blocking issue seems to have been identified (currently confirming the issue):
- when DEBUG mode is on, BO "Improve > Payment > Preferences" (EDIT: modified) page crashes on php5

**Comment by kpodemski** [comment]
Sorry for the offtopic but i really like this kind of status updates before release! gj

**Comment by matks** [comment]
> A blocking issue seems to have been identified (currently confirming the issue):
> 
> * when DEBUG mode is on, BO "Improve > Payment > Preferences" (EDIT: modified) page crashes on php5

The failure usecase is now a lot more accurate and is under investigation in https://github.com/PrestaShop/PrestaShop/issues/20012

**Comment by matks** [comment]
⛑️ Another **blocking** issue has been identified about upgrade => https://github.com/PrestaShop/PrestaShop/issues/20013

**Comment by matks** [comment]
## 🚧 🚥 STATUS UPDATE

Bug https://github.com/PrestaShop/PrestaShop/issues/20012 has been explored and it is not a blocking item for 1.7.6.6 release
Bug #20013 has been fixed by PR https://github.com/PrestaShop/PrestaShop/pull/20018

This evening, branch `1.7.6.x` is, to the best of our knowledge, free of regressions.

Consequently tomorrow we will be able to 1) build a new ZIP 1.7.6.6 archive and 2) start a QA test campaign in order to validate this build.

**Comment by eternoendless** [comment]
## 🚧 🚥 STATUS UPDATE

A second build has been created and sent for QA validation.

**Comment by matks** [comment]
## 🚀 ✅ STATUS UPDATE

1.7.6.6 is released !
- on GitHub
- on prestashop.com
- the release note is published https://build.prestashop.com/news/prestashop-1-7-6-6-maintenance-release/

**Comment by matks** [comment]
The necessary changes on PrestaShop API to allow upgrade from 1.7.6.5 to 1.7.6.6 are in progress.

If you want to upgrade immediately, you can download the ZIP archive and use "Local archive" option

**Comment by matks** [comment]
## 🚀 ✅ STATUS UPDATE

Auto-upgrade XML channels have been updated since several hours and I just did a 1.7.6.5 => 1.7.6.6 successfully using it

**Comment by matks** [comment]
## 🚧 ⛑️  STATUS UPDATE

3 issues are being investigated for 1.7.6.6, indicating a possible regression:
- https://github.com/PrestaShop/PrestaShop/issues/20044
- https://github.com/PrestaShop/PrestaShop/issues/20047
- https://github.com/PrestaShop/PrestaShop/issues/20048

**Comment by matks** [comment]
## 🚧 ⛑️  STATUS UPDATE

Analysis of https://github.com/PrestaShop/PrestaShop/issues/20044 is complete and has confirmed this is an important issue which requires the release of a new 1.7.6.X patch version. In other words, we confirm there will be a [1.7.6.7 release](https://github.com/PrestaShop/PrestaShop/issues/20054).

**Comment by matks** [comment]
Closing the issue as 1.7.6.6 release process is complete
