### ISSUE TITLE
[EPIC] Wrong product prices on adding/editing on the order's BO

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#20161]
To facilitate the tracking in the kanban, its issues are grouped in an epic.

- [x] #20010 - When I add an existing product in the order's BO
- [x] #19490 - Wrong price displayed before adding a product on an order
- [x] #18237 - Possibility to add multiple time the same product
- [x] #20533 - Order / Product price is incorrect after adding a cart rule 
- [x] #20542 - Total products price is not correctly calculated in specifics conditions

Both issues should be fixed by https://github.com/PrestaShop/PrestaShop/pull/20145

**Comment by marionf** [comment]
I added the must-have label as the PR fixes many major regressions
