### ISSUE TITLE
[EPIC] Wrong discount on the order page

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#20162]
To facilitate the tracking in the kanban, its issues are grouped in an epic.

- [x] #19960 - Order BO discount removing/changing not working properly 
- [x] #19949 - BO - order detail / Discount is deleted when deleting another discount
- [x] #19890 - Update product's price in the order does not update the discount
