### ISSUE TITLE
[EPIC] - Tables improvements

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/PrestaShop#20763]
User interviews lead by the end of last year pointed out the tables management in PrestaShop and one of the insights raised was that a lot of users wanted to better configure their columns: hiding some, adding others, etc. Improving the handling of tables will definitely be a good thing for PrestaShop so let's list here all bugs or improvements issues:

## DISPLAY
- [ ] #14018 - Improve display of Grids
- [ ] #20669 - Allow merchants to easily configure, what data do they want to see in BO

## WORDING
- [ ] #19142 - Harmonize the wording for the 'Status' column in tables

## MIGRATION & REFACTO
- [ ] #13741 - Make grids filtering action work with grids from module extension => switch all existing grids to use filterId feature 
- [ ] #16688 - Implement Grid for JavaScript
- [ ] #19009 - What is the difference and relationship between PositionColumn and DraggableColumn?
- [ ] #19272 - HelperList idea - list_skip_actions and remove_onclick

---
## BUGS
- [ ] #11054 - Filter by Size - Files Page

**Related to the import**
- [ ] #14306 - Ignore non-existing product while importing by reference

## IMPROVEMENT
**Related to the product page**
- [ ] #21503 - Search by & show EAN in Catalog / Stock Window
- [x] #25313

## FEATURE
- [ ] #14743 - Redesign of the bulk action

### OPTIONS
- [x] #19527 - Export in CSV the whole list instead of the current page on the BO list page

### DISPLAY
- [x] #15534 - Bad calendar display on some screens for migrated listing pages

### MIGRATION & REFACTO
- [x] #10910 - Introduce a 'template' property for Columns to allow override?
- [x] #12368 - Remove CategoryPositionColumn and Use PositionColumn instead
- [x] #13448 - Harmonize controller grid search action

---
### BUGS

**Related to the import**

### IMPROVEMENT
**Related to the product page**
- [x] #16101 - As a merchant I want to edit my combination reference without editing it

### FEATURE

---
Click the following link for the design suggestion by @prestascott:
👉 https://projects.invisionapp.com/d/main?origin=v7#/projects/prototypes/18710242
