### ISSUE TITLE
[Epic] - Improvement UI-KIT

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#21832]
All issues related to **UI-KIT** 

### BUGS
- [x] #21827 - Alert icon and text not align
- [x] #21831 - Rounding is missing on some buttons
- [x] #21836 - Bug on dropdown in translation
- [x] #21841 - Reduce button size in theme page
- [x] #21842 - On-Off switch does not display
- [x] #21843 - Align icon with text in email theme 
- [x] #21189 - Need to add new label classes
- [x] #21943 - BO - Order page - The Modal of updating a carrier is not well displayed
- [x] #22314  - space between the icon and the display of the tooltip
- [x] #22319 - size of searchbox with a research is too small
- [x] #22872 - Bug on dropdown in translation on click 
- [x] #22873 - bad display on switch button
- [x] #23021 - [UIKit] Switch button behavior is wrong when Yes is checked and button is disabled
- [x] #23774 - Flashing long messages of different types causes the last type to override the previous ones

### IMPROVEMENT
- [x] #21834 - Improve to on-off switch
- [x] #21835 - Improve radio button
- [x] #21839 - Improve field spacing in customer page
- [x] #21840 - Improvement customer page - reduce icon size 
- [x] #21932 - Improve input in stock
- [x] #22572 - BO pages using new theme have wrong jQuery version and no jQuery migrate
- [x] #24317 - [UI Kit] Updating tooltips colors
- [x] #24376 - Invalid inline style in prestahop ui kit

**Comment by Progi1984** [comment]
Remain an unchecked label  ;)
