### ISSUE TITLE
[EPIC] Improve legal compliance of the open source project

### ISSUE THREAD

**Issue by ttoine** [PrestaShop/PrestaShop#22311]
#### Is your feature request related to a problem?

I am studying the legal compliance of the PrestaShop open source project's Core and its dependencies. In order to be legal compliant, a few improvements are needed.

#### Describe the solution you'd like

- [x] replace jsonify (NPM) because it is in public domain, and it is not acceptable regarding the project license. An alternative exists: https://github.com/substack/jsonify/pull/7#issuecomment-612860241
- [x] update soundasleep/html2text in last version. Current used version is in EPL, and the new version is in MIT. https://github.com/soundasleep/html2text
- [ ] TinyMCE, Cropper, File uploader and PHP SQL parser must have their own repository (if we forked them) or must be managed via a dependencies manager. Currently, they are directly included directly in the Core of PrestaShop. #16475
- [ ] In modules, some librairies are included in the repository instead of being in the list of dependencies in package managers configuration #16015 #16012 #16011 
- [ ] In general, try to remove dependencies distributed under Unlicense and LGPL would be a nice to have. So, no more should be added, if it is possible replace them, it would be awesome. While it is possible to have them in the project regarding OSL, some users that are very straight about open source definition and legal compliance might consider them as a possible problem regarding legal compliance.
   - Unlicense: postcss-apply@0.3.0, postcss-apply@0.8.0, spdx-license-ids@1.2.2, tweetnacl@0.14.5
   - LGPL: ezyang/htmlpurifier, smarty/smarty, tecnickcom/tcpdf, TinyMCE
- [ ] Code origin and authors knowledge #27557

#### Additional context

Enforcing the legal compliance of the PrestaShop open source project will lead to more adoption by companies that care about it; e.g North America and Germany, and big companies in general take a lot of care about legal compliance, in order to avoid copyright issues and patent trolls.

Update note: adding a new issue to the list

## Fixed

- [x] #27172
- [x] Remove useless dependencies like "prestashop-release-script"
- [x] GDPR issue with CNDs used for fonts, #27541

**Comment by eternoendless** [comment]
Don't worry about jsonify, it's a webpack dependency so it isn't bundled:

```
prestashop-classic-dev-tools@1.0.0 /ps177x/themes/classic/_dev
└─┬ webpack@2.7.0
  ├─┬ ajv@4.11.8
  │ └─┬ json-stable-stringify@1.0.1
  │   └── jsonify@0.0.0 
  └─┬ watchpack@1.4.0
    └─┬ chokidar@1.7.0
      └─┬ fsevents@1.1.2
        └─┬ node-pre-gyp@0.6.36
          └─┬ request@2.81.0
            └─┬ har-validator@4.2.1
              └─┬ ajv@4.11.8
                └─┬ json-stable-stringify@1.0.1
                  └── jsonify@0.0.0
```

**Comment by ttoine** [comment]
for jsonify, just have a look at the link I provided, there is a quick solution to replace it.
the problem is not really that it's not bundled, but that it's in the list of dependencies. no lawyer or people like can easily sort what is shipped or not in the PrestaShop zip. so it's really better to remove it.

**Comment by Progi1984** [comment]
@ttoine In this case, you should contact @substack https://github.com/substack/json-stable-stringify to change their dependency.

[EDIT] An issue is existing : https://github.com/substack/json-stable-stringify/issues/36

**Comment by ttoine** [comment]
Any update on this topic ?

**Comment by Progi1984** [comment]
Ping @eternoendless @PrestaShop/product-team for priorization.
