### ISSUE TITLE
[Epic] - Move from Travis to GitHub Actions

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#22650]
Following degrading quality of service from TravisCI, we are moving to GitHub Actions.

### Core

- [x] PHPUnit Tests https://github.com/PrestaShop/PrestaShop/pull/22567
- [x] Linters https://github.com/PrestaShop/PrestaShop/pull/22567
- [x] Behat Tests https://github.com/PrestaShop/PrestaShop/pull/22578
- [x] UI Tests (Sanity) : #22570 
- [x] Nightly Cron trigger : #22712 #24034 #24058 #24061 #24062 #24067 #24074 #24083

### Modules and libraries

- [x] ps_facetedsearch
- [x] autoupgrade : https://github.com/PrestaShop/autoupgrade/pull/377
- [x] [blockreassurance](https://github.com/PrestaShop/blockreassurance) : PrestaShop/blockreassurance#79
- [x] [circuit-breaker](https://github.com/PrestaShop/circuit-breaker) : PrestaShop/circuit-breaker#39
- [x] productcomments
- [x] [TranslationToolsBundle](https://github.com/PrestaShop/TranslationToolsBundle) : PrestaShop/TranslationToolsBundle#84
- [x] [ps_currencyselector](https://github.com/PrestaShop/ps_currencyselector) : PrestaShop/ps_currencyselector#24
- [x] [ps_qualityassurance](https://github.com/PrestaShop/ps_qualityassurance) : PrestaShop/ps_qualityassurance#15
- [x] [ps_featuredproducts](https://github.com/PrestaShop/ps_featuredproducts) : PrestaShop/ps_featuredproducts#37
- [x] [ps_languageselector](https://github.com/PrestaShop/ps_languageselector) : PrestaShop/ps_languageselector#23
- [x] [gamification](https://github.com/PrestaShop/gamification) : PrestaShop/gamification#79
- [x] [ps_linklist](https://github.com/PrestaShop/ps_linklist) : PrestaShop/ps_linklist#120
- [x] [eslint-config](https://github.com/PrestaShop/eslint-config) : PrestaShop/eslint-config#5
- [x] [ps_wirepayment](https://github.com/PrestaShop/ps_wirepayment) : PrestaShop/ps_wirepayment#63
- [x] [ps_currencyselector](https://github.com/PrestaShop/ps_currencyselector) : PrestaShop/ps_currencyselector#24
- [x] [ps_emailsubscription](https://github.com/PrestaShop/ps_emailsubscription) : PrestaShop/ps_emailsubscription#78
- [x] [ps_mainmenu](https://github.com/PrestaShop/ps_mainmenu) : PrestaShop/ps_mainmenu#50
- [x] [gsitemap](https://github.com/PrestaShop/gsitemap) : PrestaShop/gsitemap#146
- [x] [ps_emailalerts](https://github.com/PrestaShop/ps_emailalerts): https://github.com/PrestaShop/ps_emailalerts/pull/87
- [x] [ps_imageslider](https://github.com/PrestaShop/ps_imageslider) : PrestaShop/ps_imageslider#61

### Other

- [x] [docker-ci](https://github.com/PrestaShop/docker-ci) : PrestaShop/docker-ci#20
- [x] [docker-internal-images](https://github.com/PrestaShop/docker-internal-images) : PrestaShop/docker-internal-images#35
- [x] [live-demo-devices](https://github.com/PrestaShop/live-demo-devices) **Moved to PrestaShopCorp**
- [x] [module-companion](https://github.com/PrestaShop/module-companion) **Archived**
- [x] [docs](https://github.com/PrestaShop/docs) : PrestaShop/docs#867 :heavy_check_mark: 
- [x] [build.prestashop.com](https://github.com/PrestaShop/prestashop.github.io) : PrestaShop/prestashop.github.io#847
- [x] core-weekly-generator : PrestaShop/prestashop.github.io#844
- [x] PrestHubot :robot: : https://github.com/PrestaShop/presthubot/issues/17 
- [x] [decimal](https://github.com/PrestaShop/decimal/) : PrestaShop/decimal#14
- [x] [prestonbot](https://github.com/PrestaShop/prestonbot/) : PrestaShop/prestonbot#115

**Comment by eternoendless** [comment]
FYI you can find them all here: https://travis-ci.com/github/prestashop

**Comment by Progi1984** [comment]
Thanks & Done :)
