### ISSUE TITLE
Upgrade 1.6.1.24 => 1.7.7.1 error in FO - 1.6 modules remain although 1.7 equivalent have been downloaded, this makes FO crash

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/PrestaShop#22668]
# Roadmap

- [x] Finish [ps_banner's PR](https://github.com/PrestaShop/ps_banner/pull/12)
- [x] Finish [ps_searchbar's PR](https://github.com/PrestaShop/ps_searchbar/pull/10)
- [x] Do the blockcart to ps_shoppingcart migration process
- [x] Finish [ps_customersignin's PR](https://github.com/PrestaShop/ps_customersignin/pull/15)
- [x] Finish [ps_linklist's PR](https://github.com/PrestaShop/ps_linklist/pull/65)
- [x] [Fix autoupgrade's enable theme process](https://github.com/PrestaShop/autoupgrade/pull/376)
- [x] Release [ps_banner v2.1.1](https://github.com/PrestaShop/ps_banner/pull/28) module
- [x] Release [ps_customersignin v2.0.4](https://github.com/PrestaShop/ps_customersignin/pull/33) module
- [x] Release [ps_searchbar ~~v2.1.0~~ v2.0.2](https://github.com/PrestaShop/ps_searchbar/pull/32)
- [x] Release [ps_linklist v4.0.0](https://github.com/PrestaShop/ps_linklist/pull/110) module
- [x] Release [autoupgrade v4.12.0](https://github.com/PrestaShop/autoupgrade/pull/381) module
- [x] [Fix 1.7.0.0 upgrade scripts](https://github.com/PrestaShop/PrestaShop/pull/22682)
- [x] Update composer.json [module version numbers](https://github.com/PrestaShop/PrestaShop/pull/23224/checks?check_run_id=1881224182) in `1.7.7.x` branch

# Bug description

#### Describe the bug

When I upgrade to 1.7.7.1 the front office is not working anymore

Old modules are not uninstalled and new one are not installed

#### Steps to Reproduce

1. upgrade from 1.6.1.24 to 1.7.7.1
2. See error

**Screenshots**
<img width="1384" alt="Capture d’écran 2021-01-05 à 10 29 02" src="https://user-images.githubusercontent.com/3034677/103629785-0b8a1780-4f41-11eb-8274-6110d1197830.png">

#### Additional information

* PrestaShop version: 1.7.7.1
* PHP version: 7.1

**Comment by Prestaworks** [comment]
We tried an upgrade like that last week. 1.7.7.0 require php 7.2 so the upgrade failed due to php compatibility issues.
What we did was.
1. upgrade 1.6 to 1.7.6.8 using php 5.6
2. change to php 7.x
3. upgrade 1.7.6.8 to 1.7.7.0

**Comment by atomiix** [comment]
Hi, after more investigation, here is what I found:

When performing an upgrade using the 1-click upgrade module, to try to update to a 1.7.7.1 build, you should select the "Archive" channel. When doing so, the upgrade process complete but then, the Front Office doesn't work anymore. This is because some old native modules are still installed & enabled even though their 1.7.x version are installed. Those 1.6 modules causing problem on the FO are the following:

- blockbanner
- blocksearch
- blockcart
- blockuserinfo
- blockcms

To solve this problem, their 1.7 equivalent module should handle their migration from 1.6 to 1.7. Most of them have a PR in progress already. Even though only those 5 modules are causing visible problem on the FO, every 1.7 modules that have a 1.6 equivalent should do this migration process as well. This is actually in progress too.

When 1.7.7.1 will be released, you will be able to uprade your 1.6 Shop by choosing the channel "Major". When doing so, the option "Use default theme" is selected by default. And when selected, this option cause another problem: in 1.7.0.0 we deleted some hooks without unregister modules from those hooks, leading to an error being thrown when activating the default theme.

So, for 1.7.7.2, in order to have the upgrade from 1.6 to 1.7.7.2 to run without issue, we should:

- Finish [ps_banner's PR](https://github.com/PrestaShop/ps_banner/pull/12) and release it
- Finish [ps_searchbar's PR](https://github.com/PrestaShop/ps_searchbar/pull/10) and release it
- ~~Do the blockcart to ps_shoppingcart migration process~~ Already done
- Finish [ps_customersignin's PR](https://github.com/PrestaShop/ps_customersignin/pull/15) and release it
- Finish [ps_linklist's PR](https://github.com/PrestaShop/ps_linklist/pull/65) and release it
- [Fix 1.7.0.0 upgrade scripts](https://github.com/PrestaShop/PrestaShop/pull/22682)
- [Fix autoupgrade's enable theme process](https://github.com/PrestaShop/autoupgrade/pull/376)

**Comment by fsoabsix** [comment]
Hi, i upgrade my shop in a test server from 1.6.1.24 to 1.7.7.1, i have the same problem...

**Comment by matks** [comment]
Issue updated with a "release roadmap". We have 3 PRs to merge and 5 modules to release. We better start pushing it to be ready for 1.7.7.8 !
