### ISSUE TITLE
[EPIC] - Search FO

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#23018]
All issues related to Search in FO listed in this EPIC

### Bugs
- [ ] #18411 - Wrong search indexing of description with word separated by a `<br>` line break tag
- [x] #34174 

### Bugs
- [x] #22869 - Search by ISBN

### Improvements
- [x] #15118 - [IMPROVEMENT] Make separate error templates for empty product lists and search
