### ISSUE TITLE
[EPIC] - BO Positions

### ISSUE THREAD

**Issue by hibatallahAouadni** [PrestaShop/PrestaShop#23182]
All issues related to **`Positions`**:

### Bugs
- [x] #9823 - [BOOM-4214] CLONE - Problem with Modules > Positions
- [ ] #16622 - weird behavior when displayHeader is used in theme.yml
- [ ] https://github.com/PrestaShop/PrestaShop/issues/27005
- [ ] https://github.com/PrestaShop/PrestaShop/issues/28428
- [ ] https://github.com/PrestaShop/PrestaShop/issues/35612

### Improvements
- [ ] #19435 - [BO][IMPROVIMENT] Add and stay button in Module position form
- [ ] #20973 - Improvement - Be able to select several hooks for a module in one time

### Bugs
- [x] #10405 - displayHeader is not available when transplanting modules/hooks
- [x] #14037 - Transplant module error
- [x] #15594 - Hook position not inserted in ps_hook table by default
- [x] #13371 - Position of module - hooks - can't unhook

**Comment by boo-code** [comment]
Every item left unticked on this list is closed. Resolved against the API today:

| Item | State |
|---|---|
| #16622 | closed, not planned |
| #19435 | closed, not planned |
| #20973 | closed, not planned |
| #27005 | closed, completed |
| #28428 | closed, completed |
| #35612 | closed, completed |

That is all six of the six unticked entries, so nothing on this epic is open any more and it can be closed.
