### ISSUE TITLE
[EPIC] - Add support for experimental features through Feature Flags

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#23235]
### Bugs

- [x] #34421 

### Nice-to-have => might be delivered in further releases

- [ ] https://github.com/PrestaShop/PrestaShop/issues/24002 Improve the confirmation modal behavior on Experimental Feature page
- [ ] Implement Feature Flag _requirement_ data model (see SQL structure `ps_feature_flag_requirement` below)

### Must-have => delivered for 1.7.8.0

- [x] https://github.com/PrestaShop/PrestaShop/issues/23997 Introduce Feature Flag basic data model
- [x] https://github.com/PrestaShop/PrestaShop/issues/23998 Create new Back Office page to allow merchant to modify the feature flag states
- [x] https://github.com/PrestaShop/PrestaShop/issues/23999 Handle Product Page V2 flag setup
- [x] https://github.com/PrestaShop/PrestaShop/issues/24000 Make sure Handle Product Page V2 flag is translatable
- [x] https://github.com/PrestaShop/PrestaShop/issues/24001 Implement Product Page V2 flag behavior

### Bugs

- [x] https://github.com/PrestaShop/PrestaShop/issues/23996 The help modal is broken
- [x] https://github.com/PrestaShop/PrestaShop/issues/24059 Force All Shops context for Experimental Features Back Office page
- [x] https://github.com/PrestaShop/PrestaShop/issues/24068 Wrong button name for Experimental Product page button on New Product page
- [x] https://github.com/PrestaShop/PrestaShop/issues/24267 Fix modal behavior in Experimental Features BO Page
- [x] https://github.com/PrestaShop/PrestaShop/issues/24071 Missing Back to Standard page button on Experimental Add New Product page

#### Is your feature request related to a problem?

Including new features in the Core is risky business and can end up blocking a release if the feature proves to be hard to stabilize. This also leads people to work a long time on giant Pull Requests that are very hard to review and merge.

#### Describe the solution you'd like

Introduce Feature Flags so that complex new features can be disabled or hidden by default until considered stable. Feature Flags can allow developers to deliver small incremental chunks without compromising system stability, which is a common practice in the software world.

Feature flags can be handled similarly to settings, as key -> value pairs in a dedicated table. These settings are to be shown in a new BO page, under "Advanced Settings > Experimental Features", where you will have the feature name, a switch to toggle the flag on and off, and a short description.

Feature flags may be dependent on other feature flags being on or off. Some flags might only be activated if another flag is activated as well. Conversely, some features might be mutually exclusive with other features, meaning that activating one will force the deactivation of the other.

**Comment by eternoendless** [comment]
Here are my suggested table schemas:

### ps_feature_flag

Name | Type
-----|------
id_feature_flag | int(10) unsigned NOT NULL AUTO_INCREMENT
name | varchar(255) NOT NULL
state | tinyint(1) unsigned NOT NULL DEFAULT 0
description_wording | varchar(255) NOT NULL DEFAULT ''
description_wording_domain | varchar(255) NOT NULL DEFAULT ''

PRIMARY KEY = (id_feature_flag)
UNIQUE KEY = name

### ps_feature_flag_requirement

Name | Type
-----|-----
id_feature_flag | int(10) unsigned NOT NULL
id_related_feature_flag | int(10) unsigned NOT NULL
id_required_state | tinyint(1) unsigned NOT NULL DEFAULT

PRIMARY KEY = (id_feature_flag, id_related_feature_flag)

**Comment by matks** [comment]
## First deliverable

We aim for a first delivery of this feature with the following behavior:

- a new BO page "Advanced Settings > Experimental Features", with a switch to toggle the flag on and off, and a short description

![Capture d’écran 2021-02-19 à 14 51 21](https://user-images.githubusercontent.com/3830050/108514811-9e4dfe00-72c4-11eb-9742-ad69e9d9f7f5.png)
 _(wording not frozen)_
 
- switch turned off by default, which prevents merchant to reach product page V2
- when switch is turned on, add the product page V2 below the current product page

**Comment by MatShir** [comment]
@Julievrz Could you check the wording for this issue ?
@TristanLDD Here it is the first delivery and what is expected for the feature flag from the @matks comment. We will need your advice for the next iteration to enhance the experience :)

**Comment by Julievrz** [comment]
Hi @MatShir 

I think we should only write 'Experimental product page' for the label and replace 'Yes/No' with 'Enabled/Disabled'

This way, we can avoid the help text, which is a bit redundant in my opinion. 

However, maybe we could add a piece of information* next to the 'Feature flags' labels to explain what it is to the user and why they should (or should not) enable them/what is at stake?

*like Scott suggested on the translation page here:
![image](https://user-images.githubusercontent.com/70583503/110106307-d1ef5480-7da9-11eb-8370-10aeaeea1f12.png)

What do you think?

**Comment by matks** [comment]
@Julievrz @MatShir I just did this. Does this look good?

![Capture d’écran 2021-03-11 à 16 13 54](https://user-images.githubusercontent.com/3830050/110809060-de315100-8284-11eb-8ef1-c76d8fc86c1b.png)

**Comment by matks** [comment]
@eternoendless How did you plan the `description_wording` and `description_wording_domain` fields to work? Are they a translation key and a translation domain?

If yes, our 1st Feature Flag will be Product Page V2 feature flag. So the data will look like this:

name: "Product Page V2"
state: false
description_wording	"Beta Product Page V2"
description_wording_domain "Admin.Product.Catalog"

And we'll use `$this->trans($descriptionWording, [], $descriptionWordingDomain);` to compute the name?

**Comment by matks** [comment]
@eternoendless If what I understood above is right, your plan is to insert the description_wording into Crowdin so that Core Translation files contain the translations, right?

**Comment by Julievrz** [comment]
> @Julievrz @MatShir I just did this. Does this look good?
> 
> ![Capture d’écran 2021-03-11 à 16 13 54](https://user-images.githubusercontent.com/3830050/110809060-de315100-8284-11eb-8ef1-c76d8fc86c1b.png)

Thanks @matks 
A few suggestions: Replace 'Experimental Feature' with 'Experimental **f**eature' 
Replace 'Yes/No' with 'Enabled/Disabled'

**Comment by Julievrz** [comment]
Discover new PrestaShop features before their official release.

Are you sure you want to enable this experimental feature?

**Comment by eternoendless** [comment]
> How did you plan the `description_wording` and `description_wording_domain` fields to work? Are they a translation key and a translation domain?

That's right. The way I see it, it should work pretty much the same way as the menu as implemented [here](https://github.com/PrestaShop/PrestaShop/pull/18082) (Maybe that will motivate you to merge that PR already 😛 ), except that the translated wordings don't need to be stored in a `_lang` table.

> name: "Product Page V2"
> state: false
> description_wording "Beta Product Page V2"
> description_wording_domain "Admin.Product.Catalog"

The name should be an identifier, best use the slug pattern, like `product_page_v2` if you will.

I see that we are missing a label now. So the schema should be as follows:

### ps_feature_flag

Name | Type
-----|------
id_feature_flag | int(10) unsigned NOT NULL AUTO_INCREMENT
name | varchar(255) NOT NULL
state | tinyint(1) unsigned NOT NULL DEFAULT 0
label_wording | varchar(255) NOT NULL DEFAULT ''
label_domain | varchar(255) NOT NULL DEFAULT ''
description_wording | varchar(255) NOT NULL DEFAULT ''
description_domain | varchar(255) NOT NULL DEFAULT ''

PRIMARY KEY = (id_feature_flag)
UNIQUE KEY = name

--

- `label_wording` = "Experimental product page"
- `label_domain` = I suggest `Admin.Advparameters.Feature`
- `description_wording` = "Enable the experimental Product Page" (to be completed with more information maybe?)
- `description_domain` = I suggest `Admin.Advparameters.Help`

**Comment by Julievrz** [comment]
> @Julievrz @MatShir I just did this. Does this look good?
> 
> ![Capture d’écran 2021-03-11 à 16 13 54](https://user-images.githubusercontent.com/3830050/110809060-de315100-8284-11eb-8ef1-c76d8fc86c1b.png)

Hi @matks @MatShir 

When looking at the wording of this issue and after discussing the potential risks of feature flags with @eternoendless , I think it is important to warn the users about the risks of enabling such features. I first suggested adding a tooltip next to the ‘Experimental features’ label, but I am now wondering if it is enough. Maybe a warning message would be more appropriate:

**Warning message:**

‘Testing a feature before its official release can be exciting. However, you must be aware of the potential risks of such experiments:

- Experimental features are still under development. Enabling them could therefore have unintended consequences and cause data loss.

- In any case, you should never experiment in production.'

Localized in ‘Admin.Advparameters.Notification 

I also think it would be very good to add a **warning notification**, in order to avoid misclicks. Maybe we could use the design @TristanLDD had done for module upgrades a while ago?

![image](https://user-images.githubusercontent.com/70583503/110970435-0a6ad180-835a-11eb-801d-1475ab0603e5.png)


I suggest the following wording:

‘Are you sure you want to enable this experimental feature?’

'You are about to enable a feature that is not stable yet. This should only be done in a test environment or in full knowledge of the potential risks.'

With 2 exit buttons:

‘Enable’
‘Cancel’

**Comment by Julievrz** [comment]
> * `label_wording` = "Experimental product page" ✔️ => **But 'Yes' and 'No' next to the toggle button have to be replaced by 'Enabled' and 'Disabled'.**
> * `label_domain` = I suggest `Admin.Advparameters.Feature` ✔️ 
> * `description_wording` = "Enable the experimental Product Page" (to be completed with more information maybe?) **I think it's redundant to say 'Enable the experimental product page' again in the help text. But we could use the help text to give additional details. What information do you think should be added?**
> * `description_domain` = I suggest `Admin.Advparameters.Help`

**Comment by eternoendless** [comment]
> I suggest the following wording:
> 
> ‘Are you sure you want to enable this experimental feature?’
> 
> ‘You are about to test a feature that is not stable yet. Enabling such a feature should be done with full knowledge of the potential risks and in maintenance mode.’
> 
> With 3 exit buttons:
> 
> ‘Enable’
> ‘Go to maintenance page’
> ‘Cancel’

I disagree with suggesting people to put the shop in maintenance mode. People shouldn't activate experimental features in production, regardless of whether the shop is or not accessible, unless they know exactly what they are doing.

I think we can keep part of this idea though. When the user clicks on "Save" after enabling a feature, they get a confirmation message:

> Are you sure you want to enable these experimental features?
> 
> You are about to enable a feature that is not stable yet. This should only be done in a test environment or in full knowledge of the potential risks.

With 2 exit buttons:

- ‘Enable’
- ‘Cancel’

---

> * `description_wording` = "Enable the experimental Product Page" (to be completed with more information maybe?) **I think it's redundant to say 'Enable the experimental product page' again in the help text. But we could use the help text to give additional details. What information do you think should be added?**

How about we add something about the state of the product page? Or a link to an article?

---

@MatShir @marionf This page should be fully specified after we finish brainstorming, don't you think?

**Comment by Julievrz** [comment]
@eternoendless Thanks for your feedback! Your wording suggestion for the confirmation message looks good to me! I will modify my comment. 😃

**Comment by matks** [comment]
> @MatShir @marionf This page should be fully specified after we finish brainstorming, don't you think?

FYI for now I focus on
- implement the data model (with Doctrine)
- implement the BO page, which displays 1 switch per existing feature flag
- implement the logic which allows to enable/disable flags from the BO page using the switches and a "submit" button

When I'm done with these 3 tasks, I hope that wording and interface will be frozen so I can deliver them 😄 .

**Comment by matks** [comment]
@eternoendless @Julievrz Update: this is what I have now

![Capture d’écran 2021-03-18 à 17 17 13](https://user-images.githubusercontent.com/3830050/111695084-fbd95a00-8832-11eb-8ff1-7a8edde93124.png)
<img width="697" alt="Capture d’écran 2021-03-18 à 21 43 20" src="https://user-images.githubusercontent.com/3830050/111695091-fda31d80-8832-11eb-9f4c-27c99b95e0d1.png">

**Comment by eternoendless** [comment]
@matks it looks good but the wordings are off. I highlighted the ones that you need to replace in bold italics.

> _**‘Are you sure you want to enable this experimental feature?’**_
> 
> _**'You are about to enable a feature that is not stable yet. This should only be done in a test environment or in full knowledge of the potential risks.'**_
> 
> With 2 exit buttons:
> 
> _**‘Enable’**_
> ‘Cancel’

Also, don't forget about the warning message (the one on the "i" icon) and the description for the new product page.

**Comment by Julievrz** [comment]
Here is a recap of the wording for this page: 

**Name of the page:** 'Experimental Features' in Admin.Navigation.Menu

**Name of the section:** 'Experimental features' in Admin.Advparameters.Feature

**Label:** 'Experimental product page' in Admin.Advparameters.Feature
**Toggle button's wording:** 'Enabled'/'Disabled' in Admin.Global
**Help message:** **to be determined** @MatShir what information do you think should be highlighted in the description of the new product page?
**Warning alert:** 'Testing a feature before its official release can be exciting. However, you must be aware of the potential risks of such experiments:

- Experimental features are still under development. Enabling them could therefore have unintended consequences and cause data loss.

- In any case, you should never experiment in production.' in Admin.Advparameters.Notification (If possible, this should be displayed as a yellow/orange warning alert).

**Warning notification after clicking on 'Save':** 
'Are you sure you want to enable this experimental feature?' in Admin.Advparameters.Notification
'You are about to enable a feature that is not stable yet. This should only be done in a test environment or in full knowledge of the potential risks.' in Admin.Advparameters.Notification

With **two exit buttons**:
'Enable' in Admin.Actions
'Cancel' in Admin.Actions

**Comment by toutantic** [comment]
I wonder if a user interface to turn feature flags on and off is needed. As already stated
"experimental features" are for advanced users who know what they are doing. I would say it is better to manage it from the command line, via an API or with environment variables.

**Comment by matks** [comment]
> I wonder if a user interface to turn feature flags on and off is needed. As already stated
> "experimental features" are for advanced users who know what they are doing. I would say it is better to manage it from the command line, via an API or with environment variables.

Traditional feature flags are indeed not meant to be turned on or off from the interface, but here we have mixed the concept of feature flags with the concept of experimental features / beta features.

This allows us to get some feedback on this new page from non-technical users. In 1.7.8 back-office users can test the new Product page ('experimental product page') at any time when switching the Flag to Enabled, and check whether this new to-be-completed page seems satisfying or if they can already detect some issues in its behavior and design. We have explored some technical and functional solutions for known problems about the current Product page, and we'd like the community to test what we have built and give feedback. You can think of it as a beta-system inside the software itself.

**Comment by boo-code** [comment]
The roadmap here is stale in both directions.

Of the two unchecked items, #24002 is closed - `not_planned`, by the stale bot, carrying `Stale Action Closed`. The other, the Feature Flag _requirement_ data model, was never built: 9.2 has `ps_feature_flag` and no `ps_feature_flag_requirement`, and nothing in `src/` refers to one.

The discussion at the end of the thread has been settled by implementation rather than by decision. toutantic asked in 2021 whether a user interface was the right control surface and suggested the command line, an API or environment variables instead. 9.2 has all three layers next to the back office page: `src/Core/FeatureFlag/Layer/EnvLayer.php` resolves a flag from `getenv()`, `src/Core/FeatureFlag/Layer/DotEnvLayer.php` reads it out of a `.env` file through `SYMFONY_DOTENV_VARS`, and both derive the variable name from `FeatureFlagSettings::PREFIX`, `PS_FF_`.

So this epic tracks one unbuilt item and one item that was closed as not planned. Either reduce it to the requirement data model or close it.
