### ISSUE TITLE
[EPIC] - Roadmap 8.0.0

### ISSUE THREAD

**Issue by ldeprestashop** [PrestaShop/PrestaShop#24111]
# The next version, the V8.0.0 is a major, and this is why

In an effort of innovation and technological attractiveness, the update of the technologies (PHP8 and Symfony 4.4) imposes the passage to the numbering of version in 8.x.x. This is not a breakthrough version unlike passage 1.6 -> 1.7, but a version in the continuity of the work in progress on 1.7.

Therefore, there will be no need for a complete overhaul to migrate. The version number changes, but the difficulty of upgrading to 1.7.8 and 8.0.0 will be as easy as upgrading from 1.7.7 to 1.7.8. We also take the opportunity to remove the 1 and respect Semver.

This list below contains the minimum required items (a.k.a must-have) for the V8.0.0 

# EPICS of Must-Have
### Library upgrade 
- [x] https://github.com/PrestaShop/PrestaShop/issues/28764

### Differentiate the OS Project from the Company
- [x] PrestaShop/PrestaShop#24650 
- [ ] PrestaShop/open-source#98

### Experimental product Page rework
- [ ]  PrestaShop/PrestaShop#10632 

### Auto-upgrade
- [ ] PrestaShop/PrestaShop#25647

### Documentation
- [x] PrestaShop/PrestaShop#24651

### Security

----------

### Library upgrade 
- [x]  PrestaShop/PrestaShop#20739 
- [x] PrestaShop/PrestaShop#18547 
- [x] https://github.com/PrestaShop/PrestaShop/issues/27888

### Differentiate the OS Project from the Company
- [x]  Create prestashop.org site
- [x] PrestaShop/PrestaShop#25888
- [x] PrestaShop/PrestaShop#24638 
- [x] PrestaShop/PrestaShop#24639 
- [x] PrestaShop/PrestaShop#24640
- [x] PrestaShop/PrestaShop#24643 
- [x] PrestaShop/PrestaShop#24644 
- [x] PrestaShop/PrestaShop#27075
- [x] PrestaShop/PrestaShop#24645 
- [x] PrestaShop/PrestaShop#25978
- [x] PrestaShop/PrestaShop#26144
- [x] PrestaShop/PrestaShop#26500

### Documentation
- [x] PrestaShop/PrestaShop#27493

### Security
- [x] https://github.com/PrestaShop/PrestaShop/pull/28127

**Comment by ldeprestashop** [comment]
@hibatallahAouadni It's not a Epic, it's an Epic's list ;) 

This issue list all Epics for the V 1.7.9 version.

**Comment by hibatallahAouadni** [comment]
Hello @ldeprestashop 

I see, thanks for the clarification. 
Unfortunately, we don't have a label for the EPIC list, so what should we do?

Thanks!

**Comment by ldeprestashop** [comment]
Do nothing : it's not very important :) 

Maybe we will add Roadmap tag, but don't spend time now for a small detail

**Comment by mvorisek** [comment]
> Split Open-source/Corporate

what does this mean, end of free full features open source code?

**Comment by matks** [comment]
> > Split Open-source/Corporate
> 
> what does this mean, end of free full features open source code?

ping @ttoine

**Comment by ldeprestashop** [comment]
> what does this mean, end of free full features open source code?

No @mvorisek  it is the opposite :) 

We want to remove corporate components, API call... from Open-source project

**Comment by ttoine** [comment]
The target is to have a full independent, full open source version of the software, because many tech people needs it. And also, this should become the main base to work on many PrestaShop distributions.
E.G, even the PrestaShop company is going to build the version available on prestashop.com on top of this full open source project. It will also ease the process for agencies and tech people who build e-commerce solutions for their customers.

**Comment by PierreRambaud** [comment]
Can we remove PrestaShop/PrestaShop#20084 from the Must-Have section? If this issue is a must-have for v8.0.0, we need the mock-ups and specifications as soon as possible (I'm expecting it since April) because the development was already done and QA tested, we had to close the PR because of conflicts.
We have a lot of other stuff with higher priority to do, I'm not sure it's quite relevant to keep this kind of issue in Must Have.

**Comment by ldeprestashop** [comment]
Ok we could remove the must have.

This feature is very interesting but we lost time dur to CI so we must focus on major retire like PHP, Symphony, Autoupgrade.

I remove the must have tag.

**Comment by PierreRambaud** [comment]
@ldeprestashop I don't see what's the relationship between the CI and the need of specs and mock-ups :thinking: 
The work has been done before all CI's problems :thinking:

**Comment by jf-viguier** [comment]
issue PrestaShop/PrestaShop#26134 "Update passwords in md5 to bcrypt" should be removed, already merged in 2016

**Comment by hibatallahAouadni** [comment]
@jf-viguier Thanks for the tip :wink:

**Comment by excitedbox** [comment]
PrestaShop should/needs to target Symfony 5 for several reasons. In reality, work should be starting now for Symfony 6 support.  It has taken over 2 years going from 3->4 and in less than 18 months bug fixes and security updates end. There is no point upgrading to a system that is already obsolete (ask Germany how their broadband internet rollout has gone).

A MAJOR reason to target Symfony 5 is that upgrading from 5->6 currently will not have major breaking changes, giving a MUCH MUCH simpler upgrade path for the future.  By targeting Symfony 4 now you are setting up for another long and tedious upgrade cycle in the VERY near future because Symfony 4 support is almost done. Upgrading to Symfony 5 now would allow automating the upgrade to 6 very soon once it is LTS. Going directly to 6 may avoid future headaches but will create more work now.

Symfony 4->5 had major technology changes and feature additions. Upgrading to Symfony 4.4 is an upgrade to obsolete tech that is almost EOL already. With the slow progress of this update, I do not see the migration happening before support for Symfony 4 ends in 6 months. Then it takes time for modules and plugin devs to be brought up to date until users can really make use of the new Prestashop. You are easily talking another 2+ years until the new version will reach feature parity at which point it would already need to be upgraded again.

I feel that if Presta Shop doesn't get on Symfony 5/6 it will stop being relevant very soon because:
1. Outdated technology and feature set. (php, symfony, js, node, all offer new features, that users/3rd party devs can't make use of)
2. Several major upgrade cycles in short time span for devs and 3rd parties in order to avoid EOL deadlines. (4->5->6 = more work in short succession to catch up).
4. Security risks.

I have been hyping PrestaShop for 10 years and tomorrow I would have started another customer on this platform, but I can not in good conscience recommend it, seeing that it is lagging this far behind, without a clear path to modernization. I would rather take a small hit to my reputation now though and change my proposal which I submitted than having to tell another customer his expensive system is unmaintainable and needs to be migrated to something else and started from scratch.

**Comment by eternoendless** [comment]
Hi @excitedbox and thank you for your feedback.

There are several reasons why we chose Symfony 4.4 and not 5. 

The first one is simple: 5.4 was released in November 2021, _after_ the development of PS 8 started. We have already learned from our mistakes, so we avoid adopting critical software too early (Bootstrap 4 alpha I'm looking at you).

Second, the gap between 3.4 and 5.4 was bigger than to 4.4. More work = later release.

Third, a late release would mean that we wouldn't be able to provide a PrestaShop version capable of running on a supported framework (4.4) and on a supported PHP version (8.0) for longer.

So yeah, we'd obviously want to work on Symfony 6 and PHP 8.1 right now, but we also have a responsibility towards our community to provide usable software in a realistic timeframe.

Most likely, PS 9 will be built with Symfony 5.4 and PS 10 with 6.4.

PS:
> Upgrading to Symfony 4.4 is an upgrade to obsolete tech that is almost EOL already.

That is not true. Symfony 4.4 will EOL on November 2023, in time for PS 9.

**Comment by letwang** [comment]
6666

**Comment by matks** [comment]
PrestaShop 8.0.0 has been published

https://build.prestashop-project.org/news/prestashop-8-0-0-available/

**Comment by letwang** [comment]
> PrestaShop 8.0.0 has been published
> 
> https://build.prestashop-project.org/news/prestashop-8-0-0-available/

Good Job~
