### ISSUE TITLE
Release 1.7.7.5

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#24342]
This issue tracks the status of the PrestaShop 1.7.7.5 release

### Information

Q                                    | A
-----------------------|---------------
**Type**                        | Patch version
**Estimated build**  | 31-05-2021
**Milestone** | [1.7.7.5](https://github.com/PrestaShop/PrestaShop/milestone/73)
**Kanban** | [1.7.7.5](https://github.com/PrestaShop/PrestaShop/projects/15)
**Delivery date**          | 14-06-2021

### Current status

- [x] Development
- [x] Build
- [x] QA validation
- [x] Release
- [x] Available for upgrade
- [x] Docker image

**Comment by atomiix** [comment]
## 🚧 🚥 STATUS UPDATE

`1.7.7.x` branch has been completed for release, and a 1st ZIP archive has been built. It has been delivered to QA team who will be able to launch the standard patch release test campaign.

This test campaign aims to find whether this patch introduces new bugs.

If the campaign reports that no bugs are found, the new patch release will be validated by QA team and we will be able to proceed to release.

More details about the process on https://devdocs.prestashop.com/1.7/release/minor-release-lifecycle/#what-happens-in-six-weeks

**Comment by matks** [comment]
### Status update: 1.7.7.5 is validated by Quality Assurance ✅ 

Automatic tests, manual campaign and exploratory sessions did not detected any 1.7.7.5 regressions.

**Comment by fraizor** [comment]
When will be the release ?

**Comment by matks** [comment]
> When will be the release ?

Expected today :)

**Comment by matks** [comment]
## 1.7.7.5 is released by @atomiix 

- [x] GitHub Release ✅  https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.7.5
- [x] prestashop.com Release ✅  https://www.prestashop.com/en/versions
- [x] Release note ✅  https://build.prestashop.com/news/prestashop-1-7-7-5-maintenance-release/
- [x] docker images

**Comment by weddingtextile** [comment]
there is no 1.7.7.5 label in https://github.com/PrestaShop/PrestaShop/issues

**Comment by atomiix** [comment]
## 1.7.7.5 is available through the autoupgrade module

**Comment by atomiix** [comment]
## 1.7.7.5 docker images available

**Comment by matks** [comment]
> there is no 1.7.7.5 label in https://github.com/PrestaShop/PrestaShop/issues

Fixed https://github.com/PrestaShop/PrestaShop/labels/1.7.7.5 👍  thank you for notice

**Comment by matks** [comment]
Thank you @atomiix and @marionf
