### ISSUE TITLE
[EPIC] - Update symfony to version 4.4

### ISSUE THREAD

**Issue by atomiix** [PrestaShop/PrestaShop#24608]
- [x] #24606 - Update [productcomments](https://github.com/PrestaShop/productcomments) to use [circuit-breaker](https://github.com/PrestaShop/circuit-breaker/) v4
- [x] #24607 - Update [blockreassurance](https://github.com/PrestaShop/blockreassurance) to use [circuit-breaker](https://github.com/PrestaShop/circuit-breaker/) v4

------

## Fixed

- [x] #20739 - Upgrade the latest Symfony LTS version
- [x] #24604 - Upgrade Twig to v3
- [x] #24605 - Get rid of Symfony 4.4 deprecations

**Comment by PrestaEdit** [comment]
Symfony is now in 4.4 and the two firsts points are auto-solved by the remove of circuit-breaker.

**Comment by bastien70** [comment]
Why not upgrade to 6.1 ?

**Comment by PrestaEdit** [comment]
> Why not upgrade to 6.1 ?

Because of that :  Requires: PHP 8.1.0 or higher

**Comment by atomiix** [comment]
Closing as every issue has been addressed
