### ISSUE TITLE
Release 1.7.7.6

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#25202]
This issue tracks the status of the PrestaShop 1.7.7.6 release

### Information

Q                                    | A
-----------------------|---------------
**Type**                        | Patch version
**Estimated build**  | 30 July 2021
**Milestone** | [1.7.7.6](https://github.com/PrestaShop/PrestaShop/milestone/74)
**Kanban** | [1.7.7.6](https://github.com/PrestaShop/PrestaShop/projects/16)
**Estimated delivery date**          | 6 August 2021

### Current status

- [x] Development
- [x] ~Release is not expected to happen - canceled~ - see below 🔴 https://github.com/PrestaShop/PrestaShop/issues/25202#issuecomment-874553698
- [x] Release re-expected to happen - confirmed - see below 🟢 https://github.com/PrestaShop/PrestaShop/issues/25202#issuecomment-886652569
- [x] Build
- [x] QA validation
- [x] Release
- [x] Available for upgrade
- [x] Docker image

**Comment by marionf** [comment]
QA team will not be able to test both 1.7.7.6 and 1.7.8.0 RC1 build 2 in an eligible time window.
Too much work must happen in a restricted period.

That is why **we decided to cancel 1.7.7.6 release for now.**
1.7.7.x branch will be soon merged into 1.7.8.x

**Comment by matks** [comment]
Following confirmation of bug https://github.com/PrestaShop/PrestaShop/issues/24235 we reopen this issue as a 1.7.7.6 release is now re-scheduled.

@matthieu-rolland will be release tech manager
@marionf  will be release product manager

**Comment by matks** [comment]
## 🚧 🚥 STATUS UPDATE

`1.7.7.x` branch has been completed for release, and a 1st ZIP 1.7.7.6 archive has been built. It has been delivered to QA team who will be able to launch the standard patch release test campaign.

This test campaign aims to find whether this patch introduces new bugs.

If the campaign reports that no bugs are found, the new patch release will be validated by QA team and we will be able to proceed to release.

More details about the process on https://devdocs.prestashop.com/1.7/release/minor-release-lifecycle/#what-happens-in-six-weeks

**Comment by matks** [comment]
## Status update 🚀 

1.7.7.6 has been released by @matthieu-rolland 
- on github ✅ 
- on prestashop.com ✅ 
- the release note is published https://build.prestashop.com/news/prestashop-1-7-7-6-maintenance-release/

Now we need
- docker images
- be able to upgrade

**Comment by matks** [comment]
## Status update

It is possible to upgrade to 1.7.7.6 .

Docker images for 1.7.7.6 are available.

Bravo @matthieu-rolland
