### ISSUE TITLE
All native modules must be compatible with PHP 8.0 (CI must add check for PHP 8.0)

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#25921]
check the module list:

**guidelines** -> https://github.com/PrestaShop/PrestaShop/issues/18547#issuecomment-953681691

**Administration** 

- [x] autoupgrade : PrestaShop/autoupgrade/pull/459
- [x] ps_dataprivacy : PrestaShop/ps_dataprivacy#38
- [x] psgdpr : PrestaShop/psgdpr#158
- [x] ps_faviconnotificationbo : PrestaShop/ps_faviconnotificationbo#35
- [x] ps_emailalerts : PrestaShop/ps_emailalerts#104
- [x] statsbestmanufacturers : PrestaShop/statsbestmanufacturers#14
- [x] statsbestcategories : PrestaShop/statsbestcategories#17
- [x] statsbestcustomers : PrestaShop/statsbestcustomers#27
- [x] statsbestproducts : PrestaShop/statsbestproducts#16
- [x] statsbestsuppliers : PrestaShop/statsbestsuppliers#14
- [x] statsbestvouchers : PrestaShop/statsbestvouchers#16
- [x] statscatalog : PrestaShop/statscatalog#25
- [x] statscheckup : PrestaShop/statscheckup#23
- [x] statsdata : PrestaShop/statsdata/pull/24
- [x] statsforecast : PrestaShop/statsforecast/pull/26
- [x] statsnewsletter : PrestaShop/statsnewsletter/pull/15
- [x] statspersonalinfos : PrestaShop/statspersonalinfos/pull/19
- [x] statsproduct : PrestaShop/statsproduct/pull/31
- [x] statsregistrations : PrestaShop/statsregistrations/pull/16
- [x] statssales : PrestaShop/statssales/pull/29
- [x] statssearch : PrestaShop/statssearch/pull/19
- [x] statsstock : PrestaShop/statsstock/pull/22
- [x] dashactivity : PrestaShop/dashactivity/pull/31
- [x] dashgoals : PrestaShop/dashgoals#28
- [x] dashproducts : PrestaShop/dashproducts/pull/41
- [x] dashtrends : PrestaShop/dashtrends/pull/53
- [x] graphnvd3 : PrestaShop/graphnvd3/pull/20
- [x] gridhtml : PrestaShop/gridhtml/pull/29
- [x] pagesnotfound : PrestaShop/pagesnotfound/pull/22
- [x] ps_bestsellers : PrestaShop/ps_bestsellers/pull/21
- [x] ps_googleanalytics : PrestaShop/ps_googleanalytics/pull/109

**Design & Navigation**
- [x] blockreassurance : PrestaShop/blockreassurance/pull/355
- [x] blockwishlist : PrestaShop/blockwishlist#159
- [x] contactform : PrestaShop/contactform#59
- [x] productcomments : PrestaShop/productcomments/pull/134
- [x] ps_banner : PrestaShop/ps_banner#42
- [x] ps_categorytree : PrestaShop/ps_categorytree/pull/57
- [x] ps_contactinfo : PrestaShop/ps_contactinfo/pull/47
- [x] ps_currencyselector : PrestaShop/ps_currencyselector/pull/27
- [x] ps_customeraccountlinks : PrestaShop/ps_customeraccountlinks/pull/39
- [x] ps_customersignin : PrestaShop/ps_customersignin/pull/44
- [x] ps_customtext : PrestaShop/ps_customtext/pull/69
- [x] ps_facetedsearch : PrestaShop/ps_facetedsearch/pull/614
- [x] ps_featuredproducts : PrestaShop/ps_featuredproducts/pull/47
- [x] ps_imageslider : PrestaShop/ps_imageslider/pull/69
- [x] ps_languageselector : PrestaShop/ps_languageselector/pull/28
- [x] ps_linklist : PrestaShop/ps_linklist/pull/145
- [x] ps_mainmenu : PrestaShop/ps_mainmenu/pull/60
- [x] ps_searchbar : PrestaShop/ps_searchbar/pull/46
- [x] ps_shoppingcart : PrestaShop/ps_shoppingcart/pull/84
- [x] ps_themecusto : PrestaShop/ps_themecusto/pull/51
- [x] ps_brandlist : PrestaShop/ps_brandlist/pull/13
- [x] ps_newproducts : PrestaShop/ps_newproducts/pull/13
- [x] ps_specials : PrestaShop/ps_specials/pull/7
- [x] ps_supplierlist : PrestaShop/ps_supplierlist/pull/12
- [x] ps_viewedproduct : PrestaShop/ps_viewedproduct/pull/24

**Facebook & Social networks**
- [x] ps_sharebuttons : PrestaShop/ps_sharebuttons/pull/53
- [x] ps_socialfollow : PrestaShop/ps_socialfollow/pull/33

**Payment**
- [x] ps_checkpayment : PrestaShop/ps_checkpayment#56
- [x] ps_wirepayment : PrestaShop/ps_wirepayment/pull/69
- [x] ps_cashondelivery : PrestaShop/ps_cashondelivery#41

**Promotion & Marketing**
- [x] ps_crossselling : PrestaShop/ps_crossselling/pull/33
- [x] ps_categoryproducts : PrestaShop/ps_categoryproducts/pull/31
- [x] ps_emailsubscription : PrestaShop/ps_emailsubscription/pull/88

**Traffic & Marketplace**
- [x] gsitemap : PrestaShop/gsitemap/pull/151

**Comment by Progi1984** [comment]
@MatShir Do we add support for PHP 8.1 at the same time ? (FYI @atomiix).

**Comment by Progi1984** [comment]
And it's finished. :muscle:
