### ISSUE TITLE
[BO] Buttons are not well displayed (part 3)

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#26040]
#### Describe the bug

After fixing this issue #25740 and this https://github.com/PrestaShop/PrestaShop/issues/25980
Some buttons are still NOK

- [x] First issue --> Fixed on develop PR #25056
![image](https://user-images.githubusercontent.com/16067358/135472125-b5221767-37c2-44b4-b801-cc495e2cefdb.png)
~1. Resize the window to 1664px * 945px~
~2. Go to BO > Orders > Add new Order~
~3. Choose a customer~
~4. Choose a product~
~5. Add to cart button is NOK~

---
- [x] Second issue -> Fixed by #26227
![image](https://user-images.githubusercontent.com/16067358/135472603-85c870db-9f3e-4858-9390-2b99e600b57d.png)

1. Go to BO > Orders page > View any order
2. In the Status block, the button `Update status` is NOK

---
- [x] Third issue -> Fixed by #26227
![image](https://user-images.githubusercontent.com/16067358/135473348-e05fb736-5c90-4133-a13b-003530844f1e.png)

1. Resize the window to 1664px * 945px
1. Go to BO > Catalog > Products page
2. Click on "Filter by categories"
3. Select a category 
![image](https://user-images.githubusercontent.com/16067358/135473107-3426f5b5-cef3-4c08-b785-75a26f8e2cb8.png)
4. Click on Reorder
4. Drag and drop two products
5. The button "Save & refresh" is NOK 

---
- [x] Fourth issue -> Fixed by #26227
![image](https://user-images.githubusercontent.com/16067358/135473577-5eb5cc60-935b-4a6e-9ec1-ddbed5aedfdd.png)
1. Go to BO > Catalog > Discounts > Catalog price rule page
2. Add new catalog price rule 
3. Add a condition 
4. See the button `Add condition` is NOK

---
- [x] Fifth issue -> Fixed by #26227
![image](https://user-images.githubusercontent.com/23308427/137091311-399d4cdb-e721-4e91-9971-313975ff38f7.png)

1. Resize the window to 1103px * 918 px
2. Go to BO > Design > Theme & Logo page
3. ~the button `Visit the theme catalog` is NOK~ => it will be deleted (linked to Addons)
4. The button My current theme is NOK

PS: PrestaShop 1.7.8.0 rc => ok

#### Additional information

* PrestaShop version: 178x, develop
* PHP version: 72

**Comment by hibatallahAouadni** [comment]
Ping @Hlavtox

**Comment by Hlavtox** [comment]
@khouloudbelguith @hibatallahAouadni @NeOMakinG 

We need to treat all of these issues separately, because the buttons just want to fit into the space they have. Poor babies :D

- Update status is squished because the select has width 100% and pushes everything to be as small as possible. The same the Add condition button in Catalog prices.
- Save & refresh squishes because it wants to fit into a table where is no space.
- The theme buttons wrap because they have nowhere to go, because the card is just too small. Look how it would look without the wrapping enabled...

![Výstřižek](https://user-images.githubusercontent.com/6097524/135869840-2c58d651-ad7a-4211-bf85-04e834efcec4.JPG)

**Comment by Hlavtox** [comment]
And also, because the button has nowhere to move 🔪
![Výstřižek](https://user-images.githubusercontent.com/6097524/135871433-29f4b740-a620-435c-9e2b-bc96d5098e41.JPG)

**Comment by Progi1984** [comment]
Fixed by @hibatallahAouadni in #26227

**Comment by Progi1984** [comment]
@hibatallahAouadni Do you have all fixed ?

**Comment by hibatallahAouadni** [comment]
@Progi1984 yes, why? did you find another button that @khouloudbelguith didn't mention in this issue?

**Comment by hibatallahAouadni** [comment]
@Progi1984 if you're talking about the first issue? 
> ![image](https://user-images.githubusercontent.com/16067358/135472125-b5221767-37c2-44b4-b801-cc495e2cefdb.png)
> 1. Resize the window to 1664px * 945px
> 2. Go to BO > Orders > Add new Order
> 3. Choose a customer
> 4. Choose a product
> 5. Add to cart button is NOK

This issue is already fixed on develop with @Hlavtox PR #25056

**Comment by Progi1984** [comment]
Thanks @hibatallahAouadni
