### ISSUE TITLE
Release 8.0.0

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#26427]
This issue tracks the status of the PrestaShop 8.0.0 release

### Information

Q                                     | A
-----------------------|--------
**Type**                        | Major version
**Milestone**                | [8.0.0](https://github.com/PrestaShop/PrestaShop/milestone/64)
**Epic**                         | [Roadmap 8.0.0](https://github.com/PrestaShop/PrestaShop/issues/24111)
**Kanban**                   | [8.0.0](https://github.com/PrestaShop/PrestaShop/projects/12)
**Feature Freeze**      | 2022-06-09
**Beta**                        | 2022-08-08
[**Release Candidate**](https://build.prestashop-project.org/news/prestashop-8-0-rc1-release/) | 2022-10-13
[**Final release**](https://build.prestashop-project.org/news/prestashop-8-0-0-available/) | 2022-10-26
**Release manager tech**           |  @jolelievre 
**Release manager product**     |  

### Current status

- [x] Specification
- [x] Feature development
- [x] Feature freeze https://github.com/PrestaShop/PrestaShop/issues/28708
- [x] Alpha test
- [x] [Beta release](https://build.prestashop.com/news/prestashop-8-0-beta-release/)
- [x] [Release Candidate 1](https://build.prestashop-project.org/news/prestashop-8-0-rc1-release/) 🎉
- [x] Final release
- [x] Available for upgrade -> not yet, to be done in https://github.com/PrestaShop/PrestaShop/issues/29215

**Comment by matks** [comment]
Feature freeze happened on 2022-06-09 https://github.com/PrestaShop/PrestaShop/issues/28708

**Comment by matks** [comment]
## Status update

Alpha test started yesterday by QA team. Following the results, we'll know how far we are from being able to release a alpha version.

**Comment by khouloudbelguith** [comment]
## Status update : QA feedback

Hello,

The test of the alpha 8.0.0 is finished
Final report of QA on the 8.0.0 alpha:
The manual functional test campaign is done.
The exploratory test session is now complete.
Summary of regressions detected during the test:
**Major regressions**

- https://github.com/PrestaShop/PrestaShop/issues/28933
- https://github.com/PrestaShop/PrestaShop/issues/28958
- https://github.com/PrestaShop/PrestaShop/issues/28961
- https://github.com/PrestaShop/PrestaShop/issues/28968
- https://github.com/PrestaShop/PrestaShop/issues/28981
- https://github.com/PrestaShop/PrestaShop/issues/29012
- https://github.com/PrestaShop/PrestaShop/issues/29017
- https://github.com/PrestaShop/PrestaShop/issues/29006
- https://github.com/PrestaShop/PrestaShop/issues/28958

**Minor regressions**

- https://github.com/PrestaShop/PrestaShop/issues/28934
- https://github.com/PrestaShop/PrestaShop/issues/28875
- https://github.com/PrestaShop/PrestaShop/issues/28885
- https://github.com/PrestaShop/PrestaShop/issues/28894
- https://github.com/PrestaShop/PrestaShop/issues/28924
- https://github.com/PrestaShop/PrestaShop/issues/28919
- https://github.com/PrestaShop/PrestaShop/issues/28896
- https://github.com/PrestaShop/PrestaShop/issues/28873
- https://github.com/PrestaShop/PrestaShop/issues/28998
- https://github.com/PrestaShop/PrestaShop/issues/28965
- https://github.com/PrestaShop/PrestaShop/issues/29014
- https://github.com/PrestaShop/PrestaShop/issues/28868
- https://github.com/PrestaShop/PrestaShop/issues/29005
- https://github.com/PrestaShop/PrestaShop/issues/29001
- https://github.com/PrestaShop/PrestaShop/issues/28996

**Trivial regressions**

- https://github.com/PrestaShop/PrestaShop/issues/28874
- https://github.com/PrestaShop/PrestaShop/issues/28877
- https://github.com/PrestaShop/PrestaShop/issues/28892
- https://github.com/PrestaShop/PrestaShop/issues/28895
- https://github.com/PrestaShop/PrestaShop/issues/28974
- https://github.com/PrestaShop/PrestaShop/issues/28986
- https://github.com/PrestaShop/PrestaShop/issues/28863
- https://github.com/PrestaShop/PrestaShop/issues/29002
- https://github.com/PrestaShop/PrestaShop/issues/29018
- https://github.com/PrestaShop/PrestaShop/issues/28990

Some other bugs (no regressions) were found.
Thank you :slightly_smiling_face:

**Comment by PrestaEdit** [comment]
While I'm trying to filter the issues backlog in order to found them easier and see on the listing if there is a Pull Request associated, I'm not able to found the good combinations of labels, milestones, version...
I found more issues than this listing.

How can we found them more easier to see if there is a pull request associated without opening them one by one ?

**Comment by letwang** [comment]
66666

**Comment by jolelievre** [comment]
## Status update 🚀

We just released the 8.0.0 Beta 1 version of PrestaShop https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0-beta.1

**Comment by matks** [comment]
Bravo @jolelievre Release Manager for PrestaShop 8 🎉 and the whole team behind

**Comment by eternoendless** [comment]
The beta is now over: [39 bugs have been reported](https://github.com/PrestaShop/PrestaShop/search?q=created%3A2022-08-09..2022-09-04+is%3Aissue+label%3A8.0.x+-label%3AInvalid+-label%3ADuplicate&type=issues) during this period, of which 9 have been fixed at the time of writing. The remaining items to fix before the first release candidate can be tracked on the [project's kanban](https://github.com/PrestaShop/PrestaShop/projects/12). Please note that not all the issues reported during beta are necessarily blockers for RC and may be fixed after the initial release.

Thank you to everyone who contributed for this beta version!

**Comment by matks** [comment]
## Status update

PrestaShop 8.0.0 RC1 has been built, and PrestaShop Autoupgrade module 4.15.0 also [has a release candidate](https://github.com/PrestaShop/autoupgrade/pull/513).

Both releases candidates have been delivered to QA team for testing. Testing of the upgrade process will first focus on upgrades from 1.7.8 to 8.0.0 RC1.

**Comment by florine2623** [comment]
Hello :slightly_smiling_face:,

Final report of QA on the 8.0.0 RC1 :
The manual functional test campaign is done and OK.
The exploratory test session is now complete.

Summary of the issues detected during the test:

**Trivial:**
 - #29866 
- #29884
- #29925
- #29916

**Minor:**
- #29838
- #29843
- #29862
- #29865
- #29913
- #29914
- #29933
- #29824
- #29918
- #29858
- #29929
- #29863

**Major:**
- #29867
- #29895

In conclusion, it’s a NO GO for the release.
Thank you

**Comment by MatShir** [comment]
Thank @florine2623 and the @PrestaShop/qa-functional for your work 💯 

Many of the issues listed are not blockers and are not regressions. The only blocking issue for the release is https://github.com/PrestaShop/PrestaShop/issues/29867. Once fixed, we can finally release the RC 🚀 
The remaining regressions will be fixed in the 8.0.1 patch.

Stay tuned !

**Comment by MatShir** [comment]
🥳 PrestaShop 8.0 RC has been released and is ready to be tested !
Blog: https://build.prestashop-project.org/news/prestashop-8-0-rc1-release/
Tag: https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0-rc.1

Next target the final release, if there is no critical bug release shared by the community, we plan to release the 24th October.

Thanks again to all the people involved in this release ❤️

**Comment by matks** [comment]
[PrestaShop 8.0.0 is released](https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.0) on GitHub

Docker images incoming, as well as release notes

**Comment by ghost** [comment]
hallo evry one, how can we implement next to phone-fax-e-mail shop info also VAT Number (btw-nummer) and KvK nummer? maby whatsapp ? 

And by import products bug i mist that the id number for referentie leverancier dosn't show after import. reference supplier # 

importing purchase price product now where? i have 2 do this 1 by 1 for 99999 products. 

no import SKU

importing catogory url image's also now where.

Not working importing incl Vat and price exl VAT. 

Missing sup catagorie import.

product url image's works good. :) nice writing.

**Comment by ghost** [comment]
<div id="contact-link">
	<a href="{$urls.pages.contact}">{l s='Contact us' d='Modules.Contactinfo.Shop'}</a>
    {if $contact_infos.phone}
      {* First tag [1][/1] is for a HTML tag. *}
      {l
        s='Call us: [1]%phone%[/1]'
        sprintf=[
          '[1]' => '<span>',
          '[/1]' => '</span>',
          '%phone%' => $contact_infos.phone
        ]
        d='Modules.Contactinfo.Shop'
      }
    {/if}
</div>

**Comment by ghost** [comment]
We will try to make it or self. now one is here 2 help.

**Comment by MatShir** [comment]
Hi @Gruttershop,
If you have found a bug, I suggest you to report it [here](https://github.com/PrestaShop/PrestaShop/issues/new/choose). We will try to reproduce it in our end.
Otherwise, if you need help check out this [page](https://devdocs.prestashop-project.org/1.7/faq/i-need-help/).

**Comment by doeselschnecke** [comment]
Hey just wondering why 8.0.0 is still not available for update? PHP 7.4 won't get security patches in two weeks

**Comment by matks** [comment]
> Hey just wondering why 8.0.0 is still not available for update? PHP 7.4 won't get security patches in two weeks

Hello @doeselschnecke this is because the upgrade from 1.7.x versions to 8.0.0 is a complex thing to achieve, and we want to make it as stable as possible 😊 . It's working for most shops, but we are working on some usecases less common but still important.

If you want to try upgrading your shop to 8.0, you can use the candidate for autoupgrade 4.15.0 : you need to build the module from the branch of PR https://github.com/PrestaShop/autoupgrade/pull/522

If you test the upgrade process on a copy of your shop, you can check whether the upgrade is successfull on your copy shop - it's a test to do before doing this on the real shop. If the test is successfull, you should be fine 👍 (although it's always good to keep a backup just in case).

**Comment by doeselschnecke** [comment]
> > Hey just wondering why 8.0.0 is still not available for update? PHP 7.4 won't get security patches in two weeks
> 
> Hello @doeselschnecke this is because the upgrade from 1.7.x versions to 8.0.0 is a complex thing to achieve, and we want to make it as stable as possible 😊 . It's working for most shops, but we are working on some usecases less common but still important.

Thanks for the fast reply. I'll wait for the automated update for the updater module then. It's still 10 days PHP support and at the moment there's no new PHP vulnerability.

I was just wondering why it's possible to download 8.0.0 but why it's not available for upgrade. Thanks a lot, you've answered my question :)

**Comment by matks** [comment]
In order to avoid confusion I close this GitHub issue and replace it with https://github.com/PrestaShop/PrestaShop/issues/29215 instead
