### ISSUE TITLE
Build release packages for all the project's modules automatically and append them to the Github release

### ISSUE THREAD

**Issue by eternoendless** [PrestaShop/PrestaShop#26767]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Currently, most modules are released with code sources, but not a ready-to-use zip package that you can upload to your shop ([see example](https://github.com/PrestaShop/gsitemap/releases)). Usually, this package requires executing `composer install` and building assets, then putting the content of the module in a directory, then zipping the directory.

### Describe the solution you'd like

A release package should be built by CI and the resulting artifact should be added to the Github release automatically.

## Actions
Add the workflow [Build Release](https://github.com/PrestaShop/ps_languageselector/blob/dev/.github/workflows/build-release.yml) to each module : 
- [x] [autoupgrade](https://github.com/PrestaShop/autoupgrade/blob/dev/.github/workflows/build-release.yml) : PrestaShop/autoupgrade#444
- [x] [blockreassurance](https://github.com/PrestaShop/blockreassurance/blob/dev/.github/workflows/build-release.yml) : PrestaShop/blockreassurance#334
- [x] [blockwishlist](https://github.com/PrestaShop/blockwishlist/blob/dev/.github/workflows/build-release.yml) : PrestaShop/blockwishlist#144
- [x] [contactform](https://github.com/PrestaShop/contactform/blob/dev/.github/workflows/build-release.yml) : PrestaShop/contactform#58
- [x] [dashactivity](https://github.com/PrestaShop/dashactivity/blob/dev/.github/workflows/build-release.yml) : PrestaShop/dashactivity#29
- [x] [dashgoals](https://github.com/PrestaShop/dashgoals/blob/dev/.github/workflows/build-release.yml) : PrestaShop/dashgoals#26
- [x] [dashproducts](https://github.com/PrestaShop/dashproducts/blob/dev/.github/workflows/build-release.yml) : PrestaShop/dashproducts#38
- [x] [dashtrends](https://github.com/PrestaShop/dashtrends/blob/dev/.github/workflows/build-release.yml) : PrestaShop/dashtrends#50
- [x] [gamification](https://github.com/PrestaShop/gamification/blob/dev/.github/workflows/build-release.yml)
- [x] [graphnvd3](https://github.com/PrestaShop/graphnvd3/blob/dev/.github/workflows/build-release.yml) : PrestaShop/graphnvd3#19
- [x] [gridhtml](https://github.com/PrestaShop/gridhtml/blob/dev/.github/workflows/build-release.yml) : PrestaShop/gridhtml#28
- [x] [gsitemap](https://github.com/PrestaShop/gsitemap/blob/dev/.github/workflows/build-release.yml)
- [x] [pagesnotfound](https://github.com/PrestaShop/pagesnotfound/blob/dev/.github/workflows/build-release.yml) : PrestaShop/pagesnotfound#20
- [x] [productcomments](https://github.com/PrestaShop/productcomments/blob/dev/.github/workflows/build-release.yml) : PrestaShop/productcomments#128
- [x] [ps_banner](https://github.com/PrestaShop/ps_banner/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_banner#40
- [x] [ps_bestsellers](https://github.com/PrestaShop/ps_bestsellers/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_bestsellers#17
- [x] [ps_brandlist](https://github.com/PrestaShop/ps_brandlist/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_brandlist#10
- [x] [ps_buybuttonlite](https://github.com/PrestaShop/ps_buybuttonlite/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_buybuttonlite#55
- [x] [ps_cashondelivery](https://github.com/PrestaShop/ps_cashondelivery/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_cashondelivery#38 / PrestaShop/ps_cashondelivery#39
- [x] [ps_categoryproducts](https://github.com/PrestaShop/ps_categoryproducts/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_categoryproducts#28
- [x] [ps_categorytree](https://github.com/PrestaShop/ps_categorytree/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_categorytree#56
- [x] [ps_checkpayment](https://github.com/PrestaShop/ps_checkpayment/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_checkpayment#54
- [x] [ps_contactinfo](https://github.com/PrestaShop/ps_contactinfo/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_contactinfo#46
- [x] [ps_crossselling](https://github.com/PrestaShop/ps_crossselling/blob/dev/.github/workflows/build-release.yml) :  PrestaShop/ps_crossselling#30 / PrestaShop/ps_crossselling#31
- [x] [ps_currencyselector](https://github.com/PrestaShop/ps_currencyselector/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_currencyselector#25
- [x] [ps_customeraccountlinks](https://github.com/PrestaShop/ps_customeraccountlinks/blob/dev/.github/workflows/build-release.yml) :  PrestaShop/ps_customeraccountlinks#37
- [x] [ps_customersignin](https://github.com/PrestaShop/ps_customersignin/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_customersignin#42
- [x] [ps_customtext](https://github.com/PrestaShop/ps_customtext/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_customtext#67
- [x] [ps_dataprivacy](https://github.com/PrestaShop/ps_dataprivacy/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_dataprivacy#36
- [x] [ps_emailalerts](https://github.com/PrestaShop/ps_emailalerts/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_emailalerts#100
- [x] [ps_emailsmanager](https://github.com/PrestaShop/ps_emailsmanager/blob/dev/.github/workflows/build-release.yml) : PrestaShopCorp/ps_emailsmanager#18
- [x] [ps_emailsubscription](https://github.com/PrestaShop/ps_emailsubscription/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_emailsubscription#86
- [x] [ps_facetedsearch](https://github.com/PrestaShop/ps_facetedsearch/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_facetedsearch#584
- [x] [ps_faviconnotificationbo](https://github.com/PrestaShop/ps_faviconnotificationbo/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_faviconnotificationbo#34
- [x] [ps_featuredproducts](https://github.com/PrestaShop/ps_featuredproducts/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_featuredproducts#46
- [x] [psgdpr](https://github.com/PrestaShop/psgdpr/blob/dev/.github/workflows/build-release.yml) : PrestaShop/psgdpr#156
- [x] [ps_googleanalytics](https://github.com/PrestaShop/ps_googleanalytics/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_googleanalytics#108
- [x] [ps_imageslider](https://github.com/PrestaShop/ps_imageslider/blob/dev/.github/workflows/build-release.yml)
- [x] [ps_languageselector](https://github.com/PrestaShop/ps_languageselector/blob/dev/.github/workflows/build-release.yml)
- [x] [ps_linklist](https://github.com/PrestaShop/ps_linklist/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_linklist#141
- [x] [ps_mainmenu](https://github.com/PrestaShop/ps_mainmenu/blob/dev/.github/workflows/build-release.yml)
- [x] [ps_newproducts](https://github.com/PrestaShop/ps_newproducts/blob/dev/.github/workflows/build-release.yml) :  PrestaShop/ps_newproducts#11
- [x] [ps_searchbar](https://github.com/PrestaShop/ps_searchbar/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_searchbar#44
- [x] [ps_sharebuttons](https://github.com/PrestaShop/ps_sharebuttons/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_sharebuttons#51
- [x] [ps_shoppingcart](https://github.com/PrestaShop/ps_shoppingcart/blob/dev/.github/workflows/build-release.yml)
- [x] [ps_socialfollow](https://github.com/PrestaShop/ps_socialfollow/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_socialfollow#29
- [x] [ps_specials](https://github.com/PrestaShop/ps_specials/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_specials#5
- [x] [ps_supplierlist](https://github.com/PrestaShop/ps_supplierlist/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_supplierlist#11
- [x] [ps_themecusto](https://github.com/PrestaShop/ps_themecusto/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_themecusto#48
- [x] [ps_viewedproduct](https://github.com/PrestaShop/ps_viewedproduct/blob/dev/.github/workflows/build-release.yml) : PrestaShop/ps_viewedproduct#23
- [x] [ps_wirepayment](https://github.com/PrestaShop/ps_wirepayment/blob/dev/.github/workflows/build-release.yml)
- [x] [statsbestcategories](https://github.com/PrestaShop/statsbestcategories/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestcategories#15
- [x] [statsbestcustomers](https://github.com/PrestaShop/statsbestcustomers/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestcustomers#24 / PrestaShop/statsbestcustomers#25
- [x] [statsbestmanufacturers](https://github.com/PrestaShop/statsbestmanufacturers/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestmanufacturers#12
- [x] [statsbestproducts](https://github.com/PrestaShop/statsbestproducts/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestproducts#14
- [x] [statsbestsuppliers](https://github.com/PrestaShop/statsbestsuppliers/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestsuppliers#12
- [x] [statsbestvouchers](https://github.com/PrestaShop/statsbestvouchers/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsbestvouchers#14
- [x] [statscarrier](https://github.com/PrestaShop/statscarrier/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statscarrier#12
- [x] [statscatalog](https://github.com/PrestaShop/statscatalog/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statscatalog#23
- [x] [statscheckup](https://github.com/PrestaShop/statscheckup/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statscheckup#21
- [x] [statsdata](https://github.com/PrestaShop/statsdata/blob/dev/.github/workflows/build-release.yml) :  PrestaShop/statsdata#21
- [x] [statsforecast](https://github.com/PrestaShop/statsforecast/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsforecast#23
- [x] [statsnewsletter](https://github.com/PrestaShop/statsnewsletter/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsnewsletter#13
- [x] [statspersonalinfos](https://github.com/PrestaShop/statspersonalinfos/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statspersonalinfos#17
- [x] [statsproduct](https://github.com/PrestaShop/statsproduct/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsproduct#29
- [x] [statsregistrations](https://github.com/PrestaShop/statsregistrations/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statsregistrations#13
- [x] [statssales](https://github.com/PrestaShop/statssales/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statssales#27
- [x] [statssearch](https://github.com/PrestaShop/statssearch/blob/dev/.github/workflows/build-release.yml) : PrestaShop/statssearch#15
- [x] [statsstock](https://github.com/PrestaShop/statsstock/blob/dev/.github/workflows/build-release.yml) :  PrestaShop/statsstock#19
- [x] [welcome](https://github.com/PrestaShop/welcome/blob/dev/.github/workflows/build-release.yml) : PrestaShop/welcome#136

**Comment by Progi1984** [comment]
@eternoendless It's done :muscle: 

Thanks @Kaudaj @jf-viguier & @nenes25
