### ISSUE TITLE
Release 1.7.8.3

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#26969]
This issue tracks the status of the PrestaShop 1.7.8.3 release

### Information

Q                                    | A
-----------------------|---------------
**Type**          | Patch version
**Est. Build date**  |  2022-01-04
**Milestone** | [1.7.8.3](https://github.com/PrestaShop/PrestaShop/milestone/79)
**Kanban** | [1.7.8.3](https://github.com/PrestaShop/PrestaShop/projects/22)
**Delivery date**          |  2022-01-26
### Current status

- [x] Development
- [x] Build 1
- [x] QA validation 🔴  - issues reported
- [x] Build 2
- [x] QA validation 🔴  - issue reported
- [x] Build 3
- [x] QA validation : @boubkerbribri & @Robin-Fischer-PS validate the last buid
- [x] Release
- [x] Available for upgrade
- [x] Docker image

**Comment by Progi1984** [comment]
Build sent in QA : The :soccer: is there for your team @Robin-Fischer-PS.

**Comment by Robin-Fischer-PS** [comment]
Thanks @Progi1984 ! Test campaign is now ready, we will start it tomorrow :)

**Comment by matks** [comment]
## Status update - issues reported in build 1

Release blocked by
- https://github.com/PrestaShop/PrestaShop/issues/27261 => upgrade process issue
- https://github.com/PrestaShop/PrestaShop/issues/27243

When both issues are fixed a build 2 will be delivered.

**Comment by Progi1984** [comment]
The last but not the least : https://build.prestashop.com/news/prestashop-1-7-8-3-maintenance-release/
