### ISSUE TITLE
[EPIC] Improve the image system

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/PrestaShop#27318]
## EPIC's Goal

🎯 **As a merchant, I want to use the lightest and highest quality image, depending on the browser image compatibility and the viewport size.**
As a theme developer, I want my theme to be compatible with all the different image format easily to get the best possible output. 

## Context
HighDPI images for every size is a thing of a past. We must do it by source sets. It is not optimized for the viewport with such a variety of dpi.

The main idea is to generate [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) tags for the front office that will contain in the [sources sets](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source#attr-srcset) all formats with the image type configured from the back office. The tag img will contain the JPG image fallback if the browser doesn't support them.

### To investigate 
- Does the src-set need to be prioritized in the picture tag? Or the browser can calculate which src-set is the most effective. @NeOMakinG 

- Double-check the issue #28664

## US order by priority
- [x] #28048
- [ ] Feature flag the new image system
- [x] https://github.com/PrestaShop/PrestaShop/issues/29893
- [x] #27322 - Be able to generate multiple image type instead of only one 
- [x] #27320 - Add webp format inside the image object in FO
- [x] #27323 - Create a component in order to generate the picture element in FO
- [x] #27319 - Add multiple sizes to the image system
- [x] #27264 - Add avif format to the core
- [ ]  #25790 - Provide an original size to images in FO
- [ ] Add a warning for the marchent if the image doesn’t match the requirement for all size when uploading the images.
- [ ] Add an information in the form to warn users that adding image format will increase the generation of images 
- [x] https://github.com/PrestaShop/PrestaShop/pull/29304 to be finished and merged

```
<picture>
<source srcset="/img/product_1920.avif 1920w, /img/product_1280.avif 1280w, 
  /img/product_640.avif640w, /img/product_320.avif 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw" 
  type="image/avif"/>
<source srcset="/img/product_1920.webp 1920w, /img/product_1280.webp 1280w, 
  /img/product_640.webp 640w, /img/product_320.webp 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw"
  type="image/webp"/>
<img srcset="/img/product_1920.jpg 1920w, /img/product_1280.jpg 1280w,
    /img/product_640.jpg 640w, /img/product_320.jpg 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw"
  src="/img/1920.jpg"
  alt="Product"
  width="1920"
  height="1920">
</picture>
```

### Hummingbird theme task 
- [ ] Specify which widths of images we want to use in the new theme
  - We need to get precise width list of images to be used in the new theme, for each object.
  - We need to take account also the scaled devices. Sizes should overlay nicely for both 1x and 2x scaled devices, maybe even for 3x devices.
  - For example products: 200px, 400px, 600px, 800px, 1200px, 1600px - These sizes will nicely overlay for both 1x and 2x devices.

**TODO:**
| Name  | Size |
| ------------- | ------------- |
| product_160  | 160 x 160  |
| product_320  | 320 x 320  |
| product_640  | 640 x 640  |
| product_800  | 800 x 800  |
| product_1280  | 1280 x 1280  |
| product_1600  | 1600 x 1600  |
| category_160  | 160 x 160  |
| category_320  | 320 x 320  |
etc.

### Clean up and improvements
- [ ] Deprecate HighDPI images, the sizes have the same effect and does not generate duplicate images.
  - Imagine you have product size like home_default 400px and large_default 800px. The HightDPI image function generates home_default_2x in 800px width, while we already have that dimension. It's only a waste of space.
  - https://github.com/PrestaShop/PrestaShop/issues/26886
- [ ] Find a way to make core completely independent on the long-known image format names. Every theme can bring their own formats. If the devs were selfish, it will completely break the core and FO.
- [ ] Find a way to make a backward compatible bridge for every legacy module asking for a dimension that does not exist. We should provide the nearest bigger image size.

**Comment by NeOMakinG** [comment]
Thanks @Hlavtox for the work done on redacting everything and thinking about it

**Comment by NeOMakinG** [comment]
@MatShir 

We're going to need this feature soon inside the new theme as it begins to be more mature, do you think a backend dev can think about it?

**Comment by MeKeyCool** [comment]
#  [[EPIC] Improve the image system](https://github.com/PrestaShop/PrestaShop/issues/27318)

## Analysis of image management current situation

### Data persistance

#### Database

Images meta data are stored on tables : `ps_image`, `ps_image_lang`, `ps_image_shop`, `ps_image_type`

```shell
DESCRIBE ps_image;
+------------+----------------------+------+-----+---------+----------------+
| Field      | Type                 | Null | Key | Default | Extra          |
+------------+----------------------+------+-----+---------+----------------+
| id_image   | int(10) unsigned     | NO   | PRI | NULL    | auto_increment |
| id_product | int(10) unsigned     | NO   | MUL | NULL    |                |
| position   | smallint(2) unsigned | NO   |     | 0       |                |
| cover      | tinyint(1) unsigned  | YES  |     | NULL    |                |
+------------+----------------------+------+-----+---------+----------------+

DESCRIBE ps_image_lang;
+----------+------------------+------+-----+---------+-------+
| Field    | Type             | Null | Key | Default | Extra |
+----------+------------------+------+-----+---------+-------+
| id_image | int(10) unsigned | NO   | PRI | NULL    |       |
| id_lang  | int(10) unsigned | NO   | PRI | NULL    |       |
| legend   | varchar(128)     | YES  |     | NULL    |       |
+----------+------------------+------+-----+---------+-------+

DESCRIBE ps_image_shop;
+------------+---------------------+------+-----+---------+-------+
| Field      | Type                | Null | Key | Default | Extra |
+------------+---------------------+------+-----+---------+-------+
| id_product | int(10) unsigned    | NO   | MUL | NULL    |       |
| id_image   | int(11) unsigned    | NO   | PRI | NULL    |       |
| id_shop    | int(11) unsigned    | NO   | PRI | NULL    |       |
| cover      | tinyint(1) unsigned | YES  |     | NULL    |       |
+------------+---------------------+------+-----+---------+-------+

DESCRIBE ps_image_type;
+---------------+------------------+------+-----+---------+----------------+
| Field         | Type             | Null | Key | Default | Extra          |
+---------------+------------------+------+-----+---------+----------------+
| id_image_type | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name          | varchar(64)      | NO   | MUL | NULL    |                |
| width         | int(10) unsigned | NO   |     | NULL    |                |
| height        | int(10) unsigned | NO   |     | NULL    |                |
| products      | tinyint(1)       | NO   |     | 1       |                |
| categories    | tinyint(1)       | NO   |     | 1       |                |
| manufacturers | tinyint(1)       | NO   |     | 1       |                |
| suppliers     | tinyint(1)       | NO   |     | 1       |                |
| stores        | tinyint(1)       | NO   |     | 1       |                |
+---------------+------------------+------+-----+---------+----------------+
```


#### Filesystem

On filesystem, path are associated to hard coded "environment variables".

{prestashop}/config/defines.inc.php
```php
define('_PS_IMG_SOURCE_DIR_', _PS_ROOT_DIR_.'/img/');
if (!defined('_PS_IMG_DIR_')) {
    $dir = (defined('_PS_IN_TEST_') && _PS_IN_TEST_) ? '/tests/Resources/img/' : '/img/';
    define('_PS_IMG_DIR_', _PS_ROOT_DIR_.$dir);
}

define('_PS_CORE_IMG_DIR_', _PS_CORE_DIR_.'/img/');
define('_PS_CAT_IMG_DIR_', _PS_IMG_DIR_.'c/');
define('_PS_COL_IMG_DIR_', _PS_IMG_DIR_.'co/');
define('_PS_EMPLOYEE_IMG_DIR_', _PS_IMG_DIR_.'e/');
define('_PS_GENDERS_DIR_', _PS_IMG_DIR_.'genders/');
define('_PS_LANG_IMG_DIR_', _PS_IMG_DIR_.'l/');
define('_PS_MANU_IMG_DIR_', _PS_IMG_DIR_.'m/');
define('_PS_ORDER_STATE_IMG_DIR_', _PS_IMG_DIR_.'os/');
define('_PS_PRODUCT_IMG_DIR_', _PS_IMG_DIR_ . 'p/');
// @deprecated since 1.7.8.1 version use _PS_PRODUCT_IMG_DIR_ instead
define('_PS_PROD_IMG_DIR_', _PS_PRODUCT_IMG_DIR_);
define('_PS_PROFILE_IMG_DIR_', _PS_IMG_DIR_.'pr/');
define('_PS_SHIP_IMG_DIR_', _PS_IMG_DIR_.'s/');
define('_PS_STORE_IMG_DIR_', _PS_IMG_DIR_.'st/');
define('_PS_SUPP_IMG_DIR_', _PS_IMG_DIR_.'su/');
define('_PS_TMP_IMG_DIR_', _PS_IMG_DIR_.'tmp/');
```

As we can see in `{prestashop}/src/Adapter/Import/ImageCopier.php`,
```php
/**
 * Copy an image located in $url and save it in a path.
 *
 * @param int $entityId id of product or category (set in entity)
 * @param int $imageId id of the image if watermark enabled
 * @param string $url path or url to use
 * @param string $entity 'products' or 'categories'
 * @param bool $regenerate
 *
 * @return bool
 */
public function copyImg($entityId, $imageId = null, $url = '', $entity = 'products', $regenerate = true)
{
    $tmpDir = $this->configuration->get('_PS_TMP_IMG_DIR_');
    $tmpFile = tempnam($tmpDir, 'ps_import');
    $watermarkTypes = explode(',', $this->configuration->get('WATERMARK_TYPES'));

    switch ($entity) {
        default:
        case 'products':
            $image_obj = new Image($imageId);
            $path = $image_obj->getPathForCreation();
            break;
        case 'categories':
            $path = $this->configuration->get('_PS_CAT_IMG_DIR_') . (int) $entityId;
            break;
        case 'manufacturers':
            $path = $this->configuration->get('_PS_MANU_IMG_DIR_') . (int) $entityId;
            break;
        case 'suppliers':
            $path = $this->configuration->get('_PS_SUPP_IMG_DIR_') . (int) $entityId;
            break;
        case 'stores':
            $path = $this->configuration->get('_PS_STORE_IMG_DIR_') . (int) $entityId;
            break;
    }

...
```
dynamically managed images are stored in `{related_entity_directory}/{related_entity_id_directory}`

A problem is that each entity has its own way to manage images (path/naming/sizing/...)

* For **manufacturers** (`_PS_MANU_IMG_DIR_`)
    > see `{prestashop}/src/Adapter/Image/Uploader/ManufacturerImageUploader.php`
    > ```php
    > private function generateDifferentSizeImages($manufacturerId)
    > {
    >     $resized = true;
    >     $generateHighDpiImages = (bool) Configuration::get('PS_HIGHT_DPI');
    > 
    >     try {
    >         /* Generate images with different size */
    >         if (count($_FILES) &&
    >             file_exists(_PS_MANU_IMG_DIR_ . $manufacturerId . '.jpg')
    >         ) {
    >             $imageTypes = ImageType::getImagesTypes('manufacturers');
    > 
    >             foreach ($imageTypes as $imageType) {
    >                 $resized &= ImageManager::resize(
    >                     _PS_MANU_IMG_DIR_ . $manufacturerId . '.jpg',
    >                     _PS_MANU_IMG_DIR_ . $manufacturerId . '-' . stripslashes($imageType['name']) . '.jpg',
    >                     (int) $imageType['width'],
    >                     (int) $imageType['height']
    >                 );
    > 
    >                 if ($generateHighDpiImages) {
    >                     $resized &= ImageManager::resize(
    >                         _PS_MANU_IMG_DIR_ . $manufacturerId . '.jpg',
    >                         _PS_MANU_IMG_DIR_ . $manufacturerId . '-' . stripslashes($imageType['name']) . '2x.jpg',
    >                         (int) $imageType['width'] * 2,
    >                         (int) $imageType['height'] * 2
    >                     );
    >                 }
    >             }
    > 
    >             $currentLogo = _PS_TMP_IMG_DIR_ . 'manufacturer_mini_' . $manufacturerId . '.jpg';
    > 
    >             if ($resized && file_exists($currentLogo)) {
    >                 unlink($currentLogo);
    >             }
    >         }
    >     } catch (PrestaShopException $e) {
    >         throw new ImageOptimizationException('Unable to resize one or more of your pictures.');
    >     }
    > 
    >     if (!$resized) {
    >         throw new ImageOptimizationException('Unable to resize one or more of your pictures.');
    >     }
    > 
    >     return $resized;
    > }
    > ```
* For **categories** (`_PS_CAT_IMG_DIR_`)
    > see `{prestashop}/classes/Category.php`
    > ```php
    > /**
    >  * CategoryCore constructor.
    >  *
    >  * @param int|null $idCategory
    >  * @param int|null $idLang
    >  * @param int|null $idShop
    >  */
    > public function __construct($idCategory = null, $idLang = null, $idShop = null)
    > {
    >     parent::__construct($idCategory, $idLang, $idShop);
    >     $this->image_dir = _PS_CAT_IMG_DIR_;
    >     $this->id_image = ($this->id && file_exists($this->image_dir . (int) $this->id . '.jpg')) ? (int) $this->id : false;
    >     if (defined('PS_INSTALLATION_IN_PROGRESS')) {
    >         $this->doNotRegenerateNTree = true;
    >     }
    > }
    > ```
* For **suppliers** (`_PS_SUPP_IMG_DIR_`)
    > see `{prestashop}/src/Adapter/Image/Uploader/SupplierImageUploader.php` and `{prestashop}/src/Adapter/Image/Uploader/AbstractImageUploader.php`
    > ```php
    > /**
    >  * {@inheritdoc}
    >  */
    > public function upload($supplierId, UploadedFile $image)
    > {
    >     $this->checkImageIsAllowedForUpload($image);
    >     $tempImageName = $this->createTemporaryImage($image);
    >     $this->deleteOldImage($supplierId);
    > 
    >     $destination = _PS_SUPP_IMG_DIR_ . $supplierId . '.jpg';
    >     $this->uploadFromTemp($tempImageName, $destination);
    > 
    >     if (file_exists($destination)) {
    >         $this->generateDifferentSize($supplierId, _PS_SUPP_IMG_DIR_, 'suppliers');
    >     }
    > }
    > 
    > [...]
    > 
    > /**
    >  * Generates different size images
    >  *
    >  * @param int $id
    >  * @param string $imageDir
    >  * @param string $belongsTo to whom the image belongs (for example 'suppliers' or 'categories')
    >  *
    >  * @return bool
    >  *
    >  * @throws ImageOptimizationException
    >  */
    > protected function generateDifferentSize($id, $imageDir, $belongsTo)
    > {
    >     $resized = true;
    > 
    >     try {
    >         $imageTypes = ImageType::getImagesTypes($belongsTo);
    > 
    >         foreach ($imageTypes as $imageType) {
    >             $resized &= $this->resize($id, $imageDir, $imageType);
    >         }
    >     } catch (PrestaShopException $e) {
    >         throw new ImageOptimizationException('Unable to resize one or more of your pictures.');
    >     }
    >     if (!$resized) {
    >         throw new ImageOptimizationException('Unable to resize one or more of your pictures.');
    >     }
    > 
    >     return $resized;
    > }
    > 
    > /**
    >  * Resizes the image depending on its type
    >  *
    >  * @param int $id
    >  * @param string $imageDir
    >  * @param array $imageType
    >  *
    >  * @return bool
    >  */
    > private function resize($id, $imageDir, array $imageType)
    > {
    >     $ext = '.jpg';
    >     $width = $imageType['width'];
    >     $height = $imageType['height'];
    > 
    >     if (Configuration::get('PS_HIGHT_DPI')) {
    >         $ext = '2x.jpg';
    >         $width *= 2;
    >         $height *= 2;
    >     }
    > 
    >     return ImageManager::resize(
    >         $imageDir . $id . '.jpg',
    >         $imageDir . $id . '-' . stripslashes($imageType['name']) . $ext,
    >         (int) $width,
    >         (int) $height
    >     );
    > }
    > ```
* For **stores** (`_PS_STORE_IMG_DIR_`)
    :warning: I didn't find any Adapter or recent class.

    > see `{prestashop}/classes/Link.php`
    > ```php
    > /**
    >  * Returns a link to a store image for display.
    >  *
    >  * @param string $name
    >  * @param int $idStore
    >  * @param string|null $type image type (small_default, medium_default, large_default, etc.)
    >  *
    >  * @return string
    >  */
    > public function getStoreImageLink($name, $idStore, $type = null)
    > {
    >     $idStore = (int) $idStore;
    > 
    >     if (file_exists(_PS_STORE_IMG_DIR_ . $idStore . (empty($type) ? '.jpg' : '-' . $type . '.jpg'))) {
    >         $uriPath = _THEME_STORE_DIR_ . $idStore . (empty($type) ? '.jpg' : '-' . $type . '.jpg');
    >     } elseif (!empty($type) && file_exists(_PS_STORE_IMG_DIR_ . $idStore . '.jpg')) { // !empty($type) because if is empty, is already tested
    >         $uriPath = _THEME_STORE_DIR_ . $idStore . '.jpg';
    >     } elseif (file_exists(_PS_STORE_IMG_DIR_ . Context::getContext()->language->iso_code . (empty($type) ? '.jpg' : $type . '.jpg'))) {
    >         $uriPath = _THEME_STORE_DIR_ . Context::getContext()->language->iso_code . (empty($type) ? '.jpg' : $type . '.jpg');
    >     } else {
    >         $uriPath = _THEME_STORE_DIR_ . Context::getContext()->language->iso_code . '.jpg';
    >     }
    > 
    >     return $this->protocol_content . Tools::getMediaServer($uriPath) . $uriPath;
    > }
    > ```
* For **products** (`_PS_PRODUCT_IMG_DIR_`)
    > see `{prestashop}/src/Adapter/Product/Image/ProductImagePathFactory.php`
    > ```php
    > /**
    >  * @param ImageId $imageId
    >  * @param string $type
    >  * @param string $extension
    >  *
    >  * @return string
    >  */
    > public function getPathByType(ImageId $imageId, string $type, string $extension = self::DEFAULT_IMAGE_FORMAT): string
    > {
    >     $path = $this->getBaseImagePathWithoutExtension($imageId);
    > 
    >     return sprintf('%s-%s.%s', $path, $type, $extension);
    > }
    > ```


### Hardcoded URL's

We can find some hard coded URLs in code :

> ex. {prestashop}/classes/module/Module.php l.1004
> ```php
> $output = '
> <div class="displayed_flag">
>     <img src="../img/l/' . $default_language . '.jpg" class="pointer" id="language_current_' . $id . '" onclick="toggleLanguageFlags(this);" alt="" />
> </div>
> <div id="languages_' . $id . '" class="language_flags">
>     ' . $this->getTranslator()->trans('Choose language:', [], 'Admin.Actions') . '<br /><br />';
> foreach ($languages as $language) {
>     if ($use_vars_instead_of_ids) {
>         $output .= '<img src="../img/l/' . (int) $language['id_lang'] . '.jpg" class="pointer" alt="' . $language['name'] . '" title="' . $language['name'] . '" onclick="changeLanguage(\'' . $id . '\', ' . $ids . ', ' . $language['id_lang'] . ', \'' . $language['iso_code'] . '\');" /> ';
>     } else {
>         $output .= '<img src="../img/l/' . (int) $language['id_lang'] . '.jpg" class="pointer" alt="' . $language['name'] . '" title="' . $language['name'] . '" onclick="changeLanguage(\'' . $id . '\', \'' . $ids . '\', ' . $language['id_lang'] . ', \'' . $language['iso_code'] . '\');" /> ';
>     }
> }
> $output .= '</div>';
> ```

> ex. {prestashop}/controllers/admin/AdminShopController.php
> ```php
> if (!isset($tree[$id_shop_group]['children'][$id_shop])) {
>     $tree[$id_shop_group]['children'][$id_shop] = [
>         'data' => [
>             'title' => $row['shop_name'],
>             'icon' => 'themes/' . $this->context->employee->bo_theme . '/img/tree-multishop-shop.png',
>             'attr' => [
>                 'href' => $this->context->link->getAdminLink('AdminShopUrl') . '&shop_id=' . (int) $id_shop,
>                 'title' => $this->trans('Click here to display the URLs of the %name% shop', ['%name%' => $row['shop_name']], 'Admin.Advparameters.Help'),
>             ],
>         ],
>         'attr' => [
>             'id' => 'tree-shop-' . $id_shop,
>         ],
>         'children' => [],
>     ];
> }
> ```

> :question: As it looks those codes are from legacy part of Prestashop, are they still used ?

If I understand well, legacy code should not be called due to :
`{prestashop}/admin-dev/index.php`
```php
try {
    require_once __DIR__.'/../autoload.php';
    $response = $kernel->handle($request, HttpKernelInterface::MASTER_REQUEST, false);
    $response->send();
    $kernel->terminate($request, $response);
} catch (NotFoundHttpException $exception) {
    define('ADMIN_LEGACY_CONTEXT', true);
    // correct Apache charset (except if it's too late)
    if (!headers_sent()) {
        header('Content-Type: text/html; charset=utf-8');
    }

    // Prepare and trigger LEGACY admin dispatcher
    Dispatcher::getInstance()->dispatch();
}
```
I still didn't get how it works with FO to bypass legacy parts.

Furthermore Prestashop isn't designed to be integrated under a well configured web server so it adds some `index.php` files to manage assets web direct access (that implies we need some consistency between filesystem image storage structure and linking conventions).

> ex. {prestashop}/img/e/index.php
> ```php
> <?php
> /**
>  * Copyright since 2007 PrestaShop SA and Contributors
>  * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
>  *
>  * NOTICE OF LICENSE
>  *
>  * This source file is subject to the Open Software License (OSL 3.0)
>  * that is bundled with this package in the file LICENSE.md.
>  * It is also available through the world-wide-web at this URL:
>  * https://opensource.org/licenses/OSL-3.0
>  * If you did not receive a copy of the license and are unable to
>  * obtain it through the world-wide-web, please send an email
>  * to license@prestashop.com so we can send you a copy immediately.
>  *
>  * DISCLAIMER
>  *
>  * Do not edit or add to this file if you wish to upgrade PrestaShop to newer
>  * versions in the future. If you wish to customize PrestaShop for your
>  * needs please refer to https://devdocs.prestashop.com/ for more information.
>  *
>  * @author    PrestaShop SA and Contributors <contact@prestashop.com>
>  * @copyright Since 2007 PrestaShop SA and Contributors
>  * @license   https://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
>  */
> 
> header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
> header("Last-Modified: ".gmdate("D, d M Y H:i:s")." GMT");
> 
> header("Cache-Control: no-store, no-cache, must-revalidate");
> header("Cache-Control: post-check=0, pre-check=0", false);
> header("Pragma: no-cache");
> 
> header("Location: ../");
> exit;
> ```


### Product images sizing and theme integration

It looks that "sizing" (small/medium/large/...) is reserved to product images in current architecture.

In `{prestashop}/src/PrestaShopBundle/Resources/config/services/adapter/product/_image.yml`, we can find product images classes definition. 

We have a recent class : `{prestashop}/src/Adapter/Product/Image/ProductImagePathFactory.php` that centralizes image path conventions for products :
```php
class ProductImagePathFactory
{
    public const IMAGE_TYPE_SMALL_DEFAULT = 'small_default';
    public const IMAGE_TYPE_MEDIUM_DEFAULT = 'medium_default';
    public const IMAGE_TYPE_LARGE_DEFAULT = 'large_default';
    public const IMAGE_TYPE_HOME_DEFAULT = 'home_default';
    public const IMAGE_TYPE_CART_DEFAULT = 'cart_default';
```

> :point_up: Has we can see, the image types are defined there for php !

It is also redefined in themes :

ex. {prestashop}/themes/hummingbird/config/theme.yml
```yaml
image_types:
  cart_default:
    width: 125
    height: 125
    scope: [products]
  small_default:
    width: 98
    height: 98
    scope: [products, categories, manufacturers, suppliers]
  medium_default:
    width: 452
    height: 452
    scope: [products, manufacturers, suppliers]
  home_default:
    width: 250
    height: 250
    scope: [products]
  large_default:
    width: 800
    height: 800
    scope: [products, manufacturers, suppliers]
  category_default:
    width: 141
    height: 180
    scope: [categories]
  stores_default:
    width: 170
    height: 115
    scope: [stores]
```

ex. src/prestashop/themes/classic/config/theme.yml
```yml
image_types:
  cart_default:
    width: 125
    height: 125
    scope: [ products ]
  small_default:
    width: 98
    height: 98
    scope: [ products, categories, manufacturers, suppliers ]
  medium_default:
    width: 452
    height: 452
    scope: [ products, manufacturers, suppliers ]
  home_default:
    width: 250
    height: 250
    scope: [ products ]
  large_default:
    width: 800
    height: 800
    scope: [ products, manufacturers, suppliers ]
  category_default:
    width: 141
    height: 180
    scope: [ categories ]
  stores_default:
    width: 170
    height: 115
    scope: [ stores ]
```

And it is used for Theme integration in `{prestashop}/src/Core/Addon/Theme/ThemeValidator.php`
```php
private function hasRequiredProperties(Theme $theme)
{
    $themeName = $theme->getName();

    foreach ($this->getRequiredProperties() as $prop) {
        if (!$theme->has($prop)) {
            if (!array_key_exists($themeName, $this->errors)) {
                $this->errors[$themeName] = [];
            }

            $this->errors[$themeName] = $this->translator->trans(
                'An error occurred. The information "%s" is missing.',
                [$prop],
                'Admin.Design.Notification'
            );
        }
    }

    return !array_key_exists($themeName, $this->errors);
}

public function getRequiredProperties()
{
    return [
        'name',
        'display_name',
        'version',
        'author.name',
        'meta.compatibility.from',
        'meta.available_layouts',
        'global_settings.image_types.cart_default',
        'global_settings.image_types.small_default',
        'global_settings.image_types.medium_default',
        'global_settings.image_types.large_default',
        'global_settings.image_types.home_default',
        'global_settings.image_types.category_default',
        'theme_settings.default_layout',
    ];
}
```

Then images URLs are transmitted to template files thanks to `{prestashop}/src/Adapter/Image/ImageRetriever.php`
```php
/**
 * @param Product|Store|Category $object
 * @param int $id_image
 *
 * @return array|null
 *
 * @throws PrestaShopDatabaseException
 */
public function getImage($object, $id_image)
{
    if (!$id_image) {
        return null;
    }

    if (get_class($object) === 'Product') {
        $type = 'products';
        $getImageURL = 'getImageLink';
        $root = _PS_PRODUCT_IMG_DIR_;
        $imageFolderPath = implode(DIRECTORY_SEPARATOR, [
            rtrim($root, DIRECTORY_SEPARATOR),
            rtrim(Image::getImgFolderStatic($id_image), DIRECTORY_SEPARATOR),
        ]);
    } elseif (get_class($object) === 'Store') {
        $type = 'stores';
        $getImageURL = 'getStoreImageLink';
        $root = _PS_STORE_IMG_DIR_;
        $imageFolderPath = rtrim($root, DIRECTORY_SEPARATOR);
    } else {
        $type = 'categories';
        $getImageURL = 'getCatImageLink';
        $root = _PS_CAT_IMG_DIR_;
        $imageFolderPath = rtrim($root, DIRECTORY_SEPARATOR);
    }

    $urls = [];
    $image_types = ImageType::getImagesTypes($type, true);

    $ext = 'jpg';

    $mainImagePath = implode(DIRECTORY_SEPARATOR, [
        $imageFolderPath,
        $id_image . '.' . $ext,
    ]);
    $generateHighDpiImages = (bool) Configuration::get('PS_HIGHT_DPI');

    foreach ($image_types as $image_type) {
        $resizedImagePath = implode(DIRECTORY_SEPARATOR, [
            $imageFolderPath,
            $id_image . '-' . $image_type['name'] . '.' . $ext,
        ]);

        if (!file_exists($resizedImagePath)) {
            ImageManager::resize(
                $mainImagePath,
                $resizedImagePath,
                (int) $image_type['width'],
                (int) $image_type['height']
            );
        }

        if ($generateHighDpiImages) {
            $resizedImagePathHighDpi = implode(DIRECTORY_SEPARATOR, [
                $imageFolderPath,
                $id_image . '-' . $image_type['name'] . '2x.' . $ext,
            ]);
            if (!file_exists($resizedImagePathHighDpi)) {
                ImageManager::resize(
                    $mainImagePath,
                    $resizedImagePathHighDpi,
                    (int) $image_type['width'] * 2,
                    (int) $image_type['height'] * 2
                );
            }
        }

        $url = $this->link->$getImageURL(
            isset($object->link_rewrite) ? $object->link_rewrite : $object->name,
            $id_image,
            $image_type['name']
        );

        $urls[$image_type['name']] = [
            'url' => $url,
            'width' => (int) $image_type['width'],
            'height' => (int) $image_type['height'],
        ];
    }

    uasort($urls, function (array $a, array $b) {
        return $a['width'] * $a['height'] > $b['width'] * $b['height'] ? 1 : -1;
    });

    $keys = array_keys($urls);

    $small = $urls[$keys[0]];
    $large = end($urls);
    $medium = $urls[$keys[ceil((count($keys) - 1) / 2)]];

    return [
        'bySize' => $urls,
        'small' => $small,
        'medium' => $medium,
        'large' => $large,
        'legend' => isset($object->meta_title) ? $object->meta_title : $object->name,
        'id_image' => $id_image,
    ];
}
```
with `bySize` object that is associated to entities or images objects.


## What's next ?


### Expected interface ?

I try to be sure what behavior you waiting for.

Accoridng `{prestashop}/src/Core/Addon/Theme/ThemeValidator.php` if we want to avoid BC, we have to keep those `global_settings.image_types.` configuration
> ```yaml
> # Deprecated
> image_types:
>   home_default:
>     width: 250
>     height: 250
>     scope: [products]
>   small_default:
>     width: 98
>     height: 98
>     scope: [products, categories, manufacturers, suppliers]
>   medium_default:
>     width: 452
>     height: 452
>     scope: [products, manufacturers, suppliers]
>   large_default:
>     width: 800
>     height: 800
>     scope: [products, manufacturers, suppliers]
>   cart_default:
>     width: 125
>     height: 125
>     scope: [products]
>   category_default:
>     width: 141
>     height: 180
>     scope: [categories]
> ```

But if I understand well what you want, Prestashop should offer to theme developpers this kind of configuration :

> ```yaml
> global_settings:
>   image:
>     available_sizes:
>       - 200px
>       - 400px
>       - 800px
>       - ...
>     formats:
>       - .avif
>       - .webp
>       - .jpg
>       - ...
>     fo_keys:
>       200px-jpg:
>         size: 200px
>         format: .jpg
>         scope: [products, categories, ...]
>       ...
>     ...
> ```

`available_sizes` and `formats` should be used by backend during upload to generate all images format.
`fo_keys` should define keys you can access inside your FO templates

I think this task will be a really big one and I would recommand to reinforce our refactoring process / tooling before starting such a deep change.

If you could scope this epic to your hummingbird needs, what should we do ?


### Question list for the task

- Do you confirm that option/behavior evolution requested isn't reserved to product images ? (As we can read some `category` exemples).
- At my current level, I still need a better understanding of images metadata storage and entity linking. I'll update this post when I'll update my knowledge.
    - Is database image table list exhaustive ?
    - How does the model link images to entity types ? Are `ps_image_type.products`, `ps_image_type.categories`, `ps_image_type.manufacturers`, `ps_image_type.suppliers` and `ps_image_type.stores` used like a bit set ?
    - ...
- Did I miss any modern architecture for "store" management ?
- Did I miss some legacy part that I should consider for this subject ? (For me legacy is avoided for most entities except stores)
- If I should avoid breaking changes, I assume that I should not add new options to `global_settings.image_types.*`. Am I right ? Or can we think about it ? Does creating a kind of adapter with a dedicated deprecated configuration may do the job ?
  > ```yaml
  > global_settings:
  >   image:
  >     ...
  >     # Deprecated
  >     default:
  >       home :
  >         width: 250
  >         height: 250
  >         scope: [products]
  >       small :
  >         width: 98
  >         height: 98
  >         scope: [products, categories, manufacturers, suppliers]
  >       medium :
  >         width: 452
  >         height: 452
  >         scope: [products, manufacturers, suppliers]
  >       large :
  >         width: 800
  >         height: 800
  >         scope: [products, manufacturers, suppliers]
  >       cart :
  >         width: 125
  >         height: 125
  >         scope: [products]
  >       category :
  >         width: 141
  >         height: 180
  >         scope: [categories]
  >       ...
  >     ...
  > ```

**Comment by Hlavtox** [comment]
@MeKeyCool We need to investigate category images also. 

- The thumbnail field in BO creates /img/c/12_thumb.jpg image and generates 12-small_default from it, even if cannot be configured in Image settings at all, it seems.
- This image is not available in frontend category object at all.

**Comment by MeKeyCool** [comment]
@NeOMakinG , could we add #28664 to the todo list ?

**Comment by Hlavtox** [comment]
@MatShir Proper picture tag example for main image on product page.

```
<picture>
  <source 
    srcset="
    https://www.domain.com/48013-medium_default/some-cool-product-rewrite.webp 452w,
    https://www.domain.com/48013-pdt_180/some-cool-product-rewrite.webp 180w,
    https://www.domain.com/48013-pdt_300/some-cool-product-rewrite.webp 300w,
    https://www.domain.com/48013-pdt_360/some-cool-product-rewrite.webp 360w,
    https://www.domain.com/48013-pdt_540/some-cool-product-rewrite.webp 540w,
    https://www.domain.com/48013-pdt_590/some-cool-product-rewrite.webp 590w" 
    sizes="(min-width: 1300px) 590px, (min-width: 768px) 50vw, 100vw" 
    type="image/webp">

  <img class="img-fluid" 
    srcset="
    https://www.domain.com/48013-medium_default/some-cool-product-rewrite.jpg 452w,
    https://www.domain.com/48013-pdt_180/some-cool-product-rewrite.jpg 180w,
    https://www.domain.com/48013-pdt_300/some-cool-product-rewrite.jpg 300w,
    https://www.domain.com/48013-pdt_360/some-cool-product-rewrite.jpg 360w,
    https://www.domain.com/48013-pdt_540/some-cool-product-rewrite.jpg 540w,
    https://www.domain.com/48013-pdt_590/some-cool-product-rewrite.jpg 590w"
    sizes="(min-width: 1300px) 590px, (min-width: 768px) 50vw, 100vw" 
    src="https://www.domain.com/48013-medium_default/some-cool-product-rewrite.jpg" 
    loading="eager" 
    alt="Some cool product name" 
    title="Some cool product name">
</picture>
```

**Comment by MatShir** [comment]
Most of the issue are done. We can close this issue and open a new one if needed. Thanks @Hlavtox & @NeOMakinG for their great work!

**Comment by Hlavtox** [comment]
Welllll there is still a nasty bug that must be fixed before 8.1 release - https://github.com/PrestaShop/PrestaShop/issues/31809
