### ISSUE TITLE
No hook to alter category meta tags

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#27466]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

On all my shops, I am using an older, but awesome module to alter meta tags of all pages. This module is using overrides to do it's job.

![meta](https://user-images.githubusercontent.com/6097524/151141888-4680c81e-0836-48d6-b3f7-a67e3a9693f3.JPG)

In a quest of removing all overrides, I searched the core and found out there is no hook to modify meta information of pages.

### Describe the solution you'd like

There should be a hook that would allow to dynamically modify meta information of all pages.

Either here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/controller/FrontController.php#L1691

Or here:
https://github.com/PrestaShop/PrestaShop/blob/develop/classes/Meta.php#L313

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @Hlavtox 

Thank you for your suggestion. The Developer Team will take it into consideration for future developments. 
Please be aware that there is no guarantee that this feature will be developed anytime soon.
So, we're waiting for your PR :rocket: 

Thank you

**Comment by matks** [comment]
What's the expected behavior?

I think the BO page allows a module to hook at the data exchange level (when data comes from database and is injected into form, and when form data is submitted and then goes to data level then stored). But from your writing I think you're not thinking about a BO hook.

**Comment by Hlavtox** [comment]
I ended up using `hookActionFrontControllerSetVariables`, so this hook is not really needed. Can I close it @kpodemski?
