### ISSUE TITLE
Product page MultiShop Migration

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#27618]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Product page needs to be integrated for multishop, the page itself is only editable in Single shop mode. But to help modifying all shops with one action a checkbox is integrated with each field that can be customized between shops. Here are the parts of the page that need to be adapted with the "Modify all shops" checkbox:

- [ ] Handle stock data for multishop (#27719 by @jolelievre )
- [ ] Handle SEO data for multishop (#27895 by @saulaski)
- [ ] Handle options data for multishop (#27783 by @zuk3975 )
- [ ] Handle customization fields data for multishop (WIP by @Amoifr)
- [ ] Handle shipping data for multishop (#27670 by @zuk3975 )

### Describe the solution you'd like

A POC has been realized to handle the product prices, you can look into the details of the implementation in this PR https://github.com/PrestaShop/PrestaShop/pull/25464 

But to actually adapt a new part for multishop the simpler example is this PR https://github.com/PrestaShop/PrestaShop/pull/27584 which handles basic fields (description, name, ...)

Here are the steps to follow:
- add a field `ShopConstraint` to the related CQRS command, the field is MANDATORY in the constructor
- in the handler replace the `ProductRepository` with `ProductMultiShopRepository` and use the constraint to get the appropriate data for the shop, and update the appropriate shop as well
- adapt behat tests since the command now needs a ShopConstraint so that single shop tests are fixed and turn as before
- update `shop_management.feature` to make sure the copy of a product from shop to shop correctly duplicates the data related to the command
- add behat test to check that the shop constraint is correctly handled (you can inspire from update_multishop_prices.feature feature) when modifying a specific single shop AND all shops (add a feature file ins the Shop folder to handle only the command's scope)
- update the command builder which now needs to implement `MultiShopProductCommandsBuilderInterface` the easiest way to modify its behaviour is to use the `CommandBuilder` component (see example in PricesCommandsBuilder)
- update the builder tests accordingly (fix single shop, and add multi shop tests)
- finally you need to add the `'modify_all_shops' => true,` option on each field that handles multishop

This should be enough, unless the form field is a special component, then you might need to update the form theme or JS a little. But most fields are already handled.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
@jolelievre will this PR #27584 fix/close this issue/feature?

**Comment by jolelievre** [comment]
Hi @hibatallahAouadni 
the PR is only a part of this issue
