### ISSUE TITLE
[EPIC] Differentiate the OS Project from the Company part 2

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#28771]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

- [x] https://github.com/PrestaShop/PrestaShop/issues/30425
- [x] Many methods to remove as unused: #27912 by @eternoendless 

`controllers/admin/AdminModulesController.php`
Templates, with addon links, unused:
 `admin-dev/themes/default/template/controllers/modules/tab_modules_list.tpl`
`src/PrestaShopBundle/Resources/views/Admin/Module/tab-modules-list.html.twig`

- [x]  Carrier wording related to Addons' platform : #28842
![Capture d’écran 2022-05-11 à 16 00 19](https://user-images.githubusercontent.com/43613217/174095168-ddb5d248-0ce4-4ed9-a5c1-409d428c2ed6.png)

- [x] Link to Addons favicon generator : #28843
![Capture d’écran 2022-05-11 à 15 42 48](https://user-images.githubusercontent.com/43613217/174095152-b235b063-1c02-4ccd-aa34-0ceeabe6f279.png)

- [ ] https://github.com/PrestaShop/PrestaShop/issues/30604
- [ ] https://github.com/PrestaShop/PrestaShop/issues/31793
- [ ] https://github.com/PrestaShop/PrestaShop/issues/31791

- Call to prestashop.com remaining.

### Describe the solution you'd like

remove them 🤘 !

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [X] I'm willing to provide any wireframes or design assets required for this feature.
- [ ] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by MatShir** [comment]
New item -> https://github.com/PrestaShop/PrestaShop/issues/30604
