### ISSUE TITLE
List of feedbacks for Horizontal Migration

### ISSUE THREAD

**Issue by tegbessou** [PrestaShop/PrestaShop#28831]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Fix returns make in the PR for Horizontal Migration

### Describe the solution you'd like

- [X] Add `shopShareDatas` in the `HelperListConfiguration` class and replace this

```php
$whereShop = Shop::addSqlRestriction(false, 'a');
```

by

```php
//$whereShop = Shop::addSqlRestriction($helperListConfiguration->shopShareDatas, 'a');
```

- [x] Change in the `configure` method from the `HeaderConfigurator` class, the line

```php
$controllerConfiguration->templatesVars['current'] = $this->router->generate('admin_features_index');
$controllerConfiguration->templatesVars['currentIndex'] = $this->router->generate('admin_features_index');
```

- [X] Use the request to add the current URL in the template vars

In the `configure` method from the `ToolbarFlagsConfigurator` class, you have to change the line and use the service ⇒ OK

```php
$controllerConfiguration->templatesVars['debug_mode'] = (bool) _PS_MODE_DEV_;
```

- [x] Change in the `configure` method from the `ToolbarFlagsConfigurator` class, the line. But look how to change this (**EDIT** - url_post doesnt seem to be used anywhere, the change has no effect. Related https://github.com/PrestaShop/PrestaShop/pull/28890)

```php
$controllerConfiguration->templatesVars['url_post'] = $this->router->generate('admin_features_index');
```

- [x] Move this from `HelperListBridge` to `HelperListFeatureBridge` (**EDIT** this is not related with feature list, it should be handled during dedicated feature_value list migration)

```php
if ($helperListConfiguration->table == 'feature_value') {
    $helperListConfiguration->where .= ' AND (a.custom = 0 OR a.custom IS NULL)';
}
```

- [X] Put a `@todo` in `HelperListBridge` to investigate on why the `order` table is hardcoded

- [X] Look if the `display` method from `SmartyBridge` class can be put in `private`

- [x] Create a method in the `Controller` to initiate the controller configuration instead of in the listener, this method should be call in the `InitControllerListener`. We must put this method in the interface `LegacyAdminControllerInterface` (#28886)

- [x] Remove `getTable`, `getClassName`, `getIdentifier`, `getPositionidentifier` and put all of these information in the method which initiate the controller configuration (#28886)

- [x] Rename `buildGenericAction` in `buildGenericActions` in `FeatureController` (#28886 - renamed to `setToolbarActions`)

- [x] Use `!tagged` to pass all `Configurator` to the `SmartyBridge` (#28886)

- [x] Create a `BridgeObject` which will be passed to hook with legacy name for property. This object will be instantiated in …. (I don’t know yet) (#28886)

- [x] Remove `multishop_context` and `multi_shop_context` from `FeatureController` and put it in the `BridgeObject` (#28886)

- [x] Change url from (Use Link getAdminLink)

- [x] LegacyControllerBridge and ControllerConfiguration (introduced in https://github.com/PrestaShop/PrestaShop/pull/28886)  should be cleaned up - we should get rid of public properties and add needed getters/setters/constructor arguments instead to have a clean contract
```bash
/index.php/sell/catalog/features/index.php?controller=AdminFeatures&updatefeature=&id_feature=1&token=6474fb6128d494963d8fdb6d085753b0
```

To

```bash
/index.php?controller=AdminFeatures&updatefeature=&id_feature=1&token=6474fb6128d494963d8fdb6d085753b0
```

- [x] This url come from legacy HelperList for actions

- [x] Document all properties in `ControllerConfiguration` and `HelperListConfiguration`

**Comment by sLorenzini** [comment]
Hello @tegbessou ,

Thank you for your suggestion.
Waiting for your PR 🚀 

Thank you

**Comment by zuk3975** [comment]
I think all feedback was resolved in latest PR. So I close the issue.
