### ISSUE TITLE
Remove default meta description "Shop powered by PrestaShop"

### ISSUE THREAD

**Issue by jf-viguier** [PrestaShop/PrestaShop#28941]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

Ton of stores have  "Shop powered by PrestaShop" in meta description : it's bad for seo.

### Describe the solution you'd like

And empty description is best for beginner seo: Google will compute a description based on the home page content. IT's more relevant.

### Do you plan to work on this feature?

- [ ] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [ ] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by hibatallahAouadni** [comment]
Hello @jf-viguier 

Thank you for your suggestion. The Product Team will take it into consideration for future developments. 
Thanks again for your PR :rocket: 

Thank you

**Comment by jf-viguier** [comment]
@hibatallahAouadni why Needs Specs label ? For removing a default dummy text ?

**Comment by hibatallahAouadni** [comment]
@jf-viguier No! But to get the PM approval 😉

**Comment by kpodemski** [comment]
@PrestaShop/product-team easy approval guys :-)

**Comment by eshraw** [comment]
LGTM @kpodemski @jf-viguier @hibatallahAouadni 
Thanks for the issue + PR @jf-viguier !
