### ISSUE TITLE
EPIC: PrestaShop language packages auto-generation

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#29533]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Is your feature request related to a problem?

This epic aims at refactoring and improving our TranslationTool application in order to handle PrestaShop language packages via Github CI automatic CI runs instead of a server with cron tasks (current solution), it was initiated while we are handling the packages for the new v8 version.

The purpose here is multiple:
- improve the command so that they can be run more easily by anyone
- centralize all the automatic tasks in Github so that the open source maintainers and contributors have a better view and control over this process (the project thus would be more autonomous for this process)
- switch back the TranstionTool to an open organization so that contributors can also use them and build their own packages if neededPrestashop

### Describe the solution you'd like

Here is the list of tasks that need to be done for this epic, for now the purpose is to handle all this for the version 8.0 of PrestaShop:

- [x] Handle v8 for catalog export (https://github.com/PrestaShopCorp/TranslationTool/pull/103)
- [x] Handle v8 crowdin push (https://github.com/PrestaShopCorp/TranslationTool/pull/103)
- [x] Handle TranslationFiles update for v8 (https://github.com/PrestaShopCorp/TranslationTool/pull/104)
- [x] Handle Crowdin archive building (https://github.com/PrestaShopCorp/TranslationTool/pull/104)
- [x] #29562
- [x] #29563
- [x] #29564 
- [x] (Nice to have) add some manual GitHub actions that can help with catalog extraction/update for the core and crowdin updates
- [x] #29565

### Additional context

Once the v8 process is correctly handled with Github CI we'll be able to setup it for the 1.7.8 version as well and thus w'll be able to turn off this process handled by PrestaShop SA server so far.

### Do you plan to work on this feature?

- [X] I'm willing to contribute a [formal specification](https://github.com/PrestaShop/prestashop-specs).
- [ ] I'm willing to provide any wireframes or design assets required for this feature.
- [X] I'm willing to submit a Pull Request that implements this feature.
- [X] I'm willing to help verify that the implemented feature works as intended and produces no unintended side effects.

**Comment by MatShir** [comment]
Nice work everyone ! :) 
Epic done !!!
