### ISSUE TITLE
Setup ci for the recurrent tasks:

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#29564]
**task:**
  - [x] Export/build/publish archives from crowdin
  - [x] Update TranslationFiles repository based on latest crowdin build
  - [x] CI for GCP archive pushing (this CI could be set on the TranslationFiles repo on each push, but I guess it can still use the TranslationTool docker commands for its execution)

**Comment by MatShir** [comment]
Blocked until this issue is closed https://github.com/PrestaShop/PrestaShop/issues/29562
