### ISSUE TITLE
BO - Translations - Error 500 is displayed after updating a language

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/PrestaShop#29962]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Related to this https://github.com/PrestaShop/PrestaShop/issues/29895
In the BO > International > Translations page, when we try to add/update a language, an error is displayed

### Expected behavior

No error displayed

### TODO

- [ ] Investigate the issue first to understand the pb and why it is different for everyone

### Steps to reproduce

1. Install 8.0.x with English language & France country
2. Go to BO > International > Localization page
3. Import the Algeria pack
4. Click on "My profile" and change the employee language to Arabic
5. Go to BO > International > Translations page
6. Update The Arabic language many times
7. Sometimes => OK
8. Sometimes error 500 
![image](https://user-images.githubusercontent.com/16067358/195126960-ace5453d-3827-4dda-b74c-88c127cb94e5.png)
11. I found an exception that reproduced only one time 
 [language.pdf](https://github.com/PrestaShop/PrestaShop/files/9757305/language.pdf)

I attached a screen record

https://user-images.githubusercontent.com/16067358/195127949-38ec38a6-cb06-4bb0-a816-1c8f14fbfa66.mp4

[Untitled_ Oct 11, 2022 2_09 PM.webm](https://user-images.githubusercontent.com/16067358/195127957-b8a9e69d-2ac2-4228-b9a0-9853ad9cb835.webm)

I tried with php7.4, same issue (error 500)
[php7.webm](https://user-images.githubusercontent.com/16067358/195128385-e4fb1fc2-a592-4025-8bf5-0659558d8a92.webm)

PS: I checked with PS1.7.8.7 + PHP 7.4 => ok

### PrestaShop version(s) where the bug happened

8.0.x

### PHP version(s) where the bug happened

7.2, 7.4

**Comment by matks** [comment]
@khouloudbelguith What do you mean by "Update The Arabic language many times" 😊 ?

**Comment by khouloudbelguith** [comment]
@matks,

I tried to update the Arabic language for the first time => NOK: error 500
I tried to update the Arabic language the second time => Ok
I tried to update the Arabic language again => exception 

As described in my screen records

Thanks!

**Comment by AureRita** [comment]
Hi @khouloudbelguith  ,

Thank you for the report, I reproduced it on 8.0.0 and 1.7.7.8 but not on 1.7.8.7. 
For me, in first use, it update somewhere the languages is not updated and after I get the exception. as you can see : 

[Untitled_ Oct 11, 2022 5_56 PM.webm](https://user-images.githubusercontent.com/100699445/195141328-8fdc17a7-936c-4dfd-b43d-1ea52f066b6a.webm)

After some test, I see that will come even with other languages ( no need RTL I think ) 

[Untitled_ Oct 11, 2022 5_54 PM.webm](https://user-images.githubusercontent.com/100699445/195140606-158a466a-38e4-4bf3-be90-0579889fad30.webm)

Thank you

**Comment by matks** [comment]
> Thank you for the report, I reproduced it on 8.0.0 and 1.7.7.8

Oh? That means issue is not related to http://i18n.prestashop-project.org/ as it's something only PrestaShop 8 uses

**Comment by eternoendless** [comment]
Could it be a timeout?

**Comment by AureRita** [comment]
Sorry for this bad infos, I didn't reproduce it on 1.7.7.8. Indeed, we need to disable the cache in 1.7.7.8 to no longer have another issue. 

Even if you disable the cache in 8.0.0, the issue is still there. 

@eternoendless, in the 1.7.7.8 version, without disabling the cache, we can have some timeout. 
In the 8.0.0 version, no

**Comment by eternoendless** [comment]
If you get an HTTP 500 error even when in dev mode, it probably means that either the web server or PHP is crashing. The Apache (or whatever your server is) error log might be of use to find where the problem is coming from.

**Comment by jolelievre** [comment]
I had a similar error locally, I thought it was related to my environment so I ignored it at the time. I didn't understand why but I noticed that the path mentioned in the error `var/cache/dev/whatheverthecontainerfolder` was actually referring to a container folder that doesn't exist in the cache

I don't know why though, but maybe when a language is installed the kernel or container is rebooted at some point to update the translations from the new package and it seems like this part is failing (might be related to our symfony cache clear method as well). I don't pretend I understand the issue but it's a lead

**Comment by matks** [comment]
I have this on localhost

> 1. Install 8.0.x in French
> 2. Go to BO > International > Localization page
> 3. Import the Algeria pack
> 5. Go to BO > International > Translations page
> 6. Update The French language -> first time it works
> 7. Update The French language -> I get an exception

![Capture d’écran 2022-10-13 à 09 57 09](https://user-images.githubusercontent.com/3830050/195575450-8ff63770-a7f8-4035-9220-539933d2627d.png)

And I notice in var/cache/dev I have 3 container files:
- ContainerAxJHC44
- ContainerAxJHC44.legacy
- ContainerB75kEGA

It looks like the first clic on "Update language button" generates a new dumped container file and then the situation is unstable so on second clic it crashes

**Comment by HanaRebaiQA** [comment]
Hello everybody, 

Thank you @khouloudbelguith for your report.
I tried to reproduce the issue on PS1778, PS1787 and PS8.0.x. 

- **PS1778** : When I changed the BO language to Arabic, the menu is changed in Arabic and i was able to reproduce the 500 error when I click on update languages many times : **NOK (500 Error)** :x: 

https://user-images.githubusercontent.com/92912932/195576794-72678f3a-3c3b-495c-81a6-488436c78a2f.mp4


- **PS1787** : When I changed the BO language to Arabic, the menu is not changed in Arabic and i was not able to reproduce the 500 error when I click on update languages many times : **OK (No 500 error)** :heavy_check_mark: 

https://user-images.githubusercontent.com/92912932/195576803-53aadb49-6fb3-4b97-a7aa-a56254349f34.mp4


- **PS8.0.x** : Same as PS1787. I wasn't able to reproduce the issue : **OK  (No 500 error)** :heavy_check_mark:  

https://user-images.githubusercontent.com/92912932/195576816-b50d6656-2342-458e-97a7-73b0406d873a.mp4


Thank You!

**Comment by eshraw** [comment]
To investigate w/ dev @PrestaShop/product-team

**Comment by atomiix** [comment]
Just tried to reproduce it but I was unable to. I tried in 8.0.x and develop.
Can someone that was able to reproduce it before can try again on those branches?

**Comment by HanaRebaiQA** [comment]
Hello @atomiix 

Me too I was unable to reproduce it on 8.0.x and PS1787
ping @PrestaShop/qa-functional Could someone try to reproduce this issue please ?

Thank you!

**Comment by sallemiines** [comment]
Hello 

I check the issue with **PS800  NOK** 

[Untitled_ Dec 7, 2022 11_54 AM.webm](https://user-images.githubusercontent.com/31663369/206160847-02707110-4bbb-4c5e-ad8f-a2c9366ec1e1.webm)


**PS 1787 OK**


https://user-images.githubusercontent.com/31663369/206165483-4cf45595-d0be-483a-909a-7655965189c6.mp4

**PS 80.x NOK**

![image](https://user-images.githubusercontent.com/31663369/206172606-e10d1945-0cc7-4ce0-8e4f-6d8e49f57d79.png)

Thank you !

**Comment by atomiix** [comment]
Hi @sallemiines, I'm not sure to understand, the error in the first screen record is not the same as the last screen capture but the version looks the same? Also, for the last screen capture, this is a timeout issue that is not related to the 8.0.x branch.

**Comment by HanaRebaiQA** [comment]
Hello,

For me I was unable to reproduce this issue. 
ping @PrestaShop/qa-functional What we will do for this issue since @sallemiines was able to reproduce it ? Could someone else try to reproduce it or we close it ?

Thank You!

**Comment by HanaRebaiQA** [comment]
Hello everyone, 

I'll close this issue since the error provided by @sallemiines about the timeout, is different compared to the original issue.

Thank You!
