### ISSUE TITLE
UI Tests : Migration to TypeScript

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/PrestaShop#30263]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

### Descriptiion

Migration of UI Tests from JavaScript to TypeScript 

#### POC 
* #30125 

#### Migration
* campaigns
  * functional 
    * BO
      * [x] 01_login : #30739
      * [x] 02_orders : #30749
      * [x] 03_catalog : #30738
      * [x] 04_customers : #30724
      * [x] 05_customerService : #30681
      * [x] 07_modules : #30681
      * [x] 08_design : #30660
      * [x] 09_shipping : #30639
      * [x] 10_payment : #30621
      * [x] 11_international : #30593
      * [x] 13_shopParameters : #30575
      * [x] 14_advancedParameters : #30329 - #30466
      * [x] 15_header : #30298
    * FO 
      * [x] 01_login : #30657
      * [x] 02_headerAndFooter : #30638
      * [x] 03_userAccount : #30627 
      * [x] 04_newsletter : #30611
      * [x] 05_contactUs : #30611
      * [x] 06_homePage : #30611
      * [x] 07_search : #30583
      * [x] 08_menuAndNavigation : #30583
      * [x] 09_productPage : #30548
      * [x] 11_checkout : #30458
      * [x] 12_orderConfirmation : #30371
  * [x] productV2 : #30718
  * [x] regression : #30679 
  * [x] sanity : #30682
* commonTests
  * [x] BO : #30861
  * [x] FO : #30661 - #30826
* data
  * [x] demo : #30951
  * [x] faker : 
    * #30693
    * #30695
    * #30726
    * #30752
    * #30777
    * #30838
    * #30914
  * [x] import : #31217
* pages
  * [x] BO
    * #30790  
    * #30809
    * #31010
    * #31030
    * #31049
    * #31108
    * #31179
  * [x] FO : #30743
  * [x] install : #30640
  * [x] BOBasePage : #30466
  * [x] FOBasePage : #30458
  * [x] CommonPage : #30371
* [x] tools : #30368 - #30524 
* [x] utils : #30615 - #30646

#### Last Steps
* [x] Check all forEach : #31238
* [x] Remove all `@ts-ignore` : #31238
* [x]  Check all `as` cast : #31238
* [x] Pass on each public selector and create the function that on the appropriate page that can be used on the test and make them private of course : #31257
* [x] TypeCheck : #30574 ![image](https://user-images.githubusercontent.com/1533248/207092951-d0e20f05-7ae1-4430-a737-5f1f43eecbd6.png)
* [x] Remove the JS Part : #32595 & #32607

### Status  (on `develop` branch)
* Command : `find . -type f -not -path "./node_modules/*" | grep -c '\.js$'`
* Calcul % Migration : (`Nb .ts` × 100) ÷ (`Nb .js`+`Nb .ts`)
* 2022-12-02 : 685 `.js` - 34 `.ts` => 4.72%
* 2022-12-15 : 655 `.js` - 66 `.ts` => 9.15%
* 2022-12-21 : 507 `.js` - 221 `.ts` => 30.36%
* 2022-12-29 : 488 `.js` - 241 `.ts` => 33.06%
* 2023-01-02 : 413 `.js` - 324 `.ts` => 43.96%
* 2023-01-13 : 173 `.js` - 587 `.ts` => 77.24%
* 2023-01-16 : 147 `.js` - 619 `.ts` => 80.81%
* 2023-01-23 : 114 `.js` - 678 `.ts` => 85.61%
* 2023-02-03 : 9 `.js` - 787 `.ts` => 98,87%
* 2023-02-06 : :tada: Finished... It's time to last steps

**Comment by Progi1984** [comment]
@boubkerbribri / @nesrineabdmouleh / @NeOMakinG : It's finished 🎉🎉🎉
