### ISSUE TITLE
Release 8.1.0 🚀

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#30719]
This issue tracks the status of the PrestaShop 8.1.0 release

### Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        | Minor version
**Milestone**                                | [8.1.0](https://github.com/PrestaShop/PrestaShop/milestone/84)
**Kanban**                                    | [8.1.x](https://github.com/PrestaShop/PrestaShop/projects/28)
**[Feature Freeze](https://build.prestashop-project.org/news/2023/prestashop-8-1-feature-freeze/)** | 2023-01-31
**[Beta](https://build.prestashop-project.org/news/2023/prestashop-8-1-beta-release/)** | 2023-02-17
**[Release candidate 1](https://build.prestashop-project.org/news/2023/prestashop-8-1-rc1-release/)**             | 2023-05-25
**Est. Final release**   | 2023-06-26
**Release manager tech**           | @lartist @matks 
**Release manager product**     |   @fabienvallon 
**Release manager QA**              |  @MhiriFaten 

### Current status
- [x] [Specification](https://github.com/PrestaShop/PrestaShop/issues/30292)
- [x] Feature development
- [x] [Feature freeze](https://build.prestashop-project.org/news/2023/prestashop-8-1-feature-freeze/) 
- [x] Build (beta) https://drive.google.com/file/d/1n5mWRbpt8tRV_9-4XcEi_vem1BfXFkHk/view?usp=share_link
- [x] Stabilization 
#### Remaining stabilization tasks
- [x] https://github.com/PrestaShop/PrestaShop/issues/31851
- [x] #31979
- [x] #31833
~~Release GDPR Module (https://github.com/PrestaShop/psgdpr)~~
- [x] Product UI issues : https://github.com/PrestaShop/PrestaShop/pull/31968
  - [x] https://github.com/PrestaShop/PrestaShop/issues/31588
  - [x] https://github.com/PrestaShop/PrestaShop/issues/31589
- [x] https://github.com/PrestaShop/PrestaShop/pull/32379 
- [x] #32460
- [x] Push new wording towards crowdin

#### Release Candidate and final release
- [x] Build (RC1)
- [x] Release Candidate 1
  - [x] Backport a fix into 8.1 release candidate branch : [#32936](https://github.com/PrestaShop/PrestaShop/issues/32936)
- [x] QA and community validation
- [x] Final release

#### Available for upgrade
- [x] Finalize autoupgrade --> https://github.com/PrestaShop/autoupgrade/milestone/26

**Comment by letwang** [comment]
Hi, when will 8.1.0 be released?

What is the difference between the release time of 8.0.1 and 8.1.0? Should I wait for 8.0.1 or 8.1.0?

**Comment by matks** [comment]
@letwang 8.0.1 is expected to be delivered within the 2 weeks (3 worst case scenario) while 8.1.0 would rather be delivered somewhere between March and May

Please note this are very broad estimates that I guess from _previous release schedules_ of minor or patch versions. I simply extrapolate scenarii happened before to these releases.

**Comment by letwang** [comment]
Great~ looking forward to 8.0.1 and 8.1.0

**Comment by matks** [comment]
@lartist will be Release Manager for PrestaShop 8.1.0

**Comment by BenTen** [comment]
Congratulation!

**Comment by matks** [comment]
## 2023-01-31 [PrestaShop 8.1 Is Now In Feature Freeze](https://build.prestashop-project.org/news/2023/prestashop-8-1-feature-freeze/)

**Comment by matks** [comment]
## 2023-02-17 [PrestaShop 8.1 Beta Is Open For Feedback](https://build.prestashop-project.org/news/2023/prestashop-8-1-beta-release/)

A little late to the party, but [PrestaShop 8.1.0 Beta period](https://build.prestashop-project.org/news/2023/prestashop-8-1-beta-release/) has been opened since 17th of February, 2 weeks ago.

Check out the [Minor release lifecycle documentation page](https://devdocs.prestashop-project.org/8/project/release/minor-release-lifecycle/) for details about public beta period

There is still 2 weeks ahead to help us test and find all blocker bugs for 8.1.0, then we'll be able to fix them all and publish a Release Candidate!

**Comment by letwang** [comment]
good jobs!

**Comment by matks** [comment]
Hello over there, I must inform you we have been focusing a lot of efforts on delivering [PrestaShop 8.0.2](https://github.com/PrestaShop/PrestaShop/issues/31143) that has proven to be quite a difficult release to land. We can expect the unplanned work that was needed for 8.0.2 to delay 8.1.0 release.

**Comment by matks** [comment]
## 2023-04-27 Status update

Last weeks we have published multiple 8.0.x patch releases which requested a lot of energy from the project team, postponing further and further PrestaShop 8.1.0 .

Last 8.0.x (and 1.7.8.x!) release, PrestaShop 8.0.4, was even _blocking_ 8.1.0 release because it was a security release so we had to wait for 8.0.4 to be released to be able to push the security fixes into 8.1.0 . We could not do it before because we had to keep the security fixes secret until 8.0.4 was released.

Hopefully road ahead of us is now clear to release PrestaShop 8.1.0 in the next weeks

**Comment by matks** [comment]
## 2023-05-17 Status update

The content of 8.1.0 is mostly done, we are now performing the release process to create the release candidate ZIP. We found multiple issues, fixed many of them. Last known one is https://github.com/PrestaShop/PrestaShop/issues/32575 we're working on it right now.

**Comment by letwang** [comment]
good jobs!

**Comment by matks** [comment]
Following last item https://github.com/PrestaShop/PrestaShop/issues/32575 being merged, I was able to build a Release Candidate for PrestaShop 8.1.0 using [my branch](https://github.com/matks/PrestaShop/tree/8.1.0-build1) (you can find it in this PR https://github.com/PrestaShop/PrestaShop/pull/32659).

- the ZIP file https://drive.google.com/file/d/1fQS89OYld8Lp_ZNBjc74BMoipO6a4NTc/view?usp=share_link
- the XML to use if you want to verify integrity https://drive.google.com/file/d/1vFm_LgxjG5hQymEbE9ALsJcyubwE6HOH/view?usp=sharing

Before publishing it, let's do some basic checks 😄

**Comment by matks** [comment]
Basic checks were performed by QA team, thank you to them ❤️ .

[8.1.0 Release Candidate 1](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.0-rc.1) has been published. Release note will be published very soon, with all the details you need to know in it. One very important thing to be aware of is that this Release Candidate version is being shared simultaneously with the community and the project's QA team.

The idea is for everyone to collectively confirm that all issues identified in the beta version have been resolved. In the past we used to request QA team help _then_ community help and we think it might be more efficient to do the two simultaneously.

EDIT: Release note published https://build.prestashop-project.org/news/2023/prestashop-8-1-rc1-release/

**Comment by justeen35** [comment]
At last 😁

**Comment by markoopapa** [comment]
When will be rady for update from 8.0.4?

**Comment by darkf3d3** [comment]
It's wrote:
Est. Final release | End of June 2023

**Comment by matks** [comment]
> When will be rady for update from 8.0.4?

As written in https://build.prestashop-project.org/news/2023/prestashop-8-1-rc1-release/

> ## Upgrade from 1.7.8 and 8.0 to 8.1
> The upgrade path to PrestaShop 8.1.0 is not available yet. We are prioritizing the development of the autoupgrade module which will let you upgrade your shops from versions 8.0.x and 1.7.8.x to the upcoming 8.1.0 version. We set a one-month goal to complete this module before the 8.1.0 final release on June 26th, 2023. However, regardless of the module’s completion status, the 8.1.0 release will proceed.

**Comment by ps-jarvis** [comment]
Go go PrestaShop team!

**Comment by MatShir** [comment]
Released !!!! 🎉 Thanks for everyone involved

Checkout the detail below ⬇️
[https://www.prestashop-project.org/releases/prestashop81/](https://www.prestashop-project.org/releases/prestashop81/
)
[https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.0](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.0)
