### ISSUE TITLE
Release 8.0.2 ✈️ 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#31143]
This issue tracks the status of the PrestaShop 8.0.2 release

### Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        | Patch version
**1st Build date**                               |  2023-02-27
**2nd Build date**                               |  2023-03-10
**Milestone**                                | [8.0.2](https://github.com/PrestaShop/PrestaShop/milestone/88)
**Kanban**                                    | [8.0.x](https://github.com/PrestaShop/PrestaShop/projects/27)
**Delivery date**                   |  2023-03-13
**Release manager tech**           |  @matthieu-rolland  
**Release manager product**     |   @Zoefinders 
**Release manager QA**              |  @sallemiines 

### Current status

- [x] Development
- [x] Build 1 
- [x] QA validation 🔴 - build 1 has been reported faulty
- [x] Build 2 [accessible here](https://drive.google.com/file/d/1NrrzxyRkZnX_juKGHcVHVV28N87YyDTd/view?usp=sharing)
- [x] QA validation ✅ 
- [x] [Release](https://build.prestashop-project.org/news/2023/prestashop-8-0-2-maintenance-release/)
- [x] Available for upgrade
- [x] Docker image

**Comment by matks** [comment]
## 2023-02-28 Build has started

Release Manager @matthieu-rolland started the build process yesterday

**Comment by matks** [comment]
## 2023-03-02 QA validation started

QA validation campaign started, monitored by @sallemiines QA Release Manager

**Comment by matks** [comment]
## Status update 10/03/2023

- On Tuesday 07/03/2023 QA test campaign ended however multiple blockers have been identified (for example https://github.com/PrestaShop/PrestaShop/issues/31593), including some related to the upgrade process from 1.7.8.x to 8.0.x
- The maintainer team has been working to deliver bug fixes for the blockers identified the whole week
- Thanks to everyone effort, a new build was delivered by @matthieu-rolland at noon today 10/03/2023 to QA team

So now we wait for our friends from the QA team to tell us whether this new build is valid or not 👍 .

**Comment by matks** [comment]
## 2023-03-13 8.0.2 has been released

https://build.prestashop-project.org/news/2023/prestashop-8-0-2-maintenance-release/

**Comment by matks** [comment]
8.0.2 is available for upgrade and docker images are available too

https://hub.docker.com/r/prestashop/prestashop/tags

**Comment by matks** [comment]
Thank you @matthieu-rolland @sallemiines and @Zoefinders ! 🎉
