### ISSUE TITLE
Add Github action to check licence on files 

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31230]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

#### Description
We will use the header-stamp tool, that is already use by the module team, we have to make it compatible with our needs then add the github action.

Then we can require it in all native modules and add a github action for each of them.

#### To do

- [x] Modify header-stamp so that it suits our needs ([PR in progress](https://github.com/PrestaShopCorp/header-stamp/pull/41))
- [ ] Make a PR updating licence header using header-stamp: 
- [ ] Require header-stamp on prestashop core and add the github action

##### Require header-stamp and add a github action for all native modules:

- [ ] blockreassurance
- [ ] blockwishlist
- [ ] circuit-breaker
- [ ] classic
- [ ] contactform
- [ ] dashactivity
- [ ] dashgoals
- [ ] dashproducts
- [ ] dashtrends
- [ ] decimal
- [ ] graphnvd3
- [ ] gridhtml
- [ ] gsitemap
- [ ] laminas-code-lts
- [ ] pagesnotfound
- [ ] productcomments
- [ ] ps_banner
- [ ] ps_bestsellers
- [ ] ps_brandlist
- [ ] ps_cashondelivery
- [ ] ps_categoryproducts
- [ ] ps_categorytree
- [ ] ps_checkpayment
- [ ] ps_contactinfo
- [ ] ps_crossselling
- [ ] ps_currencyselector
- [ ] ps_customeraccountlinks
- [ ] ps_customersignin
- [ ] ps_customtext
- [ ] ps_dataprivacy
- [ ] ps_distributionapiclient
- [ ] ps_emailalerts
- [ ] ps_emailsubscription
- [ ] ps_facetedsearch
- [ ] ps_faviconnotificationbo
- [ ] ps_featuredproducts
- [ ] ps_googleanalytics
- [ ] ps_imageslider
- [ ] ps_languageselector
- [ ] ps_linklist
- [ ] ps_mainmenu
- [ ] ps_newproducts
- [ ] ps_searchbar
- [ ] ps_sharebuttons
- [ ] ps_shoppingcart
- [ ] ps_socialfollow
- [ ] ps_specials
- [ ] ps_supplierlist
- [ ] ps_themecusto
- [ ] ps_viewedproduct
- [ ] ps_wirepayment
- [ ] psgdpr
- [ ] statsbestcategories
- [ ] statsbestcustomers
- [ ] statsbestmanufacturers
- [ ] statsbestproducts
- [ ] statsbestsuppliers
- [ ] statsbestvouchers
- [ ] statscarrier
- [ ] statscatalog
- [ ] statscheckup
- [ ] statsdata
- [ ] statsforecast
- [ ] statsnewsletter
- [ ] statspersonalinfos
- [ ] statsproduct
- [ ] statsregistrations
- [ ] statssales
- [ ] statssearch
- [ ] statsstock

#### Complexity
Size: XS
