### ISSUE TITLE
Add Github action to check Symfony routes and security

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31231]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing features request](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3AImprovement%2CFeature%2CDeveloper+Feature+) and found no previous suggestion of this feature.

#### Description
The legacy-link linter command gives us a list of routes that don't have the properties `legacy_controller` and  `legacy_link` configured. We must do it.

Here is an example of a route properly configured:

```yml
admin_order_invoices_process:
  path: /
  methods: [ POST ]
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Sell\Order\InvoicesController::processAction'
    _legacy_controller: AdminInvoices
    _legacy_link: AdminInvoices:update
```

With this configuration, if a module generates a link for the legacy URL like this:

```php
$link->getAdminLink('AdminInvoices', true, [], ['action' => 'update']);
````

It will properly match the Symfony route `admin_order_invoices_process` because the parameters `_legacy_controller` and `_legacy_link` are correctly configured.

Sometimes, a new URL has no legacy equivalent, in this case you can tell the linter to ignore it like it was done in [this pull request](https://github.com/PrestaShop/PrestaShop/pull/31495/files)

### how to find the legacy controller and action for a symfony route ?

There is no simple way, each time you have to check the legacy controller and explore, find what could have been the legacy action.

- [x] https://github.com/PrestaShop/PrestaShop/issues/32305
- [x] https://github.com/PrestaShop/PrestaShop/issues/32306
- [x] https://github.com/PrestaShop/PrestaShop/issues/32307
- [x] https://github.com/PrestaShop/PrestaShop/issues/32308
- [x] https://github.com/PrestaShop/PrestaShop/issues/32309
- [ ] Check attribute security
