### ISSUE TITLE
Update dependencies for PrestaShop 9.0

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#31847]
### Describe the bug and add attachments

- [x] In PrestaShop 9.0 we should upgrade to the new version of Symfony 5.4 (at least for now, we may decide to upgrade further, but this will be the first step)
- [x] We also need to get rid of SwiftMailer as it is not maintained anymore, we should remove it with the Symfony mailer component, since we need DKIM feature we need Symfony to be updated first ( https://github.com/PrestaShop/PrestaShop/issues/30556 ) 
- [x] We need to support PHP 8.2 but so far it is blocked by the deprecation notices from SwiftMailer, so the previous steps are mandatory for this one (https://github.com/PrestaShop/PrestaShop/issues/30335)
- [x] https://github.com/PrestaShop/PrestaShop/issues/31937

### PrestaShop version(s) where the bug happened

9.0

**Comment by jolelievre** [comment]
A PR to upgrade Symfony 5.4 is already in progress https://github.com/PrestaShop/PrestaShop/pull/31216

**Comment by Progi1984** [comment]
A PR to upgrade PHP 8.2 is already in progress #29116
