### ISSUE TITLE
Release 8.0.3 ✈️

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#31851]
This issue tracks the status of the PrestaShop 8.0.3 release

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        | Patch version
**Est. Build date**.                       | End of March
**Milestone**                                | [8.0.3](https://github.com/PrestaShop/PrestaShop/milestone/91)
**Kanban**                                    | [8.0.x](https://github.com/PrestaShop/PrestaShop/projects/27)
**Est. Delivery date**                   |  End of March
**Release manager tech**           |  @matthieu-rolland  
**Release manager product**     |  @RosaBenouamer 
**Release manager QA**              |  @paulnoelcholot 

# Current status

## 1. Development

- [x] Deliver https://github.com/PrestaShop/PrestaShop/issues/31627, https://github.com/PrestaShop/PrestaShop/issues/31625 and https://github.com/PrestaShop/open-source/issues/166
- [x] [Release 1.1.0 in ps_distributionapiclient](https://github.com/PrestaShop/ps_distributionapiclient/pull/23)
- [x] Include version 1.1.0 of ps_distributionclient [in composer.lock](https://github.com/PrestaShop/PrestaShop/pull/31907)
- [x] Validate https://github.com/PrestaShop/PrestaShop/pull/31902
- [x] Finalize https://github.com/PrestaShop/PrestaShop/pull/31820
- [x] https://github.com/PrestaShop/PrestaShop/issues/31945
## 2. Preparing the source code for release

- [x] Preliminary tasks (https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) 

## 3. Build process

- [x] Merge security PRs locally.
- [x] Update the Changelog and Contributors list. (https://github.com/PrestaShop/PrestaShop/pull/31930)
- [x] Build the zip archive. here is [the xml](https://drive.google.com/file/d/1-cXFRdOxFHMPayiJKoRUT8SwfwJO_G1F/view?usp=sharing) and here is [the zip](https://drive.google.com/file/d/1UFfOglT_jflX595OfIWNWHbP6ZSU4AHf/view?usp=sharing)

- [x] QA validation
  - [x] Check https://github.com/PrestaShop/PrestaShop/issues/31978
- [x] Release
  - [x] Merge security PRs on GitHub.
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.

- [x] Communicate.

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image

**Comment by matks** [comment]
### Status update 2023-03-07

8.0.3 ZIP archive was delivered by @matthieu-rolland  to QA team for validation yesterday.

Here is [the xml](https://drive.google.com/file/d/1-cXFRdOxFHMPayiJKoRUT8SwfwJO_G1F/view?usp=sharing) and here is [the archive](https://drive.google.com/file/d/1UFfOglT_jflX595OfIWNWHbP6ZSU4AHf/view?usp=sharing).

**Comment by matks** [comment]
### Status update 2023-03-31

QA team has validated the ZIP 🎉 but as it's Friday, [our rules mention](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/release-publicly/) "Make certain you have go for publish! Also, avoid starting this process after 4 PM or on a Friday."

Release will be published on Monday

**Comment by matks** [comment]
### Status update 2023-04-04

PrestaShop 8.0.3 has been released https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.3

Next steps:
- allow people to upgrade from older versions to 8.0.3
- release new docker images

**Comment by matks** [comment]
The release process has been completed by @matthieu-rolland smooth and clean 🚀 thank you!
