### ISSUE TITLE
[EPIC] [GDPR]: Technical migration of the GDPR module

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#31941]
The performance team in collaboration with the core is working on the Symphony migration of the GDPR module.

List of PR associated with this migration :

- [x] https://github.com/PrestaShop/psgdpr/pull/189
- [x] https://github.com/PrestaShop/psgdpr/pull/191
- [x] https://github.com/PrestaShop/psgdpr/pull/192
- [x] https://github.com/PrestaShop/psgdpr/pull/193
- [x] https://github.com/PrestaShop/psgdpr/pull/194
- [x] https://github.com/PrestaShop/psgdpr/pull/195
- [x] https://github.com/PrestaShop/psgdpr/pull/196
- [x] https://github.com/PrestaShop/psgdpr/pull/197
- [x] https://github.com/PrestaShop/psgdpr/pull/198
- [x] https://github.com/PrestaShop/psgdpr/pull/199
- [x] https://github.com/PrestaShop/psgdpr/pull/200
- [x] https://github.com/PrestaShop/psgdpr/pull/202
- [x] https://github.com/PrestaShop/psgdpr/pull/205

**Comment by RosaBenouamer** [comment]
The performance team in collaboration with the core is working on the Symphony migration of the GDPR module.

List of PR associated with this migration :
https://github.com/PrestaShop/psgdpr/pull/189
https://github.com/PrestaShop/psgdpr/pull/191
https://github.com/PrestaShop/psgdpr/pull/192
https://github.com/PrestaShop/psgdpr/pull/193
https://github.com/PrestaShop/psgdpr/pull/194
https://github.com/PrestaShop/psgdpr/pull/195
https://github.com/PrestaShop/psgdpr/pull/196
https://github.com/PrestaShop/psgdpr/pull/197
https://github.com/PrestaShop/psgdpr/pull/198
https://github.com/PrestaShop/psgdpr/pull/199

**Comment by matks** [comment]
Hi @RosaBenouamer as this is an international project, it would be better to write in English 😉 this allows everybody to understand the topic

**Comment by fox-john** [comment]
One another Pull request for refactor entry point of export/delete and use pattern strategy
* [ ] https://github.com/PrestaShop/psgdpr/pull/199
