### ISSUE TITLE
Release 8.0.4 👨‍🚀 

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#31979]
This issue tracks the status of the PrestaShop 8.0.4 release 

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        | Patch version
**Est. Build date**.                       |  2023-04-20
**Milestone**                                | [8.0.4](https://github.com/PrestaShop/PrestaShop/milestone/93)
**Delivery date**                   |  2023-04-25
**Release manager tech 8.0.4**           |  @FabienPapet 
**Release manager product**     |  @Zoefinders 
**Release manager QA**              |  @djoelleuch 

# Current status

## 1. Development
- [x] Finalize #31851 
- [x] #31390 
- [x] #31285 
- [x] Analyze two issues detected by automated tests:
  - [x] #32053
  - [x] #32052

## 2. Preparing the source code for release

- [x] #32031 
- [x] Preliminary tasks (https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) 

## 3. Build process

- [x] Merge security PRs locally.
- [x] Update the Changelog and Contributors list 
- [x] Build the zip archive. here is [the xml](https://drive.google.com/file/d/1ndAekQ2Wc9QxAExDl224ONhC5IDwxPIN/view?usp=sharing) and here is [the zip](https://drive.google.com/file/d/1mJBoxUp8ZCBJlZcXFOd-coLt9-bV6HI7/view?usp=sharing)
- [x] QA validation
- [x] Release
  - [x] Merge security PRs on GitHub.
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Communicate.

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image

**Comment by ghost** [comment]
Hello, small bug in the description https://github.com/PrestaShop/PrestaShop/pull/30295 -->  https://github.com/PrestaShop/PrestaShop/pull/31987

**Comment by 0x346e3730** [comment]
> Hello, small bug in the description #30295 --> #31987

I fixed it, thank you !

**Comment by matks** [comment]
### 2023-04-25 8.0.4 is released

https://build.prestashop-project.org/news/2023/prestashop-8-0-4-maintenance-release/

**Comment by matks** [comment]
Docker images are available, release process is over

https://hub.docker.com/r/prestashop/prestashop/

**Comment by matks** [comment]
Thank you @djoelleuch  @Zoefinders @FabienPapet  and @matthieu-rolland who was behind the scene
