### ISSUE TITLE
Release 1.7.8.9 🪂

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#32036]
This issue tracks the status of the PrestaShop 1.7.8.9 release 

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        | Patch version
**Est. Build date**.                       |  2023-04-20
**Milestone**                                | [1.7.8.9](https://github.com/PrestaShop/PrestaShop/milestone/94)
**Est. Delivery date**                   |  2023-04-25
**Release manager tech 8.0.4**           |  @mflasquin 
**Release manager product**     |  @Zoefinders 
**Release manager QA**              |  @HanaRebaiQA 

# Current status

## 2. Preparing the source code for release

- [x] Preliminary tasks (https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) 

## 3. Build process

- [x] Merge security PRs locally.
- [x] Update the Changelog and Contributors list 
- [x] Build the zip archive. here is [the xml](https://drive.google.com/file/d/1-cXFRdOxFHMPayiJKoRUT8SwfwJO_G1F/view?usp=sharing) and here is [the zip](https://drive.google.com/file/d/1UFfOglT_jflX595OfIWNWHbP6ZSU4AHf/view?usp=sharing)
- [x] QA validation
- [x] Release
  - [x] Merge security PRs on GitHub.
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Communicate.

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image

**Comment by ghost** [comment]
Need an update regards

**Comment by matks** [comment]
### 2023-04-25 1.7.8.9 is released

https://build.prestashop-project.org/news/2023/prestashop-1-7-8-9-maintenance-release/

**Comment by matks** [comment]
Docker images are available, release process is over

https://hub.docker.com/r/prestashop/prestashop/

**Comment by matks** [comment]
Thank you @HanaRebaiQA @Zoefinders @mflasquin and @matthieu-rolland who was behind the scene
