### ISSUE TITLE
[Epic] Symfony Layout

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#32875]
The Symfony layout was initialized in this PR https://github.com/PrestaShop/PrestaShop/pull/32235/files it is meerly a POC that initializes this new feature, from this PR a lot of work is still left to do, some components must be added, some refacto is needed. This epic lists all the tasks eft to do for this feature to be full and for the Syfony layout to replace completely the legacy one.

### Replacing legacy components
- [x] #33101 Step 1 of this epic
  - [x] #32979
  - [x] #33085
  - [x] #33086
  - [x] #32988
  - [x] #32989
  - [x] #32990
  - [x] #33102
  - [x] #33103
  - [x] #33175
  - [x] #33087
  - [x] #33088
- [x] #33101 Step 2 of this epic
  - [x] #33176
  - [x] #33177
  - [x] #33178
  - [x] #33179
  - [x] #33180
  - [x] #33181
  - [x] #33182
  - [x] #33183
  - [x] #33185
  - [x] #33186
  - [x] #33187
  - [x] #33803

### Create the Symfony/twig default layout
- [x] #33138
- [x] #33140
- [x] #33191

### Replacing layout in legacy pages
- [x] #32980
- [x] #33804
- [x] #32981
- [x] #33192

### Improvement about Context
- [x] #33193
- [x] #33194

### Small refacto less impactful or less related
- [x] In `LegacyControllerBridge` (but in many other places, legacy and modern) the base URI depends on the shop from the context `$this->legacyContext->getContext()->shop->getBaseURI()` (but not only the URI depends on the shop), this can be problematic since it means if the DB is not set, not accessible or the Shop is not defined correctly the base URI of the whole BO is not accessible, and it also can not even be deduced from a CI perspective or for CLI commands without access to the database. We should think if this could be improved, maybe base this data on a configuration but that's a very simple suggestion that needs to be thought more deeply, and we should keep in mind the multishop problematic in this reflection.

### Layout variables cleanup (probably not relevant anymore but kept here for now)
- [x] `ControllerConfiguration` will probably need to be refactored and cleaned For now, many legacy variables have been integrated for backward compatibility purposes without much reflection, but some are probably useless in a new twig theme. We should investigate which are still relevant, and which ones could be removed (keeping in mind that some modules may depend on them, any variable removed should have a legitimate alternative)
- [x] In the same spirit as the `ControllerConfiguration` that was introduced during the horizontal migration POC many variables are injected in the template's variables, some directly in `SymfonyLayoutExtension` that contains complete smart rendered templates used in the legacy layout (but maybe not useful anymore, or that could be refactored and rendered via twig components instead), and many more are built vie the Configurators that populate `ControllerConfiguration::templateVars` property, some investigation is needed about these variables to detect which were purely related to the legacy layout and can be removed, which should be replaced by more modern components/variables/alternatives, and which are really mandatory and need to be kept but maybe refactored
- [x] `SymfonyLayoutExtension` injects some blocks based on smarty, mostly modals, but it is also used to set some hard-coded smarty variables maybe it's not the right place, and maybe those modals should be removed completely. The extension should mostly be about setting global variables from the controller configuration. Although it's quite useful and easy to do it this way maybe it's not an ideal way (part of ControllerConfiguration refacto).
- [x] The `@PrestaShop/Admin/Layout/default_layout.html.twig` was mostly built based on `admin-dev/themes/new-theme/template/layout.tpl` the initial purpose is to keep the same markup as the previous to avoid unexpected side effects. But it may be interesting to refactor it later with better variables naming, maybe some pieces won't be relevant anymore. We should consider if the new variables are useful for legacy purposes (modules, overrides, ...) and if we need to keep the old names for backward compatibility. (this task is related to the first one about controller/layout variables)
- [x] Similarly in `@PrestaShop/Admin/Layout/header.html.twig` a lot of javascript variables are initialized, some of them may become useless.
- [x] The `@PrestaShop/Admin/Layout/page_header_toolbar.html.twig` can probably be optimized/simplified It seems like buttons are displayed twice for some reason

**Comment by matks** [comment]
People curious about this topic can read https://build.prestashop-project.org/news/2019/prestashop-in-2019-and-beyond-part-2-pain-points/
