### ISSUE TITLE
Release 8.1.1 🧑‍✈

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#33097]
This issue tracks the status of the PrestaShop 8.1.1 release 

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        |  Patch version
**Build date**.                       |  2023-07-20
**Milestone**                                | [8.1.1](https://github.com/PrestaShop/PrestaShop/milestone/96)
**Delivery date**                   | 2023-08-07
**Release manager tech**           |  @M0rgan01  / @mflasquin  
**Release manager product**     |  @Zoefinders 
**Release manager QA**              |  @AureRita 

RMT = Release manager tech

# Current status
- [x] Create milestone **Lead A&D**

## 1. Development - latest topics to deliver
- [x] https://github.com/PrestaShop/autoload/pull/5
- [x] https://github.com/PrestaShop/PrestaShop/issues/33021
- [x] [After disabling/enabling a tax, the linked tax rule is not present for the Ecotax#32914](https://github.com/PrestaShop/PrestaShop/issues/32914)

_Next steps mirror the release process documented [here](https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/)_.

## 2. Preparing the source code for release

- [x] Preliminary tasks (https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**

## 3. Build process
- [x] Prepare communication **OSPO representative @kpodemski**
- [x] Merge security PRs locally **RMT** (to be done with the help of @matthieu-rolland)
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive.  As this will be a security release, please do not share the ZIP here. **RMT**
- [x] QA validation **RMQ**
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub (to be done with the help of @matthieu-rolland)
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide OSPO with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **OSPO**

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image
- [x] Close milestone **Lead A&D**

**Comment by matks** [comment]
## 2023-08-07 PrestaShop 8.1.1 is published

https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.1

**Comment by venditdevs** [comment]
@matks, can you clear the cache of the updates? (or what they always do), because the new versions are not visible in the autoupgrade module.

**Comment by matks** [comment]
@venditdevs Check out section 4 of the todo-list 😉 the release is not yet available for Upgrade

## 4. After release steps
 - [x] Available for upgrade
 - [x] Docker image
 - [x] Close milestone Lead A&D

**Comment by matks** [comment]
[Release note has ben published](https://build.prestashop-project.org/news/2023/prestashop-8-1-1-maintenance-release/).
Upgrade API just got updated. When the cache is cleared, it will be available for upgrade.

**Comment by matks** [comment]
Release available for upgrade https://api.prestashop.com/xml/channel.xml

Docker images not yet available

**Comment by matks** [comment]
After fixing issue https://github.com/PrestaShop/PrestaShop/issues/33568 the docker image has been published. This release process is complete.
