### ISSUE TITLE
Release 1.7.8.10 🦋

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#33171]
This issue tracks the status of the PrestaShop 1.7.8.10 release 

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        |  Patch version
**Build date**.                       |  2023-07-19
**Milestone**                                | 1.7.8.10
**Delivery date**                   | 2023-08-07
**Release manager tech**           |  @M0rgan01  / @mflasquin  
**Release manager product**     |  @Zoefinders 
**Release manager QA**              |  @sallemiines 

RMT = Release manager tech

# Current status
- [x] Create milestone **Lead A&D**

## 2. Preparing the source code for release - [preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**

- [x] Create the new version in Addons Marketplace and update native module compatibility (Ask a maintainer from the PrestaShop Company with administrative rights on the Addons Marketplace to perform this step)
- [x] Make sure the version number has been updated to 1.7.8.10 in the Core (see [example](https://github.com/PrestaShop/PrestaShop/commit/29ce0f0fba7c58fd03097b5fc09f12f3435271b9))
- [x] ~Make sure the default translation catalogue has been updated and pushed to Crowdin~ (not eligible for patch versions)
- [x] ~Lock the theme version.~ (not eligible for 1.7.x)
- [x] Manual verifications (un-eligible steps have been filtered)
  - [x] There are no known vulnerabilities in composer dependencies
  - [x] Nightly builds are green, excluding known issues

## 3. Build process
- [x] Prepare communication **OSPO** 
- [x] Merge security PRs on a local branch **RMT** (to be done with the help of @matthieu-rolland)
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive from the local branch and deliver it to QA. As this will be a security release, please do not share the ZIP here. **RMT**
- [x] QA validation **RMQ**
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub (to be done with the help of @matthieu-rolland)
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide OSPO with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **OSPO**

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image
- [x] Close milestone **Lead A&D**

**Comment by M0rgan01** [comment]
4 dependencies are affected by vulnerabilities, but none can be fixed quickly:

- guzzlehttp/guzzle (5.3.4) -> Requires an update to 6.5.8
- symfony/symfony (v3.4.49) -> Requires an update to 4.4
- twig/twig (v1.43.1) -> Requires php 7.2.5
- phpoffice/phpspreadsheet (1.12.0) -> Our use is not related to the security breach

**Comment by M0rgan01** [comment]
PR for update version from 9 to 10: https://github.com/PrestaShop/PrestaShop/pull/33246

**Comment by M0rgan01** [comment]
Updated modules: 
- prestashop/dashtrends         v2.1.1 v2.1.2 PrestaShop module dashtrends
- prestashop/ps_imageslider   v3.1.2 v3.1.3 PrestaShop - Image slider
- prestashop/ps_themecusto   v1.2.2 v1.2.3 PrestaShop module ps_themecusto

**Comment by matks** [comment]
Release in progress https://github.com/PrestaShop/PrestaShop/pull/33556

**Comment by matks** [comment]
## 2023-08-07 PrestaShop 1.7.8.10 is published

https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.10

**Comment by matks** [comment]
[Release note has ben published](https://build.prestashop-project.org/news/2023/prestashop-1-7-8-10-maintenance-release/).
Upgrade API just got updated. When the cache is cleared, it will be available for upgrade.

**Comment by matks** [comment]
Release available for upgrade https://api.prestashop.com/xml/channel.xml

Docker images not yet available

**Comment by matks** [comment]
After fixing issue https://github.com/PrestaShop/PrestaShop/issues/33568 the docker image has been published. This release process is complete.
