### ISSUE TITLE
Release 8.0.5 🛸

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#33225]
This issue tracks the status of the PrestaShop 8.0.5 release.

# Information

Q                                                     | A
--------------------------------|---------------
**Type**                                        |  Patch version
**Build date**.                       |  2023-07-19
**Milestone**                                | [8.0.5](https://github.com/PrestaShop/PrestaShop/milestone/96)
**Delivery date**                   | 2023-08-07
**Release manager tech**           |  @M0rgan01  / @mflasquin  / @matthieu-rolland
**Release manager product**     |  @Zoefinders 
**Release manager QA**              |  @aniszr (with help from @hibatallahAouadni )

RMT = Release manager tech

# Current status
- [x] Create milestone **Lead A&D**

## 1. Development - latest topics to deliver

_Next steps mirror the release process documented [here](https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/)_.

## 2. Preparing the source code for release - [preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**

- [x] Create the new version in Addons Marketplace and update native module compatibility (Ask a maintainer from the PrestaShop Company with administrative rights on the Addons Marketplace to perform this step)
- [x] Make sure the version number has been updated to 8.0.5 in the Core
- [x] ~Make sure the default translation catalogue has been updated and pushed to Crowdin~ (not eligible for patch versions)
- [x] ~Lock the theme version.~ (not needed, already up-to-date)
- [x] Manual verifications (un-eligible steps have been filtered)
  - [x] There are no known vulnerabilities in composer dependencies
  - [x] PrestaShop composer dependencies are up-to-date in composer.lock
  - [x] Nightly builds are green, excluding known issues

## 3. Build process
- [x] Prepare communication **OSPO representative @kpodemski**
- [x] Merge security PRs locally **RMT** (to be done with the help of @matthieu-rolland)
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive.  As this will be a security release, please do not share the ZIP here. **RMT**
- [x] QA validation **RMQ**
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub (to be done with the help of @matthieu-rolland)
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide OSPO with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **OSPO**

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image
- [x] Close milestone **Lead A&D**
- [x] Create a merge PR from 8.0.x branch into 8.1.x

**Comment by matks** [comment]
Release in progress https://github.com/PrestaShop/PrestaShop/pull/33557

**Comment by matks** [comment]
## 2023-08-07 PrestaShop 8.0.5 is published

https://github.com/PrestaShop/PrestaShop/releases/tag/8.0.5

**Comment by matks** [comment]
[Release note has ben published](https://build.prestashop-project.org/news/2023/prestashop-8-0-5-maintenance-release/).
Upgrade API just got updated. When the cache is cleared, it will be available for upgrade.

**Comment by matks** [comment]
Release available for upgrade https://api.prestashop.com/xml/channel.xml

Docker images not yet available

**Comment by matks** [comment]
After fixing issue https://github.com/PrestaShop/PrestaShop/issues/33568 the docker image has been published. This release process is complete.
