### ISSUE TITLE
Release 8.1.2 🏄‍♂️ 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#33601]
This issue tracks the status of the PrestaShop 8.1.2 release 

# Information

Q                                    | A
-------------------------------------|---------------
**Type**                                                  |  Patch version
**Build 1 date**.                                      |  2023-09-22
**Build 2 date**.                                      |  2023-09-27
**Milestone**                        | [8.1.2](https://github.com/PrestaShop/PrestaShop/milestone/98)
**Freeze date**                    |  2023-09-15
**Delivery date**                    | 2020-09-28
**Release manager tech**             |  @M0rgan01 
**Release manager product**          |  @MatShir 
**Release manager QA**               |  @florine2623 

RMT = Release manager tech

# Current status
- [x] Create milestone 

## 1. Development

- [x] Regular bug fixes https://github.com/PrestaShop/PrestaShop/issues/33947
- [x] Release Upgrade fixes https://github.com/PrestaShop/autoupgrade/pull/619 in Autoupgrade module 4.16.3
- [x] Extract catalog as new wordings have been introduced in 8.1.2  - using new Crowdin API thanks to https://github.com/PrestaShop/PrestaShop/issues/33655 & https://github.com/PrestaShop/PrestaShop/pull/34007
- [x] Release Upgrade fixes https://github.com/PrestaShop/autoupgrade/pull/628 in Autoupgrade module 4.16.4

## 2. Preparing the source code for release

- [x] Preliminary tasks (https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Create the new version in Addons Marketplace and update native module compatibility
  - [x] 2. Make sure the version number has been updated in the Core
  - [x] 3. Make sure the default translation catalogue has been updated and pushed to Crowdin
  - [x] 4. Lock the theme version.
  - [x] 5. Manual verifications
## 3. Build process
- [x] Prepare communication **OSPO representative**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] **Build1** - Build the zip archive. If this is a security release, please do not share the ZIP here. **RMT**
- [x] **Build1** - QA validation **RMQ** 🚫 -> one blocker bug has been detected
- [x] Fix the [blocker bug](https://github.com/PrestaShop/PrestaShop/issues/34055)
- [x] **Build2** - Build a second ZIP archive. If this is a security release, please do not share the ZIP here. **RMT**
- [x] **Build2** - QA validation **RMQ** 
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide OSPO with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **OSPO**

## 4. After release steps

- [x] Available for upgrade
- [x] Docker image
- [x] Close milestone **Lead A&D** 

## 2023-10-28 PrestaShop 8.1.2 is published

https://build.prestashop-project.org/news/2023/prestashop-8-1-2-maintenance-release/

**Comment by nicosomb** [comment]
⚠️ https://github.com/PrestaShop/autoupgrade/pull/619#issuecomment-1702699626 cc @Hlavtox

**Comment by matks** [comment]
> PrestaShop/autoupgrade#619 (comment)

Done 👍

**Comment by Hlavtox** [comment]
@matks @MatShir Please make sure this is released in time https://github.com/PrestaShop/autoupgrade/pull/634 and the version is in the channels XML. :-) It contains some 8.1.2.sql scripts.

**Comment by MatShir** [comment]
Hi @Hlavtox, 
I haven't time to reach you. But the next autoupgrade release will be a minor that will include your fix and https://github.com/PrestaShop/PrestaShop/issues/33874. We are rationalized the releases for the next one. Sorry if my message wasn't clear on slack 🙏 
The second fix should be available next week !

**Comment by MatShir** [comment]
Hello all,
Tests functional and exploratory for the release of 8.1.2 are done.

## Build 1 test report

- [98](https://forge.prestashop.com/issues/?jql=issue%20in%20testExecutionTests(%27TEST-7489%27%2C%27PASS%27)) PASS
- [12](https://forge.prestashop.com/issues/?jql=issue%20in%20testExecutionTests(%27TEST-7489%27%2C%27FAIL%27)) FAIL

Here are the issues related to the test fails :
-> https://github.com/PrestaShop/PrestaShop/issues/34032
-> https://github.com/PrestaShop/PrestaShop/issues/34074
-> https://github.com/PrestaShop/PrestaShop/issues/34055

1 Old bug :
-> https://github.com/PrestaShop/PrestaShop/issues/32126

This PR has been merged, but is not present on 8.1.2 :
-> https://github.com/PrestaShop/PrestaShop/pull/33255 -> Bug still present 

The [only bug blocking the release](https://github.com/PrestaShop/PrestaShop/issues/34055) has been fixed  ✅  Thanks @Hlavtox 

Tests of upgrades and rollback are OK  ✅ 
8.0.5 -> 8.1.2
8.1.1 -> 8.1.2
Thanks all !

## Next step

We will now create a second build with the bugfix https://github.com/PrestaShop/PrestaShop/issues/34055 included 🚀

**Comment by matks** [comment]
## 2023-09-28 PrestaShop 8.1.2 is published

https://build.prestashop-project.org/news/2023/prestashop-8-1-2-maintenance-release/
