### ISSUE TITLE
Epic Symfony 6

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#33993]
We plan on upgrading the Symfony version to SF 6 (first 6.0 probably and then step by step, but ultimately the target would be 6.4) To anticipate the upgrade some work will have to be done in advance before we actually upgrade the dependency, this way the upgrade PR will be smaller and each step can be handled separately

Based on https://github.com/symfony/symfony/blob/6.4/UPGRADE-6.0.md we will handle removing/replacing all deprecated features from 5.4
- [x] Remove deprecated code from Asset
- [x] Remove deprecated code from DoctrineBridge
- [x] #33994
- [x] Remove deprecated code from Config
- [x] Remove deprecated code from Console
- [x] #33995
- [x] Remove deprecated code from DomCrawler
- [x] Remove deprecated code from Dotenv
- [x] Remove deprecated code from EventDispatcher
- [x] Remove deprecated code from Finder
- [x] #33996
- [x] #33997
- [x] #33998
- [x] #33999
- [x] #34000
- [x] Remove deprecated code from Ldap
- [x] Remove deprecated code from Lock
- [x] Remove deprecated code from Mailer
- [x] Remove deprecated code from Messenger
- [x] Remove deprecated code from Mime
- [x] Remove deprecated code from Monolog
- [x] Remove deprecated code from Notifier
- [x] Remove deprecated code from OptionsResolver
- [x] Remove deprecated code from PropertyAccess
- [x] Remove deprecated code from PropertyInfo
- [x] Remove deprecated code from Routing
- [x] #34001
- [x] #34003
- [x] Remove deprecated code from Serializer
- [x] #34005
- [x] Remove deprecated code from Validator
- [x] Remove deprecated code from Workflow
- [x] Remove deprecated code from Yaml

Once every deprecations have been removed we can talk the fancy stuff
- [x] #34002
- [x] #34006
- [x] #34596

Dependencies to upgrade that required Symfony 6
- [x] #34854
- [x] [Finish removing sensio framework extra bundle](https://github.com/PrestaShop/PrestaShop/issues/33769)

**Comment by lxregistry** [comment]
I think this mix of Smarty and Twig is a bad idea, I think it will be simple if you will go only with Twig ^3.7, symfony ^6.3 and maybe vue 3.3
