### ISSUE TITLE
Release 8.1.3 🌟 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34113]
This issue tracks the status of the PrestaShop 8.1.3 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch version
**Build date**.                                        |  13-12-2023
**Milestone**                                         | [8.1.3](https://github.com/PrestaShop/PrestaShop/milestone/100) 
**Freeze date**                                     |  11-12-2023
**Delivery date**                            | 02-01-2024
**Release manager tech**                    |  @boherm
**Release manager product**              |  
**Release manager QA**                      |  @AureRita 

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Amerged+is%3Apr+milestone%3A8.1.3+

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core
  - [x] 2. Publish a new version of the [branch 2.1.x of classic-theme](https://github.com/PrestaShop/classic-theme/tree/2.1.x). Then bump the version used in the Core in composer.lock .
  - [x] 3. Perform multiple manual verifications as documented in the release process
  
## 3. Build process
 - [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **This is a security release, please do not share the ZIP here. RMT**
- [x] QA validation **RMQ** 
- [x] Release new version of autoupgrade with all fixes and improvements. https://github.com/PrestaShop/autoupgrade/pull/634
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by RosaBenouamer** [comment]
Here are issues planned for release 8.1.3 subject to validation : 
- [x] https://github.com/PrestaShop/PrestaShop/issues/34229
- [x] https://github.com/PrestaShop/PrestaShop/issues/33871
- [x] https://github.com/PrestaShop/PrestaShop/issues/34358
- [x] https://github.com/PrestaShop/PrestaShop/issues/34455
- [x] https://github.com/PrestaShop/PrestaShop/issues/34518
- [ ] https://github.com/PrestaShop/autoupgrade/issues/1570

**Comment by Hlavtox** [comment]
@MatShir @RosaBenouamer Can we also prioritize this one? https://github.com/PrestaShop/PrestaShop/issues/34652

**Comment by gregoire-jianda** [comment]
@matks @RosaBenouamer This one is also quite blocking : https://github.com/PrestaShop/PrestaShop/issues/34347

**Comment by matks** [comment]
@gbelorgey Issue https://github.com/PrestaShop/PrestaShop/issues/34347 has already been fixed by PR https://github.com/PrestaShop/PrestaShop/pull/34600

It will be delivered by 8.1.3 release when it is published

**Comment by RosaBenouamer** [comment]
> @MatShir @RosaBenouamer Can we also prioritize this one? PrestaShop/PrestaShop#34652

It's ok @Hlavtox

**Comment by matks** [comment]
### Update status 13-12-2023 : build 1 delivered

Release 8.1.3 has been built by @boherm and @tleon and delivered to QA team for test.

This is a security release, consequently the ZIP is not published yet.

**Comment by ghost** [comment]
Aveugles + cons:
nous sommes en 2024??
Build date 13-12-2024
Freeze date	11-12-2024

**Comment by matks** [comment]
@ghost Such a kind way to tell me I mistakenly wrote 2024 instead of 2023! I bet in real life you must be a great man 😉 . Thank you for telling me this unforgivable mistake.

**Comment by matks** [comment]
### Update status 02-01-2024 : 8.1.3 is published

PrestaShop 8.1.3 [is published](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.3) on GitHub

**Comment by matks** [comment]
Release note has been published https://build.prestashop-project.org/news/2024/prestashop-8-1-3-maintenance-release/

**Comment by matks** [comment]
The release process is complete
