### ISSUE TITLE
Bot reunification

### ISSUE THREAD

**Issue by RosaBenouamer** [PrestaShop/PrestaShop#34126]
The size of the QA is really reduced. So we have to work on the bot to optimise them and improve the automatic management of the work of the QA.

To do that we would like to improve the bots and for that migrate all the bot into one.
We need first to make some retro engineering on each bot. Then work on the reunification of each one.
- [x] Retro eng : How prestonbot works in detail :  https://github.com/PrestaShop/PrestaShop/issues/34129
- [x] Retro eng : How kanbanbot  works in detail : https://github.com/PrestaShop/PrestaShop/issues/34130
- [x] Retro eng : How issuebot works in detail : https://github.com/PrestaShop/PrestaShop/issues/34131
- [ ] Bot reunification : https://github.com/PrestaShop/PrestaShop/issues/34132
- [ ] Bot reunification - PrestonBot : https://github.com/PrestaShop/PrestaShop/issues/34156

 

__
- [ ] Kanbot is buggy ? 
No QA after 10 minutes https://github.com/PrestaShop/PrestaShop/pull/34078#event-10510259448

**Comment by boherm** [comment]
@RosaBenouamer, maybe we must create an issue aim to log all failed calls to the GitHub API, and retry them few minutes later. This could be avoid this kind of problem: No QA after 10 minutes https://github.com/PrestaShop/PrestaShop/pull/34078#event-10510259448

**Comment by boherm** [comment]
To work on retro-engineering and to prepare reunification of bots, I made a Google Sheet to list all features for all bots !
https://docs.google.com/spreadsheets/d/165vzK3-M1U2vzZVfEzuRk1atlpDGjx59WK0b7Lh36yc/edit?usp=sharing

**Comment by boo-code** [comment]
Four of the five items here are closed, and the repositories show why: `PrestaShop/prestonbot` is archived with its last push on 2024-06-07, `PrestaShop/kanbanbot` is still active with a push on 2026-08-25, and `PrestaShop/issuebot` has not been touched since 2023-12-16.

So the reunification happened in the direction described, around KanbanBot. Only #34132 is still open, and I have put the same figures there.
