### ISSUE TITLE
Adapting software & doc for change #34184 "Forbidden sensitive files extensions on modules directory"

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#34578]
Following change https://github.com/PrestaShop/PrestaShop/pull/34184 multiple changes need to be done for 9.0.0

1. Make the change crystal clear in the documentation "Notable changes in 9.0.0" to inform PrestaShop users broadly

2. Update the project modules that do not comply to this rule
- [x] ps_imageslider module has a file ajax_ps_imageslider.php https://github.com/PrestaShop/ps_imageslider/pull/96 + https://github.com/PrestaShop/ps_imageslider/pull/107
- [x] ps_wirepayment module has a file payment.php and validation.php https://github.com/PrestaShop/ps_wirepayment/pull/84 + https://github.com/PrestaShop/ps_wirepayment/pull/85
- [x] ps_facetedsearch module has 3 files ps_facetedsearch-attribute-indexer.php, ps_facetedsearch-clear-cache.php and ps_facetedsearch-price-indexer.php https://github.com/PrestaShop/ps_facetedsearch/pull/983 + https://github.com/PrestaShop/ps_facetedsearch/pull/981
- [x] gsitemap module has a file gsitemap-cron.php https://github.com/PrestaShop/gsitemap/pull/175/ + https://github.com/PrestaShop/gsitemap/pull/176
- [x] ps_checkpayment module has a file payment.php https://github.com/PrestaShop/ps_checkpayment/pull/64 + https://github.com/PrestaShop/ps_checkpayment/pull/65
- [x] ps_emailsubscription has a file verification.php https://github.com/PrestaShop/ps_emailsubscription/pull/100 + https://github.com/PrestaShop/ps_emailsubscription/pull/101

**Comment by matks** [comment]
First PR https://github.com/PrestaShop/ps_checkpayment/pull/64

**Comment by matks** [comment]
Second PR https://github.com/PrestaShop/ps_imageslider/pull/96

**Comment by Hlavtox** [comment]
Ping @clotairer @jf-viguier, friendly notice ;-)

**Comment by matks** [comment]
All items done

**Comment by touchweb-vincent** [comment]
\o/
