### ISSUE TITLE
Release 1.7.8.11 🎅 

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#34804]
This issue tracks the status of the PrestaShop 1.7.8.11 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch version
**Build date**.                                        |  13-12-2023
**Milestone**                                         | [1.7.8.11](https://github.com/PrestaShop/PrestaShop/milestone/99)
**Freeze date**                                     |  11-12-2023
**Delivery date**                                  | 02-01-2024
**Release manager tech**                    |  @tleon / @boherm 
**Release manager product**              |  
**Release manager QA**                      |  @AureRita 

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core (done by https://github.com/PrestaShop/PrestaShop/pull/34810)
  - [x] 2. Perform multiple manual verifications as documented in the release process
  
## 3. Build process
- [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **This is a security release, please do not share the ZIP here. RMT**
- [x] QA validation **RMQ** 
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
### Update status 13-12-2023 : build 1 delivered

Release 1.7.8.11 has been built by @boherm and @tleon and delivered to QA team for test.

This is a security release, consequently the ZIP is not published yet.

**Comment by ghost** [comment]
Aveugles + cons:
nous sommes en 2024??
Build date 13-12-2024
Freeze date	11-12-2024

**Comment by matks** [comment]
@ghost Such a kind way to tell me I mistakenly wrote 2024 instead of 2023! I bet in real life you must be a great man 😉 . Thank you for telling me this unforgivable mistake.

**Comment by matks** [comment]
### Update status 02-01-2024 : 1.7.8.11 is published

PrestaShop 1.7.8.11 [is published](https://github.com/PrestaShop/PrestaShop/releases/tag/1.7.8.11) on GitHub

@ghost we're in 2024 now 😛

**Comment by matks** [comment]
Release not has been published https://build.prestashop-project.org/news/2024/prestashop-1-7-8-11-maintenance-release/

**Comment by matks** [comment]
The release process is complete
