### ISSUE TITLE
[EPIC] Impact of Multi-language

### ISSUE THREAD

**Issue by MatShir** [PrestaShop/PrestaShop#34848]
Study the impact of Multi-languages for the API 

## Steps

Objectives: Test & understand how the multilanguage behave for Patch and the listing method on the API with the different CQRS command: 

V.1

- [x] #34849
  - Based on the solution, specify in the API contract whether the API can fully utilize the Patch method or not. 
  - [x] [Update the ADR](https://github.com/orgs/PrestaShop/projects/7/views/81?pane=issue&itemId=47602319)

- [x] #34850
 - 1. Only one language in parameter and one language displayed, fallback default language
 - 2. As many language parameters and by default all the language are displayed

NTH
- [ ] List all the CQRS method that don't have partial updates
  - If there are just a few, we could consider adapting them for the partial method
- [ ] The listing of language would be required if we want the dev to use the multilanguage to map the language ID with their use case.
