### ISSUE TITLE
EPIC - CLI : ps-upgrade:download  - implement download

### ISSUE THREAD

**Issue by fabienvallon** [PrestaShop/PrestaShop#35098]
As a user I want to download a new package of PrestaShop so I can install it now or later 
As a user I want to verify the integrity of PrestaShop so I can be sure that my package (and xml file)  is safe

## Description 

TBD : filesystem ' WHERE SHOULD I Download my packages " 

`ps-upgrade:download <package name>`

This command 
1. Donwload through distrib API the package named \<package name\>.zip
2. Download through distrib API the xml file name \<package name\>.xml  
3. Download through distrib API the xml file name \<package name\>.dbstruct ?  
4. Verify integrity of this 3 files through distrib API 

#### Global options 

See [Global Command options](https://symfony.com/doc/current/console/input.html#command-global-options) for Symfony commands

#### Help 

_ps-upgrade:download : download a PrestaShop package
Usage: ps:upgrade:download   \<package\> or \<version number\>
With \<package\> as package name (such as prestashop-8.1.3 ) and \<version number\> the prestashop version (such as 8.1.3) 
--verbose: sets the verbosity level (e.g. 1 the default, 2 and 3, or you can use respective shortcuts -v, -vv and -vvv)
--quiet: disables output and interaction
--no-interaction: disables interaction
--version: outputs the version number of the console application
--help: displays the command help
--ansi|--no-ansi: whether to force of disable coloring the output_ 

#### Usage 

`ps-upgrade:download <package name>`

#### Step 1 : Download 

For each \<file\> ( \<package_name\>.zip , \<package_name\>.xml, \<package_name\>.dbstuct )  
Message : _Downloading \<file\>_

(TODO progress bar ou pas ? ) 

if OK :     
Message :   _\<file\> donwloaded into \<Downloaded_Repository\>_
and go to the  next \<file\> or to the next step ( verify package integrity ) if all files have been downloaded 

if KO 
Message :  _KO: \<file\> donwloaded  failed : use -vv for more information_ ( est ce que je met plujs d'info ici ? ) 
TODO voir si un fail , est-ce que l'on test les autres ou on exit ? 

#### Step 2 : Perform chek through disrib API Endpoint

For each \<file\> ( \<package_name\>.zip , \<package_name\>.xml, \<package_name\>.dbstuct )  
_Verify \<file\> integrity...\<STATUS\>_

If KO ( end point check ) 
\<STATUS\>  = _Integrity verification failed + err Message (see TS) _  ( for errors Messages (see TS) ) 

If KO (md5sum \<file\> != md5sum provide by the endpoints ) 
\<STATUS\>  = _Bad integrity (message pourri) _

TODO voir si un fail , est-ce que l'on test les autres ou on exit ? 
  
### Acceptances tests

- Set up a distrib server with prestashop-8.1.3 & prestashop-9.0.0 & news versions of PrestaShop and a current version prestashop-8.1.2

#### Acceptance test : Help 

_$ps-upgrade:download --help 
ps-upgrade:download : download a PrestaShop package
Usage: ps:upgrade:download   \<package\> or \<version number\>
With \<package\> as package name (such as prestashop-8.1.3 ) and \<version number\> the prestashop version (such as 8.1.3) 
--verbose: sets the verbosity level (e.g. 1 the default, 2 and 3, or you can use respective shortcuts -v, -vv and -vvv)
--quiet: disables output and interaction
--no-interaction: disables interaction
--version: outputs the version number of the console application
--help: displays the command help
--ansi|--no-ansi: whether to force of disable coloring the output_ 

#### Acceptance test : Global options

See also  See [Global Command options](https://symfony.com/doc/current/console/input.html#command-global-options) for Symfony commands
and 

#### Acceptance test 1 : OK 

Run ( example , see above )  

```
$ ps-upgrade:download  prestashop-8.1.3
Downloading prestashop-8.1.3.zip ...OK 
Downloading prestashop-8.1.3.xml ...OK
Downloading prestashop-8.1.3.dbstruct ...OK
Verify integrity prestashop-8.1.3.zip ...OK 
Verify integrity prestashop-8.1.3.xml ...OK
Verify integrity prestashop-8.1.3.dbstruct ...OK
```

#### Acceptance test 2 : KO - wrong package name

```
$ ps-upgrade:download  prestashop-42.1.1
Prestashop-42.1.1 does not exist - wrong package name 
```

#### Acceptance test 3 : KO - network local

 ```
$ ps-upgrade:download  prestashop-8.1.3
Could not download prestashop-8.1.3 : Check your network
```

#### Acceptance test 4 : KO - Problem with distrib API

 ```
$ ps-upgrade:download  prestashop-8.1.3
Could not download : <ERROR> 
```

See \<ERROR\> with dev afterward and write new ACs

#### Acceptance test 5 : KO - wrong integrity package.zip

- Set up a distrib server with prestashop-8.1.3 & prestashop-9.0.0 & news versions of PrestaShop and a current version prestashop-8.1.2
- Modify prestashop-8.1.3.zip ( fort example `echo "Moo" >> prestashop-8.1.3.zip` into the server

```
$ ps-upgrade:download  prestashop-8.1.3
Downloading prestashop-8.1.3.zip ...OK 
Downloading prestashop-8.1.3.xml ...OK
Downloading prestashop-8.1.3.dbstruct ...OK
Verify integrity prestashop-8.1.3.zip ...KO Bad integrity 
Verify integrity prestashop-8.1.3.xml ...OK
Verify integrity prestashop-8.1.3.dbstruct ...OK
 
```

Do the same for restashop-8.1.3.xml  / prestashop-8.1.3.dbstruct  ( should I write new ACs ? @florine2623 )

### Technical specs

- [ ] CU: Create DBStructureGenerator service to create db struct xml files.
- [x] #35100
- [ ] DistributionApi: Add md5 checksums for archive, files checksum xml and db struct xml. (and add DB struct too 😇)
- [x] #35099
- [ ] CU: Check integrity with `ChecksumComparator` service.
- [x] #35101

**Comment by Hlavtox** [comment]
@Quetzacoalt91 @M0rgan01 Guys, can I close this and all of the issues marked Stale?

**Comment by Quetzacoalt91** [comment]
Thanks for the ping Daniel, I went on the tickets and closed them myself. At the moment a similar feature exists on Update Assistant and anything else is not planned anymore.

**Comment by M0rgan01** [comment]
If we dig a little deeper, there will be traces of ps_doctor CLI 💯

**Comment by M0rgan01** [comment]
Hoho https://github.com/PrestaShop/PrestaShop/issues/35084
