### ISSUE TITLE
Release 8.1.5 🏎️

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/PrestaShop#35216]
This issue tracks the status of the PrestaShop 8.1.5 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch version
**Build date**                                        |  March 08
**Milestone**                                         | [8.1.5](https://github.com/PrestaShop/PrestaShop/milestone/101) 
**Freeze date**                                     | February 27
**Delivery date**                                  | March 19
**Release manager tech**                    |  @matthieu-rolland 
**Release manager product**              |  @MatShir 
**Release manager QA**                      |  @paulnoelcholot 

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A8.1.5

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core - https://github.com/PrestaShop/PrestaShop/pull/35422
  - [x] 2. Publish a new version of the [branch 2.1.x of classic-theme](https://github.com/PrestaShop/classic-theme/tree/2.1.x).   
  - [x] 3. Then bump the version used in the Core in composer.lock. https://github.com/PrestaShop/PrestaShop/pull/35483
  - [x] 4. Update wording catalog in the core https://github.com/PrestaShop/PrestaShop/pull/35534
  - [x] 5. Do a Crowdin push.
  - [x] 6. Perform multiple manual verifications as documented in the release process
  
## 3. Build process
 - [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Release new version of autoupgrade with all fixes and improvements. - https://github.com/PrestaShop/autoupgrade/pull/668
- [x] Update channel.xml with new version of autoupgrade module.
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
Some news about this release:
- the work to build 8.1.5 was started 2 weeks ago, after autoupgrade 5.0.1 was released
- problems were encountered with translations
- solved last week, PR https://github.com/PrestaShop/PrestaShop/pull/35579 is the final fix for this topic
- the release has been validated by QA team

The version 8.1.5 will be published next week

**Comment by matks** [comment]
PrestaShop 8.1.5 has been [published](https://build.prestashop-project.org/news/2024/prestashop-8-1-5-maintenance-release/)
- [available for upgrade](https://api.prestashop.com/xml/channel.xml)
- available on [GitHub](https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.5)
- available on [Docker](https://hub.docker.com/r/prestashop/prestashop/)
