### ISSUE TITLE
Release 8.1.4

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#35412]
This issue tracks the status of the PrestaShop 8.1.4 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Security patch version
**Build date**                                        |  2024-02-12
**Milestone**                                         | 8.1.4
**Delivery date**                                  | 2024-02-19
**Release manager tech**                    |  @matks 
**Release manager product**              |  
**Release manager QA**                      |  

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status

## 1. Development

This is a security-only release: it only contains the version number change, the changelog and the security patch.

## 2. Preparing the source code for release

This is a security-only release: it only contains the version number change, the changelog and the security patch. So no source code preparation was needed.
  
## 3. Build process
 - [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
### Available for Upgrade

https://api.prestashop.com/xml/channel.xml

**Comment by matks** [comment]
Release process is complete
