### ISSUE TITLE
Release 9.0.0 Alpha 🧪

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#35800]
This issue tracks the status of the PrestaShop 9.0.0 Alpha release

### Information

Q                                     | A
-----------------------|--------
**Type**                        | Major version / Alpha step
**Milestone**                | [9.0.0](https://github.com/PrestaShop/PrestaShop/milestone/85)
**Publish date**         |  [06-06-2024](https://build.prestashop-project.org/news/2024/prestashop-9-alpha1-available/)

_What is an Alpha release ? 
An alpha release is an under-development version of software that is ready for initial testing by a small group of users._

### Release steps

- [x] Specification
- [x] Feature development
- [x] Green nightly (no further manual tests) (https://nightly.prestashop-project.org/)

**1. Preleminary tasks**
- [x] Update the version number in the Core.
- [x] Release classic Theme (to check with team cc @jolelievre )  
- [x] Perform manual verifications (more infos here https://www.prestashop-project.org/maintainers-guide/processes/release/prestashop/preliminary-tasks/) 

**2. Create the build**
- [x] Update the Changelog and Contributors list.
- [x] Push your work into a build branch.
- [x] Build and store the zip archive.

**3. Release publicly**
- [x] Merge the updated Changelog and Contributors list on GitHub.
- [x] Tag the version using Git and publish the release on GitHub (specific tag for V9 alpha)
- [x] Communicate

**4. Final steps**
- [x] Check that the release note has been published on the [Build Blog](https://build.prestashop-project.org/)

**Comment by matks** [comment]
Linked to https://github.com/PrestaShop/PrestaShop/issues/31144

**Comment by matks** [comment]
- release note https://build.prestashop-project.org/news/2024/prestashop-9-alpha1-available/
- git tag https://github.com/PrestaShop/PrestaShop/releases/tag/9.0.0-alpha.1
