### ISSUE TITLE
Release 8.1.6 🌊 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#35992]
This issue tracks the status of the PrestaShop 8.1.6 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch security version
**Build date**                                        |  2024-05-13
**Milestone**                                         | [8.1.6](https://github.com/PrestaShop/PrestaShop/milestone/104) 
**Delivery date**                                  |  2024-05-14
**Release manager tech**                    |  @matthieu-rolland 

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A8.1.6

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  
## 3. Build process
- [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Merge security PRs locally if there are some **RMT**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Update channel.xml with new version of autoupgrade module.
- [x] Release **RMT**
  - [x] Merge security PRs on GitHub if there are some
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
Release in progress https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.6

**Comment by matks** [comment]
Release is finished https://build.prestashop-project.org/news/2024/prestashop-8-1-6-maintenance-release/
