### ISSUE TITLE
Integrate an alpha release of the theme in the project

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/PrestaShop#36182]
This is the step to integrate an alpha version in the core, the theme will be accessible but not used as the default one

- [x] Release the theme with the latest changes into a 0.2.0 version (see this PR https://github.com/PrestaShop/hummingbird/pull/600 - the version needs to be bumped to 0.2.0)
- [ ] Prepare a page in devdocs that explains the technical constraints for this theme (can be empty at first but we need the URL for the following task) The page can later be enriched -> moved to https://github.com/PrestaShop/PrestaShop/issues/36145
  - [ ] Explain that the theme is based on bootstrap5 and won't be compatible with all modules until they handle the theme -> moved to https://github.com/PrestaShop/PrestaShop/issues/36145
  - [ ] Explain the trick about integrating the Bootstrap Compatibility Layer -> moved to https://github.com/PrestaShop/PrestaShop/issues/36145
- [ ] Integrate hummingbird 0.2.0 into composer, adapt UI tests that don't need to install the theme anymore, integrate a warning popup when the theme is enabled to warn about bootstrap with a link to devdoc for more details (also see this issue https://github.com/PrestaShop/hummingbird/issues/581) -> moved to https://github.com/PrestaShop/PrestaShop/issues/36145

**Comment by Hlavtox** [comment]
A big issue is this that classic is hardcoded in several places in the code, including the translation system - https://github.com/PrestaShop/PrestaShop/issues/35299

**Comment by matks** [comment]
I move remaining items to https://github.com/PrestaShop/PrestaShop/issues/36145 to avoid having 2 issues opened
