### ISSUE TITLE
Release 8.1.7 🌳 

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36337]
This issue tracks the status of the PrestaShop 8.1.7 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch version
**Build date**                                        |  14-06-2024
**Milestone**                                         | [8.1.7](https://github.com/PrestaShop/PrestaShop/milestone/105) 
**Delivery date**                                  |  24-06-2024
**Release manager tech**                    |  @jolelievre 
**Release manager product**              |  
**Release manager QA**                      |  

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A8.1.7

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core https://github.com/PrestaShop/PrestaShop/pull/36338
  - [x] ~2. Publish a new version of the classic-theme if needed~
  - [x] ~3. Then bump the version used in the Core in composer.lock.~
  - [x] 4. Update wording catalog in the core if needed https://github.com/PrestaShop/PrestaShop/pull/36340
  - [x] 5. Do a Crowdin push.
  - [x] 6. Perform multiple manual verifications as documented in the release process https://github.com/PrestaShop/PrestaShop/pull/36341
  
## 3. Build process
- [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Release new version of autoupgrade if needed. See below
- [x] Update channel.xml with new version of autoupgrade module.
- [x] Release **RMT**
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
Regarding Autoupgrade:

v5.0.2 contains the [SQL changes](https://github.com/PrestaShop/autoupgrade/tree/v5.0.2/upgrade/sql) for 8.1.7 so a v5.0.3 should NOT be necessary I think... to be verified

**Comment by paulc010** [comment]
v5.0.3 is required to fix #36317 otherwise out of the box the upgrade would fail (without the workaround outlined in the issue thread).

**Comment by matks** [comment]
v5.0.3 has been [published](https://github.com/PrestaShop/autoupgrade/releases/tag/v5.0.3) 😉 

On the core release side, the build has been delivered to QA team for testing

**Comment by matks** [comment]
## 24-06-2024 8.1.7 is being released

As you can see from https://github.com/PrestaShop/PrestaShop/releases/tag/8.1.7 the release is published

We are encountering trouble regarding the last items (docker images, update API...) but the release itself is complete

**Comment by jolelievre** [comment]
We're all good Docker images have been pushed to docker HUB and the Upgrade API is up to date
Nice job everyone 🎉

**Comment by matks** [comment]
## 25-06-2024 8.1.7 Release notes [have been published](https://build.prestashop-project.org/news/2024/prestashop-8-1-7-maintenance-release/)
