### ISSUE TITLE
New Branding For The Project

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36615]
Following this [blog post](https://build.prestashop-project.org/news/2023/new-project-branding/), the prestashop project moves on.

This change will be implemented by 3 PRs:
1. https://github.com/PrestaShop/prestashop-ui-kit/pull/229
2. https://github.com/PrestaShop/PrestaShop/pull/36584
3. https://github.com/PrestaShop/PrestaShop/pull/36585

The first PR aims to modify the PrestaShop UI Kit to fit with the new branding. Following its merge, we should publish a new release v2.0.0 of the UI Kit. A branch `1.x` can be kept on the UI Kit repository to be used if there must be changes / fixes for PrestaShop 8.x . It will affect the pages of the backoffice migrated to Symfony.

The second PR aims to modify the pages of the backoffice which are still using the legacy system.

The third PR aims to modify the Unzip wizard.

TODO
- [x] Rebrand the UI Kit -> achieved by https://github.com/PrestaShop/prestashop-ui-kit/pull/229
- [x] Publish a new version v2.0.0 of the UI Kit and use it in the Core `develop` branch
- [x] Rebrand the backoffice legacy pages -> achieved by https://github.com/PrestaShop/PrestaShop/pull/36584
- [x] Rebrand the Unzip wizard -> achieved by https://github.com/PrestaShop/PrestaShop/pull/36585
- [x] https://github.com/PrestaShop/PrestaShop/issues/36710
- [x] https://github.com/PrestaShop/PrestaShop/issues/36711
- [x] https://github.com/PrestaShop/PrestaShop/issues/36599

**Comment by kpodemski** [comment]
@tblivet @jolelievre 

After merging the new branding there is no indication when the shop is in the maintenance mode. I think this should definitely be addressed.

**Comment by tblivet** [comment]
Hi @kpodemski @jolelievre, I have created an issue for this : https://github.com/PrestaShop/PrestaShop/issues/36599

**Comment by kpodemski** [comment]
@tblivet ahhh, great! thanks. Could you also check if, on your installation, it is possible to toggle the menu sidebar on the Dashboard page? because on my instance it is not possible to do that, it works on the migrated pages and some of the legacy ones tho

**Comment by tblivet** [comment]
@kpodemski, it looks good to me 👍

https://github.com/user-attachments/assets/2300053e-6e73-4143-81d8-f993a4a8eb19
