### ISSUE TITLE
[EPIC] Refactor all controllers not using PrestaShopAdminController

### ISSUE THREAD

**Issue by ibahloul-ps** [PrestaShop/PrestaShop#36793]
# Context
According to [this topic](https://devdocs.prestashop-project.org/9/modules/core-updates/9.0/#symfony-controllers), we must update all controllers that are still wrongly relying on this deprecated method.
Example : [BlockWhislist Controller](https://github.com/PrestaShop/ps_linklist/pull/202/files#diff-97b9d5fc66f96c41ea20764c2bcd5da9bd22440d53adc801b48b2a283cd94450)

# Related Controllers
### Order #36799
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Order/CreditSlipController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Order/OrderController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Order/InvoicesController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Order/CartController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Order/DeliveryController
> [!NOTE]  
> All of the above will be done in one issue.
### Catalog #36826
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CatalogPriceRuleController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/StockController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/ManufacturerController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CartRuleController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttachmentController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/CategoryController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/MonitoringController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/SupplierController
- Product
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ImageController
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/ProductController
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/CombinationController
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/Product/SpecificPriceController
- Attribute
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeController
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/AttributeGroupController
- Feature
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureController
  - [x] src/PrestaShopBundle/Controller/Admin/Sell/Catalog/FeatureValueController
### Customer Service #36811
- [x] src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/MerchandiseReturnController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/OrderMessageController
- [x] src/PrestaShopBundle/Controller/Admin/Sell/CustomerService/CustomerThreadController
### Address #36820
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Address/AddressController
### Customer #36821
- [x] src/PrestaShopBundle/Controller/Admin/Sell/Customer/OutstandingController
### Advanced Parameters #37157
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PermissionController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SqlManagerController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SecurityController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportDataConfigurationController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/SystemInformationController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/PerformanceController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ImportController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ShopController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/ProfileController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/LogsController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/WebserviceController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdministrationController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmployeeController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/BackupController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/EmailController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/FeatureFlagController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/MemcacheServerController
- [x] src/PrestaShopBundle/Controller/Admin/Configure/AdvancedParameters/AdminAPIController
### Shop Parameters
- [x] #37010
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MetaController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/SearchController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderStateController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/CustomerPreferencesController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/TitleController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/StoreController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ContactsController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/OrderPreferencesController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/CustomerGroupsController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/MaintenanceController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/SearchEnginesController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/PreferencesController
  - [x] src/PrestaShopBundle/Controller/Admin/Configure/ShopParameters/ProductPreferencesController

### Design #37082
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Design/PositionsController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Design/ImageSettingsController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Design/CmsPageController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Design/MailThemeController
### Payment #37082
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentPreferencesController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Payment/PaymentMethodsController
### Shipping #37082
- [x] src/PrestaShopBundle/Controller/Admin/Improve/Shipping/PreferencesController
### Modules
- [x] #36843
### International #37136
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/CurrencyController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/TaxRulesGroupController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/StateController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/LocalizationController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/TaxController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/GeolocationController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/LanguageController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/TranslationsController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/CountryController
- [x] src/PrestaShopBundle/Controller/Admin/Improve/International/ZoneController
## Showcase Card
- [x] #37272
## Multistore
- [x] #37017
## Common
- [x] #37273
## Tests
- [x] tests/Resources/modules/demo/src/Controller/Admin/DemoController #37278
- [x] tests/Resources/modules/xlftranslatedmodule/src/Controller/Admin/ExempleController #37278
- [x] tests/Resources/modules/translationtest/src/Controller/Admin/ExempleController #37278

**Comment by jolelievre** [comment]
Everything is done great work @PrestaShop/prestashop-core-developers 🎉🎉🎉
