### ISSUE TITLE
Release 8.2.1 ❄️

### ISSUE THREAD

**Issue by WahbiPS** [PrestaShop/PrestaShop#37616]
This issue tracks the status of the PrestaShop 8.2.1 release 

# Information

Q                                                              | A
--------------------------------------|---------------
**Type**                                                  |  Patch version
**Build date**                                        |  10/02/2025
**Milestone**                                         | [8.2.1](https://github.com/PrestaShop/PrestaShop/milestone/107) 
**Delivery date**                                  |  21/02/2025
**Release manager tech**                    |  @mattgoud  
**Release manager product**              |  @ibahloul-ps 
**Release manager QA**                      |  

_Nota Bene: the release date may vary, if major bugs are identified during the test phase_

RMT = Release manager tech
RMQ = Release manager QA

# Current status
- [x] Create milestone 

## 1. Development

See below https://github.com/PrestaShop/PrestaShop/milestone/107

## 2. Preparing the source code for release

- [x] [Preliminary tasks](https://www.prestashop-project.org/maintainers-guide/releasing-prestashop/preliminary-tasks/) **RMT**
  - [x] 1. Make sure the version number has been updated in the Core
  - [x] 2. Publish a new version of the classic-theme if needed
  - [x] 3. Then bump the version used in the Core in composer.lock.
  - [x] 4. Update wording catalog in the core if needed - **⚠ this step was skipped**
  - [x] 5. Do a Crowdin push. - **⚠ this step was skipped**
  - [x] 6. Perform multiple manual verifications as documented in the release process
  
## 3. Build process
- [x] Create the new version in Addons Marketplace and update native module compatibility
- [x] Prepare communication **Communicator**
- [x] Update the Changelog and Contributors list **RMT**
- [x] Build the zip archive. **RMT**
- [x] QA validation **RMQ** 
- [x] Release new version of autoupgrade if needed. See below
- [x] Update channel.xml with new version of autoupgrade module. **⚠ this step was skipped**
- [x] Release **RMT**
  - [x] Merge the updated Changelog and Contributors list on GitHub.
  - [x] Tag the version using Git and publish the release on GitHub.
- [x] Provide Communicator with up to date informations (contributors list, changelog...) **RMT**
- [x] Communicate 
   - [x] Release note **Communicator**

## 4. After release steps
- [x] Make new version available for upgrade
- [x] Publish Docker image
- [x] Close milestone

**Comment by matks** [comment]
https://build.prestashop-project.org/news/2025/prestashop-8-2-1-maintenance-release/
