### ISSUE TITLE
[EPIC] - Multistore - All bugs & improvements

### ISSUE THREAD

**Issue by prestonBot** [PrestaShop/PrestaShop#9723]
## Product page BO

**BUGS**
- [x] #32864  
- [x] #9612 
- [x] #9613
- [x] #9576
- [x] #10137
- [x] #15383
- [x] #12244 
- [x] #9686
- [x] #27063 
- [x] #9710
- [ ] #27148
- [x] #27377
- [x] #27558
- [ ] #28697
- [ ] #28779
- [x] #24587
- [x] #29159
- [ ] #29309
- [x] #29581
- [x] #29763 
- [x] #29780
- [x] #31797

**RESTORE 1.6 ALERT MESSAGE IN A PARTICULAR SHOP CONTEXT**
- [ ] #9664 - Can’t create combinations on the second shop if multistore enabled (it was possible in 1.6) TOPWATCHERS
- [ ] #10032 - Reference of a combination is changed for all shops even when I select a particular shop: same issue in 1.6
- [ ] #12638 - Images of a combination is changed for all shops even when I select a particular shop: same issue in 1.6

![capture d'écran_1972](https://user-images.githubusercontent.com/13449658/64769207-2914c000-d54b-11e9-945a-7d751a7a4179.png)

**RESTORE 1.6 CHECKBOXES IN ALL SHOPS CONTEXT**
- [ ] #9833 - Add checkbox to choose the elements to change when you are in all shops context
- [ ] #18558 - Add checkboxes for categories
- [ ] #9940 - You shouldn’t be able to edit product quantities if:
- you are in all shops context, 
- you are in a group of shops context where quantities are not shared, 
- you are in a shop context that is in a group where quantities are shared between every shop in this group
- [ ] #10274 - Can’t change quantity of a product in all shop context if the group share quantities TOPWATCHERS

![capture d'écran_1973](https://user-images.githubusercontent.com/13449658/64769513-b8ba6e80-d54b-11e9-8d24-6785ec3f1739.png)

**IMPROVEMENT**
- [x] #12424
- [x] #16790

## Shop creation & edition
- [x] #9873 
- [ ] #11477

## Back-office
- [ ] #16753
- [x] #14375
- [x] #12179 
- [x] #10383 
- [ ] #9858
- [ ] #9843 
- [x] #21180 
- [ ] #11538
- [x] #19056
- [ ] #13210 
- [x] #9837 
- [x] #9657
- [x] #9844 
- [x] #12390 
- [x] #10943 
- [x] #13519
- [ ] #9851
- [x] #17165
- [ ] #20300
- [ ] #21318
- [x] #21482  
- [x] #22402
- [ ] #23192
- [x] #12611 
- [x] #24303 
- [x] #24815
- [x] #26014
- [x] #26385
- [x] #26582
- [x] #26859
- [x] #29075
- [x] #29354
- [x] #29458
- [x] #29631

### Order page
- [x] #9609
- [ ] #21905
- [x] #23823

## Front-office
- [x] #9569
- [x] #9573
- [x] #9568
- [ ] #21714 
- [x] #12732 
- [x] #9865 
- [x] #9772 
- [x] #16803
- [ ] #17621
- [x] #29538

## Permissions 
- [ ] #13172
- [ ] #13468 

## Modules
- [x] #9710 - Imageslider 
- [ ] https://github.com/PrestaShop/psgdpr/issues/50 GDPR 
- [ ] #12450 - Legalcompliance
- [ ] #9900 - Legalcompliance
- [ ] #19933 - Productcomments

## Webservices
- [x] #9820
- [x] #13987

## To be specified
- [x] #25478
- [ ] #19924
- [ ] #9859
- [ ] #9857
- [ ] #18833
- [x] #10383
- [x] #9861
- [ ] #16804
- [ ] #9821
- [ ] #15158
- [ ] #14357
- [x] #10942
- [ ] #19686

## Migration Features & Improvements
- [x] #19367
- [x] #19369
- [x] #19377
- [x] #19378
- [x] #19330
- [x] #19412
- [x] #19415
- [x] #19418
- [x] #19419

-------

## Product page BO

**BUGS**
- [x] #12061
- [x] #9720 
- [x] #12832 
- [x] #18919
- [x] #19999
- [x] #26979
- [x] #27540

## Migration regression
- [x] #14731
- [x] #12540 

## Shop creation & edition
- [x] #9701

## Back-office
- [x] #9848
- [x] #15367
- [x] #26581
- [x] #21741 
- [x] #21742
- [x] #21516
- [x] #18340
- [x] #14366 
- [x] #9742 
- [x] #18838
- [x] #9862
- [x] #21730
- [x] #23753
- [x] #28148

### Order page
- [x] #21817
- [x]  #21987
- [x] #22110 
- [x] #22460
- [x] #21990 

## Front-office
- [x] #24490
- [x] #28864

## Permissions 
- [x] #26953

## Modules
- [x] #9730 - FacetedSearch
- [x] #9795 - Linkwidget TOPWATCHERS

## To be specified
- [x] #26980

## Migration Features & Improvements
- [x] #19417 
- [x] #19386 
- [x] #19387

**Comment by 123monsite-regis** [comment]
Hi,
Please, could you expand titles of issues, 
we may after check if we are facing to other multishop issues,

Currently we have issues on BO admin product page with products pictures on multistore, do you know if this has been mentionned here ?

thanks

**Comment by khouloudbelguith** [comment]
Hi @123monsite-regis,

You can follow this issue: https://github.com/PrestaShop/PrestaShop/issues/10137

Best regards, Khouloud

**Comment by vcopleutre** [comment]
I updated this issue, if some people can dig into it it would be nice !
https://github.com/PrestaShop/PrestaShop/issues/9686
Regards

**Comment by angelflo** [comment]
In backend > catalog > products when I choose to displkay a grid of products for ALL SHOPS, I still have a shop_id clause in the SQL query relative to shop_id = 1
=> Can someone explain me why ??
It seems logic that if i choose to display products of "all shops" , the grid display all products without consideration of shop_id don't you think ?? any solution to fix this on 1.7.7.4 last release ?
